
. Set the passwords for all built-in users.
+
--
If you have enabled {security}, it provides built-in user credentials to help you
get up and running. The +elasticsearch-setup-passwords+ command is the simplest
method to set the built-in users' passwords for the first time.

For example, you can run the command in an "interactive" mode, which prompts you
to enter new passwords for the `elastic`, `kibana`, and `logstash_system` users:

[source,shell]
--------------------------------------------------
bin/elasticsearch-setup-passwords interactive
--------------------------------------------------

For more information about the command options, see <<setup-passwords>>.

IMPORTANT: The `elasticsearch-setup-passwords` command uses a transient
bootstrap password that is no longer valid after the command runs successfully.
You cannot run the `elasticsearch-setup-passwords` command a second time.
Instead, you can update passwords from the **Management > Users** UI in {kib} or
use the security user API.

For more information, see
{xpack-ref}/setting-up-authentication.html#set-built-in-user-passwords[Setting Built-in User Passwords].
--
