[role="xpack"]
[testenv="basic"]
[[ilm-stop]]
=== Stop {ilm} API

[subs="attributes"]
++++
<titleabbrev>Stop {ilm}</titleabbrev>
++++

Stop the {ilm} ({ilm-init}) plugin.

[[ilm-stop-request]]
==== {api-request-title}

`POST /_ilm/stop`

[[ilm-stop-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have the `manage_ilm`
cluster privilege to use this API. For more information, see
<<security-privileges>>.

[[ilm-stop-desc]]
==== {api-description-title}

Halts all lifecycle management operations and stops the {ilm-init} plugin. This
is useful when you are performing maintenance on the cluster and need to prevent
{ilm-init} from performing any actions on your indices.

The API returns as soon as the stop request has been acknowledged, but the
plugin might continue to run until in-progress operations complete and the plugin
can be safely stopped. Use the  <<ilm-get-status, Get {ilm-init} Status>> API to see
if {ilm-init} is running.

[[ilm-stop-query-params]]
==== {api-query-parms-title}

include::{docdir}/rest-api/common-parms.asciidoc[tag=timeoutparms]

[[ilm-stop-example]]
==== {api-examples-title}

The following example stops the {ilm-init} plugin.

//////////////////////////

[source,console]
--------------------------------------------------
PUT _ilm/policy/my_policy
{
  "policy": {
    "phases": {
      "warm": {
        "min_age": "10d",
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

PUT my_index
--------------------------------------------------
// TEST

//////////////////////////

[source,console]
--------------------------------------------------
POST _ilm/stop
--------------------------------------------------
// TEST[continued]

If the request does not encounter errors, you receive the following result:

[source,console-result]
--------------------------------------------------
{
  "acknowledged": true
}
--------------------------------------------------

//////////////////////////

[source,console]
--------------------------------------------------
POST _ilm/start
--------------------------------------------------
// TEST[continued]

//////////////////////////
