[role="xpack"]
[[index-lifecycle-and-snapshots]]
== Restore a managed data stream or index

When you restore a managed index or a data stream with managed backing indices, 
{ilm-init} automatically resumes executing the restored indices' policies.
A restored index's `min_age` is relative to when it was originally created or rolled over, 
not its restoration time. 
Policy actions are performed on the same schedule whether or not 
an index has been restored from a snapshot.
If you restore an index that was accidentally deleted half way through its month long lifecycle,
it proceeds normally through the last two weeks of its lifecycle.

In some cases, you might want to prevent {ilm-init} from immediately executing
its policy on a restored index.
For example, if you are restoring an older snapshot you might want to 
prevent it from rapidly progressing through all of its lifecycle phases. 
You might want to add or update documents before it's marked read-only or shrunk, 
or prevent the index from being immediately deleted.

To prevent {ilm-init} from executing a restored index's policy:

1. Go to `Kibana: Stack Management > Snapshot and Restore > Snapshots`.
2. Select the snapshot you wish to restore and click on `Next`.
3. Enable the `Reset index settings` option and add the `index.lifecycle.name` and `index.lifecycle.rollover_alias` index settings.
4. Click on `Next` and `Restore snapshot`.

Alternatively, this can also be done via the <<restore-snapshot-api,Restore snapshot API>> with the help of the `ignore_index_settings` option. And if you need to readd the {ilm-init} policy, you can do so with our <<apply-policy-manually,Apply lifecycle policy manually>> instructions.
