/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.gradle.internal;

import org.gradle.api.GradleException;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.tasks.Exec;
import org.gradle.api.tasks.JavaExec;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.gradle.api.tasks.bundling.Jar;
import org.gradle.api.tasks.compile.JavaCompile;
import org.gradle.jvm.toolchain.JavaLanguageVersion;
import org.gradle.jvm.toolchain.JavaToolchainService;

import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;

/**
 * Wires up annotation processing and post-compile module-info augmentation for modules that contain
 * {@code @LibrarySpecification} interfaces from {@code libs/ffm}.
 *
 * <p>This plugin handles two responsibilities that any consumer of the FFM annotation processor needs:
 * <ul>
 *   <li>Running the annotation processor as an external {@code javac} process (the processor requires
 *       the JDK 24+ {@code java.lang.classfile} API, which the Gradle daemon's bundled JDK 21 cannot
 *       load).</li>
 *   <li>Post-processing the compiled {@code module-info.class} to inject {@code provides
 *       org.elasticsearch.foreign.LibraryProvider with <generated $Provider classes>;} directives.
 *       The source {@code module-info.java} cannot reference these classes because they only exist
 *       as generated bytecode.</li>
 * </ul>
 *
 * <p>Applies to module-aware projects: the consuming project must have a {@code module-info.java}.
 * The module name is parsed from that file.
 */
public class ForeignLibraryPlugin implements Plugin<Project> {

    private static final int JDK_VERSION_FOR_PROCESSOR = 25;
    private static final int DEFAULT_TARGET_JAVA_RELEASE = 21;

    private final JavaToolchainService javaToolchains;

    @Inject
    public ForeignLibraryPlugin(JavaToolchainService javaToolchains) {
        this.javaToolchains = javaToolchains;
    }

    @Override
    public void apply(Project project) {
        project.getPluginManager().apply(JavaPlugin.class);

        Configuration processorPath = project.getConfigurations().create("foreignLibraryProcessor");
        project.getDependencies().add("foreignLibraryProcessor", project.project(":libs:ffm:processor"));

        DirectoryProperty generatedClassesDir = project.getObjects().directoryProperty();
        generatedClassesDir.set(project.getLayout().getBuildDirectory().dir("generated-library-classes"));

        DirectoryProperty augmentedModuleInfoDir = project.getObjects().directoryProperty();
        augmentedModuleInfoDir.set(project.getLayout().getBuildDirectory().dir("augmented-module-info"));

        registerRunAnnotationProcessorTask(project, processorPath, generatedClassesDir);
        registerAugmentModuleInfoTask(project, processorPath, generatedClassesDir, augmentedModuleInfoDir);

        // Add the annotation-processor-generated classes to the main source set's output so they
        // appear on the test runtime classpath (and any other consumer that reads main.output).
        SourceSet mainSourceSet = project.getExtensions().getByType(SourceSetContainer.class).getByName(SourceSet.MAIN_SOURCE_SET_NAME);
        mainSourceSet.getOutput().dir(java.util.Map.of("builtBy", "runAnnotationProcessor"), generatedClassesDir);

        wireCompileJava(project);
        wireJar(project, augmentedModuleInfoDir);
    }

    private void registerRunAnnotationProcessorTask(Project project, Configuration processorPath, DirectoryProperty generatedClassesDir) {
        project.getTasks().register("runAnnotationProcessor", Exec.class, task -> {
            task.dependsOn(":libs:ffm:assemble", ":libs:core:assemble", ":libs:logging:assemble", ":libs:ffm:processor:assemble");

            SourceSet mainSourceSet = project.getExtensions().getByType(SourceSetContainer.class).getByName(SourceSet.MAIN_SOURCE_SET_NAME);

            task.getOutputs().dir(generatedClassesDir);
            task.getInputs().files(mainSourceSet.getJava());
            task.getInputs().files(processorPath);
            task.getInputs().files(project.getConfigurations().getByName("compileClasspath"));

            var ffmDistDir = project.project(":libs:ffm").getLayout().getBuildDirectory().dir("distributions");
            var coreDistDir = project.project(":libs:core").getLayout().getBuildDirectory().dir("distributions");
            var loggingDistDir = project.project(":libs:logging").getLayout().getBuildDirectory().dir("distributions");
            var processorDistDir = project.project(":libs:ffm:processor").getLayout().getBuildDirectory().dir("distributions");

            task.doFirst(t -> {
                File outputDir = generatedClassesDir.get().getAsFile();
                outputDir.mkdirs();

                String javacExe = javaToolchains.compilerFor(
                    spec -> spec.getLanguageVersion().set(JavaLanguageVersion.of(JDK_VERSION_FOR_PROCESSOR))
                ).get().getMetadata().getInstallationPath().getAsFile().getAbsolutePath() + "/bin/javac";

                String ffmJar = findDistJar(ffmDistDir.get().getAsFile());
                String coreJar = findDistJar(coreDistDir.get().getAsFile());
                String loggingJar = findDistJar(loggingDistDir.get().getAsFile());
                String processorJar = findDistJar(processorDistDir.get().getAsFile());

                if (ffmJar == null || coreJar == null || loggingJar == null || processorJar == null) {
                    throw new GradleException(
                        "Could not find distribution JARs. ffm="
                            + ffmJar
                            + ", core="
                            + coreJar
                            + ", logging="
                            + loggingJar
                            + ", processor="
                            + processorJar
                    );
                }

                String modulePath = String.join(File.pathSeparator, ffmJar, coreJar, loggingJar);
                String processorModulePath = String.join(File.pathSeparator, processorJar, ffmJar, coreJar, loggingJar);

                List<String> command = new ArrayList<>();
                command.add(javacExe);
                command.add("-proc:only");
                command.add("--module-path");
                command.add(modulePath);
                command.add("--processor-module-path");
                command.add(processorModulePath);
                command.add("-AjavaVersion=" + DEFAULT_TARGET_JAVA_RELEASE);
                command.add("-d");
                command.add(outputDir.getAbsolutePath());
                for (File f : mainSourceSet.getJava().getFiles()) {
                    command.add(f.getAbsolutePath());
                }

                ((Exec) t).commandLine(command);
            });
        });
    }

    private void registerAugmentModuleInfoTask(
        Project project,
        Configuration processorPath,
        DirectoryProperty generatedClassesDir,
        DirectoryProperty augmentedModuleInfoDir
    ) {
        project.getTasks().register("augmentModuleInfo", JavaExec.class, task -> {
            task.dependsOn(
                project.getTasks().named("compileJava"),
                project.getTasks().named("runAnnotationProcessor"),
                ":libs:ffm:processor:assemble"
            );

            var compileJava = project.getTasks().named("compileJava", JavaCompile.class);
            var inputModuleInfo = compileJava.flatMap(JavaCompile::getDestinationDirectory).map(d -> d.file("module-info.class"));
            var servicesFile = generatedClassesDir.map(d -> d.file("META-INF/services/org.elasticsearch.foreign.LibraryProvider"));
            var outputModuleInfo = augmentedModuleInfoDir.map(d -> d.file("module-info.class"));

            task.getInputs().file(inputModuleInfo);
            task.getInputs().file(servicesFile);
            task.getOutputs().file(outputModuleInfo);

            task.setClasspath(processorPath);
            task.getMainClass().set("org.elasticsearch.foreign.processor.ModuleInfoAugmenter");

            task.doFirst(t -> {
                JavaExec exec = (JavaExec) t;
                exec.args(
                    inputModuleInfo.get().getAsFile().getAbsolutePath(),
                    servicesFile.get().getAsFile().getAbsolutePath(),
                    outputModuleInfo.get().getAsFile().getAbsolutePath()
                );
            });

            task.getJavaLauncher()
                .set(javaToolchains.launcherFor(spec -> spec.getLanguageVersion().set(JavaLanguageVersion.of(JDK_VERSION_FOR_PROCESSOR))));
        });
    }

    private void wireCompileJava(Project project) {
        project.getTasks().named("compileJava", JavaCompile.class).configure(task -> {
            task.dependsOn(project.getTasks().named("runAnnotationProcessor"));
            // Annotation processing already happened in runAnnotationProcessor — disable it here.
            task.getOptions().getCompilerArgs().add("-proc:none");
        });
    }

    private void wireJar(Project project, DirectoryProperty augmentedModuleInfoDir) {
        project.getTasks().named("jar", Jar.class).configure(task -> {
            task.dependsOn(project.getTasks().named("augmentModuleInfo"));

            // Substitute the augmented module-info.class for the original from compileJava.
            // The generated $Impl/$Provider classes and META-INF/services file are picked up
            // automatically via the main source set's output dirs (configured in apply()).
            Path classesDir = project.getTasks()
                .named("compileJava", JavaCompile.class)
                .flatMap(JavaCompile::getDestinationDirectory)
                .get()
                .getAsFile()
                .toPath();
            task.eachFile(details -> {
                if (details.getRelativePath().getPathString().equals("module-info.class")
                    && details.getFile().toPath().startsWith(classesDir)) {
                    details.exclude();
                }
            });
            task.from(augmentedModuleInfoDir, spec -> spec.include("module-info.class"));
        });
    }

    private static String findDistJar(File distDir) {
        File[] files = distDir.listFiles();
        if (files == null) {
            return null;
        }
        for (File f : files) {
            String name = f.getName();
            if (name.endsWith(".jar")
                && name.contains("sources") == false
                && name.contains("javadoc") == false
                && name.contains("tests") == false
                && name.endsWith(".pom") == false) {
                return f.getAbsolutePath();
            }
        }
        return null;
    }

}
