[[ml-delete-snapshot]]
==== Delete Model Snapshots

The delete model snapshot API enables you to delete an existing model snapshot.


===== Request

`DELETE _xpack/ml/anomaly_detectors/<job_id>/model_snapshots/<snapshot_id>`


===== Description

IMPORTANT: You cannot delete the active model snapshot. To delete that snapshot,
first revert to a different one.

//TBD: Where do you see restorePriority? Per old docs, the active model snapshot
//is "...the snapshot with the highest restorePriority".

===== Path Parameters

`job_id` (required)::
  (string) Identifier for the job

`snapshot_id` (required)::
  (string) Identifier for the model snapshot


===== Authorization

You must have `manage_ml`, or `manage` cluster privileges to use this API.
For more information, see <<privileges-list-cluster>>.


===== Examples

The following example deletes the `1491948163` snapshot:

[source,js]
--------------------------------------------------
DELETE _xpack/ml/anomaly_detectors/farequote/model_snapshots/1491948163
--------------------------------------------------
// CONSOLE
// TEST[skip:todo]

When the snapshot is deleted, you receive the following results:
[source,js]
----
{
  "acknowledged": true
}
----
