//lcawley Verified example output 2017-04-11
[[ml-get-datafeed-stats]]
==== Get Data Feed Statistics

The get data feed statistics API enables you to retrieve usage information for
data feeds.

===== Request

`GET _xpack/ml/datafeeds/_stats` +

`GET _xpack/ml/datafeeds/<feed_id>/_stats`

===== Description

If the data feed is stopped, the only information you receive is the
`datafeed_id` and the `state`.

You must have `monitor_ml`, `monitor`, `manage_ml`, or `manage` cluster
privileges to use this API. For more information, see <<privileges-list-cluster>>.

===== Path Parameters

`feed_id`::
  (string) Identifier for the data feed.
  This parameter does not support wildcards, but you can specify `_all` or
  omit the `feed_id` to get information about all data feeds.

===== Results

The API returns the following information:

`datafeeds`::
  (array) An array of data feed count objects.
  For more information, see <<ml-datafeed-counts,Data Feed Counts>>.

////
===== Responses

200
(EmptyResponse) The cluster has been successfully deleted
404
(BasicFailedReply) The cluster specified by {cluster_id} cannot be found (code: clusters.cluster_not_found)
412
(BasicFailedReply) The Elasticsearch cluster has not been shutdown yet (code: clusters.cluster_plan_state_error)
////
===== Examples

The following example gets usage information for the
`datafeed-farequote` data feed:

[source,js]
--------------------------------------------------
GET _xpack/ml/datafeeds/datafeed-farequote/_stats
--------------------------------------------------
// CONSOLE
// TEST[skip:todo]

The API returns the following results:
[source,js]
----
{
  "count": 1,
  "datafeeds": [
    {
      "datafeed_id": "datafeed-farequote",
      "state": "started",
      "node": {
        "id": "IO_gxe2_S8mrzu7OpmK5Jw",
        "name": "IO_gxe2",
        "ephemeral_id": "KHMWPZoMToOzSsZY9lDDgQ",
        "transport_address": "127.0.0.1:9300",
        "attributes": {
          "max_running_jobs": "10"
        }
      },
      "assignment_explanation": ""
    }
  ]
}
----
