[[mapping-fields]]
== Metadata fields

Each document has metadata associated with it, such as the `_index`, mapping
<<mapping-type-field,`_type`>>, and `_id` metadata fields.  The behavior of
some of these metadata fields can be customized when a mapping type is created.

[discrete]
=== Identity metadata fields

[horizontal]
<<mapping-index-field,`_index`>>::

    The index to which the document belongs.

<<mapping-type-field,`_type`>>::

    The document's mapping type.

<<mapping-id-field,`_id`>>::

    The document's ID.

[discrete]
=== Document source metadata fields

<<mapping-source-field,`_source`>>::

    The original JSON representing the body of the document.

{plugins}/mapper-size.html[`_size`]::

    The size of the `_source` field in bytes, provided by the
    {plugins}/mapper-size.html[`mapper-size` plugin].

[discrete]
=== Indexing metadata fields

<<mapping-field-names-field,`_field_names`>>::

    All fields in the document which contain non-null values.

<<mapping-ignored-field,`_ignored`>>::

    All fields in the document that have been ignored at index time because of
    <<ignore-malformed,`ignore_malformed`>>.

[discrete]
=== Routing metadata field

<<mapping-routing-field,`_routing`>>::

    A custom routing value which routes a document to a particular shard.

[discrete]
=== Other metadata field

<<mapping-meta-field,`_meta`>>::

    Application specific metadata.


include::fields/field-names-field.asciidoc[]

include::fields/ignored-field.asciidoc[]

include::fields/id-field.asciidoc[]

include::fields/index-field.asciidoc[]

include::fields/meta-field.asciidoc[]

include::fields/routing-field.asciidoc[]

include::fields/source-field.asciidoc[]

include::fields/type-field.asciidoc[]

