/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.multi_node;

import com.carrotsearch.randomizedtesting.annotations.ThreadLeakFilters;

import org.elasticsearch.test.TestClustersThreadFilter;
import org.elasticsearch.test.cluster.ElasticsearchCluster;
import org.elasticsearch.xpack.esql.CsvSpecReader.CsvTestCase;
import org.elasticsearch.xpack.esql.CsvTestUtils;
import org.elasticsearch.xpack.esql.plugin.ComputeService;
import org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase;
import org.junit.ClassRule;

import java.io.IOException;
import java.nio.file.Path;

import static org.elasticsearch.xpack.esql.qa.rest.RestEsqlTestCase.doesntHaveCapabilities;

/**
 * Abstract base for per-csv-spec-file test classes generated by the Gradle build.
 * The cluster is shared across all generated subclasses via {@code shared(true)} in
 * {@link Clusters#testCluster}, so it starts once for the whole JVM and data is
 * ingested exactly once (guarded by the {@code INGEST} lock in
 * {@link EsqlSpecTestCase}).
 */
// Each generated class covers one csv-spec file and should complete in a few minutes at most
@ThreadLeakFilters(filters = TestClustersThreadFilter.class)
public abstract class AbstractEsqlSpecIT extends EsqlSpecTestCase {

    private static final Path CSV_DATA_PATH = CsvTestUtils.createCsvDataDirectory();

    @ClassRule
    public static ElasticsearchCluster cluster = Clusters.testCluster(CSV_DATA_PATH, spec -> {
        spec.plugin("inference-service-test")
            .setting("logger." + ComputeService.class.getName(), "DEBUG")
            .settings(nodeSpec -> LOGGING_CLUSTER_SETTINGS);
    }, true);

    protected AbstractEsqlSpecIT(
        String fileName,
        String groupName,
        String testName,
        Integer lineNumber,
        CsvTestCase testCase,
        String instructions
    ) {
        super(fileName, groupName, testName, lineNumber, testCase, instructions);
    }

    @Override
    protected Path getCsvDataPath() {
        return CSV_DATA_PATH;
    }

    @Override
    protected String getTestRestCluster() {
        return cluster.getHttpAddresses();
    }

    @Override
    protected boolean enableRoundingDoubleValuesOnAsserting() {
        return true;
    }

    @Override
    protected boolean supportsSourceFieldMapping() {
        return false;
    }

    @Override
    protected String maybeRandomizeQuery(String query) {
        return randomlyNullify(query);
    }

    @Override
    protected void shouldSkipTest(String testName) throws IOException {
        super.shouldSkipTest(testName);
        assumeTrue(
            "Local cluster must not support " + testCase.missingCapabilitiesLocalCluster + " for test " + testName,
            doesntHaveCapabilities(adminClient(), testCase.missingCapabilitiesLocalCluster)
        );
        CsvTestUtils.assumeTrueLogging(
            "Multi-node tests don't support remote cluster capability requirements",
            testCase.missingCapabilitiesRemoteCluster.isEmpty()
        );
    }
}
