package org.elasticsearch.common;

/**
 * A strategy for rounding milliseconds since epoch.
 */
public interface PreparedRounding {
    /**
     * Rounds the given value.
     */
    long round(long utcMillis);
    /**
     * Given the rounded value (which was potentially generated by
     * {@link #round(long)}, returns the next rounding value. For
     * example, with interval based rounding, if the interval is
     * 3, {@code nextRoundValue(6) = 9}.
     */
    long nextRoundingValue(long utcMillis);
}
