/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.apache.lucene.util.BytesRef;
import org.elasticsearch.action.bulk.BulkItemRequest;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.util.ByteUtils;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.mapper.Uid;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.sourcebatch.SourceBatch;
import org.elasticsearch.xcontent.XContentType;

import java.util.List;

/**
 * A flattened, low-level representation of a batch of index operations, built early from
 * {@link IndexRequest}s and threaded through the batch-indexing fast path to the engine and
 * translog without retaining any reference to the original request objects.
 *
 * <p>All per-document data is stored in flat, parallel arrays indexed {@code [0, docCount)}.
 * The batch is created from {@link IndexRequest}s via one of the factory methods and is
 * thereafter immutable with respect to the init-stage fields (uids, routings, sources, etc.).
 *
 * <p>Three arrays — {@link #seqNoBytes()}, {@link #primaryTermBytes()}, and
 * {@link #versionBytes()} — are mutable and lazily allocated. The engine stamps the assigned
 * sequence numbers, primary terms, and versions into these arrays after planning. They are
 * handed by reference into {@link org.elasticsearch.sourcebatch.MappedColumns}, so engine
 * writes are visible to the Lucene columns without any copying.
 *
 * <p>Slices produced by {@link #slice(int, int)} share all backing arrays with the parent. Only
 * the {@link SourceBatch} is re-sliced. This lets the engine write only the slice's source data
 * to the translog while the seqNo/primaryTerm/version arrays remain full-batch-sized (accessed
 * via the {@link #offset()}).
 */
public final class IndexOperationBatch {

    // Batch-uniform values — same for every doc in the batch.
    private final Engine.Operation.Origin origin;
    private final long startTime;
    private final long primaryTerm;

    // Window into the backing arrays. 0 for root batches; > 0 for slices.
    private final int offset;
    private final int docCount;

    // Reference to the root batch that owns the backing arrays (null when this IS the root).
    private final IndexOperationBatch root;

    // Per-doc init-stage arrays (shared by slices; access via offset + i).
    private final BytesRef[] uids;
    private final boolean hasNullUid;
    private final String[] ids;
    // routings is null when no document in the batch has explicit routing; individual entries may
    // also be null for documents without routing.
    private final BytesRef[] routings;
    private final XContentType[] contentTypes;
    private final BytesReference[] sources;
    private final long[] requestedVersion;
    private final VersionType[] versionType;
    private final long[] ifSeqNo;
    private final long[] ifPrimaryTerm;
    private final long[] autoGeneratedIdTimestamp;
    private final boolean[] isRetry;

    // Source batch for this batch's docs. The root batch covers all docs; slices carry a
    // sub-range created via SourceBatch.slice().
    private final SourceBatch sourceBatch;

    // Engine-written aliased byte arrays. Lazily allocated by the root; slices delegate to root.
    // Shared by reference with MappedColumns so engine writes are visible to the Lucene columns.
    private byte[] seqNoBytes;
    private byte[] primaryTermBytes;
    private byte[] versionBytes;

    private IndexOperationBatch(
        Engine.Operation.Origin origin,
        long startTime,
        long primaryTerm,
        int offset,
        int docCount,
        IndexOperationBatch root,
        BytesRef[] uids,
        boolean hasNullUid,
        String[] ids,
        BytesRef[] routings,
        XContentType[] contentTypes,
        BytesReference[] sources,
        long[] requestedVersion,
        VersionType[] versionType,
        long[] ifSeqNo,
        long[] ifPrimaryTerm,
        long[] autoGeneratedIdTimestamp,
        boolean[] isRetry,
        SourceBatch sourceBatch
    ) {
        this.origin = origin;
        this.startTime = startTime;
        this.primaryTerm = primaryTerm;
        this.offset = offset;
        this.docCount = docCount;
        this.root = root;
        this.uids = uids;
        this.hasNullUid = hasNullUid;
        this.ids = ids;
        this.routings = routings;
        this.contentTypes = contentTypes;
        this.sources = sources;
        this.requestedVersion = requestedVersion;
        this.versionType = versionType;
        this.ifSeqNo = ifSeqNo;
        this.ifPrimaryTerm = ifPrimaryTerm;
        this.autoGeneratedIdTimestamp = autoGeneratedIdTimestamp;
        this.isRetry = isRetry;
        this.sourceBatch = sourceBatch;
    }

    /**
     * Builds a batch from a contiguous range {@code [from, to)} of a {@link BulkItemRequest} array.
     * This is the production entry point, replacing the {@link IndexRequest} array construction
     * and the {@link Engine.Index} list assembly in {@code ShardBatchMapper.mapColumnBatch}.
     *
     * <p>On {@link Engine.Operation.Origin#REPLICA}, the pre-assigned seqNo/primaryTerm/version
     * are read from the primary responses and written directly into the byte arrays at construction
     * time; {@code versionType} is {@code null} for every op and CAS fields are unset.
     *
     * <p>On {@link Engine.Operation.Origin#PRIMARY}, the byte arrays are pre-filled with their
     * default/unassigned values; the engine stamps the real values after planning.
     *
     * @param items       the full item array (only {@code [from, to)} is read)
     * @param from        first item index (inclusive)
     * @param to          last item index (exclusive)
     * @param chunkSource the source batch already sliced to {@code [from, to)}
     * @param origin      uniform origin for every op in the range
     * @param primaryTerm the shard's current operation primary term
     * @param startTime   {@code shard.getRelativeTimeInNanos()} at the start of the request
     */
    public static IndexOperationBatch initFromBulk(
        BulkItemRequest[] items,
        int from,
        int to,
        SourceBatch chunkSource,
        Engine.Operation.Origin origin,
        long primaryTerm,
        long startTime
    ) {
        final int docCount = to - from;
        final BytesRef[] uids = new BytesRef[docCount];
        final String[] ids = new String[docCount];
        final long[] requestedVersion = new long[docCount];
        final VersionType[] versionType = new VersionType[docCount];
        final long[] ifSeqNo = new long[docCount];
        final long[] ifPrimaryTerm = new long[docCount];
        final long[] autoGeneratedIdTimestamp = new long[docCount];
        final boolean[] isRetry = new boolean[docCount];
        boolean hasNullUid = false;
        BytesRef[] routings = null;
        final XContentType[] contentTypes = new XContentType[docCount];
        final BytesReference[] sources = new BytesReference[docCount];

        final byte[] seqNoBytes;
        final byte[] primaryTermBytes;
        final byte[] versionBytes;

        if (origin == Engine.Operation.Origin.REPLICA) {
            seqNoBytes = new byte[docCount * 8];
            primaryTermBytes = new byte[docCount * 8];
            versionBytes = new byte[docCount * 8];
        } else {
            seqNoBytes = null;   // lazily allocated when first requested
            primaryTermBytes = null;
            versionBytes = null;
        }

        for (int d = 0; d < docCount; d++) {
            final IndexRequest request = (IndexRequest) items[from + d].request();
            final String id = request.id();
            ids[d] = id;
            if (id == null) {
                hasNullUid = true;
            } else {
                uids[d] = Uid.encodeId(id);
            }
            final String routing = request.routing();
            if (routing != null) {
                if (routings == null) {
                    routings = new BytesRef[docCount];
                }
                routings[d] = new BytesRef(routing);
            }
            final XContentType ct = request.getContentType();
            contentTypes[d] = ct != null ? ct : XContentType.JSON;
            sources[d] = request.source();

            if (origin == Engine.Operation.Origin.REPLICA) {
                final org.elasticsearch.action.DocWriteResponse resp = items[from + d].getPrimaryResponse().getResponse();
                ByteUtils.writeLongLE(resp.getSeqNo(), seqNoBytes, d * 8);
                ByteUtils.writeLongLE(resp.getPrimaryTerm(), primaryTermBytes, d * 8);
                ByteUtils.writeLongLE(resp.getVersion(), versionBytes, d * 8);
                requestedVersion[d] = resp.getVersion();
                versionType[d] = null;
                ifSeqNo[d] = SequenceNumbers.UNASSIGNED_SEQ_NO;
                ifPrimaryTerm[d] = 0;
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            } else {
                requestedVersion[d] = request.version();
                versionType[d] = request.versionType();
                ifSeqNo[d] = request.ifSeqNo();
                ifPrimaryTerm[d] = request.ifPrimaryTerm();
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            }
        }

        final IndexOperationBatch batch = new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            0,
            docCount,
            null,
            uids,
            hasNullUid,
            ids,
            routings,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            chunkSource
        );
        if (origin == Engine.Operation.Origin.REPLICA) {
            batch.seqNoBytes = seqNoBytes;
            batch.primaryTermBytes = primaryTermBytes;
            batch.versionBytes = versionBytes;
        }
        return batch;
    }

    /**
     * Builds a batch from an {@link IndexRequest} array. Intended for mapper unit tests that
     * exercise the columnar metadata-mapper hooks without going through the full bulk path.
     * Uses {@link Engine.Operation.Origin#PRIMARY}, placeholder {@code primaryTerm=0}, and
     * {@code startTime=0} — values not significant for mapping.
     */
    public static IndexOperationBatch initFromRequests(IndexRequest[] requests) {
        final int docCount = requests.length;
        final BytesRef[] uids = new BytesRef[docCount];
        final String[] ids = new String[docCount];
        boolean hasNullUid = false;
        BytesRef[] routings = null;
        final XContentType[] contentTypes = new XContentType[docCount];
        final BytesReference[] sources = new BytesReference[docCount];
        final long[] requestedVersion = new long[docCount];
        final VersionType[] versionType = new VersionType[docCount];
        final long[] ifSeqNo = new long[docCount];
        final long[] ifPrimaryTerm = new long[docCount];
        final long[] autoGeneratedIdTimestamp = new long[docCount];
        final boolean[] isRetry = new boolean[docCount];

        for (int d = 0; d < docCount; d++) {
            final String id = requests[d].id();
            ids[d] = id;
            if (id == null) {
                hasNullUid = true;
            } else {
                uids[d] = Uid.encodeId(id);
            }
            final String routing = requests[d].routing();
            if (routing != null) {
                if (routings == null) {
                    routings = new BytesRef[docCount];
                }
                routings[d] = new BytesRef(routing);
            }
            final XContentType ct = requests[d].getContentType();
            contentTypes[d] = ct != null ? ct : XContentType.JSON;
            sources[d] = requests[d].source();
            requestedVersion[d] = requests[d].version();
            versionType[d] = requests[d].versionType();
            ifSeqNo[d] = requests[d].ifSeqNo();
            ifPrimaryTerm[d] = requests[d].ifPrimaryTerm();
            autoGeneratedIdTimestamp[d] = requests[d].getAutoGeneratedTimestamp();
            isRetry[d] = requests[d].isRetry();
        }

        return new IndexOperationBatch(
            Engine.Operation.Origin.PRIMARY,
            0L,
            0L,
            0,
            docCount,
            null,
            uids,
            hasNullUid,
            ids,
            routings,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            null
        );
    }

    /**
     * Builds a minimal batch carrying only {@code uids} (the per-document {@code _id} values).
     * All other per-doc fields are absent ({@code null}).
     *
     * <p>Used by {@link org.elasticsearch.index.mapper.ShardBatchMapper#buildMetadataContext}
     * to run the metadata-mapper columnar hooks in tests before the full field-mapper columnar
     * support is wired in.
     */
    public static IndexOperationBatch metadataOnly(int docCount, BytesRef[] uids) {
        assert uids.length == docCount;
        boolean hasNullUid = false;
        final String[] ids = new String[docCount];
        for (int d = 0; d < docCount; d++) {
            if (uids[d] == null) {
                hasNullUid = true;
            }
        }
        return new IndexOperationBatch(
            Engine.Operation.Origin.PRIMARY,
            0L,
            0L,
            0,
            docCount,
            null,
            uids,
            hasNullUid,
            ids,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    // -----------------------------------------------------------------------
    // Slicing — engine-internal sub-batch support
    // -----------------------------------------------------------------------

    /**
     * Returns a window view of this batch covering rows {@code [from, to)}.
     *
     * <p>All backing arrays are shared with the parent (accessed via an updated {@link #offset()}).
     * Only the {@link SourceBatch} is re-sliced so that {@link SourceBatch#data()} covers exactly
     * the sub-range's documents. This lets the engine write only the slice's source data to the
     * translog while the seqNo/primaryTerm/version byte arrays remain full-batch-sized (the engine
     * reads them via {@link #seqNo(int)} / {@link #assignedVersion(int)} which incorporate the
     * offset automatically).
     *
     * <p>Closing a slice is a no-op; only the root batch closes the underlying source.
     *
     * @throws IndexOutOfBoundsException if the range is invalid for this batch
     */
    public IndexOperationBatch slice(int from, int to) {
        if (from < 0 || to < from || to > docCount) {
            throw new IndexOutOfBoundsException("slice [" + from + ", " + to + ") out of range [0, " + docCount + ")");
        }
        final int newCount = to - from;
        final int newOffset = this.offset + from;
        final IndexOperationBatch rootBatch = (this.root != null) ? this.root : this;
        final SourceBatch slicedSource = (sourceBatch != null) ? sourceBatch.slice(from, to) : null;
        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            newOffset,
            newCount,
            rootBatch,
            uids,
            hasNullUid,
            ids,
            routings,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            slicedSource
        );
    }

    // -----------------------------------------------------------------------
    // Batch-uniform accessors
    // -----------------------------------------------------------------------

    /**
     * The uniform origin for every operation in this batch.
     */
    public Engine.Operation.Origin origin() {
        return origin;
    }

    /**
     * The relative start time in nanoseconds at which this batch was initiated, as returned by
     * {@code IndexShard.getRelativeTimeInNanos()}.
     */
    public long startTime() {
        return startTime;
    }

    /**
     * The operation primary term for this batch, uniform across all documents.
     */
    public long primaryTerm() {
        return primaryTerm;
    }

    /** The number of documents in this batch (or slice). */
    public int docCount() {
        return docCount;
    }

    /**
     * The offset of this batch's first document within the root's backing arrays. Always
     * {@code 0} for root batches; {@code > 0} for slices.
     */
    public int offset() {
        return offset;
    }

    // -----------------------------------------------------------------------
    // Per-doc accessors
    // -----------------------------------------------------------------------

    /**
     * Returns the Uid-encoded {@code _id} for document {@code i}.
     *
     * @throws IllegalStateException if any document in the batch has a null {@code _id} (synthetic
     *                               id is not yet supported in the columnar path)
     */
    public BytesRef uid(int i) {
        assert i >= 0 && i < docCount : "doc " + i + " out of range [0, " + docCount + ")";
        if (hasNullUid) {
            // TODO: We do not support synthetic id yet. This will change once we do.
            throw new IllegalStateException("_id should have been set on the coordinating node");
        }
        return uids[offset + i];
    }

    /**
     * Returns all Uid-encoded {@code _id}s as a raw array (length {@code totalDocCount}, not
     * slice-relative). Prefer {@link #uid(int)} for per-doc access.
     *
     * @throws IllegalStateException if any document in the batch has a null {@code _id}
     */
    public BytesRef[] uids() {
        if (hasNullUid) {
            throw new IllegalStateException("_id should have been set on the coordinating node");
        }
        return uids;
    }

    /** Returns the raw (unencoded) string {@code _id} for document {@code i}. */
    public String id(int i) {
        assert i >= 0 && i < docCount : "doc " + i + " out of range [0, " + docCount + ")";
        return ids[offset + i];
    }

    /**
     * Returns the per-document routing array. May be {@code null} when no document in the batch
     * has an explicit routing (the common case). Individual entries may still be {@code null}
     * for documents without routing even when the array is non-{@code null}.
     *
     * <p>This is the raw backing array of length {@code totalDocCount}; slices share it.
     */
    public BytesRef[] routings() {
        return routings;
    }

    /**
     * Returns the routing for document {@code i} as a {@link String}, or {@code null} if the
     * document has no explicit routing.
     */
    public String routingString(int i) {
        assert i >= 0 && i < docCount;
        if (routings == null) {
            return null;
        }
        final BytesRef r = routings[offset + i];
        return r != null ? r.utf8ToString() : null;
    }

    /**
     * Returns the per-document content-type array. Entries default to
     * {@link XContentType#JSON} when the original request carried no content type.
     *
     * <p>This is the raw backing array of length {@code totalDocCount}; slices share it.
     * May be {@code null} for metadata-only batches.
     */
    public XContentType[] contentTypes() {
        return contentTypes;
    }

    /**
     * Returns the per-document source array. Individual entries may be {@code null} for
     * documents without source.
     *
     * <p>This is the raw backing array of length {@code totalDocCount}; slices share it.
     * May be {@code null} for metadata-only batches.
     */
    public BytesReference[] sources() {
        return sources;
    }

    /**
     * Returns the requested version for document {@code i}.
     * On primary this is from the request; on replica it is the assigned version.
     */
    public long requestedVersion(int i) {
        assert i >= 0 && i < docCount;
        return requestedVersion[offset + i];
    }

    /**
     * Returns the version type for document {@code i}. {@code null} on replica operations.
     */
    public VersionType versionType(int i) {
        assert i >= 0 && i < docCount;
        return versionType[offset + i];
    }

    /**
     * Returns the {@code if_seq_no} condition for document {@code i}.
     * {@link SequenceNumbers#UNASSIGNED_SEQ_NO} when no CAS condition was set.
     */
    public long ifSeqNo(int i) {
        assert i >= 0 && i < docCount;
        return ifSeqNo[offset + i];
    }

    /**
     * Returns the {@code if_primary_term} condition for document {@code i}.
     * {@code 0} when no CAS condition was set.
     */
    public long ifPrimaryTerm(int i) {
        assert i >= 0 && i < docCount;
        return ifPrimaryTerm[offset + i];
    }

    /**
     * Returns the auto-generated-id timestamp for document {@code i}, or a negative value if the
     * id was not auto-generated.
     */
    public long autoGeneratedIdTimestamp(int i) {
        assert i >= 0 && i < docCount;
        return autoGeneratedIdTimestamp[offset + i];
    }

    /** Returns {@code true} if document {@code i} is a retry of a previously attempted index. */
    public boolean isRetry(int i) {
        assert i >= 0 && i < docCount;
        return isRetry[offset + i];
    }

    /**
     * Returns the source batch for this window. For root batches this covers all {@link #docCount()}
     * documents; for slices it covers only the slice's range (created via
     * {@link SourceBatch#slice(int, int)}). May be {@code null} for metadata-only batches.
     */
    public SourceBatch sourceBatch() {
        return sourceBatch;
    }

    // -----------------------------------------------------------------------
    // Engine-written aliased byte arrays
    // -----------------------------------------------------------------------

    /**
     * Returns the mutable {@code _seq_no} backing byte array (length {@code totalDocCount * 8},
     * little-endian longs). Each 8-byte slot is pre-filled with
     * {@link SequenceNumbers#UNASSIGNED_SEQ_NO}; the engine overwrites the real per-document
     * value after planning. Lazily allocated on first call.
     *
     * <p>The returned array is the same instance handed to
     * {@link org.elasticsearch.sourcebatch.MappedColumns} by {@code BatchMappingContext.columns()},
     * so engine writes through {@code MappedColumns.setSeqNo(i, v)} are immediately visible to the
     * Lucene columns without any copy.
     *
     * <p>For slices, this returns the root's array (full-batch-sized); individual elements are
     * accessed at position {@code (offset + i) * 8}.
     */
    public byte[] seqNoBytes() {
        final IndexOperationBatch owner = (root != null) ? root : this;
        if (owner.seqNoBytes == null) {
            owner.seqNoBytes = new byte[owner.docCount * 8];
            for (int d = 0; d < owner.docCount; d++) {
                ByteUtils.writeLongLE(SequenceNumbers.UNASSIGNED_SEQ_NO, owner.seqNoBytes, d * 8);
            }
        }
        return owner.seqNoBytes;
    }

    /**
     * Returns the mutable {@code _primary_term} backing byte array (length
     * {@code totalDocCount * 8}, little-endian longs). Slots are zero-initialized; the engine
     * fills the real value after planning. Lazily allocated on first call.
     *
     * <p>For slices, this returns the root's array; individual elements are accessed at
     * position {@code (offset + i) * 8}.
     */
    public byte[] primaryTermBytes() {
        final IndexOperationBatch owner = (root != null) ? root : this;
        if (owner.primaryTermBytes == null) {
            owner.primaryTermBytes = new byte[owner.docCount * 8];
        }
        return owner.primaryTermBytes;
    }

    /**
     * Returns the mutable {@code _version} backing byte array (length {@code totalDocCount * 8},
     * little-endian longs). Slots are zero-initialized; the engine fills the real assigned version
     * after planning. Lazily allocated on first call.
     *
     * <p>For slices, this returns the root's array; individual elements are accessed at
     * position {@code (offset + i) * 8}.
     */
    public byte[] versionBytes() {
        final IndexOperationBatch owner = (root != null) ? root : this;
        if (owner.versionBytes == null) {
            owner.versionBytes = new byte[owner.docCount * 8];
        }
        return owner.versionBytes;
    }

    /**
     * Returns the assigned sequence number for document {@code i}.
     * Only valid after the engine has stamped values into {@link #seqNoBytes()}.
     */
    public long seqNo(int i) {
        assert i >= 0 && i < docCount;
        return ByteUtils.readLongLE(seqNoBytes(), (offset + i) * 8);
    }

    /**
     * Returns the assigned version for document {@code i}.
     * Only valid after the engine has stamped values into {@link #versionBytes()}.
     */
    public long assignedVersion(int i) {
        assert i >= 0 && i < docCount;
        return ByteUtils.readLongLE(versionBytes(), (offset + i) * 8);
    }

    /**
     * Returns the assigned primary term for document {@code i}.
     * Only valid after the engine has stamped values into {@link #primaryTermBytes()}.
     */
    public long assignedPrimaryTerm(int i) {
        assert i >= 0 && i < docCount;
        return ByteUtils.readLongLE(primaryTermBytes(), (offset + i) * 8);
    }

    /**
     * Returns a positioned read-only cursor ({@link OpView}) for document {@code i} in this batch.
     * All fields are read from the batch's flat arrays at {@code offset + i}.
     */
    public Engine.IndexOpView opView(int i) {
        assert i >= 0 && i < docCount : "doc " + i + " out of range [0, " + docCount + ")";
        return new OpView(offset + i);
    }

    /**
     * Builds a batch from an existing {@link List} of {@link Engine.Index} operations and a
     * pre-built {@link SourceBatch}. All fields are copied from the operations; the byte arrays are
     * lazily allocated (not pre-filled), matching the {@link Engine.Operation.Origin#PRIMARY} init
     * path. Intended for {@code InternalEngineTests.engineBatch} so the ~30 call sites keep their
     * current signature.
     */
    public static IndexOperationBatch fromIndexOps(List<Engine.Index> operations, SourceBatch sourceBatch) {
        final int docCount = operations.size();
        final BytesRef[] uids = new BytesRef[docCount];
        final String[] ids = new String[docCount];
        boolean hasNullUid = false;
        BytesRef[] routings = null;
        final XContentType[] contentTypes = new XContentType[docCount];
        final BytesReference[] sources = new BytesReference[docCount];
        final long[] requestedVersion = new long[docCount];
        final VersionType[] versionType = new VersionType[docCount];
        final long[] ifSeqNo = new long[docCount];
        final long[] ifPrimaryTerm = new long[docCount];
        final long[] autoGeneratedIdTimestamp = new long[docCount];
        final boolean[] isRetry = new boolean[docCount];

        final Engine.Operation.Origin origin = operations.isEmpty() ? Engine.Operation.Origin.PRIMARY : operations.getFirst().origin();
        final long primaryTerm = operations.isEmpty() ? 0L : operations.getFirst().primaryTerm();
        final long startTime = operations.isEmpty() ? 0L : operations.getFirst().startTime();

        for (int d = 0; d < docCount; d++) {
            final Engine.Index op = operations.get(d);
            assert op.primaryTerm() == primaryTerm
                : "all operations in a batch must share the same primary term; expected ["
                    + primaryTerm
                    + "] but op["
                    + d
                    + "] has ["
                    + op.primaryTerm()
                    + "]";
            uids[d] = op.uid();
            ids[d] = op.id();
            final String routing = op.routing();
            if (routing != null) {
                if (routings == null) {
                    routings = new BytesRef[docCount];
                }
                routings[d] = new BytesRef(routing);
            }
            final XContentType ct = op.parsedDoc().getXContentType();
            contentTypes[d] = ct != null ? ct : XContentType.JSON;
            sources[d] = op.source().originalBytes();
            requestedVersion[d] = op.version();
            versionType[d] = op.versionType();
            ifSeqNo[d] = op.getIfSeqNo();
            ifPrimaryTerm[d] = op.getIfPrimaryTerm();
            autoGeneratedIdTimestamp[d] = op.getAutoGeneratedIdTimestamp();
            isRetry[d] = op.isRetry();
        }

        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            0,
            docCount,
            null,
            uids,
            hasNullUid,
            ids,
            routings,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            sourceBatch
        );
    }

    /**
     * Positioned read-only cursor over a single document in this batch, implementing
     * {@link Engine.IndexOpView}. Reads directly from the batch's flat arrays using an absolute
     * index ({@code offset + i}). SeqNo, primaryTerm, and version are read from the aliased byte
     * arrays, so they reflect any values stamped by the engine after planning.
     */
    public final class OpView implements Engine.IndexOpView {
        private final int absIdx;

        private OpView(int absIdx) {
            this.absIdx = absIdx;
        }

        @Override
        public BytesRef uid() {
            return uids[absIdx];
        }

        @Override
        public String id() {
            return ids[absIdx];
        }

        @Override
        public Engine.Operation.Origin origin() {
            return IndexOperationBatch.this.origin;
        }

        @Override
        public long version() {
            return requestedVersion[absIdx];
        }

        @Override
        public VersionType versionType() {
            return versionType[absIdx];
        }

        @Override
        public long seqNo() {
            return ByteUtils.readLongLE(seqNoBytes(), absIdx * 8);
        }

        @Override
        public long primaryTerm() {
            return IndexOperationBatch.this.primaryTerm;
        }

        @Override
        public long startTime() {
            return IndexOperationBatch.this.startTime;
        }

        @Override
        public long getAutoGeneratedIdTimestamp() {
            return autoGeneratedIdTimestamp[absIdx];
        }

        @Override
        public boolean isRetry() {
            return isRetry[absIdx];
        }

        @Override
        public long getIfSeqNo() {
            return ifSeqNo[absIdx];
        }

        @Override
        public long getIfPrimaryTerm() {
            return ifPrimaryTerm[absIdx];
        }

        @Override
        public int reservingDocs() {
            return 1;
        }

        @Override
        public String documentDescription() {
            return ids[absIdx];
        }
    }
}
