/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.apache.lucene.util.BytesRef;
import org.elasticsearch.action.bulk.BulkItemRequest;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.io.stream.Writeable;
import org.elasticsearch.common.util.ByteUtils;
import org.elasticsearch.core.Nullable;
import org.elasticsearch.escf.EscfBatch;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.mapper.ParsedDocument;
import org.elasticsearch.index.mapper.SourceToParse;
import org.elasticsearch.index.mapper.Uid;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.translog.Translog;
import org.elasticsearch.sourcebatch.MappedColumns;
import org.elasticsearch.sourcebatch.SourceBatch;
import org.elasticsearch.sourcebatch.SourceRow;
import org.elasticsearch.sourcebatch.SourceRowToXContent;
import org.elasticsearch.sourcebatch.SourceRowXContentParser;
import org.elasticsearch.xcontent.XContentBuilder;
import org.elasticsearch.xcontent.XContentType;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

/**
 * Flattened, low-level batch of index operations — per-doc data in parallel arrays indexed
 * {@code [0, docCount)}.
 *
 * <p>{@link #seqNoBytes()}, {@link #primaryTermBytes()}, and {@link #versionBytes()} are aliased
 * into {@link MappedColumns} by reference; engine writes are visible to Lucene columns without
 * copying. Slices share all backing arrays with the parent; only the {@link SourceBatch} is
 * re-sliced. Use {@link #offset()} to find per-doc positions within the full-batch-sized arrays.
 */
public final class IndexOperationBatch {

    // Batch Level Characteristics

    private final Engine.Operation.Origin origin;
    private final long startTime;
    private final long primaryTerm;

    // Sliced Metadata

    private final int offset;
    private final int docCount;

    // Transient Indexing Metadata

    private final String[] ids;
    // TODO: Will go away when we make source mappers operation directly on SourceBatch
    private final BytesReference[] sources;
    private final long[] requestedVersion;
    private final VersionType[] versionType;
    // null when no document has a CAS condition; accessors return the sentinel value when null.
    private final long[] ifSeqNo;
    private final long[] ifPrimaryTerm;
    private final boolean[] isRetry;

    // Translog Storage - stored in the translog

    private final BytesRef[] uids;
    private final long[] autoGeneratedIdTimestamp;
    // null when no document has explicit routing.
    private final BytesRef[] routings;
    // null when no document carries a coordinator-computed tsid (set only for time_series indices).
    private final BytesRef[] tsids;
    private final XContentType[] contentTypes;

    // Aliased into MappedColumns — engine writes are visible to Lucene columns without copying.
    private final BytesRef seqNoBytes;
    private final BytesRef primaryTermBytes;
    private final BytesRef versionBytes;

    private final SourceBatch sourceBatch;

    IndexOperationBatch(
        Engine.Operation.Origin origin,
        long startTime,
        long primaryTerm,
        int offset,
        int docCount,
        BytesRef[] uids,
        String[] ids,
        @Nullable BytesRef[] routings,
        @Nullable BytesRef[] tsids,
        XContentType[] contentTypes,
        BytesReference[] sources,
        long[] requestedVersion,
        VersionType[] versionType,
        @Nullable long[] ifSeqNo,
        @Nullable long[] ifPrimaryTerm,
        long[] autoGeneratedIdTimestamp,
        boolean[] isRetry,
        @Nullable SourceBatch sourceBatch,
        BytesRef seqNoBytes,
        BytesRef primaryTermBytes,
        BytesRef versionBytes
    ) {
        assert docCount >= 1 : "batch must contain at least one document, got docCount [" + docCount + "]";
        assert offset >= 0 : "offset must be non-negative, got [" + offset + "]";
        assert assertArraysCover(
            offset,
            docCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
        this.origin = origin;
        this.startTime = startTime;
        this.primaryTerm = primaryTerm;
        this.offset = offset;
        this.docCount = docCount;
        this.uids = uids;
        this.ids = ids;
        this.routings = routings;
        this.tsids = tsids;
        this.contentTypes = contentTypes;
        this.sources = sources;
        this.requestedVersion = requestedVersion;
        this.versionType = versionType;
        this.ifSeqNo = ifSeqNo;
        this.ifPrimaryTerm = ifPrimaryTerm;
        this.autoGeneratedIdTimestamp = autoGeneratedIdTimestamp;
        this.isRetry = isRetry;
        this.sourceBatch = sourceBatch;
        this.seqNoBytes = seqNoBytes;
        this.primaryTermBytes = primaryTermBytes;
        this.versionBytes = versionBytes;
    }

    private static boolean assertArraysCover(
        int offset,
        int docCount,
        BytesRef[] uids,
        String[] ids,
        @Nullable BytesRef[] routings,
        @Nullable BytesRef[] tsids,
        XContentType[] contentTypes,
        BytesReference[] sources,
        long[] requestedVersion,
        VersionType[] versionType,
        @Nullable long[] ifSeqNo,
        @Nullable long[] ifPrimaryTerm,
        long[] autoGeneratedIdTimestamp,
        boolean[] isRetry,
        BytesRef seqNoBytes,
        BytesRef primaryTermBytes,
        BytesRef versionBytes
    ) {
        final int end = offset + docCount;
        assertCovers("uids", uids.length, end);
        assertCovers("ids", ids.length, end);
        assertCovers("contentTypes", contentTypes.length, end);
        assertCovers("sources", sources.length, end);
        assertCovers("requestedVersion", requestedVersion.length, end);
        assertCovers("versionType", versionType.length, end);
        assertCovers("autoGeneratedIdTimestamp", autoGeneratedIdTimestamp.length, end);
        assertCovers("isRetry", isRetry.length, end);
        if (routings != null) {
            assertCovers("routings", routings.length, end);
        }
        if (tsids != null) {
            assertCovers("tsids", tsids.length, end);
        }
        if (ifSeqNo != null) {
            assertCovers("ifSeqNo", ifSeqNo.length, end);
        }
        if (ifPrimaryTerm != null) {
            assertCovers("ifPrimaryTerm", ifPrimaryTerm.length, end);
        }
        assertLongBuffer("seqNoBytes", seqNoBytes, end);
        assertLongBuffer("primaryTermBytes", primaryTermBytes, end);
        assertLongBuffer("versionBytes", versionBytes, end);
        return true;
    }

    private static void assertCovers(String name, int length, int end) {
        assert length >= end : name + " length [" + length + "] does not cover window up to [" + end + ")";
    }

    private static void assertLongBuffer(String name, BytesRef buf, int end) {
        assert buf.offset == 0 : name + " must be a zero-offset BytesRef, got offset [" + buf.offset + "]";
        assertCovers(name, buf.bytes.length / 8, end);
    }

    /**
     * Production entry point. Reads items {@code [from, to)}. On REPLICA, seqNo/primaryTerm/version
     * are copied from primary responses and versionType is {@code null}. On PRIMARY, seqNoBytes is
     * pre-filled with {@link SequenceNumbers#UNASSIGNED_SEQ_NO}; the engine stamps real values after
     * planning.
     */
    public static IndexOperationBatch initFromBulk(
        BulkItemRequest[] items,
        int from,
        int to,
        SourceBatch chunkSource,
        Engine.Operation.Origin origin,
        long primaryTerm,
        long startTime
    ) {
        Objects.checkFromToIndex(from, to, items.length);
        if (from == to) {
            throw new IllegalArgumentException("empty batch [" + from + ", " + to + "); initFromBulk requires at least one item");
        }
        final int docCount = to - from;
        final BytesRef[] uids = new BytesRef[docCount];
        final String[] ids = new String[docCount];
        final long[] requestedVersion = new long[docCount];
        final VersionType[] versionType = new VersionType[docCount];
        long[] ifSeqNoBuf = null;
        long[] ifPrimaryTermBuf = null;
        final long[] autoGeneratedIdTimestamp = new long[docCount];
        final boolean[] isRetry = new boolean[docCount];
        BytesRef[] routings = null;
        BytesRef[] tsids = null;
        final XContentType[] contentTypes = new XContentType[docCount];
        final BytesReference[] sources = new BytesReference[docCount];

        final BytesRef seqNoBytes = new BytesRef(new byte[docCount * 8]);
        final BytesRef primaryTermBytes = new BytesRef(new byte[docCount * 8]);
        final BytesRef versionBytes = new BytesRef(new byte[docCount * 8]);

        if (origin != Engine.Operation.Origin.REPLICA) {
            for (int d = 0; d < docCount; d++) {
                ByteUtils.writeLongLE(SequenceNumbers.UNASSIGNED_SEQ_NO, seqNoBytes.bytes, d * 8);
            }
        }

        for (int d = 0; d < docCount; d++) {
            final IndexRequest request = (IndexRequest) items[from + d].request();
            final String id = request.id();
            ids[d] = id;
            if (id != null) {
                uids[d] = Uid.encodeId(id);
            }
            final String routing = request.routing();
            if (routing != null) {
                if (routings == null) {
                    routings = new BytesRef[docCount];
                }
                routings[d] = new BytesRef(routing);
            }
            final BytesRef tsid = request.tsid();
            if (tsid != null) {
                if (tsids == null) {
                    tsids = new BytesRef[docCount];
                }
                tsids[d] = tsid;
            }
            final XContentType ct = request.getContentType();
            contentTypes[d] = ct != null ? ct : XContentType.JSON;
            sources[d] = request.source();

            if (origin == Engine.Operation.Origin.REPLICA) {
                final org.elasticsearch.action.DocWriteResponse resp = items[from + d].getPrimaryResponse().getResponse();
                ByteUtils.writeLongLE(resp.getSeqNo(), seqNoBytes.bytes, d * 8);
                ByteUtils.writeLongLE(resp.getPrimaryTerm(), primaryTermBytes.bytes, d * 8);
                ByteUtils.writeLongLE(resp.getVersion(), versionBytes.bytes, d * 8);
                requestedVersion[d] = resp.getVersion();
                versionType[d] = null;
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            } else {
                requestedVersion[d] = request.version();
                versionType[d] = request.versionType();
                final long ifSeq = request.ifSeqNo();
                if (ifSeq != SequenceNumbers.UNASSIGNED_SEQ_NO) {
                    if (ifSeqNoBuf == null) {
                        ifSeqNoBuf = new long[docCount];
                        Arrays.fill(ifSeqNoBuf, SequenceNumbers.UNASSIGNED_SEQ_NO);
                    }
                    ifSeqNoBuf[d] = ifSeq;
                }
                final long ifPT = request.ifPrimaryTerm();
                if (ifPT != 0L) {
                    if (ifPrimaryTermBuf == null) {
                        ifPrimaryTermBuf = new long[docCount];
                    }
                    ifPrimaryTermBuf[d] = ifPT;
                }
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            }
        }

        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            0,
            docCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNoBuf,
            ifPrimaryTermBuf,
            autoGeneratedIdTimestamp,
            isRetry,
            chunkSource,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
    }

    /**
     * Returns a view of {@code [from, to)} sharing all backing arrays with the parent. Only the
     * {@link SourceBatch} is re-sliced; seqNo/primaryTerm/version arrays remain full-batch-sized.
     *
     * @throws IndexOutOfBoundsException if the range is invalid
     */
    public IndexOperationBatch slice(int from, int to) {
        Objects.checkFromToIndex(from, to, docCount);
        if (from == to) {
            throw new IllegalArgumentException("empty slice [" + from + ", " + to + "); a batch must contain at least one document");
        }
        final int newCount = to - from;
        final int newOffset = this.offset + from;
        final SourceBatch slicedSource = (sourceBatch != null) ? sourceBatch.slice(from, to) : null;
        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            newOffset,
            newCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            slicedSource,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
    }

    public Engine.Operation.Origin origin() {
        return origin;
    }

    public long startTime() {
        return startTime;
    }

    public long primaryTerm() {
        return primaryTerm;
    }

    public int docCount() {
        return docCount;
    }

    public int offset() {
        return offset;
    }

    public BytesRef uid(int i) {
        return uids[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> uid array — not offset-adjusted and not trimmed to this
     * batch's range. Callers must combine it with {@link #offset()} and {@link #docCount()};
     * index {@code i} in this batch lives at {@code uids()[offset() + i]}.
     */
    public BytesRef[] uids() {
        return uids;
    }

    public String id(int i) {
        return ids[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> routing array, or {@code null} if no document has explicit
     * routing. When non-null, individual entries may still be {@code null}. Callers must combine it
     * with {@link #offset()} and {@link #docCount()}.
     */
    public BytesRef[] routings() {
        return routings;
    }

    /**
     * The raw, <b>full-batch-sized</b> tsid array, or {@code null} if no document carries a
     * coordinator-computed tsid (only set for {@code time_series} indices). When non-null,
     * individual entries may still be {@code null} for documents whose tsid was not set.
     * Callers must combine it with {@link #offset()} and {@link #docCount()}.
     */
    @Nullable
    public BytesRef[] tsids() {
        return tsids;
    }

    /**
     * Sets the synthetic {@code _id} and uid for document {@code i} in this batch slice.
     *
     * @param i   document index within this slice ({@code 0..docCount-1})
     * @param id  the plain-text id
     * @param uid the Uid-encoded binary representation (from {@link Uid#encodeId(String)})
     */
    public void setSyntheticId(int i, String id, BytesRef uid) {
        final int absIdx = abs(i);
        this.ids[absIdx] = id;
        this.uids[absIdx] = uid;
    }

    public String routingString(int i) {
        final int absIdx = abs(i);
        if (routings == null) {
            return null;
        }
        final BytesRef r = routings[absIdx];
        return r != null ? r.utf8ToString() : null;
    }

    public XContentType contentType(int i) {
        return contentTypes[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> content-type array. Entries default to
     * {@link XContentType#JSON} when the request had none. Callers must combine it with
     * {@link #offset()} and {@link #docCount()}.
     */
    public XContentType[] contentTypes() {
        return contentTypes;
    }

    /**
     * The raw, <b>full-batch-sized</b> source array. Individual entries may be {@code null} for
     * documents that carry no source. Callers must combine it with {@link #offset()} and
     * {@link #docCount()}.
     */
    public BytesReference[] sources() {
        return sources;
    }

    /** {@link SequenceNumbers#UNASSIGNED_SEQ_NO} when no CAS condition was set. */
    public long ifSeqNo(int i) {
        final int absIdx = abs(i);
        return ifSeqNo != null ? ifSeqNo[absIdx] : SequenceNumbers.UNASSIGNED_SEQ_NO;
    }

    /** {@code 0} when no CAS condition was set. */
    public long ifPrimaryTerm(int i) {
        final int absIdx = abs(i);
        return ifPrimaryTerm != null ? ifPrimaryTerm[absIdx] : 0L;
    }

    /** Negative if the id was not auto-generated. */
    public long autoGeneratedIdTimestamp(int i) {
        return autoGeneratedIdTimestamp[abs(i)];
    }

    public SourceBatch sourceBatch() {
        return sourceBatch;
    }

    /**
     * Mutable {@code _seq_no} buffer (little-endian longs, full-batch-sized). Pre-filled with
     * {@link SequenceNumbers#UNASSIGNED_SEQ_NO} on PRIMARY; the engine stamps real values after
     * planning. Aliased into {@link MappedColumns} by reference — engine writes are visible to
     * Lucene columns without copying. Slices return the same {@link BytesRef} as the parent.
     *
     * <p>This buffer is <em>not</em> offset-adjusted. External mutators that hold a slice must add
     * {@link #offset()} when computing the byte position:
     * {@code ByteUtils.writeLongLE(v, slice.seqNoBytes().bytes, (slice.offset() + i) * 8)}.
     */
    public BytesRef seqNoBytes() {
        return seqNoBytes;
    }

    /** Mutable {@code _primary_term} buffer; same shape and aliasing contract as {@link #seqNoBytes()}. */
    public BytesRef primaryTermBytes() {
        return primaryTermBytes;
    }

    /** Mutable {@code _version} buffer; same shape and aliasing contract as {@link #seqNoBytes()}. */
    public BytesRef versionBytes() {
        return versionBytes;
    }

    public long seqNo(int i) {
        return ByteUtils.readLongLE(seqNoBytes.bytes, abs(i) * 8);
    }

    public long version(int i) {
        return ByteUtils.readLongLE(versionBytes.bytes, abs(i) * 8);
    }

    /**
     * Materializes a single {@link Engine.Index} for position {@code i} in this batch slice.
     * Reads seqNo/primaryTerm/version from the aliased byte arrays at call time, so this reflects
     * whatever values have been stamped (e.g. after primary seqNo assignment).
     */
    public Engine.Index toIndexOp(int i) {
        final int absIdx = abs(i);
        final String routing = routings != null && routings[absIdx] != null ? routings[absIdx].utf8ToString() : null;
        // TODO: The SourceToParse using a size of 0 makes estimated sizes off in index listeners.
        // We will eventually replace those listeners with batch calls.
        final ParsedDocument doc = new ParsedDocument(
            null,
            null,
            ids[absIdx],
            routing,
            List.of(),
            SourceToParse.Source.fromBytes(BytesArray.EMPTY, XContentType.JSON),
            null,
            0
        );
        return new Engine.Index(
            uids[absIdx],
            doc,
            ByteUtils.readLongLE(seqNoBytes.bytes, absIdx * 8),
            primaryTerm,
            requestedVersion[absIdx],
            versionType[absIdx],
            origin,
            startTime,
            autoGeneratedIdTimestamp[absIdx],
            isRetry[absIdx],
            ifSeqNo(i),
            ifPrimaryTerm(i)
        );
    }

    /**
     * Reconstructs {@link Engine.Index} ops from the flat arrays for listener callbacks. Each op
     * carries a minimal {@link ParsedDocument} (id and routing only). SeqNo/version reflect
     * whatever is currently stamped in the byte arrays.
     */
    public List<Engine.Index> materializeIndexOps() {
        final Engine.Index[] ops = new Engine.Index[docCount];
        for (int i = 0; i < docCount; i++) {
            ops[i] = toIndexOp(i);
        }
        return List.of(ops);
    }

    private int abs(int i) {
        Objects.checkIndex(i, docCount);
        return offset + i;
    }

    /**
     * Builds the translog representation of this batch.
     */
    public TranslogRecord toTranslogRecord(byte[] rowStatuses, @Nullable String[] noOpReasons) {
        if (rowStatuses.length != docCount) {
            throw new IllegalArgumentException(
                "rowStatuses length [" + rowStatuses.length + "] does not match batch docCount [" + docCount + "]"
            );
        }

        final long[] seqNos = new long[docCount];
        final long[] versions = new long[docCount];
        final long[] timestamps = new long[docCount];
        final XContentType[] types = new XContentType[docCount];
        final BytesRef[] rowUids = new BytesRef[docCount];
        // Don't allocate routings and reasons upfront
        String[] rowRoutings = null;
        String[] reasons = null;
        for (int i = 0; i < docCount; i++) {
            switch (rowStatuses[i]) {
                case TranslogRecord.ROW_INDEXED -> {
                    seqNos[i] = seqNo(i);
                    versions[i] = version(i);
                    timestamps[i] = autoGeneratedIdTimestamp(i);
                    types[i] = contentType(i);
                    rowUids[i] = uid(i);
                    final String routing = routingString(i);
                    // If routing is non-null, allocate and set it for this row.
                    if (routing != null) {
                        if (rowRoutings == null) {
                            rowRoutings = new String[docCount];
                        }
                        rowRoutings[i] = routing;
                    }
                }
                case TranslogRecord.ROW_NO_OP -> {
                    seqNos[i] = seqNo(i);
                    assert noOpReasons != null : "NO_OP must have a reason";
                    if (reasons == null) {
                        reasons = new String[docCount];
                    }
                    reasons[i] = noOpReasons[i];
                    assert reasons[i] != null : "NO_OP must have a reason";
                }
                case TranslogRecord.ROW_PREFLIGHT_ERROR -> {
                    seqNos[i] = SequenceNumbers.UNASSIGNED_SEQ_NO;
                }
                default -> throw new IllegalArgumentException("unknown row status [" + rowStatuses[i] + "] for row [" + i + "]");
            }
        }
        return new TranslogRecord(
            primaryTerm,
            rowStatuses,
            seqNos,
            versions,
            timestamps,
            types,
            rowUids,
            rowRoutings,
            reasons,
            sourceBatch.data()
        );
    }

    /**
     * The translog representation of an {@link IndexOperationBatch}
     * Fields of this record are written to the translog metadata in the header
     *
     * <p>{@code routings} is null when no row carries a routing value, and {@code noOpReasons} is
     * null when no row is a {@link #ROW_NO_OP}; callers pass an array only when it has at least
     * one non-null element.
     */
    public record TranslogRecord(
        long primaryTerm,
        byte[] rowStatuses,
        long[] seqNos,
        long[] versions,
        long[] autoGeneratedIdTimestamps,
        XContentType[] contentTypes,
        BytesRef[] uids,
        @Nullable String[] routings,
        @Nullable String[] noOpReasons,
        BytesReference batchData
    ) implements Translog.Record, Writeable {

        /**
         * Wire-format version for batch records. The batch format is not yet considered stable;
         * readers reject any value other than this constant rather than negotiating backwards
         * compatibility.
         */
        public static final int EXPERIMENTAL_PRE_RELEASE = 0;

        /** The row was successfully indexed and replays as a {@link Translog.Index}. */
        public static final byte ROW_INDEXED = 0;
        /** The row failed after consuming a seqNo and replays as a {@link Translog.NoOp}. */
        public static final byte ROW_NO_OP = 1;
        /** The row hit a preflight failure. */
        public static final byte ROW_PREFLIGHT_ERROR = 2;

        public TranslogRecord {
            Objects.requireNonNull(batchData, "batchData");

            // Ensure all lengths are the same
            final int docCount = rowStatuses.length;
            checkLength("seqNos", seqNos.length, docCount);
            checkLength("versions", versions.length, docCount);
            checkLength("autoGeneratedIdTimestamps", autoGeneratedIdTimestamps.length, docCount);
            checkLength("contentTypes", contentTypes.length, docCount);
            checkLength("uids", uids.length, docCount);
            if (routings != null) {
                checkLength("routings", routings.length, docCount);
                assert nonNullValueInNonNullArray(routings) : "a non-null array must contain at least one non-null value";
            }
            if (noOpReasons != null) {
                checkLength("noOpReasons", noOpReasons.length, docCount);
                assert nonNullValueInNonNullArray(noOpReasons) : "a non-null array must contain at least one non-null value";
            }

            int operations = 0;
            for (int i = 0; i < rowStatuses.length; i++) {
                switch (rowStatuses[i]) {
                    case ROW_INDEXED -> operations++;
                    case ROW_NO_OP -> {
                        assert noOpReasons != null && noOpReasons[i] != null : "NO_OP row [" + i + "] must have a reason";
                        operations++;
                    }
                    case ROW_PREFLIGHT_ERROR -> {
                        // never consumed a seqNo; nothing to replay
                    }
                    default -> throw new IllegalArgumentException("unknown row status [" + rowStatuses[i] + "] for row [" + i + "]");
                }
            }
            if (operations == 0) {
                throw new IllegalArgumentException("a batch must contain at least one replayable row");
            }
        }

        /** The number of rows in this batch, replayable or not; always matches the source batch. */
        public int docCount() {
            return rowStatuses.length;
        }

        public byte rowStatus(int i) {
            return rowStatuses[i];
        }

        public long seqNo(int i) {
            return seqNos[i];
        }

        /** The routing value of row {@code i}, or null if the row has none. */
        @Nullable
        public String routing(int i) {
            return routings == null ? null : routings[i];
        }

        /** The number of rows that replay as an operation, i.e. rows not {@link #ROW_PREFLIGHT_ERROR}. */
        public int operationCount() {
            int count = 0;
            for (byte status : rowStatuses) {
                if (status != ROW_PREFLIGHT_ERROR) {
                    count++;
                }
            }
            return count;
        }

        private static void checkLength(String name, int length, int expected) {
            assert length == expected : name + " length [" + length + "] does not match row count [" + expected + "]";
        }

        /**
         * A non-null array must carry at least one non-null value (a value-free array is stored
         * as null); returns true when the array is null or has a non-null element.
         */
        private static boolean nonNullValueInNonNullArray(@Nullable String[] values) {
            if (values == null) {
                return true;
            }
            for (String value : values) {
                if (value != null) {
                    return true;
                }
            }
            return false;
        }

        public static TranslogRecord readFrom(StreamInput in) throws IOException {
            final int format = in.readVInt();
            if (format != EXPERIMENTAL_PRE_RELEASE) {
                throw new IOException("unsupported translog batch format [" + format + "], expected [" + EXPERIMENTAL_PRE_RELEASE + "]");
            }
            final long primaryTerm = in.readLong();
            final int docCount = in.readVInt();
            if (docCount <= 0) {
                throw new IOException("invalid batch row count [" + docCount + "]");
            }
            final byte[] rowStatuses = new byte[docCount];
            in.readBytes(rowStatuses, 0, docCount);
            final long[] seqNos = new long[docCount];
            final long[] versions = new long[docCount];
            final long[] timestamps = new long[docCount];
            final XContentType[] types = new XContentType[docCount];
            final BytesRef[] uids = new BytesRef[docCount];
            for (int i = 0; i < docCount; i++) {
                switch (rowStatuses[i]) {
                    case ROW_INDEXED -> {
                        versions[i] = in.readLong();
                        seqNos[i] = in.readLong();
                        timestamps[i] = in.readLong();
                        types[i] = XContentType.ofOrdinal(in.readByte());
                        uids[i] = in.readBytesRef();
                    }
                    case ROW_NO_OP -> seqNos[i] = in.readLong();
                    case ROW_PREFLIGHT_ERROR -> {
                        seqNos[i] = SequenceNumbers.UNASSIGNED_SEQ_NO;
                    }
                    default -> throw new IOException("unknown row status [" + rowStatuses[i] + "] for row [" + i + "]");
                }
            }
            final String[] routings = readOptionalRowArray(in, "routings", docCount);
            final String[] reasons = readOptionalRowArray(in, "noOpReasons", docCount);
            final BytesReference batchData = in.readBytesReference();
            return new TranslogRecord(primaryTerm, rowStatuses, seqNos, versions, timestamps, types, uids, routings, reasons, batchData);
        }

        @Nullable
        private static String[] readOptionalRowArray(StreamInput in, String name, int docCount) throws IOException {
            final String[] values = in.readOptionalArray(StreamInput::readOptionalString, String[]::new);
            if (values != null && values.length != docCount) {
                throw new IOException(name + " length [" + values.length + "] does not match batch row count [" + docCount + "]");
            }
            return values;
        }

        @Override
        public void writeTo(StreamOutput out) throws IOException {
            out.writeByte(Translog.Record.Type.BATCH.id());
            writeHeader(out);
            batchData.writeTo(out);
        }

        /**
         * Writes every body field except the {@link #batchData} bytes themselves (their vint
         * length prefix is included). See {@link Translog#writeBatchHeaderWithSize}
         */
        public void writeHeader(StreamOutput out) throws IOException {
            out.writeVInt(EXPERIMENTAL_PRE_RELEASE);
            out.writeLong(primaryTerm);
            final int docCount = rowStatuses.length;
            out.writeVInt(docCount);
            out.writeBytes(rowStatuses, 0, docCount);
            for (int i = 0; i < docCount; i++) {
                switch (rowStatuses[i]) {
                    case ROW_INDEXED -> {
                        out.writeLong(versions[i]);
                        out.writeLong(seqNos[i]);
                        out.writeLong(autoGeneratedIdTimestamps[i]);
                        out.writeByte((byte) contentTypes[i].ordinal());
                        out.writeBytesRef(uids[i]);
                    }
                    case ROW_NO_OP -> out.writeLong(seqNos[i]);
                    case ROW_PREFLIGHT_ERROR -> {
                        // nothing to write; the status byte alone reconstructs the row
                    }
                    default -> throw new AssertionError("unknown row status [" + rowStatuses[i] + "]");
                }
            }
            // whole-array optionals: a batch without routing values or no-op rows costs one byte each
            assert nonNullValueInNonNullArray(routings) : "a non-null routings array must contain at least one non-null value";
            assert nonNullValueInNonNullArray(noOpReasons) : "a non-null noOpReasons array must contain at least one non-null value";
            out.writeOptionalArray(StreamOutput::writeOptionalString, routings);
            out.writeOptionalArray(StreamOutput::writeOptionalString, noOpReasons);
            out.writeVInt(batchData.length());
        }

        /**
         * Decodes this batch back into one {@link Translog.Operation} per replayable row,
         * reconstructing each indexed source via {@link SourceRowToXContent#writeRowFromSchema} in
         * the original {@link XContentType}. {@link #ROW_NO_OP} rows decode to
         * {@link Translog.NoOp} records; {@link #ROW_PREFLIGHT_ERROR} rows are omitted.
         */
        public List<Translog.Operation> explode() throws IOException {
            try (SourceBatch sourceBatch = EscfBatch.parse(batchData, () -> {})) {
                final int docCount = checkRowCount(sourceBatch);
                final SourceRowXContentParser.SchemaNode schemaTree = SourceRowXContentParser.buildSchemaTree(sourceBatch.schema());
                final List<Translog.Operation> out = new ArrayList<>(operationCount());
                for (int i = 0; i < docCount; i++) {
                    switch (rowStatuses[i]) {
                        case ROW_INDEXED -> out.add(toIndex(sourceBatch, schemaTree, i));
                        case ROW_NO_OP -> out.add(new Translog.NoOp(seqNos[i], primaryTerm, noOpReasons[i]));
                        case ROW_PREFLIGHT_ERROR -> {
                            // never consumed a seqNo; nothing to replay
                        }
                        default -> throw new AssertionError("unknown row status [" + rowStatuses[i] + "]");
                    }
                }
                return out;
            }
        }

        /**
         * Gets a single document's {@link Translog.Index} operation from this batch by row index,
         * without re-materializing the other rows.
         *
         * @throws IOException if the row is out of range or is not a {@link #ROW_INDEXED} row
         */
        public Translog.Index getIndexOp(int rowIndex) throws IOException {
            if (rowIndex < 0 || rowIndex >= rowStatuses.length) {
                throw new IOException("row [" + rowIndex + "] out of range for batch with [" + rowStatuses.length + "] rows");
            }
            if (rowStatuses[rowIndex] != ROW_INDEXED) {
                throw new IOException("row [" + rowIndex + "] is not an indexed row (status [" + rowStatuses[rowIndex] + "])");
            }
            try (SourceBatch sourceBatch = EscfBatch.parse(batchData, () -> {})) {
                checkRowCount(sourceBatch);
                final SourceRowXContentParser.SchemaNode schemaTree = SourceRowXContentParser.buildSchemaTree(sourceBatch.schema());
                return toIndex(sourceBatch, schemaTree, rowIndex);
            }
        }

        private int checkRowCount(SourceBatch sourceBatch) throws IOException {
            final int docCount = rowStatuses.length;
            if (sourceBatch.docCount() != docCount) {
                throw new IOException(
                    "batch metadata covers [" + docCount + "] rows but batch data contains [" + sourceBatch.docCount() + "] rows"
                );
            }
            return docCount;
        }

        private Translog.Index toIndex(SourceBatch sourceBatch, SourceRowXContentParser.SchemaNode schemaTree, int i) throws IOException {
            final SourceRow row = sourceBatch.row(i);
            final BytesReference source;
            try (XContentBuilder builder = XContentBuilder.builder(contentTypes[i].xContent())) {
                SourceRowToXContent.writeRowFromSchema(row, schemaTree, builder);
                source = BytesReference.bytes(builder);
            }
            return new Translog.Index(uids[i], seqNos[i], primaryTerm, versions[i], source, routing(i), autoGeneratedIdTimestamps[i]);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o instanceof TranslogRecord other) {
                return primaryTerm == other.primaryTerm
                    && Arrays.equals(rowStatuses, other.rowStatuses)
                    && Arrays.equals(seqNos, other.seqNos)
                    && Arrays.equals(versions, other.versions)
                    && Arrays.equals(autoGeneratedIdTimestamps, other.autoGeneratedIdTimestamps)
                    && Arrays.equals(contentTypes, other.contentTypes)
                    && Arrays.equals(uids, other.uids)
                    && Arrays.equals(routings, other.routings)
                    && Arrays.equals(noOpReasons, other.noOpReasons)
                    && batchData.equals(other.batchData);
            }
            return false;
        }

        @Override
        public int hashCode() {
            int result = Long.hashCode(primaryTerm);
            result = 31 * result + Arrays.hashCode(rowStatuses);
            result = 31 * result + Arrays.hashCode(seqNos);
            result = 31 * result + Arrays.hashCode(versions);
            result = 31 * result + Arrays.hashCode(autoGeneratedIdTimestamps);
            result = 31 * result + Arrays.hashCode(contentTypes);
            result = 31 * result + Arrays.hashCode(uids);
            result = 31 * result + Arrays.hashCode(routings);
            result = 31 * result + Arrays.hashCode(noOpReasons);
            result = 31 * result + batchData.hashCode();
            return result;
        }
    }

}
