/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.apache.lucene.util.BytesRef;
import org.elasticsearch.action.bulk.BulkItemRequest;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.util.ByteUtils;
import org.elasticsearch.core.Nullable;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.mapper.ParsedDocument;
import org.elasticsearch.index.mapper.SourceToParse;
import org.elasticsearch.index.mapper.Uid;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.sourcebatch.MappedColumns;
import org.elasticsearch.sourcebatch.SourceBatch;
import org.elasticsearch.xcontent.XContentType;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

/**
 * Flattened, low-level batch of index operations — per-doc data in parallel arrays indexed
 * {@code [0, docCount)}.
 *
 * <p>{@link #seqNoBytes()}, {@link #primaryTermBytes()}, and {@link #versionBytes()} are aliased
 * into {@link MappedColumns} by reference; engine writes are visible to Lucene columns without
 * copying. Slices share all backing arrays with the parent; only the {@link SourceBatch} is
 * re-sliced. Use {@link #offset()} to find per-doc positions within the full-batch-sized arrays.
 */
public final class IndexOperationBatch {

    // Batch Level Characteristics

    private final Engine.Operation.Origin origin;
    private final long startTime;
    private final long primaryTerm;

    // Sliced Metadata

    private final int offset;
    private final int docCount;

    // Transient Indexing Metadata

    private final String[] ids;
    // TODO: Will go away when we make source mappers operation directly on SourceBatch
    private final BytesReference[] sources;
    private final long[] requestedVersion;
    private final VersionType[] versionType;
    // null when no document has a CAS condition; accessors return the sentinel value when null.
    private final long[] ifSeqNo;
    private final long[] ifPrimaryTerm;
    private final boolean[] isRetry;

    // Translog Storage - stored in the translog

    private final BytesRef[] uids;
    private final long[] autoGeneratedIdTimestamp;
    // null when no document has explicit routing.
    private final BytesRef[] routings;
    // null when no document carries a coordinator-computed tsid (set only for time_series indices).
    private final BytesRef[] tsids;
    private final XContentType[] contentTypes;

    // Aliased into MappedColumns — engine writes are visible to Lucene columns without copying.
    private final BytesRef seqNoBytes;
    private final BytesRef primaryTermBytes;
    private final BytesRef versionBytes;

    private final SourceBatch sourceBatch;

    IndexOperationBatch(
        Engine.Operation.Origin origin,
        long startTime,
        long primaryTerm,
        int offset,
        int docCount,
        BytesRef[] uids,
        String[] ids,
        @Nullable BytesRef[] routings,
        @Nullable BytesRef[] tsids,
        XContentType[] contentTypes,
        BytesReference[] sources,
        long[] requestedVersion,
        VersionType[] versionType,
        @Nullable long[] ifSeqNo,
        @Nullable long[] ifPrimaryTerm,
        long[] autoGeneratedIdTimestamp,
        boolean[] isRetry,
        @Nullable SourceBatch sourceBatch,
        BytesRef seqNoBytes,
        BytesRef primaryTermBytes,
        BytesRef versionBytes
    ) {
        assert docCount >= 1 : "batch must contain at least one document, got docCount [" + docCount + "]";
        assert offset >= 0 : "offset must be non-negative, got [" + offset + "]";
        assert assertArraysCover(
            offset,
            docCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
        this.origin = origin;
        this.startTime = startTime;
        this.primaryTerm = primaryTerm;
        this.offset = offset;
        this.docCount = docCount;
        this.uids = uids;
        this.ids = ids;
        this.routings = routings;
        this.tsids = tsids;
        this.contentTypes = contentTypes;
        this.sources = sources;
        this.requestedVersion = requestedVersion;
        this.versionType = versionType;
        this.ifSeqNo = ifSeqNo;
        this.ifPrimaryTerm = ifPrimaryTerm;
        this.autoGeneratedIdTimestamp = autoGeneratedIdTimestamp;
        this.isRetry = isRetry;
        this.sourceBatch = sourceBatch;
        this.seqNoBytes = seqNoBytes;
        this.primaryTermBytes = primaryTermBytes;
        this.versionBytes = versionBytes;
    }

    private static boolean assertArraysCover(
        int offset,
        int docCount,
        BytesRef[] uids,
        String[] ids,
        @Nullable BytesRef[] routings,
        @Nullable BytesRef[] tsids,
        XContentType[] contentTypes,
        BytesReference[] sources,
        long[] requestedVersion,
        VersionType[] versionType,
        @Nullable long[] ifSeqNo,
        @Nullable long[] ifPrimaryTerm,
        long[] autoGeneratedIdTimestamp,
        boolean[] isRetry,
        BytesRef seqNoBytes,
        BytesRef primaryTermBytes,
        BytesRef versionBytes
    ) {
        final int end = offset + docCount;
        assertCovers("uids", uids.length, end);
        assertCovers("ids", ids.length, end);
        assertCovers("contentTypes", contentTypes.length, end);
        assertCovers("sources", sources.length, end);
        assertCovers("requestedVersion", requestedVersion.length, end);
        assertCovers("versionType", versionType.length, end);
        assertCovers("autoGeneratedIdTimestamp", autoGeneratedIdTimestamp.length, end);
        assertCovers("isRetry", isRetry.length, end);
        if (routings != null) {
            assertCovers("routings", routings.length, end);
        }
        if (tsids != null) {
            assertCovers("tsids", tsids.length, end);
        }
        if (ifSeqNo != null) {
            assertCovers("ifSeqNo", ifSeqNo.length, end);
        }
        if (ifPrimaryTerm != null) {
            assertCovers("ifPrimaryTerm", ifPrimaryTerm.length, end);
        }
        assertLongBuffer("seqNoBytes", seqNoBytes, end);
        assertLongBuffer("primaryTermBytes", primaryTermBytes, end);
        assertLongBuffer("versionBytes", versionBytes, end);
        return true;
    }

    private static void assertCovers(String name, int length, int end) {
        assert length >= end : name + " length [" + length + "] does not cover window up to [" + end + ")";
    }

    private static void assertLongBuffer(String name, BytesRef buf, int end) {
        assert buf.offset == 0 : name + " must be a zero-offset BytesRef, got offset [" + buf.offset + "]";
        assertCovers(name, buf.bytes.length / 8, end);
    }

    /**
     * Production entry point. Reads items {@code [from, to)}. On REPLICA, seqNo/primaryTerm/version
     * are copied from primary responses and versionType is {@code null}. On PRIMARY, seqNoBytes is
     * pre-filled with {@link SequenceNumbers#UNASSIGNED_SEQ_NO}; the engine stamps real values after
     * planning.
     */
    public static IndexOperationBatch initFromBulk(
        BulkItemRequest[] items,
        int from,
        int to,
        SourceBatch chunkSource,
        Engine.Operation.Origin origin,
        long primaryTerm,
        long startTime
    ) {
        Objects.checkFromToIndex(from, to, items.length);
        if (from == to) {
            throw new IllegalArgumentException("empty batch [" + from + ", " + to + "); initFromBulk requires at least one item");
        }
        final int docCount = to - from;
        final BytesRef[] uids = new BytesRef[docCount];
        final String[] ids = new String[docCount];
        final long[] requestedVersion = new long[docCount];
        final VersionType[] versionType = new VersionType[docCount];
        long[] ifSeqNoBuf = null;
        long[] ifPrimaryTermBuf = null;
        final long[] autoGeneratedIdTimestamp = new long[docCount];
        final boolean[] isRetry = new boolean[docCount];
        BytesRef[] routings = null;
        BytesRef[] tsids = null;
        final XContentType[] contentTypes = new XContentType[docCount];
        final BytesReference[] sources = new BytesReference[docCount];

        final BytesRef seqNoBytes = new BytesRef(new byte[docCount * 8]);
        final BytesRef primaryTermBytes = new BytesRef(new byte[docCount * 8]);
        final BytesRef versionBytes = new BytesRef(new byte[docCount * 8]);

        if (origin != Engine.Operation.Origin.REPLICA) {
            for (int d = 0; d < docCount; d++) {
                ByteUtils.writeLongLE(SequenceNumbers.UNASSIGNED_SEQ_NO, seqNoBytes.bytes, d * 8);
            }
        }

        for (int d = 0; d < docCount; d++) {
            final IndexRequest request = (IndexRequest) items[from + d].request();
            final String id = request.id();
            ids[d] = id;
            if (id != null) {
                uids[d] = Uid.encodeId(id);
            }
            final String routing = request.routing();
            if (routing != null) {
                if (routings == null) {
                    routings = new BytesRef[docCount];
                }
                routings[d] = new BytesRef(routing);
            }
            final BytesRef tsid = request.tsid();
            if (tsid != null) {
                if (tsids == null) {
                    tsids = new BytesRef[docCount];
                }
                tsids[d] = tsid;
            }
            final XContentType ct = request.getContentType();
            contentTypes[d] = ct != null ? ct : XContentType.JSON;
            sources[d] = request.source();

            if (origin == Engine.Operation.Origin.REPLICA) {
                final org.elasticsearch.action.DocWriteResponse resp = items[from + d].getPrimaryResponse().getResponse();
                ByteUtils.writeLongLE(resp.getSeqNo(), seqNoBytes.bytes, d * 8);
                ByteUtils.writeLongLE(resp.getPrimaryTerm(), primaryTermBytes.bytes, d * 8);
                ByteUtils.writeLongLE(resp.getVersion(), versionBytes.bytes, d * 8);
                requestedVersion[d] = resp.getVersion();
                versionType[d] = null;
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            } else {
                requestedVersion[d] = request.version();
                versionType[d] = request.versionType();
                final long ifSeq = request.ifSeqNo();
                if (ifSeq != SequenceNumbers.UNASSIGNED_SEQ_NO) {
                    if (ifSeqNoBuf == null) {
                        ifSeqNoBuf = new long[docCount];
                        Arrays.fill(ifSeqNoBuf, SequenceNumbers.UNASSIGNED_SEQ_NO);
                    }
                    ifSeqNoBuf[d] = ifSeq;
                }
                final long ifPT = request.ifPrimaryTerm();
                if (ifPT != 0L) {
                    if (ifPrimaryTermBuf == null) {
                        ifPrimaryTermBuf = new long[docCount];
                    }
                    ifPrimaryTermBuf[d] = ifPT;
                }
                autoGeneratedIdTimestamp[d] = request.getAutoGeneratedTimestamp();
                isRetry[d] = request.isRetry();
            }
        }

        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            0,
            docCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNoBuf,
            ifPrimaryTermBuf,
            autoGeneratedIdTimestamp,
            isRetry,
            chunkSource,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
    }

    /**
     * Returns a view of {@code [from, to)} sharing all backing arrays with the parent. Only the
     * {@link SourceBatch} is re-sliced; seqNo/primaryTerm/version arrays remain full-batch-sized.
     *
     * @throws IndexOutOfBoundsException if the range is invalid
     */
    public IndexOperationBatch slice(int from, int to) {
        Objects.checkFromToIndex(from, to, docCount);
        if (from == to) {
            throw new IllegalArgumentException("empty slice [" + from + ", " + to + "); a batch must contain at least one document");
        }
        final int newCount = to - from;
        final int newOffset = this.offset + from;
        final SourceBatch slicedSource = (sourceBatch != null) ? sourceBatch.slice(from, to) : null;
        return new IndexOperationBatch(
            origin,
            startTime,
            primaryTerm,
            newOffset,
            newCount,
            uids,
            ids,
            routings,
            tsids,
            contentTypes,
            sources,
            requestedVersion,
            versionType,
            ifSeqNo,
            ifPrimaryTerm,
            autoGeneratedIdTimestamp,
            isRetry,
            slicedSource,
            seqNoBytes,
            primaryTermBytes,
            versionBytes
        );
    }

    public Engine.Operation.Origin origin() {
        return origin;
    }

    public long startTime() {
        return startTime;
    }

    public long primaryTerm() {
        return primaryTerm;
    }

    public int docCount() {
        return docCount;
    }

    public int offset() {
        return offset;
    }

    public BytesRef uid(int i) {
        return uids[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> uid array — not offset-adjusted and not trimmed to this
     * batch's range. Callers must combine it with {@link #offset()} and {@link #docCount()};
     * index {@code i} in this batch lives at {@code uids()[offset() + i]}.
     */
    public BytesRef[] uids() {
        return uids;
    }

    public String id(int i) {
        return ids[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> routing array, or {@code null} if no document has explicit
     * routing. When non-null, individual entries may still be {@code null}. Callers must combine it
     * with {@link #offset()} and {@link #docCount()}.
     */
    public BytesRef[] routings() {
        return routings;
    }

    /**
     * The raw, <b>full-batch-sized</b> tsid array, or {@code null} if no document carries a
     * coordinator-computed tsid (only set for {@code time_series} indices). When non-null,
     * individual entries may still be {@code null} for documents whose tsid was not set.
     * Callers must combine it with {@link #offset()} and {@link #docCount()}.
     */
    @Nullable
    public BytesRef[] tsids() {
        return tsids;
    }

    /**
     * Sets the synthetic {@code _id} and uid for document {@code i} in this batch slice.
     *
     * @param i   document index within this slice ({@code 0..docCount-1})
     * @param id  the plain-text id
     * @param uid the Uid-encoded binary representation (from {@link Uid#encodeId(String)})
     */
    public void setSyntheticId(int i, String id, BytesRef uid) {
        final int absIdx = abs(i);
        this.ids[absIdx] = id;
        this.uids[absIdx] = uid;
    }

    public String routingString(int i) {
        final int absIdx = abs(i);
        if (routings == null) {
            return null;
        }
        final BytesRef r = routings[absIdx];
        return r != null ? r.utf8ToString() : null;
    }

    public XContentType contentType(int i) {
        return contentTypes[abs(i)];
    }

    /**
     * The raw, <b>full-batch-sized</b> content-type array. Entries default to
     * {@link XContentType#JSON} when the request had none. Callers must combine it with
     * {@link #offset()} and {@link #docCount()}.
     */
    public XContentType[] contentTypes() {
        return contentTypes;
    }

    /**
     * The raw, <b>full-batch-sized</b> source array. Individual entries may be {@code null} for
     * documents that carry no source. Callers must combine it with {@link #offset()} and
     * {@link #docCount()}.
     */
    public BytesReference[] sources() {
        return sources;
    }

    /** {@link SequenceNumbers#UNASSIGNED_SEQ_NO} when no CAS condition was set. */
    public long ifSeqNo(int i) {
        final int absIdx = abs(i);
        return ifSeqNo != null ? ifSeqNo[absIdx] : SequenceNumbers.UNASSIGNED_SEQ_NO;
    }

    /** {@code 0} when no CAS condition was set. */
    public long ifPrimaryTerm(int i) {
        final int absIdx = abs(i);
        return ifPrimaryTerm != null ? ifPrimaryTerm[absIdx] : 0L;
    }

    /** Negative if the id was not auto-generated. */
    public long autoGeneratedIdTimestamp(int i) {
        return autoGeneratedIdTimestamp[abs(i)];
    }

    public SourceBatch sourceBatch() {
        return sourceBatch;
    }

    /**
     * Mutable {@code _seq_no} buffer (little-endian longs, full-batch-sized). Pre-filled with
     * {@link SequenceNumbers#UNASSIGNED_SEQ_NO} on PRIMARY; the engine stamps real values after
     * planning. Aliased into {@link MappedColumns} by reference — engine writes are visible to
     * Lucene columns without copying. Slices return the same {@link BytesRef} as the parent.
     *
     * <p>This buffer is <em>not</em> offset-adjusted. External mutators that hold a slice must add
     * {@link #offset()} when computing the byte position:
     * {@code ByteUtils.writeLongLE(v, slice.seqNoBytes().bytes, (slice.offset() + i) * 8)}.
     */
    public BytesRef seqNoBytes() {
        return seqNoBytes;
    }

    /** Mutable {@code _primary_term} buffer; same shape and aliasing contract as {@link #seqNoBytes()}. */
    public BytesRef primaryTermBytes() {
        return primaryTermBytes;
    }

    /** Mutable {@code _version} buffer; same shape and aliasing contract as {@link #seqNoBytes()}. */
    public BytesRef versionBytes() {
        return versionBytes;
    }

    public long seqNo(int i) {
        return ByteUtils.readLongLE(seqNoBytes.bytes, abs(i) * 8);
    }

    /**
     * Materializes a single {@link Engine.Index} for position {@code i} in this batch slice.
     * Reads seqNo/primaryTerm/version from the aliased byte arrays at call time, so this reflects
     * whatever values have been stamped (e.g. after primary seqNo assignment).
     */
    public Engine.Index toIndexOp(int i) {
        final int absIdx = abs(i);
        final String routing = routings != null && routings[absIdx] != null ? routings[absIdx].utf8ToString() : null;
        // TODO: The SourceToParse using a size of 0 makes estimated sizes off in index listeners.
        // We will eventually replace those listeners with batch calls.
        final ParsedDocument doc = new ParsedDocument(
            null,
            null,
            ids[absIdx],
            routing,
            List.of(),
            SourceToParse.Source.fromBytes(BytesArray.EMPTY, XContentType.JSON),
            null,
            0
        );
        return new Engine.Index(
            uids[absIdx],
            doc,
            ByteUtils.readLongLE(seqNoBytes.bytes, absIdx * 8),
            primaryTerm,
            requestedVersion[absIdx],
            versionType[absIdx],
            origin,
            startTime,
            autoGeneratedIdTimestamp[absIdx],
            isRetry[absIdx],
            ifSeqNo(i),
            ifPrimaryTerm(i)
        );
    }

    /**
     * Reconstructs {@link Engine.Index} ops from the flat arrays for listener callbacks. Each op
     * carries a minimal {@link ParsedDocument} (id and routing only). SeqNo/version reflect
     * whatever is currently stamped in the byte arrays.
     */
    public List<Engine.Index> materializeIndexOps() {
        final Engine.Index[] ops = new Engine.Index[docCount];
        for (int i = 0; i < docCount; i++) {
            ops[i] = toIndexOp(i);
        }
        return List.of(ops);
    }

    /**
     * Keep a copy of listener ops for {@link org.elasticsearch.index.shard.IndexingOperationListener}
     */
    private List<Engine.Index> listenerOps;

    /**
     * Return the {@link #listenerOps} for {@link org.elasticsearch.index.shard.IndexingOperationListener}
     * batch callbacks: pre and post hooks see the same (pre-seqNo-stamping) ops.
     * Engine must keep using {@link #materializeIndexOps()} since this returns a pre-index memo
     */
    public List<Engine.Index> listenerOps() {
        if (listenerOps == null) {
            listenerOps = materializeIndexOps();
        }
        return listenerOps;
    }

    private int abs(int i) {
        Objects.checkIndex(i, docCount);
        return offset + i;
    }

}
