==== Connect clients to {es}

When you start {es} for the first time, it generates a hex-coded SHA-256
fingerprint of the generated HTTPS CA DER-encoded certificate in the terminal.
To connect your client to {es}, copy this fingerprint and pass it as a parameter.
Any clients that connect to {es}, such as the 
https://www.elastic.co/guide/en/elasticsearch/client/index.html[{es} Clients],
{beats}, {ls}, and {fleet} can verify that any certificate in the chain
matches the fingerprint.

If the auto-configuration process already completed, you can still obtain the 
fingerprint of the security certificate. Run the following command on any
node in the {es} cluster that you want to connect to.

[source,sh]
----
openssl x509 -fingerprint -sha256 -in config/tls_auto_config_<timestamp>/http_ca.crt
----

`<timestamp>`:: The timestamp of when the auto-configuration process created the security files directory.

The command returns the the security certificate, including the fingerprint.
The `issuer` should be `Elasticsearch security auto-configuration HTTP CA`.

[source,sh]
----
issuer= /CN=Elasticsearch security auto-configuration HTTP CA
SHA256 Fingerprint=<fingerprint>
----