==== Running Elasticsearch from the command line

[IMPORTANT]
.Unidentified developer warnings
====
Apple's rollout of stricter notarization requirements affected the notarization
of the {version} {es} artifacts. If macOS Catalina displays an unidentified
developer warning when you first run {es}, you will need to add a security
override.

To add a security override, follow the instructions in
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac[Open
a Mac app from an unidentified developer].
====

Elasticsearch can be started from the command line as follows:

[source,sh]
--------------------------------------------
./bin/elasticsearch
--------------------------------------------

By default, Elasticsearch runs in the foreground, prints its logs to the
standard output (`stdout`), and can be stopped by pressing `Ctrl-C`.

NOTE: All scripts packaged with Elasticsearch require a version of Bash
that supports arrays and assume that Bash is available at `/bin/bash`.
As such, Bash should be available at this path either directly or via a
symbolic link.

