/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.bulk.BulkItemRequest;
import org.elasticsearch.action.bulk.BulkItemResponse;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.action.index.IndexResponse;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.util.ByteUtils;
import org.elasticsearch.core.Assertions;
import org.elasticsearch.escf.EscfBatch;
import org.elasticsearch.escf.EscfEncoder;
import org.elasticsearch.index.mapper.Uid;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.test.ESTestCase;
import org.elasticsearch.xcontent.XContentType;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.nullValue;
import static org.hamcrest.Matchers.sameInstance;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class IndexOperationBatchTests extends ESTestCase {

    private static BulkItemRequest[] items(int n) {
        final BulkItemRequest[] items = new BulkItemRequest[n];
        for (int d = 0; d < n; d++) {
            items[d] = new BulkItemRequest(d, new IndexRequest("index").id("doc-" + d).source(src(d), XContentType.JSON));
        }
        return items;
    }

    private static IndexOperationBatch primaryBatch(int n) {
        return IndexOperationBatch.initFromBulk(items(n), 0, n, null, Engine.Operation.Origin.PRIMARY, 1L, 0L);
    }

    private static IndexOperationBatch primaryBatch(BulkItemRequest[] items, int from, int to) {
        return IndexOperationBatch.initFromBulk(items, from, to, null, Engine.Operation.Origin.PRIMARY, 1L, 0L);
    }

    private static BytesArray src(int d) {
        return new BytesArray("{\"n\":" + d + "}");
    }

    private static BulkItemRequest replicaItem(int id, IndexRequest request, long seqNo, long primaryTerm, long version) {
        final BulkItemRequest item = mock(BulkItemRequest.class);
        doReturn(request).when(item).request();
        when(item.getPrimaryResponse()).thenReturn(
            BulkItemResponse.success(
                id,
                DocWriteRequest.OpType.INDEX,
                new IndexResponse(new ShardId("index", "_na_", 0), request.id(), seqNo, primaryTerm, version, true)
            )
        );
        return item;
    }

    private static EscfBatch escfBatch(int docCount) throws IOException {
        final List<BytesReference> sources = new ArrayList<>(docCount);
        for (int d = 0; d < docCount; d++) {
            sources.add(src(d));
        }
        return EscfEncoder.encode(sources, XContentType.JSON);
    }

    public void testInitFromBulkMapsPerDocFields() {
        final int n = randomIntBetween(1, 16);
        final BulkItemRequest[] items = new BulkItemRequest[n];
        for (int d = 0; d < n; d++) {
            final IndexRequest req = new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON);
            items[d] = new BulkItemRequest(d, req);
        }
        final IndexOperationBatch batch = primaryBatch(items, 0, n);

        assertThat(batch.docCount(), equalTo(n));
        assertThat(batch.offset(), equalTo(0));
        for (int d = 0; d < n; d++) {
            assertThat(batch.id(d), equalTo("id-" + d));
            assertThat(batch.uid(d), equalTo(Uid.encodeId("id-" + d)));
            assertThat(batch.contentType(d), equalTo(XContentType.JSON));
            assertThat(batch.routingString(d), nullValue());
            assertThat(batch.autoGeneratedIdTimestamp(d), equalTo(IndexRequest.UNSET_AUTO_GENERATED_TIMESTAMP));
            assertFalse(batch.toIndexOp(d).isRetry());
        }
    }

    public void testInitFromBulkDefaultsContentTypeToJson() {
        // IndexRequest with no source → getContentType() returns null
        final BulkItemRequest[] items = { new BulkItemRequest(0, new IndexRequest("index").id("doc-0")) };
        final IndexOperationBatch batch = primaryBatch(items, 0, 1);
        assertThat(batch.contentType(0), equalTo(XContentType.JSON));
        assertThat(batch.sources()[0], nullValue());
    }

    public void testInitFromBulkRoutingArrayAllocatedLazily() {
        final int n = randomIntBetween(2, 8);
        final BulkItemRequest[] items = new BulkItemRequest[n];
        for (int d = 0; d < n; d++) {
            items[d] = new BulkItemRequest(d, new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON));
        }
        // No routing on any doc → routings array stays null
        final IndexOperationBatch noRouting = primaryBatch(items, 0, n);
        assertThat(noRouting.routings(), nullValue());
        for (int d = 0; d < n; d++) {
            assertThat(noRouting.routingString(d), nullValue());
        }

        // Add routing to a random subset, rebuild
        final int routedDoc = randomIntBetween(0, n - 1);
        final String expectedRouting = randomAlphaOfLength(6);
        items[routedDoc] = new BulkItemRequest(
            routedDoc,
            new IndexRequest("index").id("id-" + routedDoc).source(src(routedDoc), XContentType.JSON).routing(expectedRouting)
        );
        final IndexOperationBatch withRouting = primaryBatch(items, 0, n);
        assertNotNull(withRouting.routings());
        assertThat(withRouting.routings().length, equalTo(n));
        assertThat(withRouting.routingString(routedDoc), equalTo(expectedRouting));
        for (int d = 0; d < n; d++) {
            if (d != routedDoc) {
                assertThat(withRouting.routingString(d), nullValue());
            }
        }
    }

    public void testInitFromBulkCasSentinelsWhenAbsent() {
        final int n = randomIntBetween(1, 8);
        final IndexOperationBatch batch = primaryBatch(n);
        for (int d = 0; d < n; d++) {
            assertThat(batch.ifSeqNo(d), equalTo(SequenceNumbers.UNASSIGNED_SEQ_NO));
            assertThat(batch.ifPrimaryTerm(d), equalTo(0L));
        }
    }

    public void testInitFromBulkCasSentinelsWhenPartiallySet() {
        final int n = randomIntBetween(2, 8);
        final BulkItemRequest[] items = new BulkItemRequest[n];
        for (int d = 0; d < n; d++) {
            items[d] = new BulkItemRequest(d, new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON));
        }
        final int casDoc = randomIntBetween(0, n - 1);
        final long expectedIfSeqNo = randomNonNegativeLong();
        final long expectedIfPrimaryTerm = randomLongBetween(1, Long.MAX_VALUE);
        items[casDoc] = new BulkItemRequest(
            casDoc,
            new IndexRequest("index").id("id-" + casDoc)
                .source(src(casDoc), XContentType.JSON)
                .setIfSeqNo(expectedIfSeqNo)
                .setIfPrimaryTerm(expectedIfPrimaryTerm)
        );
        final IndexOperationBatch batch = primaryBatch(items, 0, n);

        assertThat(batch.ifSeqNo(casDoc), equalTo(expectedIfSeqNo));
        assertThat(batch.ifPrimaryTerm(casDoc), equalTo(expectedIfPrimaryTerm));
        for (int d = 0; d < n; d++) {
            if (d != casDoc) {
                // ifSeqNoBuf uses Arrays.fill(UNASSIGNED_SEQ_NO) before setting the specific entry;
                // ifPrimaryTermBuf relies on Java's 0L default — assert both explicitly.
                assertThat("ifSeqNo sentinel at d=" + d, batch.ifSeqNo(d), equalTo(SequenceNumbers.UNASSIGNED_SEQ_NO));
                assertThat("ifPrimaryTerm sentinel at d=" + d, batch.ifPrimaryTerm(d), equalTo(0L));
            }
        }
    }

    public void testInitFromBulkPrimaryPrefillsUnassignedSeqNo() {
        final int n = randomIntBetween(1, 8);
        final IndexOperationBatch batch = primaryBatch(n);
        for (int d = 0; d < n; d++) {
            assertThat(batch.seqNo(d), equalTo(SequenceNumbers.UNASSIGNED_SEQ_NO));
        }
        // Byte buffer is correctly sized and zero-offset
        assertThat(batch.seqNoBytes().offset, equalTo(0));
        assertThat(batch.seqNoBytes().bytes.length, equalTo(n * 8));
        // primaryTermBytes/versionBytes are all-zero on primary
        for (int d = 0; d < n; d++) {
            assertThat(ByteUtils.readLongLE(batch.primaryTermBytes().bytes, d * 8), equalTo(0L));
            assertThat(ByteUtils.readLongLE(batch.versionBytes().bytes, d * 8), equalTo(0L));
        }
    }

    public void testInitFromBulkSubRange() {
        // items array is larger than the actual batch range
        final int total = randomIntBetween(3, 12);
        final int from = randomIntBetween(0, total - 2);
        final int to = randomIntBetween(from + 1, total);
        final BulkItemRequest[] allItems = new BulkItemRequest[total];
        for (int d = 0; d < total; d++) {
            allItems[d] = new BulkItemRequest(d, new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON));
        }
        final IndexOperationBatch batch = IndexOperationBatch.initFromBulk(
            allItems,
            from,
            to,
            null,
            Engine.Operation.Origin.PRIMARY,
            1L,
            0L
        );
        assertThat(batch.docCount(), equalTo(to - from));
        // initFromBulk always produces offset == 0; offset != 0 arises only via slice()
        assertThat(batch.offset(), equalTo(0));
        // Reads items[from..to) into positions [0..docCount)
        for (int i = 0; i < to - from; i++) {
            assertThat(batch.id(i), equalTo("id-" + (from + i)));
        }
        assertThat(batch.uids().length, equalTo(to - from));
    }

    public void testInitFromBulkRejectsInvalidRange() {
        final int n = randomIntBetween(2, 8);
        final BulkItemRequest[] items = items(n);
        // from < 0
        expectThrows(
            IndexOutOfBoundsException.class,
            () -> IndexOperationBatch.initFromBulk(items, -1, 1, null, Engine.Operation.Origin.PRIMARY, 1L, 0L)
        );
        // to > items.length
        expectThrows(
            IndexOutOfBoundsException.class,
            () -> IndexOperationBatch.initFromBulk(items, 0, n + 1, null, Engine.Operation.Origin.PRIMARY, 1L, 0L)
        );
        // to < from
        expectThrows(
            IndexOutOfBoundsException.class,
            () -> IndexOperationBatch.initFromBulk(items, 2, 1, null, Engine.Operation.Origin.PRIMARY, 1L, 0L)
        );
        // from == to (empty range) — rejected with IllegalArgumentException (not OOB; in-bounds but empty)
        final int x = randomIntBetween(0, n);
        final IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> IndexOperationBatch.initFromBulk(items, x, x, null, Engine.Operation.Origin.PRIMARY, 1L, 0L)
        );
        assertTrue(e.getMessage().contains("empty batch"));
    }

    public void testInitFromBulkReplicaCopiesPrimaryResponse() {
        final int n = randomIntBetween(1, 6);
        final BulkItemRequest[] items = new BulkItemRequest[n];
        final long[] seqNos = new long[n];
        final long[] primaryTerms = new long[n];
        final long[] versions = new long[n];
        for (int d = 0; d < n; d++) {
            seqNos[d] = randomNonNegativeLong();
            primaryTerms[d] = randomLongBetween(1, Long.MAX_VALUE);
            versions[d] = randomLongBetween(1, Long.MAX_VALUE);
            final IndexRequest req = new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON);
            items[d] = replicaItem(d, req, seqNos[d], primaryTerms[d], versions[d]);
        }
        final IndexOperationBatch batch = IndexOperationBatch.initFromBulk(items, 0, n, null, Engine.Operation.Origin.REPLICA, 1L, 0L);
        for (int d = 0; d < n; d++) {
            assertThat("seqNo at d=" + d, batch.seqNo(d), equalTo(seqNos[d]));
            assertThat("primaryTerm at d=" + d, ByteUtils.readLongLE(batch.primaryTermBytes().bytes, d * 8), equalTo(primaryTerms[d]));
            assertThat("version at d=" + d, ByteUtils.readLongLE(batch.versionBytes().bytes, d * 8), equalTo(versions[d]));
            assertThat(batch.toIndexOp(d).versionType(), nullValue());
            assertThat(batch.toIndexOp(d).version(), equalTo(versions[d]));
            // seqNo is NOT pre-filled with UNASSIGNED_SEQ_NO on the replica path
            assertNotEquals(SequenceNumbers.UNASSIGNED_SEQ_NO, batch.seqNo(d));
        }
    }

    public void testInitFromBulkStoresSourceBatch() throws IOException {
        final int n = randomIntBetween(1, 6);
        try (EscfBatch escf = escfBatch(n)) {
            final IndexOperationBatch batch = IndexOperationBatch.initFromBulk(
                items(n),
                0,
                n,
                escf,
                Engine.Operation.Origin.PRIMARY,
                1L,
                0L
            );
            assertThat(batch.sourceBatch(), sameInstance(escf));
            assertThat(batch.sourceBatch().docCount(), equalTo(n));
        }
    }

    public void testSliceOffsetAndDocCount() {
        final int n = randomIntBetween(3, 12);
        final IndexOperationBatch parent = primaryBatch(n);
        final int from = randomIntBetween(0, n - 2);
        final int to = randomIntBetween(from + 1, n);
        final IndexOperationBatch slice = parent.slice(from, to);

        assertThat(slice.offset(), equalTo(from));
        assertThat(slice.docCount(), equalTo(to - from));
        assertThat(slice.origin(), equalTo(parent.origin()));
        assertThat(slice.primaryTerm(), equalTo(parent.primaryTerm()));
        assertThat(slice.startTime(), equalTo(parent.startTime()));
    }

    public void testSliceAccessorsMatchParent() {
        final int n = randomIntBetween(3, 12);
        final BulkItemRequest[] items = new BulkItemRequest[n];
        for (int d = 0; d < n; d++) {
            final String routing = randomBoolean() ? randomAlphaOfLength(5) : null;
            final IndexRequest req = new IndexRequest("index").id("id-" + d).source(src(d), XContentType.JSON);
            if (routing != null) {
                req.routing(routing);
            }
            items[d] = new BulkItemRequest(d, req);
        }
        final IndexOperationBatch parent = primaryBatch(items, 0, n);
        final int from = randomIntBetween(0, n - 2);
        final int to = randomIntBetween(from + 1, n);
        final IndexOperationBatch slice = parent.slice(from, to);

        // Write known seqNos into the shared buffer so seqNo() returns something meaningful
        for (int d = 0; d < n; d++) {
            ByteUtils.writeLongLE(d + 100L, parent.seqNoBytes().bytes, d * 8);
        }

        for (int i = 0; i < slice.docCount(); i++) {
            final int parentIdx = from + i;
            assertThat("uid at i=" + i, slice.uid(i), equalTo(parent.uid(parentIdx)));
            assertThat("id at i=" + i, slice.id(i), equalTo(parent.id(parentIdx)));
            assertThat("contentType at i=" + i, slice.contentType(i), equalTo(parent.contentType(parentIdx)));
            assertThat("routingString at i=" + i, slice.routingString(i), equalTo(parent.routingString(parentIdx)));
            assertThat(
                "autoGeneratedIdTimestamp at i=" + i,
                slice.autoGeneratedIdTimestamp(i),
                equalTo(parent.autoGeneratedIdTimestamp(parentIdx))
            );
            assertThat("ifSeqNo at i=" + i, slice.ifSeqNo(i), equalTo(parent.ifSeqNo(parentIdx)));
            assertThat("ifPrimaryTerm at i=" + i, slice.ifPrimaryTerm(i), equalTo(parent.ifPrimaryTerm(parentIdx)));
            assertThat("seqNo at i=" + i, slice.seqNo(i), equalTo(parent.seqNo(parentIdx)));
        }
    }

    public void testSliceSharesMutableByteBuffers() {
        final int n = randomIntBetween(3, 10);
        final IndexOperationBatch parent = primaryBatch(n);
        final int from = randomIntBetween(1, n - 1);
        final IndexOperationBatch slice = parent.slice(from, n);

        // The three byte buffers must be the same object in both parent and slice
        assertThat(slice.seqNoBytes(), sameInstance(parent.seqNoBytes()));
        assertThat(slice.primaryTermBytes(), sameInstance(parent.primaryTermBytes()));
        assertThat(slice.versionBytes(), sameInstance(parent.versionBytes()));

        // A write via the slice is visible through the parent (and vice versa)
        final int sliceIdx = randomIntBetween(0, slice.docCount() - 1);
        final long written = randomNonNegativeLong();
        ByteUtils.writeLongLE(written, slice.seqNoBytes().bytes, (slice.offset() + sliceIdx) * 8);

        assertThat("slice sees its own write", slice.seqNo(sliceIdx), equalTo(written));
        assertThat("parent sees the slice's write", parent.seqNo(from + sliceIdx), equalTo(written));

        // Neighbouring parent doc (if any) is unaffected
        if (from > 0) {
            final long before = ByteUtils.readLongLE(parent.seqNoBytes().bytes, (from - 1) * 8);
            assertThat(before, equalTo(SequenceNumbers.UNASSIGNED_SEQ_NO));
        }
    }

    public void testSliceOfSlice() {
        final int n = randomIntBetween(4, 12);
        final IndexOperationBatch root = primaryBatch(n);
        final int from1 = randomIntBetween(0, n - 3);
        final int to1 = randomIntBetween(from1 + 2, n);
        final IndexOperationBatch mid = root.slice(from1, to1);

        final int from2 = randomIntBetween(0, mid.docCount() - 2);
        final int to2 = randomIntBetween(from2 + 1, mid.docCount());
        final IndexOperationBatch inner = mid.slice(from2, to2);

        assertThat(inner.offset(), equalTo(from1 + from2));
        assertThat(inner.docCount(), equalTo(to2 - from2));
        for (int i = 0; i < inner.docCount(); i++) {
            assertThat("id at i=" + i, inner.id(i), equalTo(root.id(from1 + from2 + i)));
        }
    }

    public void testFullRangeSliceMatchesParent() {
        final int n = randomIntBetween(2, 8);
        final IndexOperationBatch parent = primaryBatch(n);
        final IndexOperationBatch full = parent.slice(0, n);

        assertThat(full.offset(), equalTo(0));
        assertThat(full.docCount(), equalTo(n));
        for (int i = 0; i < n; i++) {
            assertThat(full.id(i), equalTo(parent.id(i)));
            assertThat(full.uid(i), equalTo(parent.uid(i)));
        }
    }

    public void testBoundarySlices() {
        final int n = randomIntBetween(3, 10);
        final IndexOperationBatch parent = primaryBatch(n);

        final IndexOperationBatch first = parent.slice(0, 1);
        assertThat(first.offset(), equalTo(0));
        assertThat(first.docCount(), equalTo(1));
        assertThat(first.id(0), equalTo(parent.id(0)));

        final IndexOperationBatch last = parent.slice(n - 1, n);
        assertThat(last.offset(), equalTo(n - 1));
        assertThat(last.docCount(), equalTo(1));
        assertThat(last.id(0), equalTo(parent.id(n - 1)));
    }

    public void testSliceOutOfRangeThrows() {
        final int n = randomIntBetween(2, 8);
        final IndexOperationBatch batch = primaryBatch(n);
        // from < 0
        expectThrows(IndexOutOfBoundsException.class, () -> batch.slice(-1, 1));
        // to > docCount
        expectThrows(IndexOutOfBoundsException.class, () -> batch.slice(0, n + 1));
        // to < from
        expectThrows(IndexOutOfBoundsException.class, () -> batch.slice(2, 1));
        // from and to both beyond docCount
        expectThrows(IndexOutOfBoundsException.class, () -> batch.slice(n + 1, n + 2));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.slice(-1, -1));
    }

    public void testEmptySliceRejected() {
        final int n = randomIntBetween(1, 8);
        final IndexOperationBatch batch = primaryBatch(n);
        final int x = randomIntBetween(0, n - 1);
        final IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> batch.slice(x, x));
        assertTrue(e.getMessage().contains("empty slice"));
    }

    public void testSliceForwardsSourceBatchWithRelativeCoordinates() throws IOException {
        final int n = randomIntBetween(3, 8);
        try (EscfBatch rootEscf = escfBatch(n)) {
            final IndexOperationBatch parent = IndexOperationBatch.initFromBulk(
                items(n),
                0,
                n,
                rootEscf,
                Engine.Operation.Origin.PRIMARY,
                1L,
                0L
            );
            final int from = randomIntBetween(0, n - 2);
            final int to = randomIntBetween(from + 1, n);
            final IndexOperationBatch slice = parent.slice(from, to);

            assertNotNull(slice.sourceBatch());
            assertThat(slice.sourceBatch().docCount(), equalTo(to - from));
            // Slice with null source → null sourceBatch on the slice
        }
        final IndexOperationBatch noSource = primaryBatch(n);
        assertThat(noSource.slice(0, 1).sourceBatch(), nullValue());
    }

    public void testOutOfBoundsAccessorsThrow() {
        final int n = 10;
        final IndexOperationBatch parent = primaryBatch(n);

        for (int bad : new int[] { -1, n }) {
            final int b = bad;
            // Parent
            expectThrows(IndexOutOfBoundsException.class, () -> parent.uid(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.id(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.routingString(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.contentType(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.ifSeqNo(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.ifPrimaryTerm(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.autoGeneratedIdTimestamp(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.seqNo(b));
            expectThrows(IndexOutOfBoundsException.class, () -> parent.toIndexOp(b));
        }

        // Strict interior slice: [3, 7) — parent indices 3–6, neighbours 2 and 7 exist in the parent
        final IndexOperationBatch slice = parent.slice(3, 7);
        // The parent holds real, different data just outside the slice window
        assertNotEquals(parent.id(2), slice.id(0));
        assertNotEquals(parent.id(7), slice.id(slice.docCount() - 1));

        for (int bad : new int[] { -1, slice.docCount() }) {
            final int b = bad;
            expectThrows(IndexOutOfBoundsException.class, () -> slice.uid(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.id(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.routingString(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.contentType(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.ifSeqNo(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.ifPrimaryTerm(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.autoGeneratedIdTimestamp(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.seqNo(b));
            expectThrows(IndexOutOfBoundsException.class, () -> slice.toIndexOp(b));
        }
    }

    public void testOutOfBoundsRoutingStringWithNullArrayThrows() {
        final IndexOperationBatch batch = primaryBatch(randomIntBetween(1, 6));
        assertThat(batch.routings(), nullValue());
        expectThrows(IndexOutOfBoundsException.class, () -> batch.routingString(-1));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.routingString(batch.docCount()));
    }

    public void testOutOfBoundsCasSentinelAccessorsWithNullArrayThrows() {
        final IndexOperationBatch batch = primaryBatch(randomIntBetween(1, 6));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.ifSeqNo(-1));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.ifSeqNo(batch.docCount()));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.ifPrimaryTerm(-1));
        expectThrows(IndexOutOfBoundsException.class, () -> batch.ifPrimaryTerm(batch.docCount()));
    }

    public void testConstructorAssertsDocCountAtLeastOne() {
        assumeTrue("test only works with assertions enabled", Assertions.ENABLED);
        final int n = 4;
        final IndexOperationBatch parent = primaryBatch(n);
        // Produce a zero-docCount batch by calling the package-private ctor via slice — but
        // slice now rejects from == to, so we verify that the rejection is an IllegalArgumentException
        // with the right message (the assert in the ctor is the backstop; slice is the first gate).
        final IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> parent.slice(2, 2));
        assertTrue(e.getMessage().contains("empty slice"));
    }

    public void testRawArrayAccessorsReturnFullParentArrays() {
        final int n = randomIntBetween(3, 10);
        final IndexOperationBatch parent = primaryBatch(n);
        final int from = randomIntBetween(1, n - 1);
        final IndexOperationBatch slice = parent.slice(from, n);

        // Raw arrays are shared — same reference
        assertThat(slice.uids(), sameInstance(parent.uids()));
        assertThat(slice.contentTypes(), sameInstance(parent.contentTypes()));
        assertThat(slice.sources(), sameInstance(parent.sources()));

        // Length is the full-batch length, not the slice length
        assertThat(slice.uids().length, equalTo(n));

        // Element at offset() in the raw array matches element 0 in the slice
        assertThat(slice.uids()[slice.offset()], equalTo(slice.uid(0)));
        assertThat(slice.contentTypes()[slice.offset()], equalTo(slice.contentType(0)));
    }

    public void testToIndexOpReflectsLateSeqNoStamping() {
        final int n = randomIntBetween(2, 8);
        final IndexOperationBatch parent = primaryBatch(n);
        final int from = randomIntBetween(0, n - 1);
        final IndexOperationBatch slice = parent.slice(from, n);

        // Stamp random seqNos after construction — toIndexOp must reflect them
        final long[] expected = new long[slice.docCount()];
        for (int i = 0; i < slice.docCount(); i++) {
            expected[i] = randomNonNegativeLong();
            ByteUtils.writeLongLE(expected[i], slice.seqNoBytes().bytes, (slice.offset() + i) * 8);
        }
        for (int i = 0; i < slice.docCount(); i++) {
            assertThat("seqNo at i=" + i, slice.toIndexOp(i).seqNo(), equalTo(expected[i]));
        }
    }

    public void testMaterializeIndexOpsOnSlice() {
        final int n = randomIntBetween(3, 10);
        final IndexOperationBatch parent = primaryBatch(n);
        final int from = randomIntBetween(0, n - 2);
        final int to = randomIntBetween(from + 1, n);
        final IndexOperationBatch slice = parent.slice(from, to);

        final List<Engine.Index> ops = slice.materializeIndexOps();
        assertThat(ops.size(), equalTo(to - from));
        for (int i = 0; i < ops.size(); i++) {
            assertThat(ops.get(i).id(), equalTo(slice.id(i)));
            assertThat(ops.get(i).id(), equalTo(parent.id(from + i)));
        }
    }
}
