[[ilm-forcemerge]]
=== Force Merge

Phases allowed: hot, warm.

NOTE: The index is made read-only when this action is run.
See <<dynamic-index-settings,`index.blocks.write`>>.

NOTE: If the `forcemerge` action is used in the `hot` phase, the `rollover` action *must* be preset.
{ilm-init} validates this predicate and will refuse a policy with a forcemerge in the hot phase without a
rollover action.

The force merge action <<indices-forcemerge,force merges>> the index into a
specified maximum number of <<indices-segments,segments>>.

[[ilm-forcemerge-options]]
.Force Merge Options
[options="header"]
|======
| Name                 | Required  | Default             | Description
| `max_num_segments`   | yes       | -                   | The number of segments to merge to. To fully merge the index, set it to `1`
| `codec`              | no        | -                   | Optional specification of the `best_compression` codec
|======

[WARNING]
======
When using the `"codec": "best_compression"` configuration in the {ilm-init} forcemerge action, {ilm-int} will
<<indices-close,close>> and then <<indices-open-close,re-open>> the index prior to a forcemerge.
During this time the index will be unavailable for either read or write operations.
======

[source,console]
--------------------------------------------------
PUT _ilm/policy/my_policy
{
  "policy": {
    "phases": {
      "warm": {
        "actions": {
          "forcemerge" : {
            "max_num_segments": 1
          }
        }
      }
    }
  }
}
--------------------------------------------------
