[[stopping-elasticsearch]]
=== Stopping Elasticsearch

An orderly shutdown of Elasticsearch ensures that Elasticsearch has a chance to cleanup and close
outstanding resources. For example, a node that is shutdown in an orderly fashion will remove itself
from the cluster, sync translogs to disk, and perform other related cleanup activities. You can help
ensure an orderly shutdown by properly stopping Elasticsearch.

If you're running Elasticsearch as a service, you can stop Elasticsearch via the service management
functionality provided by your installation.

If you're running Elasticsearch directly, you can stop Elasticsearch by sending control-C if you're
running Elasticsearch in the console, or by sending `SIGTERM` to the Elasticsearch process on a
POSIX system. You can obtain the PID to send the signal to via various tools (e.g., `ps` or `jps`),
from the Elasticsearch statrup logs, or by specifying a location to write a PID file to on startup
(`-p <path>`).

[source,sh]
--------------------------------------------------
$ ./bin/elasticsearch -p /tmp/elasticsearch-pid -d
$ cat /tmp/elasticsearch-pid && echo
7801
$ kill -SIGTERM 7801
--------------------------------------------------

[[fatal-errors]
[float]
=== Stopping on Fatal Errors

During the life of the Elasticsearch virtual machine, certain fatal errors could arise that put the
virtual machine in a questionable state. Such fatal errors include out of memory errors, internal
errors in virtual machine, and serious I/O errors.

When Elasticsearch detects that the virtual machine has encountered such a fatal error Elasticsearch
will attempt to log the error and then will halt the virtual machine. When Elasticsearch initiates
such a shutdown, it does not go through an orderly shutdown as described above. The Elasticsearch
process will also return with a special status code indicating the nature of the error.

[horizontal]
JVM internal error:: 128
Out of memory error:: 127
Stack overflow error:: 126
Unknown virtual machine error:: 125
Serious I/O error:: 124
Unknown fatal error:: 1
