[role="xpack"]
[[watcher-trigger-schedule]]
=== {watcher} schedule trigger
++++
<titleabbrev>Schedule trigger</titleabbrev>
++++

Schedule <<watcher-triggers,triggers>> define when the watch execution should start based
on date and time. All times are specified in UTC time.

{watcher} uses the system clock to determine the current time. To ensure schedules
are triggered when expected, you should synchronize the clocks of all nodes in the
cluster using a time service such as http://www.ntp.org/[NTP].

Keep in mind that the throttle period can affect when a watch is actually executed.
The default throttle period is five seconds (5000 ms). If you configure a schedule
that's more frequent than the throttle period, the throttle period overrides the
schedule. For example, if you set the throttle period to one minute (60000 ms)
and set the schedule to every 10 seconds, the watch is executed no more than
once per minute. For more information about throttling, see
<<watcher-actions-ack-throttle>>.

{watcher} provides several types of schedule triggers:

* <<watcher-schedule-hourly, `hourly`>>
* <<watcher-schedule-daily, `daily`>>
* <<watcher-schedule-weekly, `weekly`>>
* <<watcher-schedule-monthly, `monthly`>>
* <<watcher-schedule-yearly, `yearly`>>
* <<watcher-schedule-cron, `cron`>>
* <<watcher-schedule-interval, `interval`>>

include::schedule/hourly.asciidoc[]

include::schedule/daily.asciidoc[]

include::schedule/weekly.asciidoc[]

include::schedule/monthly.asciidoc[]

include::schedule/yearly.asciidoc[]

include::schedule/cron.asciidoc[]

include::schedule/interval.asciidoc[]
