/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.nativeaccess;

import org.elasticsearch.common.logging.LogConfigurator;
import org.elasticsearch.common.logging.NodeNamePatternConverter;
import org.elasticsearch.core.PathUtils;
import org.elasticsearch.test.ESTestCase;
import org.junit.BeforeClass;

import java.io.IOException;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.notNullValue;

/**
 * Tests for the parquet-rs native library FFI plumbing.
 *
 * <p> Uses an embedded test.parquet resource (3 rows, 2 columns: id INT64, name STRING).
 * The resource was generated by {@code ParquetRsNativeTests.createTestParquetBytes()} in the
 * esql-datasource-parquet-rs module. To regenerate, run that method and write the bytes to
 * {@code libs/native/src/test/resources/org/elasticsearch/nativeaccess/test.parquet}.
 *
 * <p> Full Parquet/Arrow integration tests live in the esql-datasource-parquet-rs module.
 */
public class ParquetRsFunctionsTests extends ESTestCase {

    static {
        NodeNamePatternConverter.setGlobalNodeName("test");
        LogConfigurator.loadLog4jPlugins();
        LogConfigurator.configureESLogging();
    }

    static ParquetRsFunctions parquetRs;
    static Path testParquetFile;

    @BeforeClass
    public static void loadLib() throws Exception {
        var opt = NativeAccess.instance().getParquetRsFunctions();
        assumeTrue("parquet-rs native library not available", opt.isPresent());
        parquetRs = opt.get();
        testParquetFile = PathUtils.get(ParquetRsFunctionsTests.class.getResource("test.parquet").toURI());
    }

    // -- getStatistics positive tests --

    public void testGetStatistics() throws Exception {
        long[] stats = parquetRs.getStatistics(testParquetFile.toAbsolutePath().toString(), null);
        assertThat(stats, notNullValue());
        assertThat(stats.length, equalTo(2));
        assertThat(stats[0], equalTo(3L));
        assertThat(stats[1], greaterThan(0L));
    }

    public void testGetStatisticsWithNullConfig() throws Exception {
        long[] stats = parquetRs.getStatistics(testParquetFile.toAbsolutePath().toString(), null);
        assertThat(stats, notNullValue());
        assertThat(stats[0], equalTo(3L));
    }

    public void testGetStatisticsWithEmptyConfig() throws Exception {
        long[] stats = parquetRs.getStatistics(testParquetFile.toAbsolutePath().toString(), "{}");
        assertThat(stats, notNullValue());
        assertThat(stats[0], equalTo(3L));
    }

    public void testGetStatisticsWithValidConfig() throws Exception {
        long[] stats = parquetRs.getStatistics(testParquetFile.toAbsolutePath().toString(), "{\"key\": \"value\"}");
        assertThat(stats, notNullValue());
        assertThat(stats[0], equalTo(3L));
    }

    // -- getSchemaFFI positive tests --

    public void testGetSchemaFFI() throws Exception {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment schemaMem = arena.allocate(FFI_ARROW_SCHEMA_SIZE);
            parquetRs.getSchemaFFI(testParquetFile.toAbsolutePath().toString(), null, schemaMem.address());
            assertValidArrowSchema(schemaMem, 2);
        }
    }

    public void testGetSchemaFFIWithEmptyConfig() throws Exception {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment schemaMem = arena.allocate(FFI_ARROW_SCHEMA_SIZE);
            parquetRs.getSchemaFFI(testParquetFile.toAbsolutePath().toString(), "{}", schemaMem.address());
            assertValidArrowSchema(schemaMem, 2);
        }
    }

    public void testGetSchemaFFIWithValidConfig() throws Exception {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment schemaMem = arena.allocate(FFI_ARROW_SCHEMA_SIZE);
            parquetRs.getSchemaFFI(testParquetFile.toAbsolutePath().toString(), "{\"key\": \"value\"}", schemaMem.address());
            assertValidArrowSchema(schemaMem, 2);
        }
    }

    // -- getStatistics error cases --

    public void testGetStatisticsNonExistentFile() {
        IOException e = expectThrows(IOException.class, () -> parquetRs.getStatistics("/nonexistent/file.parquet", null));
        assertThat(e.getMessage(), containsString("getStatistics failed"));
        assertThat(e.getMessage(), containsString("/nonexistent/file.parquet"));
    }

    public void testGetStatisticsOnDirectory() {
        Path dir = createTempDir();
        IOException e = expectThrows(IOException.class, () -> parquetRs.getStatistics(dir.toAbsolutePath().toString(), null));
        assertThat(e.getMessage(), containsString("getStatistics failed"));
    }

    public void testGetStatisticsEmptyFile() throws Exception {
        Path file = createTempDir().resolve("empty.parquet");
        Files.createFile(file);
        IOException e = expectThrows(IOException.class, () -> parquetRs.getStatistics(file.toAbsolutePath().toString(), null));
        assertThat(e.getMessage(), containsString("getStatistics failed"));
    }

    public void testGetStatisticsNotParquet() throws Exception {
        Path file = createTempDir().resolve("not_parquet.parquet");
        Files.writeString(file, "this is not a parquet file");
        IOException e = expectThrows(IOException.class, () -> parquetRs.getStatistics(file.toAbsolutePath().toString(), null));
        assertThat(e.getMessage(), containsString("getStatistics failed"));
    }

    // -- getSchemaFFI error cases --

    public void testGetSchemaFFINonExistentFile() {
        IOException e = expectThrows(IOException.class, () -> parquetRs.getSchemaFFI("/nonexistent/file.parquet", null, 0));
        assertThat(e.getMessage(), containsString("getSchemaFFI failed"));
        assertThat(e.getMessage(), containsString("/nonexistent/file.parquet"));
    }

    public void testGetSchemaFFIOnDirectory() {
        Path dir = createTempDir();
        IOException e = expectThrows(IOException.class, () -> parquetRs.getSchemaFFI(dir.toAbsolutePath().toString(), null, 0));
        assertThat(e.getMessage(), containsString("getSchemaFFI failed"));
    }

    public void testGetSchemaFFIEmptyFile() throws Exception {
        Path file = createTempDir().resolve("empty.parquet");
        Files.createFile(file);
        IOException e = expectThrows(IOException.class, () -> parquetRs.getSchemaFFI(file.toAbsolutePath().toString(), null, 0));
        assertThat(e.getMessage(), containsString("getSchemaFFI failed"));
    }

    public void testGetSchemaFFINotParquet() throws Exception {
        Path file = createTempDir().resolve("not_parquet.parquet");
        Files.writeString(file, "this is not a parquet file");
        IOException e = expectThrows(IOException.class, () -> parquetRs.getSchemaFFI(file.toAbsolutePath().toString(), null, 0));
        assertThat(e.getMessage(), containsString("getSchemaFFI failed"));
    }

    // -- configJson error cases --

    public void testGetStatisticsWithMalformedConfigJson() {
        IOException e = expectThrows(
            IOException.class,
            () -> parquetRs.getStatistics(testParquetFile.toAbsolutePath().toString(), "not valid json{{{")
        );
        assertThat(e.getMessage(), containsString("getStatistics failed"));
    }

    public void testGetSchemaFFIWithMalformedConfigJson() {
        IOException e = expectThrows(
            IOException.class,
            () -> parquetRs.getSchemaFFI(testParquetFile.toAbsolutePath().toString(), "not valid json{{{", 0)
        );
        assertThat(e.getMessage(), containsString("getSchemaFFI failed"));
    }

    // -- Arrow C Data Interface schema validation --

    // Arrow C Data Interface FFI_ArrowSchema struct: 9 pointer-sized fields = 72 bytes on 64-bit.
    // See https://arrow.apache.org/docs/format/CDataInterface.html#the-arrowschema-structure
    private static final int FFI_ARROW_SCHEMA_SIZE = 72;

    // Field offsets within FFI_ArrowSchema (all 8 bytes on 64-bit):
    // 0: const char* format
    // 8: const char* name
    // 16: const char* metadata
    // 24: int64_t flags
    // 32: int64_t n_children
    // 40: ArrowSchema** children
    // 48: ArrowSchema* dictionary
    // 56: void (*release)(ArrowSchema*)
    // 64: void* private_data
    private static final long OFFSET_FORMAT = 0;
    private static final long OFFSET_N_CHILDREN = 32;
    private static final long OFFSET_CHILDREN = 40;
    private static final long OFFSET_RELEASE = 56;

    /**
     * Validates that a raw FFI_ArrowSchema memory segment looks like a valid exported schema.
     * This performs lightweight structural checks without requiring Arrow Java dependencies:
     * <ul>
     *   <li>The {@code format} pointer is non-null (every valid schema has a format string)</li>
     *   <li>The {@code n_children} field matches the expected column count</li>
     *   <li>The {@code children} pointer is non-null (since n_children &gt; 0)</li>
     *   <li>The {@code release} function pointer is non-null (Rust sets this for deallocation)</li>
     * </ul>
     *
     * @param schemaMem       the memory segment containing the FFI_ArrowSchema struct
     * @param expectedChildren the expected number of top-level columns
     */
    private static void assertValidArrowSchema(MemorySegment schemaMem, int expectedChildren) {
        long formatPtr = schemaMem.get(ValueLayout.JAVA_LONG, OFFSET_FORMAT);
        assertThat("format pointer should be non-null", formatPtr, not(equalTo(0L)));

        long nChildren = schemaMem.get(ValueLayout.JAVA_LONG, OFFSET_N_CHILDREN);
        assertThat("n_children", nChildren, equalTo((long) expectedChildren));

        long childrenPtr = schemaMem.get(ValueLayout.JAVA_LONG, OFFSET_CHILDREN);
        assertThat("children pointer should be non-null", childrenPtr, not(equalTo(0L)));

        long releasePtr = schemaMem.get(ValueLayout.JAVA_LONG, OFFSET_RELEASE);
        assertThat("release function pointer should be non-null", releasePtr, not(equalTo(0L)));
    }
}
