/*
 * @notice
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modifications copyright (C) 2024 Elasticsearch B.V.
 */
package org.elasticsearch.index.codec.vectors.es93;

import org.apache.lucene.codecs.hnsw.FlatVectorsFormat;

import java.util.Map;
import java.util.concurrent.ExecutorService;

public class ES93HnswBinaryQuantizedVectorsFormat extends ES93GenericHnswVectorsFormat {

    public static final String NAME = "ES93HnswBinaryQuantizedVectorsFormat";

    private static final FlatVectorsFormat flatVectorsFormat = new ES93BinaryQuantizedVectorsFormat();

    private static final Map<String, FlatVectorsFormat> supportedFormats = Map.of(flatVectorsFormat.getName(), flatVectorsFormat);

    private final boolean useDirectIO;

    /** Constructs a format using default graph construction parameters */
    public ES93HnswBinaryQuantizedVectorsFormat() {
        super(NAME);
        useDirectIO = false;
    }

    /**
     * Constructs a format using the given graph construction parameters.
     *
     * @param maxConn the maximum number of connections to a node in the HNSW graph
     * @param beamWidth the size of the queue maintained during graph construction.
     */
    public ES93HnswBinaryQuantizedVectorsFormat(int maxConn, int beamWidth) {
        super(NAME, maxConn, beamWidth);
        useDirectIO = false;
    }

    /**
     * Constructs a format using the given graph construction parameters.
     *
     * @param maxConn the maximum number of connections to a node in the HNSW graph
     * @param beamWidth the size of the queue maintained during graph construction.
     * @param useDirectIO whether direct IO should be used for reads for data written using this format
     */
    public ES93HnswBinaryQuantizedVectorsFormat(int maxConn, int beamWidth, boolean useDirectIO) {
        super(NAME, maxConn, beamWidth);
        this.useDirectIO = useDirectIO;
    }

    /**
     * Constructs a format using the given graph construction parameters and scalar quantization.
     *
     * @param maxConn the maximum number of connections to a node in the HNSW graph
     * @param beamWidth the size of the queue maintained during graph construction.
     * @param numMergeWorkers number of workers (threads) that will be used when doing merge. If
     *     larger than 1, a non-null {@link ExecutorService} must be passed as mergeExec
     * @param mergeExec the {@link ExecutorService} that will be used by ALL vector writers that are
     *     generated by this format to do the merge
     */
    public ES93HnswBinaryQuantizedVectorsFormat(int maxConn, int beamWidth, int numMergeWorkers, ExecutorService mergeExec) {
        super(NAME, maxConn, beamWidth, numMergeWorkers, mergeExec);
        useDirectIO = false;
    }

    @Override
    protected FlatVectorsFormat writeFlatVectorsFormat() {
        return flatVectorsFormat;
    }

    @Override
    protected boolean useDirectIOReads() {
        return useDirectIO;
    }

    @Override
    protected Map<String, FlatVectorsFormat> supportedReadFlatVectorsFormats() {
        return supportedFormats;
    }
}
