/*
 * @notice
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modifications copyright (C) 2024 Elasticsearch B.V.
 */
package org.elasticsearch.index.codec.vectors.es93;

import org.apache.lucene.codecs.hnsw.FlatVectorsFormat;
import org.apache.lucene.util.SetOnce;

import java.util.Map;
import java.util.concurrent.ExecutorService;

/**
 * Copied from Lucene, replace with Lucene's implementation sometime after Lucene 10
 */
public class ES93HnswBinaryQuantizedVectorsFormat extends ES93GenericHnswVectorsFormat {

    public static final String NAME = "ES93HnswBinaryQuantizedVectorsFormat";

    private static final FlatVectorsFormat defaultFlatVectorsFormat = new ES93BinaryQuantizedVectorsFormat(false);
    private static final FlatVectorsFormat directIOFlatVectorsFormat = new ES93BinaryQuantizedVectorsFormat(true);

    private static final Map<String, FlatVectorsFormat> supportedFormats = Map.of(
        defaultFlatVectorsFormat.getName(),
        defaultFlatVectorsFormat,
        directIOFlatVectorsFormat.getName(),
        directIOFlatVectorsFormat
    );

    /** Constructs a format using default graph construction parameters */
    public ES93HnswBinaryQuantizedVectorsFormat() {
        super(NAME);
    }

    /**
     * Constructs a format using the given graph construction parameters.
     *
     * @param maxConn the maximum number of connections to a node in the HNSW graph
     * @param beamWidth the size of the queue maintained during graph construction.
     */
    public ES93HnswBinaryQuantizedVectorsFormat(int maxConn, int beamWidth) {
        super(NAME, maxConn, beamWidth);
    }

    /**
     * Constructs a format using the given graph construction parameters and scalar quantization.
     *
     * @param maxConn the maximum number of connections to a node in the HNSW graph
     * @param beamWidth the size of the queue maintained during graph construction.
     * @param numMergeWorkers number of workers (threads) that will be used when doing merge. If
     *     larger than 1, a non-null {@link ExecutorService} must be passed as mergeExec
     * @param mergeExec the {@link ExecutorService} that will be used by ALL vector writers that are
     *     generated by this format to do the merge
     */
    public ES93HnswBinaryQuantizedVectorsFormat(int maxConn, int beamWidth, int numMergeWorkers, ExecutorService mergeExec) {
        super(NAME, maxConn, beamWidth, numMergeWorkers, mergeExec);
    }

    private final SetOnce<FlatVectorsFormat> writeFormat = new SetOnce<>();

    public void useDirectIO() {
        writeFormat.set(directIOFlatVectorsFormat);
    }

    @Override
    protected FlatVectorsFormat writeFlatVectorsFormat() {
        var format = writeFormat.get();
        if (format == null) {
            format = defaultFlatVectorsFormat;
            writeFormat.set(defaultFlatVectorsFormat);
        }
        return format;
    }

    @Override
    protected Map<String, FlatVectorsFormat> supportedReadFlatVectorsFormats() {
        return supportedFormats;
    }
}
