[discrete]
[[breaking_80_api_changes]]
==== REST API changes

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]
.The deprecated freeze index API has been removed.
[%collapsible]
====
*Details* +
The freeze index API (`POST /<index>/_freeze`) was deprecated in 7.14 and
removed in 8.0.
https://www.elastic.co/blog/significantly-decrease-your-elasticsearch-heap-memory-usage[Improvements
in heap memory usage] have eliminated the reason to freeze indices.
Existing frozen indices can still be unfrozen with the
<<unfreeze-index-api,unfreeze index API>>.

*Impact* +
Requests made to the old freeze index API will return an error.
====

.The cat node API's `local` query parameter has been removed.
[%collapsible]
====
*Details* +
The `?local` parameter to the `GET _cat/nodes` API was deprecated in 7.x and is
rejected in 8.0. This parameter caused the API to use the local cluster state
to determine the nodes returned by the API rather than the cluster state from
the master, but this API requests information from each selected node
regardless of the `?local` parameter which means this API does not run in a
fully node-local fashion.

*Impact* +
Discontinue use of the `?local` query parameter. {ref}/cat-nodes.html[cat node
API] requests that include this parameter will return an error.
====

.The cat shard API's `local` query parameter has been removed.
[%collapsible]
====
*Details* +
The `?local` parameter to the `GET _cat/shards` API was deprecated in 7.x and is
rejected in 8.0. This parameter caused the API to use the local cluster state
to determine the nodes returned by the API rather than the cluster state from
the master, but this API requests information from each selected node
regardless of the `?local` parameter which means this API does not run in a
fully node-local fashion.

*Impact* +
Discontinue use of the `?local` query parameter. {ref}/cat-shards.html[cat shards
API] requests that include this parameter will return an error.
====

.The cat indices API's `local` query parameter has been removed.
[%collapsible]
====
*Details* +
The `?local` parameter to the `GET _cat/indices` API was deprecated in 7.x and is
rejected in 8.0. This parameter caused the API to use the local cluster state
to determine the nodes returned by the API rather than the cluster state from
the master, but this API requests information from each selected node
regardless of the `?local` parameter which means this API does not run in a
fully node-local fashion.

*Impact* +
Discontinue use of the `?local` query parameter. {ref}/cat-indices.html[cat indices
API] requests that include this parameter will return an error.
====

.The get field mapping API's `local` query parameter has been removed.
[%collapsible]
====
*Details* +
The `local` parameter for get field mapping API was deprecated in 7.8 and is
removed in 8.0. This parameter is a no-op and field mappings are always retrieved
locally.

*Impact* +
Discontinue use of the `local` query parameter.
{ref}/indices-get-field-mapping.html[get field mapping API] requests that
include this parameter will return an error.
====

.Post data to jobs API is deprecated.
[%collapsible]
====
*Details* +
The {ml} {ref}/ml-post-data.html[post data to jobs API] is deprecated starting in 7.11.0
and will be removed in a future major version.

*Impact* +
Use {ref}/ml-apis.html#ml-api-datafeed-endpoint[{dfeeds}] instead.
====

.The `job_id` property of the Update {dfeeds} API has been removed.
[%collapsible]
====
*Details* +
The ability to update a `job_id` in a {dfeed} was deprecated in 7.3.0. and is
removed in 8.0.

*Impact* +
It is not possible to move {dfeeds} between {anomaly-jobs}.
====

.Create repository and delete repository API's return `409` status code when a repository is in use instead of `500`.
[%collapsible]
====
*Details* +
The {ref}/put-snapshot-repo-api.html[Create or update snapshot repository API] and
{ref}/delete-snapshot-repo-api.html[Delete snapshot repository API] return `409`
status code when the request is attempting to modify an existing repository that's in use instead of status code `500`.

*Impact* +
Update client code that handles creation and deletion of repositories to reflect this change.
====
// end::notable-breaking-changes[]
