[float]
[[breaking_80_snapshots_changes]]
=== Snapshot and Restore changes

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

// end::notable-breaking-changes[]

[float]
==== Deprecated node level compress setting removed

For shared file system repositories (`"type": "fs"`), the node level setting `repositories.fs.compress` could
previously be used to enable compression for all shared file system repositories where `compress` was not specified.
The `repositories.fs.compress` setting has been removed.

Instead use the repository specific `compress` setting to enable compression. See <<modules-snapshots>> for information
on the `compress` setting.

[float]
==== Compression of meta data files is now on by default

Previously, the default value for `compress` was `false`. The default has been changed to `true`.

This change will affect both newly created repositories and existing repositories where `compress=false` has not been
explicitly specified.

For more information on the compress option, see <<modules-snapshots>>

[float]
==== The S3 repository plugin uses the DNS style access pattern by default

Starting in version 7.2 using the path style access pattern with the S3 repository is deprecated.
Previously the S3 repository plugin was exclusively using the path style access pattern so this is a breaking
change for deployments that do not also allow for the DNS style access pattern. For short-term compatibility with these deployments users
must configure the S3 client setting `path_style_access` to `true` to retain the previous behaviour but should be advised that
the option to enable path style access will be removed in future versions of Elasticsearch.

This breaking change was made necessary by https://forums.aws.amazon.com/ann.jspa?annID=6776[AWS's announcement] to no longer support
the path-style API past September 30th, 2020.
