[role="xpack"]
[testenv="basic"]
[[search-aggregations-pipeline-cumulative-cardinality-aggregation]]
=== Cumulative Cardinality Aggregation

A parent pipeline aggregation which calculates the Cumulative Cardinality in a parent histogram (or date_histogram)
aggregation. The specified metric must be a cardinality aggregation and the enclosing histogram 
must have `min_doc_count` set to `0` (default for `histogram` aggregations).

The `cumulative_cardinality` agg is useful for finding "total new items", like the number of new visitors to your
website each day.  A regular cardinality aggregation will tell you how many unique visitors came each day, but doesn't
differentiate between "new" or "repeat" visitors.  The Cumulative Cardinality aggregation can be used to determine
how many of each day's unique visitors are "new".

==== Syntax

A `cumulative_cardinality` aggregation looks like this in isolation:

[source,js]
--------------------------------------------------
{
    "cumulative_cardinality": {
        "buckets_path": "my_cardinality_agg"
    }
}
--------------------------------------------------
// NOTCONSOLE

[[cumulative-cardinality-params]]
.`cumulative_cardinality` Parameters
[options="header"]
|===
|Parameter Name |Description |Required |Default Value
|`buckets_path` |The path to the cardinality aggregation we wish to find the cumulative cardinality for (see <<buckets-path-syntax>> for more
 details) |Required |
|`format` |format to apply to the output value of this aggregation |Optional |`null` 
|===

The following snippet calculates the cumulative cardinality of the total monthly `sales`:

[source,js]
--------------------------------------------------
POST /sales/_search
{
    "size": 0,
    "aggs" : {
        "sales_per_month" : {
            "date_histogram" : {
                "field" : "date",
                "calendar_interval" : "month"
            },
            "aggs": {
                "distinct_sale_types": {
                    "cardinality": {
                        "field": "type"
                    }
                },
                "total_new_types": {
                    "cumulative_cardinality": {
                        "buckets_path": "distinct_sale_types" <1>
                    }
                }
            }
        }
    }
}
--------------------------------------------------
// CONSOLE
// TEST[setup:sales]

<1> `buckets_path` instructs this aggregation to use the output of the `distinct_sale_types` aggregation for the cumulative cardinality

And the following may be the response:

[source,js]
--------------------------------------------------
{
   "took": 11,
   "timed_out": false,
   "_shards": ...,
   "hits": ...,
   "aggregations": {
      "sales_per_month": {
         "buckets": [
            {
               "key_as_string": "2015/01/01 00:00:00",
               "key": 1420070400000,
               "doc_count": 3,
               "distinct_sale_types": {
                  "value": 3
               },
               "total_new_types": {
                  "value": 3
               }
            },
            {
               "key_as_string": "2015/02/01 00:00:00",
               "key": 1422748800000,
               "doc_count": 2,
               "distinct_sale_types": {
                  "value": 2
               },
               "total_new_types": {
                  "value": 3
               }
            },
            {
               "key_as_string": "2015/03/01 00:00:00",
               "key": 1425168000000,
               "doc_count": 2,
               "distinct_sale_types": {
                  "value": 2
               },
               "total_new_types": {
                  "value": 3
               }
            }
         ]
      }
   }
}
--------------------------------------------------
// TESTRESPONSE[s/"took": 11/"took": $body.took/]
// TESTRESPONSE[s/"_shards": \.\.\./"_shards": $body._shards/]
// TESTRESPONSE[s/"hits": \.\.\./"hits": $body.hits/]


==== Incremental cumulative cardinality

The `cumulative_cardinality` agg will show you the total, distinct count since the beginning of the time period
being queried.  Sometimes, however, it is useful to see the "incremental" count.  Meaning, how many new users
are added each day, rather than the total cumulative count.

This can be accomplished by adding a `derivative` aggregation to our query:

[source,js]
--------------------------------------------------
POST /sales/_search
{
    "size": 0,
    "aggs" : {
        "sales_per_month" : {
            "date_histogram" : {
                "field" : "date",
                "calendar_interval" : "month"
            },
            "aggs": {
                "distinct_sale_types": {
                    "cardinality": {
                        "field": "type"
                    }
                },
                "total_new_types": {
                    "cumulative_cardinality": {
                        "buckets_path": "distinct_sale_types"
                    }
                },
                "incremental_new_types": {
                    "derivative": {
                        "buckets_path": "total_new_types"
                    }
                }
            }
        }
    }
}
--------------------------------------------------
// CONSOLE
// TEST[setup:sales]


And the following may be the response:

[source,js]
--------------------------------------------------
{
   "took": 11,
   "timed_out": false,
   "_shards": ...,
   "hits": ...,
   "aggregations": {
      "sales_per_month": {
         "buckets": [
            {
               "key_as_string": "2015/01/01 00:00:00",
               "key": 1420070400000,
               "doc_count": 3,
               "distinct_sale_types": {
                  "value": 3
               },
               "total_new_types": {
                  "value": 3
               }
            },
            {
               "key_as_string": "2015/02/01 00:00:00",
               "key": 1422748800000,
               "doc_count": 2,
               "distinct_sale_types": {
                  "value": 2
               },
               "total_new_types": {
                  "value": 3
               },
               "incremental_new_types": {
                  "value": 0.0
               }
            },
            {
               "key_as_string": "2015/03/01 00:00:00",
               "key": 1425168000000,
               "doc_count": 2,
               "distinct_sale_types": {
                  "value": 2
               },
               "total_new_types": {
                  "value": 3
               },
               "incremental_new_types": {
                  "value": 0.0
               }
            }
         ]
      }
   }
}
--------------------------------------------------
// TESTRESPONSE[s/"took": 11/"took": $body.took/]
// TESTRESPONSE[s/"_shards": \.\.\./"_shards": $body._shards/]
// TESTRESPONSE[s/"hits": \.\.\./"hits": $body.hits/]
