steps:
  - label: Update lucene-snapshot branch
    command: .buildkite/scripts/lucene-snapshot/update-branch.sh
    timeout_in_minutes: 15
  - wait
  - trigger: "elasticsearch-lucene-snapshot-tests"
    build:
      branch: "${BUILDKITE_BRANCH}"
    async: true
  - trigger: "elasticsearch-lucene-snapshot-update-branch"
    label: Update lucene_snapshot_11 branch
    if: build.branch == "lucene_snapshot"
    build:
      branch: "lucene_snapshot_11"
    async: true
