[[release-notes-6.0.0]]
== 6.0.0 Release Notes

These release notes include all changes made in the alpha, beta, and RC releases of 6.0.0,
excluding those that have already been released in the 5.x series before 6.0.0-alpha1.

Also see:

* <<breaking-changes-6.0>>
* <<release-notes-6.0.0-alpha1-5x>>

[[breaking-6.0.0]]
[float]
=== Breaking changes

Aggregations::
* Change parsing of numeric `to` and `from` parameters in `date_range` aggregation {pull}25376[#25376] (issue: {issue}17920[#17920])

Aliases::
* Wrong behavior deleting alias {pull}23997[#23997] (issues: {issue}10106[#10106], {issue}23960[#23960])

Allocation::
* Remove `cluster.routing.allocation.snapshot.relocation_enabled` setting {pull}20994[#20994]

Analysis::
* Do not allow custom analyzers to have the same names as built-in analyzers {pull}22349[#22349] (issue: {issue}22263[#22263])
* Removing query-string parameters in `_analyze` API {pull}20704[#20704] (issue: {issue}20246[#20246])

CAT API::
* Write -1 on unbounded queue in cat thread pool {pull}21342[#21342] (issue: {issue}21187[#21187])

CRUD::
* Disallow `VersionType.FORCE` for GetRequest {pull}21079[#21079] (issue: {issue}20995[#20995])
* Disallow `VersionType.FORCE` versioning for 6.x indices {pull}20995[#20995] (issue: {issue}20377[#20377])
* If the index does not exist, delete document will not auto create it {pull}24518[#24518] (issue: {issue}15425[#15425])

Cluster::
* Disallow : in cluster and index/alias names {pull}26247[#26247] (issue: {issue}23892[#23892])
* No longer allow cluster name in data path {pull}20433[#20433] (issue: {issue}20391[#20391])

Core::
* Simplify file store {pull}24402[#24402] (issue: {issue}24390[#24390])
* Make boolean conversion strict {pull}22200[#22200]
* Remove the `default` store type. {pull}21616[#21616]
* Remove store throttling. {pull}21573[#21573]

Geo::
* Remove deprecated geo search features {pull}22876[#22876]
* Reduce GeoDistance Insanity {pull}19846[#19846]

Highlighting::
* Remove the postings highlighter and make unified the default highlighter choice {pull}25028[#25028]

Index APIs::
* Remove (deprecated) support for '+' in index expressions {pull}25274[#25274] (issue: {issue}24515[#24515])
* Delete index API to work only against concrete indices {pull}25268[#25268] (issues: {issue}2318[#2318], {issue}23997[#23997])
* Open/Close index api to allow_no_indices by default {pull}24401[#24401] (issues: {issue}24031[#24031], {issue}24341[#24341])
* Remove support for controversial `ignore_unavailable` and `allow_no_indices` from indices exists api {pull}20712[#20712]

Index Templates::
* Allows multiple patterns to be specified for index templates {pull}21009[#21009] (issue: {issue}20690[#20690])

Indexed Scripts/Templates::
* Scripting: Remove search template actions {pull}25717[#25717]

Ingest::
* update ingest-user-agent regexes.yml {pull}25608[#25608]
* remove ingest.new_date_format {pull}25583[#25583]

Inner Hits::
* Return the _source of inner hit nested as is without wrapping it into its full path context {pull}26982[#26982] (issues: {issue}26102[#26102], {issue}26944[#26944])

Java API::
* Enforce Content-Type requirement on the rest layer and remove deprecated methods {pull}23146[#23146] (issue: {issue}19388[#19388])

Java REST Client::
* Remove deprecated created and found from index, delete and bulk {pull}25516[#25516] (issues: {issue}19566[#19566], {issue}19630[#19630], {issue}19633[#19633])

Mapping::
* Reject out of range numbers for float, double and half_float {pull}25826[#25826] (issue: {issue}25534[#25534])
* Enforce at most one type. {pull}24428[#24428] (issue: {issue}24317[#24317])
* Disallow `include_in_all` for 6.0+ indices {pull}22970[#22970] (issue: {issue}22923[#22923])
* Disable _all by default, disallow configuring _all on 6.0+ indices {pull}22144[#22144] (issues: {issue}19784[#19784], {issue}20925[#20925], {issue}21341[#21341])
* Throw an exception on unrecognized "match_mapping_type" {pull}22090[#22090] (issue: {issue}17285[#17285])

Network::
* Remove unused Netty-related settings {pull}26161[#26161]
* Remove blocking TCP clients and servers {pull}22639[#22639]
* Remove `modules/transport_netty_3` in favor of `netty_4` {pull}21590[#21590]
* Remove LocalTransport in favor of MockTcpTransport {pull}20695[#20695]

Packaging::
* Configure heap dump path out of the box {pull}26755[#26755] (issue: {issue}26665[#26665])
* Remove support for ES_INCLUDE {pull}25804[#25804]
* Setup: Change default heap to 1G {pull}25695[#25695]
* Use config directory to find jvm.options {pull}25679[#25679] (issue: {issue}23004[#23004])
* Remove implicit 32-bit support {pull}25435[#25435]
* Remove default path settings {pull}25408[#25408] (issue: {issue}25357[#25357])
* Remove path.conf setting {pull}25392[#25392] (issue: {issue}25357[#25357])
* Honor masking of systemd-sysctl.service {pull}24234[#24234] (issues: {issue}21899[#21899], {issue}806[#806])
* Rename CONF_DIR to ES_PATH_CONF {pull}26197[#26197] (issue: {issue}26154[#26154])
* Remove customization of ES_USER and ES_GROUP {pull}23989[#23989] (issue: {issue}23848[#23848])

Percolator::
* Remove deprecated percolate and mpercolate apis {pull}22331[#22331]

Plugin Analysis ICU::
* Upgrade icu4j for the ICU analysis plugin to 59.1 {pull}25243[#25243] (issue: {issue}21425[#21425])
* Upgrade icu4j to latest version {pull}24821[#24821]

Plugin Delete By Query::
* Require explicit query in _delete_by_query API {pull}23632[#23632] (issue: {issue}23629[#23629])

Plugin Discovery Azure Classic::
* Remove `discovery.type` BWC layer from the EC2/Azure/GCE plugins {pull}25080[#25080] (issue: {issue}24543[#24543])

Plugin Discovery EC2::
* Ec2 Discovery: Cleanup deprecated settings {pull}24150[#24150]
* Discovery EC2: Remove region setting {pull}23991[#23991] (issue: {issue}22758[#22758])
* AWS Plugins: Remove signer type setting {pull}23984[#23984] (issue: {issue}22599[#22599])

Plugin Lang JS::
* Remove lang-python and lang-javascript {pull}20734[#20734] (issue: {issue}20698[#20698])

Plugin Mapper Attachment::
* Remove mapper attachments plugin {pull}20416[#20416] (issue: {issue}18837[#18837])

Plugin Repository Azure::
* Remove global `repositories.azure` settings {pull}23262[#23262] (issues: {issue}22800[#22800], {issue}22856[#22856])
* Remove auto creation of container for azure repository {pull}22858[#22858] (issue: {issue}22857[#22857])

Plugin Repository GCS::
* GCS Repository: Remove specifying credential file on disk {pull}24727[#24727]

Plugin Repository S3::
* S3 Repository: Cleanup deprecated settings {pull}24097[#24097]
* S3 Repository: Remove region setting {pull}22853[#22853] (issue: {issue}22758[#22758])
* S3 Repository: Remove bucket auto create {pull}22846[#22846] (issue: {issue}22761[#22761])
* S3 Repository: Remove env var and sysprop credentials support {pull}22842[#22842]
* Remove deprecated S3 settings {pull}24445[#24445]

Plugins::
* Make plugin loading stricter {pull}25405[#25405]

Query DSL::
* Remove deprecated `type` and `slop` field in `match` query {pull}26720[#26720]
* Remove several parse field deprecations in query builders {pull}26711[#26711]
* Remove deprecated parameters from `ids_query` {pull}26508[#26508]
* Refactor QueryStringQuery for 6.0 {pull}25646[#25646] (issue: {issue}25574[#25574])
* Change `split_on_whitespace` default to false {pull}25570[#25570] (issue: {issue}25470[#25470])
* Remove deprecated template query {pull}24577[#24577] (issue: {issue}19390[#19390])
* Throw exception in scroll requests using `from` {pull}26235[#26235] (issue: {issue}9373[#9373])
* Remove deprecated `minimum_number_should_match` in BoolQueryBuilder {pull}22416[#22416]
* Remove support for empty queries {pull}22092[#22092] (issue: {issue}17624[#17624])
* Remove deprecated query names: in, geo_bbox, mlt, fuzzy_match and match_fuzzy {pull}21852[#21852]
* The `terms` query should always map to a Lucene `TermsQuery`. {pull}21786[#21786]
* Be strict when parsing values searching for booleans {pull}21555[#21555] (issue: {issue}21545[#21545])
* Remove collect payloads parameter {pull}20385[#20385]

REST::
* IndexClosedException to return 400 rather than 403 {pull}25752[#25752]
* Remove comma-separated feature parsing for GetIndicesAction {pull}24723[#24723] (issue: {issue}24437[#24437])
* Improve REST error handling when endpoint does not support HTTP verb, add OPTIONS support {pull}24437[#24437] (issues: {issue}0[#0], {issue}15335[#15335], {issue}17916[#17916])
* Remove ldjson support and document ndjson for bulk/msearch {pull}23049[#23049] (issue: {issue}23025[#23025])
* Enable strict duplicate checks for all XContent types {pull}22225[#22225] (issues: {issue}19614[#19614], {issue}22073[#22073])
* Enable strict duplicate checks for JSON content {pull}22073[#22073] (issue: {issue}19614[#19614])
* Remove lenient stats parsing {pull}21417[#21417] (issues: {issue}20722[#20722], {issue}21410[#21410])
* Remove allow unquoted JSON {pull}20388[#20388] (issues: {issue}17674[#17674], {issue}17801[#17801])
* Remove FORCE version_type {pull}20377[#20377] (issue: {issue}19769[#19769])

Scripting::
* remove lang url parameter from stored script requests {pull}25779[#25779] (issue: {issue}22887[#22887])
* Disallow lang to be used with Stored Scripts {pull}25610[#25610]
* Remove Deprecated Script Settings {pull}24756[#24756] (issue: {issue}24532[#24532])
* Scripting: Remove native scripts {pull}24726[#24726] (issue: {issue}19966[#19966])
* Scripting: Remove file scripts {pull}24627[#24627] (issue: {issue}21798[#21798])
* Make dates be ReadableDateTimes in scripts {pull}22948[#22948] (issue: {issue}22875[#22875])
* Remove groovy scripting language {pull}21607[#21607]
* Remove script access to term statistics {pull}19462[#19462] (issue: {issue}19359[#19359])

Search::
* Make `index` in TermsLookup mandatory {pull}25753[#25753] (issue: {issue}25750[#25750])
* Removes FieldStats API {pull}25628[#25628] (issue: {issue}25577[#25577])
* Remove deprecated fielddata_fields from search request {pull}25566[#25566] (issue: {issue}25537[#25537])
* Removes deprecated fielddata_fields {pull}25537[#25537] (issue: {issue}19027[#19027])
* ProfileResult and CollectorResult should print machine readable timing information {pull}22561[#22561]
* Remove indices query {pull}21837[#21837] (issue: {issue}17710[#17710])
* Remove ignored type parameter in search_shards api {pull}21688[#21688]

Sequence IDs::
* Change certain replica failures not to fail the replica shard {pull}22874[#22874] (issue: {issue}10708[#10708])

Settings::
* Settings: Remove shared setting property {pull}24728[#24728]
* Settings: Remove support for yaml and json config files {pull}24664[#24664] (issue: {issue}19391[#19391])

Shadow Replicas::
* Remove shadow replicas {pull}23906[#23906] (issue: {issue}22024[#22024])

Similarities::
* Similarity should accept dynamic settings when possible {pull}20339[#20339] (issue: {issue}6727[#6727])



[[breaking-java-6.0.0]]
[float]
=== Breaking Java changes

Aggregations::
* Remove the unused SignificantTerms.compareTerm() method {pull}24714[#24714]
* Make SignificantTerms.Bucket an interface rather than an abstract class {pull}24670[#24670] (issue: {issue}24492[#24492])
* Fix NPE when `values` is omitted on percentile_ranks agg {pull}26046[#26046]
* Make Terms.Bucket an interface rather than an abstract class {pull}24492[#24492]
* Compound order for histogram aggregations  {pull}22343[#22343] (issues: {issue}14771[#14771], {issue}20003[#20003], {issue}23613[#23613])

Internal::
* Collapses package structure for some bucket aggs {pull}25579[#25579] (issue: {issue}22868[#22868])

Java API::
* Remove deprecated IdsQueryBuilder ctor {pull}25529[#25529]
* Removing unneeded getTookInMillis method {pull}23923[#23923]
* Java api: ActionRequestBuilder#execute to return a PlainActionFuture {pull}24415[#24415] (issues: {issue}24412[#24412], {issue}9201[#9201])

Java High Level REST Client::
* Unify the result interfaces from get and search in Java client {pull}25361[#25361] (issue: {issue}16440[#16440])
* Allow RestHighLevelClient to use plugins {pull}25024[#25024]

Java REST Client::
* Rename client artifacts {pull}25693[#25693] (issue: {issue}20248[#20248])

Network::
* Simplify TransportAddress {pull}20798[#20798]

Plugin Delete By Query::
* Move DeleteByQuery and Reindex requests into core {pull}24578[#24578]

Plugins::
* Drop name from TokenizerFactory {pull}24869[#24869]

Query DSL::
* Remove QueryParseContext {pull}25486[#25486]
* Remove QueryParseContext from parsing QueryBuilders {pull}25448[#25448]

REST::
* Return index name and empty map for `/{index}/_alias` with no aliases {pull}25114[#25114] (issues: {issue}24723[#24723], {issue}25090[#25090])



[[deprecation-6.0.0]]
[float]
=== Deprecations

Index APIs::
* Deprecated use of + in index expressions {pull}24585[#24585] (issue: {issue}24515[#24515])

Index Templates::
* Restore deprecation warning for invalid match_mapping_type values {pull}22304[#22304]

Indexed Scripts/Templates::
* Scripting: Deprecate stored search template apis {pull}25437[#25437] (issue: {issue}24596[#24596])

Internal::
* Deprecate XContentType auto detection methods in XContentFactory {pull}22181[#22181] (issue: {issue}19388[#19388])

Percolator::
* Deprecate percolate query's document_type parameter. {pull}25199[#25199]

Plugins::
* Plugins: Add backcompat for sha1 checksums {pull}26748[#26748] (issue: {issue}26746[#26746])

Scripting::
* Scripting: Change keys for inline/stored scripts to source/id {pull}25127[#25127]
* Scripting: Deprecate native scripts {pull}24692[#24692] (issue: {issue}19966[#19966])
* Scripting: Deprecate index lookup {pull}24691[#24691] (issue: {issue}19359[#19359])
* Deprecate Fine Grain Settings for Scripts {pull}24573[#24573] (issue: {issue}24532[#24532])
* Scripting: Deprecate file script settings {pull}24555[#24555] (issue: {issue}21798[#21798])
* Scripting: Deprecate file scripts {pull}24552[#24552] (issue: {issue}21798[#21798])

Settings::
* Settings: Update settings deprecation from yml to yaml {pull}24663[#24663] (issue: {issue}19391[#19391])
* Deprecate settings in .yml and .json {pull}24059[#24059] (issue: {issue}19391[#19391])

Tribe Node::
* Deprecate tribe service {pull}24598[#24598] (issue: {issue}24581[#24581])



[[feature-6.0.0]]
[float]
=== New features

Aggregations::
* SignificantText aggregation - like significant_terms, but for text {pull}24432[#24432] (issue: {issue}23674[#23674])

Analysis::
* Expose simplepattern and simplepatternsplit tokenizers {pull}25159[#25159] (issue: {issue}23363[#23363])
* Parse synonyms with the same analysis chain {pull}8049[#8049] (issue: {issue}7199[#7199])

Core::
* Enable index-time sorting {pull}24055[#24055] (issue: {issue}6720[#6720])

Internal::
* Automatically adjust search threadpool queue_size {pull}23884[#23884] (issue: {issue}3890[#3890])

Mapping::
* Add new ip_range field type {pull}24433[#24433]

Parent/Child::
* Move parent_id query to the parent-join module {pull}25072[#25072] (issue: {issue}20257[#20257])
* Introduce ParentJoinFieldMapper, a field mapper that creates parent/child relation within documents of the same index {pull}24978[#24978] (issue: {issue}20257[#20257])

Plugin Analysis ICU::
* Add ICUCollationFieldMapper {pull}24126[#24126]

Search::
* Automatically early terminate search query based on index sorting {pull}24864[#24864] (issue: {issue}6720[#6720])

Sequence IDs::
* Add a scheduled translog retention check {pull}25622[#25622] (issues: {issue}10708[#10708], {issue}25294[#25294])
* Initialize sequence numbers on a shrunken index {pull}25321[#25321] (issue: {issue}10708[#10708])
* Initialize primary term for shrunk indices {pull}25307[#25307] (issue: {issue}10708[#10708])
* Introduce translog size and age based retention policies {pull}25147[#25147] (issue: {issue}10708[#10708])

Stats::
* Adds nodes usage API to monitor usages of actions {pull}24169[#24169]

Task Manager::
* Task Management [ISSUE] {pull}15117[#15117]

Upgrade API::
* TemplateUpgraders should be called during rolling restart {pull}25263[#25263] (issues: {issue}24379[#24379], {issue}24680[#24680])



[[enhancement-6.0.0]]
[float]
=== Enhancements

Aggregations::
* Add strict parsing of aggregation ranges {pull}25769[#25769]
* Adds rewrite phase to aggregations {pull}25495[#25495] (issue: {issue}17676[#17676])
* Tweak AggregatorBase.addRequestCircuitBreakerBytes {pull}25162[#25162] (issue: {issue}24511[#24511])
* Add superset size to Significant Term REST response {pull}24865[#24865]
* Add document count to Matrix Stats aggregation response {pull}24776[#24776]
* Adds an implementation of LogLogBeta for the cardinality aggregation {pull}22323[#22323] (issue: {issue}22230[#22230])
* Support distance units in GeoHashGrid aggregation precision {pull}26291[#26291] (issue: {issue}5042[#5042])
* Reject multiple methods in `percentiles` aggregation {pull}26163[#26163] (issue: {issue}26095[#26095])
* Use `global_ordinals_hash` execution mode when sorting by sub aggregations. {pull}26014[#26014] (issue: {issue}24359[#24359])
* Add a specialized deferring collector for terms aggregator {pull}25190[#25190]
* Agg builder accessibility fixes {pull}24323[#24323]
* Remove support for the include/pattern syntax. {pull}23141[#23141] (issue: {issue}22933[#22933])
* Promote longs to doubles when a terms agg mixes decimal and non-decimal numbers {pull}22449[#22449] (issue: {issue}22232[#22232])

Allocation::
* Adjust status on bad allocation explain requests {pull}25503[#25503] (issue: {issue}25458[#25458])
* Promote replica on the highest version node {pull}25277[#25277] (issue: {issue}10708[#10708])

Analysis::
* [Analysis] Support normalizer in request param {pull}24767[#24767] (issue: {issue}23347[#23347])
* Enforce validation for PathHierarchy tokenizer {pull}23510[#23510]
* [analysis-icu] Allow setting unicodeSetFilter {pull}20814[#20814] (issue: {issue}20820[#20820])
* Match- and MultiMatchQueryBuilder should only allow setting analyzer on string values {pull}23684[#23684] (issue: {issue}21665[#21665])

Bulk::
* Simplify bulk request execution  {pull}20109[#20109]

CAT API::
* expand `/_cat/nodes` to return information about hard drive {pull}21775[#21775] (issue: {issue}21679[#21679])

CRUD::
* Added validation for upsert request {pull}24282[#24282] (issue: {issue}16671[#16671])

Circuit Breakers::
* ScriptService: Replace max compilation per minute setting with max compilation rate {pull}26399[#26399]

Cluster::
* Validate a joining node's version with version of existing cluster nodes {pull}25808[#25808]
* Switch indices read-only if a node runs out of disk space {pull}25541[#25541] (issue: {issue}24299[#24299])
* Add a cluster block that allows to delete indices that are read-only {pull}24678[#24678]
* Separate publishing from applying cluster states {pull}24236[#24236]
* Adds cluster state size to /_cluster/state response {pull}23440[#23440] (issue: {issue}3415[#3415])

Core::
* Allow `InputStreamStreamInput` array size validation where applicable {pull}26692[#26692]
* Refactor bootstrap check results and error messages {pull}26637[#26637]
* Add BootstrapContext to expose settings and recovered state to bootstrap checks {pull}26628[#26628]
* Unit testable index creation task on MetaDataCreateIndexService {pull}25961[#25961]
* Ignore .DS_Store files on macOS {pull}27108[#27108] (issue: {issue}23982[#23982])
* Add max file size bootstrap check {pull}25974[#25974]
* Add compatibility versions to main action response {pull}25799[#25799]
* Index ids in binary form. {pull}25352[#25352] (issues: {issue}18154[#18154], {issue}24615[#24615])
* Explicitly reject duplicate data paths {pull}25178[#25178]
* Use SPI in High Level Rest Client to load XContent parsers {pull}25097[#25097]
* Upgrade to lucene-7.0.0-snapshot-a0aef2f {pull}24775[#24775]
* Speed up PK lookups at index time. {pull}19856[#19856]
* Use Java 9 FilePermission model {pull}26302[#26302] (issue: {issue}21534[#21534])
* Add friendlier message on bad keystore permissions {pull}26284[#26284]
* Epoch millis and second formats accept float implicitly {pull}26119[#26119] (issue: {issue}14641[#14641])
* Remove connect SocketPermissions from core {pull}22797[#22797]
* Add repository-url module and move URLRepository {pull}22752[#22752] (issue: {issue}22116[#22116])
* Remove accept SocketPermissions from core {pull}22622[#22622] (issue: {issue}22116[#22116])
* Move IfConfig.logIfNecessary call into bootstrap {pull}22455[#22455] (issue: {issue}22116[#22116])
* Remove artificial default processors limit {pull}20874[#20874] (issue: {issue}20828[#20828])
* Simplify write failure handling {pull}19105[#19105] (issue: {issue}20109[#20109])
* Improve bootstrap checks error messages {pull}24548[#24548]

Discovery::
* Allow plugins to validate cluster-state on join {pull}26595[#26595]

Engine::
* Add refresh stats tracking for realtime get {pull}25052[#25052] (issue: {issue}24806[#24806])
* Introducing a translog deletion policy {pull}24950[#24950]
* Fill missing sequence IDs up to max sequence ID when recovering from store {pull}24238[#24238] (issue: {issue}10708[#10708])
* Use sequence numbers to identify out of order delivery in replicas & recovery {pull}24060[#24060] (issue: {issue}10708[#10708])
* Add replica ops with version conflict to translog {pull}22626[#22626]
* Clarify global checkpoint recovery {pull}21934[#21934] (issue: {issue}21254[#21254])
* Move the IndexDeletionPolicy to be engine internal {pull}24930[#24930] (issue: {issue}10708[#10708])

Exceptions::
* IllegalStateException: Only duplicated jar instead of classpath {pull}24953[#24953]

Highlighting::
* Picks offset source for the unified highlighter directly from the es mapping {pull}25747[#25747] (issue: {issue}25699[#25699])

Index APIs::
* Let primary own its replication group {pull}25692[#25692] (issue: {issue}25485[#25485])
* Create index request should return the index name {pull}25139[#25139] (issue: {issue}23044[#23044])

Index Templates::
* Fix error message for a put index template request without index_patterns {pull}27102[#27102] (issue: {issue}27100[#27100])

Ingest::
* Add Ingest-Processor specific Rest Endpoints & Add Grok endpoint {pull}25059[#25059] (issue: {issue}24725[#24725])
* Port support for commercial GeoIP2 databases from Logstash. {pull}24889[#24889]
* add `exclude_keys` option to KeyValueProcessor {pull}24876[#24876] (issue: {issue}23856[#23856])
* Allow removing multiple fields in ingest processor {pull}24750[#24750] (issue: {issue}24622[#24622])
* Add target_field parameter to ingest processors {pull}24133[#24133] (issues: {issue}23228[#23228], {issue}23682[#23682])

Inner Hits::
* Reuse inner hit query weight {pull}24571[#24571] (issue: {issue}23917[#23917])

Internal::
* TemplateUpgradeService should only run on the master {pull}27294[#27294]
* Cleanup IndexFieldData visibility {pull}25900[#25900]
* Bump the min compat version to 5.6.0 {pull}25805[#25805]
* "shard started" should show index and shard ID {pull}25157[#25157]
* Break out clear scroll logic from TransportClearScrollAction {pull}25125[#25125] (issue: {issue}25094[#25094])
* Add helper methods to TransportActionProxy to identify proxy actions and requests {pull}25124[#25124]
* Add remote cluster infrastructure to fetch discovery nodes. {pull}25123[#25123] (issue: {issue}25094[#25094])
* Add the ability to set eager_global_ordinals in the new parent-join field {pull}25019[#25019]
* Disallow multiple parent-join fields per mapping {pull}25002[#25002]
* Remove the need for _UNRELEASED suffix in versions {pull}24798[#24798] (issue: {issue}24768[#24768])
* Optimize the order of bytes in uuids for better compression. {pull}24615[#24615] (issue: {issue}18209[#18209])
* Prevent cluster internal `ClusterState.Custom` impls to leak to a client {pull}26232[#26232]
* Use holder pattern for lazy deprecation loggers {pull}26218[#26218] (issue: {issue}26210[#26210])
* Allow `ClusterState.Custom` to be created on initial cluster states {pull}26144[#26144]
* Try to convince the JVM not to lose stacktraces {pull}24426[#24426] (issue: {issue}24376[#24376])
* Make document write requests immutable {pull}23038[#23038]
* Add assertions enabled helper {pull}24834[#24834]

Java API::
* Always Accumulate Transport Exceptions {pull}25017[#25017] (issue: {issue}23099[#23099])

Java High Level REST Client::
* [DOCS] restructure java clients docs pages {pull}25517[#25517]
* Use SPI in High Level Rest Client to load XContent parsers {pull}25098[#25098] (issues: {issue}25024[#25024], {issue}25097[#25097])
* Add support for clear scroll to high level REST client {pull}25038[#25038]
* Add search scroll method to high level REST client {pull}24938[#24938] (issue: {issue}23331[#23331])
* Add search method to high level REST client {pull}24796[#24796] (issues: {issue}24794[#24794], {issue}24795[#24795])
* Make RestHighLevelClient Closeable and simplify its creation {pull}26180[#26180] (issue: {issue}26086[#26086])
* Add info method to High Level Rest client {pull}23350[#23350]
* Add support for named xcontent parsers to high level REST client {pull}23328[#23328]
* Add BulkRequest support to High Level Rest client {pull}23312[#23312]
* Add UpdateRequest support to High Level Rest client {pull}23266[#23266]
* Add delete API to the High Level Rest Client {pull}23187[#23187]
* Add Index API to High Level Rest Client {pull}23040[#23040]
* Add get/exists method to RestHighLevelClient {pull}22706[#22706]
* Add fromxcontent methods to delete response {pull}22680[#22680] (issue: {issue}22229[#22229])
* Add REST high level client gradle submodule and first simple method {pull}22371[#22371]
* Add doc_count to ParsedMatrixStats {pull}24952[#24952] (issue: {issue}24776[#24776])
* Add fromXContent method to ClearScrollResponse {pull}24909[#24909]
* ClearScrollRequest to implement ToXContentObject {pull}24907[#24907]
* SearchScrollRequest to implement ToXContentObject {pull}24906[#24906] (issue: {issue}3889[#3889])
* Add aggs parsers for high level REST Client {pull}24824[#24824] (issues: {issue}23965[#23965], {issue}23973[#23973], {issue}23974[#23974], {issue}24085[#24085], {issue}24160[#24160], {issue}24162[#24162], {issue}24182[#24182], {issue}24183[#24183], {issue}24208[#24208], {issue}24213[#24213], {issue}24239[#24239], {issue}24284[#24284], {issue}24312[#24312], {issue}24330[#24330], {issue}24365[#24365], {issue}24371[#24371], {issue}24442[#24442], {issue}24521[#24521], {issue}24524[#24524], {issue}24564[#24564], {issue}24583[#24583], {issue}24589[#24589], {issue}24648[#24648], {issue}24667[#24667], {issue}24675[#24675], {issue}24682[#24682], {issue}24700[#24700], {issue}24706[#24706], {issue}24717[#24717], {issue}24720[#24720], {issue}24738[#24738], {issue}24746[#24746], {issue}24789[#24789], {issue}24791[#24791], {issue}24794[#24794], {issue}24796[#24796], {issue}24822[#24822])

Java REST Client::
* Shade external dependencies in the rest client jar {pull}25780[#25780] (issue: {issue}25208[#25208])
* RestClient uses system properties and system default SSLContext {pull}25757[#25757] (issue: {issue}23231[#23231])
* Wrap rest httpclient with doPrivileged blocks {pull}22603[#22603] (issue: {issue}22116[#22116])

Logging::
* Prevent excessive disk consumption by log files {pull}25660[#25660]
* Use LRU set to reduce repeat deprecation messages {pull}25474[#25474] (issue: {issue}25457[#25457])

Mapping::
* More efficient encoding of range fields. {pull}26470[#26470] (issue: {issue}26443[#26443])
* Don't detect source's XContentType in DocumentParser.parseDocument() {pull}26880[#26880]
* Better validation of `copy_to`. {pull}25983[#25983]
* Optimize `terms` queries on `ip` addresses to use a `PointInSetQuery` whenever possible. {pull}25669[#25669] (issue: {issue}25667[#25667])
* Loosen the restrictions on disabling _all in 6.x {pull}26259[#26259]
* Date detection should not rely on a hardcoded set of characters. {pull}22171[#22171] (issue: {issue}1694[#1694])
* Identify documents by their `_id`. {pull}24460[#24460]

Network::
* Add additional low-level logging handler {pull}26887[#26887]
* Unwrap causes when maybe dying {pull}26884[#26884]
* Move TransportStats accounting into TcpTransport {pull}25251[#25251]
* Simplify connection closing and cleanups in TcpTransport {pull}25250[#25250]
* Disable the Netty recycler in the client {pull}24793[#24793] (issues: {issue}22452[#22452], {issue}24721[#24721])
* Remove Netty logging hack {pull}24653[#24653] (issues: {issue}24469[#24469], {issue}5624[#5624], {issue}6568[#6568], {issue}6696[#6696])
* Isolate SocketPermissions to Netty {pull}23057[#23057]
* Wrap netty accept/connect ops with doPrivileged {pull}22572[#22572] (issue: {issue}22116[#22116])
* Replace Socket, ServerSocket, and HttpServer usages in tests with mocksocket versions {pull}22287[#22287] (issue: {issue}22116[#22116])

Packaging::
* Remove memlock suggestion from systemd service {pull}25979[#25979]
* Set address space limit in systemd service file {pull}25975[#25975]
* Version option should display if snapshot {pull}25970[#25970]
* Ignore JVM options before checking Java version {pull}25969[#25969]
* Also skip JAVA_TOOL_OPTIONS on Windows {pull}25968[#25968]
* Introduce elasticsearch-env for Windows {pull}25958[#25958]
* Introduce elasticsearch-env {pull}25815[#25815] (issue: {issue}20286[#20286])
* Stop exporting HOSTNAME from scripts {pull}25807[#25807]
* Set number of processes in systemd unit file {pull}24970[#24970] (issue: {issue}20874[#20874])

Parent/Child::
* Remove ParentJoinFieldSubFetchPhase {pull}25550[#25550] (issue: {issue}25363[#25363])
* Support parent id being specified as number in the _source {pull}25547[#25547]

Percolator::
* Store the QueryBuilder's Writable representation instead of its XContent representation {pull}25456[#25456]
* Add support for selecting percolator query candidate matches containing wildcard / prefix queries {pull}25351[#25351]

Plugin Discovery EC2::
* Read ec2 discovery address from aws instance tags {pull}22743[#22743] (issue: {issue}22566[#22566])

Plugin Lang Painless::
* Allow Custom Whitelists in Painless {pull}25557[#25557]
* Update Painless to Allow Augmentation from Any Class {pull}25360[#25360]
* Add Needs Methods to Painless Script Context Factories {pull}25267[#25267]
* Support Script Context Stateful Factory in Painless {pull}25233[#25233]
* Generate Painless Factory for Creating Script Instances {pull}25120[#25120]
* Update Painless to Use New Script Contexts {pull}25015[#25015]
* Optimize instance creation in LambdaBootstrap {pull}24618[#24618]
* Make Painless Compiler Use an Instance Per Context {pull}24972[#24972]
* Make PainlessScript An Interface {pull}24966[#24966]

Plugin Repository GCS::
* GCS Repository: Add secure storage of credentials {pull}24697[#24697]

Plugin Repository HDFS::
* Add permission checks before reading from HDFS stream {pull}26716[#26716] (issue: {issue}26714[#26714])
* Add doPrivilege blocks for socket connect ops in repository-hdfs {pull}22793[#22793] (issue: {issue}22116[#22116])
* Add Kerberos support for Repo HDFS plugin [ISSUE] {pull}21990[#21990]

Plugin Repository S3::
* S3 Repository: Add back repository level credentials {pull}24609[#24609]

Plugins::
* Adjust SHA-512 supported format on plugin install {pull}27093[#27093]
* Move tribe to a module {pull}25778[#25778]
* Plugins can register pre-configured char filters {pull}25000[#25000] (issue: {issue}23658[#23658])
* Add purge option to remove plugin CLI {pull}24981[#24981]
* Allow plugins to register pre-configured tokenizers {pull}24751[#24751] (issues: {issue}24223[#24223], {issue}24572[#24572])
* Move ReindexAction class to core {pull}24684[#24684] (issue: {issue}24578[#24578])
* Make PreConfiguredTokenFilter harder to misuse {pull}24572[#24572] (issue: {issue}23658[#23658])
* Plugins: Remove leniency for missing plugins dir {pull}24173[#24173]
* Add doPrivilege blocks for socket connect operations in plugins {pull}22534[#22534] (issue: {issue}22116[#22116])

Query DSL::
* Make slop optional when parsing `span_near` query {pull}25677[#25677] (issue: {issue}25642[#25642])
* Require a field when a `seed` is provided to the `random_score` function. {pull}25594[#25594] (issue: {issue}25240[#25240])
* Add support for auto_generate_synonyms_phrase_query in match_query, multi_match_query, query_string and simple_query_string {pull}23147[#23147]

REST::
* Cat shards bytes {pull}26952[#26952]
* Refactor PathTrie and RestController to use a single trie for all methods {pull}25459[#25459] (issue: {issue}24437[#24437])
* Make ObjectParser support string to boolean conversion {pull}24668[#24668] (issue: {issue}21802[#21802])

Recovery::
* Introduce a History UUID as a requirement for ops based recovery  {pull}26577[#26577] (issue: {issue}10708[#10708])
* Goodbye, Translog Views {pull}25962[#25962]
* Disallow multiple concurrent recovery attempts for same target shard {pull}25428[#25428]
* Live primary-replica resync (no rollback) {pull}24841[#24841] (issue: {issue}10708[#10708])
* Peer Recovery: remove maxUnsafeAutoIdTimestamp hand off {pull}24243[#24243] (issue: {issue}24149[#24149])
* Introduce sequence-number-based recovery {pull}22484[#22484] (issue: {issue}10708[#10708])

Scripting::
* Scripting: Rename SearchScript.needsScores to needs_score {pull}25235[#25235]
* Scripting: Add optional context parameter to put stored script requests {pull}25014[#25014]
* Add New Security Script Settings {pull}24637[#24637] (issue: {issue}24532[#24532])
* Add StatefulFactoryType as optional intermediate factory in script contexts {pull}24974[#24974] (issue: {issue}20426[#20426])
* Make contexts available to ScriptEngine construction {pull}24896[#24896]
* Make ScriptEngine.compile generic on the script context {pull}24873[#24873]
* Add instance and compiled classes to script contexts {pull}24868[#24868]

Search::
* Add soft limit on allowed number of script fields in request {pull}26598[#26598] (issue: {issue}26390[#26390])
* Add a soft limit for the number of requested doc-value fields {pull}26574[#26574] (issue: {issue}26390[#26390])
* Rewrite search requests on the coordinating nodes {pull}25814[#25814] (issue: {issue}25791[#25791])
* Ensure query resources are fetched asynchronously during rewrite {pull}25791[#25791]
* Introduce a new Rewriteable interface to streamline rewriting {pull}25788[#25788]
* Reduce the scope of `QueryRewriteContext` {pull}25787[#25787]
* Reduce the overhead of timeouts and low-level search cancellation. {pull}25776[#25776]
* Reduce profiling overhead. {pull}25772[#25772] (issue: {issue}24799[#24799])
* Prevent `can_match` requests from sending to incompatible nodes {pull}25705[#25705] (issue: {issue}25704[#25704])
* Add a shard filter search phase to pre-filter shards based on query rewriting {pull}25658[#25658]
* Ensure we rewrite common queries to `match_none` if possible {pull}25650[#25650]
* Limit the number of concurrent shard requests per search request {pull}25632[#25632]
* Add cluster name validation to RemoteClusterConnection {pull}25568[#25568]
* Speed up sorted scroll when the index sort matches the search sort {pull}25138[#25138] (issue: {issue}6720[#6720])
* Leverage scorerSupplier when applicable. {pull}25109[#25109]
* Add Cross Cluster Search support for scroll searches {pull}25094[#25094]
* Track EWMA[1] of task execution time in search threadpool executor {pull}24989[#24989] (issue: {issue}24915[#24915])
* Query range fields by doc values when they are expected to be more efficient than points {pull}24823[#24823] (issue: {issue}24314[#24314])
* Search: Fairer balancing when routing searches by session ID {pull}24671[#24671] (issue: {issue}24642[#24642])
*  Add parsing from xContent to Suggest {pull}22903[#22903]
* Add parsing from xContent to ShardSearchFailure {pull}22699[#22699]
* Eliminate array access in tight loops when profiling is enabled. {pull}24959[#24959]
* Support Multiple Inner Hits on a Field Collapse Request {pull}24517[#24517]
* Expand cross cluster search indices for search requests to the concrete index or to it's aliases {pull}24502[#24502]

Search Templates::
* Add max concurrent searches to multi template search {pull}24255[#24255] (issues: {issue}20912[#20912], {issue}21907[#21907])

Sequence IDs::
* Roll translog generation on primary promotion {pull}27313[#27313]
* Restoring from snapshot should force generation of a new history uuid {pull}26694[#26694] (issues: {issue}10708[#10708], {issue}26544[#26544], {issue}26557[#26557], {issue}26577[#26577])
* Add global checkpoint tracking on the primary {pull}26666[#26666] (issue: {issue}26591[#26591])
* Introduce global checkpoint background sync {pull}26591[#26591] (issues: {issue}26573[#26573], {issue}26630[#26630], {issue}26666[#26666])
* Move `UNASSIGNED_SEQ_NO` and `NO_OPS_PERFORMED` to SequenceNumbers` {pull}26494[#26494] (issue: {issue}10708[#10708])
* Move primary term from ReplicationRequest to ConcreteShardRequest {pull}25822[#25822]
* Add reason to global checkpoint updates on replica {pull}25612[#25612] (issue: {issue}10708[#10708])
* Introduce primary/replica mode for GlobalCheckPointTracker {pull}25468[#25468]
* Throw back replica local checkpoint on new primary {pull}25452[#25452] (issues: {issue}10708[#10708], {issue}25355[#25355])
* Update global checkpoint when increasing primary term on replica {pull}25422[#25422] (issues: {issue}10708[#10708], {issue}25355[#25355])
* Enable a long translog retention policy by default {pull}25294[#25294] (issues: {issue}10708[#10708], {issue}25147[#25147])
* Introduce primary context {pull}25122[#25122] (issues: {issue}10708[#10708], {issue}25355[#25355])
* Block older operations on primary term transition {pull}24779[#24779] (issue: {issue}10708[#10708])
* Block global checkpoint advances when recovering {pull}24404[#24404] (issue: {issue}10708[#10708])
* Add primary term to doc write response {pull}24171[#24171] (issue: {issue}10708[#10708])
* Preserve multiple translog generations {pull}24015[#24015] (issue: {issue}10708[#10708])
* Introduce translog generation rolling {pull}23606[#23606] (issue: {issue}10708[#10708])
* Replicate write failures {pull}23314[#23314]
* Introduce sequence-number-aware translog {pull}22822[#22822] (issue: {issue}10708[#10708])
* Introduce translog no-op {pull}22291[#22291] (issue: {issue}10708[#10708])
* Tighten sequence numbers recovery {pull}22212[#22212] (issue: {issue}10708[#10708])
* Add BWC layer to seq no infra and enable BWC tests {pull}22185[#22185] (issue: {issue}21670[#21670])
* Add internal _primary_term doc values field, fix _seq_no indexing {pull}21637[#21637] (issues: {issue}10708[#10708], {issue}21480[#21480])
* Add global checkpoint to translog checkpoints {pull}21254[#21254]
* Sequence numbers commit data for Lucene uses Iterable interface {pull}20793[#20793] (issue: {issue}10708[#10708])
* Simplify GlobalCheckpointService and properly hook it for cluster state updates {pull}20720[#20720]
* Fill gaps on primary promotion {pull}24945[#24945] (issue: {issue}10708[#10708])
* Introduce clean transition on primary promotion {pull}24925[#24925] (issue: {issue}10708[#10708])
* Guarantee that translog generations are seqNo conflict free {pull}24825[#24825] (issues: {issue}10708[#10708], {issue}24779[#24779])
* Inline global checkpoints {pull}24513[#24513] (issue: {issue}10708[#10708])

Settings::
* Add disk threshold settings validation {pull}25600[#25600] (issue: {issue}25560[#25560])
* Enable cross-setting validation {pull}25560[#25560] (issue: {issue}25541[#25541])
* Validate `transport.profiles.*` settings {pull}25508[#25508]
* Cleanup network / transport related settings {pull}25489[#25489]
* Emit settings deprecation logging at most once {pull}25457[#25457]
* IndexMetaData: Introduce internal format index setting {pull}25292[#25292]
* Persist created keystore on startup unless keystore is present {pull}26253[#26253] (issue: {issue}26126[#26126])
* Settings: Add keystore.seed auto generated secure setting {pull}26149[#26149]
* Settings: Add keystore creation to add commands {pull}26126[#26126]

Snapshot/Restore::
* Fixed references to Multi Index Syntax {pull}27283[#27283]
* Improves snapshot logging and snapshot deletion error handling {pull}25264[#25264]
* Enhances get snapshots API to allow retrieving repository index only {pull}24477[#24477] (issue: {issue}24288[#24288])

Stats::
* Update `IndexShard#refreshMetric` via a `ReferenceManager.RefreshListener` {pull}25083[#25083] (issues: {issue}24806[#24806], {issue}25052[#25052])
* Expose disk usage estimates in nodes stats {pull}22081[#22081] (issue: {issue}8686[#8686])

Store::
* Remote support for lucene versions without checksums {pull}24021[#24021]

Suggesters::
* Remove deprecated _suggest endpoint {pull}22203[#22203] (issue: {issue}20305[#20305])

Task Manager::
* Add descriptions to bulk tasks {pull}22059[#22059] (issue: {issue}21768[#21768])

Translog::
* Translog file recovery should not rely on lucene commits {pull}25005[#25005] (issue: {issue}24950[#24950])



[[bug-6.0.0]]
[float]
=== Bug fixes

Aggregations::
* Do not delegate a null scorer to LeafBucketCollectors {pull}26747[#26747] (issue: {issue}26611[#26611])
* Create weights lazily in filter and filters aggregation {pull}26983[#26983]
* Fix IndexOutOfBoundsException in histograms for NaN doubles (#26787) {pull}26856[#26856] (issue: {issue}26787[#26787])
* Scripted_metric _agg parameter disappears if params are provided {pull}19863[#19863] (issue: {issue}19768[#19768])
* Fixes array out of bounds for value count agg {pull}26038[#26038] (issue: {issue}17379[#17379])
* Aggregations bug: Significant_text fails on arrays of text. {pull}25030[#25030] (issue: {issue}25029[#25029])
* Check bucket metric ages point to a multi bucket agg {pull}26215[#26215] (issue: {issue}25775[#25775])
* Terms aggregation should remap global ordinal buckets when a sub-aggregator is used to sort the terms {pull}24941[#24941] (issue: {issue}24788[#24788])
* Correctly set doc_count when MovAvg "predicts" values on existing buckets {pull}24892[#24892] (issue: {issue}24327[#24327])
* DateHistogram: Fix `extended_bounds` with `offset` {pull}23789[#23789] (issue: {issue}23776[#23776])
* Fix ArrayIndexOutOfBoundsException when no ranges are specified in the query {pull}23241[#23241] (issue: {issue}22881[#22881])

Aliases::
* mget with an alias shouldn't ignore alias routing {pull}25697[#25697] (issue: {issue}25696[#25696])
* GET aliases should 404 if aliases are missing {pull}25043[#25043] (issue: {issue}24644[#24644])

Allocation::
* Fix DiskThresholdMonitor flood warning {pull}26204[#26204] (issue: {issue}26201[#26201])
* Allow wildcards for shard IP filtering {pull}26187[#26187] (issues: {issue}22591[#22591], {issue}26184[#26184])

Analysis::
* Pre-configured shingle filter should disable graph analysis {pull}25853[#25853] (issue: {issue}25555[#25555])
* PatternAnalyzer should lowercase wildcard queries when `lowercase` is true. {pull}24967[#24967]

CAT API::
* Fix NPE for /_cat/indices when no primary shard {pull}26953[#26953] (issue: {issue}26942[#26942])

CRUD::
* Serialize and expose timeout of acknowledged requests in REST layer {pull}26189[#26189] (issue: {issue}26213[#26213])
* Fix silent loss of last command to _bulk and _msearch due to missing newline {pull}25740[#25740] (issue: {issue}7601[#7601])

Cache::
* Reduce the default number of cached queries. {pull}26949[#26949] (issue: {issue}26938[#26938])
* fix bug of weight computation {pull}24856[#24856]

Circuit Breakers::
* Checks the circuit breaker before allocating bytes for a new big array {pull}25010[#25010] (issue: {issue}24790[#24790])

Cluster::
* Register setting `cluster.indices.tombstones.size` {pull}26193[#26193] (issue: {issue}26191[#26191])

Core::
* Correctly encode warning headers {pull}27269[#27269] (issue: {issue}27244[#27244])
* Fix cache compute if absent for expired entries {pull}26516[#26516]
* Timed runnable should delegate to abstract runnable {pull}27095[#27095] (issue: {issue}27069[#27069])
* Stop invoking non-existent syscall {pull}27016[#27016] (issue: {issue}20179[#20179])
* MetaData Builder doesn't properly prevent an alias with the same name as an index {pull}26804[#26804]
* Release operation permit on thread-pool rejection {pull}25930[#25930] (issue: {issue}25863[#25863])
* Node should start up despite of a lingering `.es_temp_file` {pull}21210[#21210] (issue: {issue}21007[#21007])
* Fix cache expire after access {pull}24546[#24546]

Dates::
* Fix typo in date format {pull}26503[#26503] (issue: {issue}26500[#26500])

Discovery::
* MasterNodeChangePredicate should use the node instance to detect master change {pull}25877[#25877] (issue: {issue}25471[#25471])

Engine::
* Die with dignity while merging {pull}27265[#27265] (issue: {issue}19272[#19272])
* Engine - do not index operations with seq# lower than the local checkpoint into lucene {pull}25827[#25827] (issues: {issue}1[#1], {issue}2[#2], {issue}25592[#25592])

Geo::
* Fix typo in GeoUtils#isValidLongitude {pull}25121[#25121]

Highlighting::
* Fix percolator highlight sub fetch phase to not highlight query twice {pull}26622[#26622]
* FastVectorHighlighter should not cache the field query globally {pull}25197[#25197] (issue: {issue}25171[#25171])
* Higlighters: Fix MultiPhrasePrefixQuery rewriting {pull}25103[#25103] (issue: {issue}25088[#25088])
* Fix nested query highlighting {pull}26305[#26305] (issue: {issue}26230[#26230])

Index APIs::
* Shrink API should ignore templates {pull}25380[#25380] (issue: {issue}25035[#25035])
* Rollover max docs should only count primaries {pull}24977[#24977] (issue: {issue}24217[#24217])
* Validates updated settings on closed indices {pull}24487[#24487] (issue: {issue}23787[#23787])

Ingest::
* date processor should not fail if timestamp is specified as json number {pull}26986[#26986] (issue: {issue}26967[#26967])
* date_index_name processor should not fail if timestamp is specified as json number {pull}26910[#26910] (issue: {issue}26890[#26890])
* Sort Processor does not have proper behavior with targetField {pull}25237[#25237] (issue: {issue}24133[#24133])
* fix grok's pattern parsing to validate pattern names in expression {pull}25063[#25063] (issue: {issue}22831[#22831])
* Remove support for Visio and potm files {pull}22079[#22079] (issue: {issue}22077[#22077])
* Fix floating-point error when DateProcessor parses UNIX {pull}24947[#24947]
* add option for _ingest.timestamp to use new ZonedDateTime (5.x backport) {pull}24030[#24030] (issues: {issue}23168[#23168], {issue}23174[#23174])

Inner Hits::
* Do not allow inner hits that fetch _source and have a non nested object field as parent {pull}25749[#25749] (issue: {issue}25315[#25315])
* When fetching nested inner hits only access stored fields when needed {pull}25864[#25864] (issue: {issue}6[#6])
* If size / offset are out of bounds just do a plain count {pull}20556[#20556] (issue: {issue}20501[#20501])
* Fix Source filtering in new field collapsing feature {pull}24068[#24068] (issue: {issue}24063[#24063])

Internal::
* Bump version to 6.0.1 [OPEN] {pull}27386[#27386]
* `IndexShard.routingEntry` should only be updated once all internal state is ready {pull}26776[#26776]
* Catch exceptions and inform handler in RemoteClusterConnection#collectNodes {pull}26725[#26725] (issue: {issue}26700[#26700])
* Internal: Add versionless alias for rest client codebase in policy files {pull}26521[#26521]
* Upgrade Lucene to version 7.0.1 {pull}26926[#26926]
* Fix BytesReferenceStreamInput#skip with offset {pull}25634[#25634]
* Fix race condition in RemoteClusterConnection node supplier {pull}25432[#25432]
* Initialise empty lists in BaseTaskResponse constructor {pull}25290[#25290]
* Extract a common base class for scroll executions {pull}24979[#24979] (issue: {issue}16555[#16555])
* Obey lock order if working with store to get metadata snapshots {pull}24787[#24787] (issue: {issue}24481[#24481])
* Fix Version based BWC and set correct minCompatVersion {pull}24732[#24732]
* Fix `_field_caps` serialization in order to support cross cluster search {pull}24722[#24722]
* Avoid race when shutting down controller processes {pull}24579[#24579]
* Fix handling of document failure exception in InternalEngine {pull}22718[#22718]
* Ensure remote cluster is connected before fetching `_field_caps` {pull}24845[#24845] (issue: {issue}24763[#24763])

Java API::
* BulkProcessor flush runnable preserves the thread context from creation time {pull}26718[#26718] (issue: {issue}26596[#26596])

Java High Level REST Client::
* Make RestHighLevelClient's Request class public {pull}26627[#26627] (issue: {issue}26455[#26455])
* Forbid direct usage of ContentType.create() methods {pull}26457[#26457] (issues: {issue}22769[#22769], {issue}26438[#26438])
* Make ShardSearchTarget optional when parsing ShardSearchFailure {pull}27078[#27078] (issue: {issue}27055[#27055])

Java REST Client::
* Better message text for ResponseException {pull}26564[#26564]
* rest-client-sniffer: configurable threadfactory {pull}26897[#26897]

Logging::
* Allow not configure logging without config {pull}26209[#26209] (issues: {issue}20575[#20575], {issue}24076[#24076])

Mapping::
* Allow copying from a field to another field that belongs to the same nested object. {pull}26774[#26774] (issue: {issue}26763[#26763])
* Fixed bug that mapper_parsing_exception is thrown for numeric field with ignore_malformed=true when inserting "NaN" {pull}25967[#25967] (issue: {issue}25289[#25289])
* Coerce decimal strings for whole number types by truncating the decimal part {pull}25835[#25835] (issue: {issue}25819[#25819])
* Fix parsing of ip range queries. {pull}25768[#25768] (issue: {issue}25636[#25636])
* Disable date field mapping changing {pull}25285[#25285] (issue: {issue}25271[#25271])
* Correctly enable _all for older 5.x indices {pull}25087[#25087] (issue: {issue}25068[#25068])
* token_count datatype should handle null value {pull}25046[#25046] (issue: {issue}24928[#24928])
* keep _parent field while updating child type mapping {pull}24407[#24407] (issue: {issue}23381[#23381])
* ICUCollationKeywordFieldMapper use SortedSetDocValuesField {pull}26267[#26267]
* Fix serialization of the `_all` field. {pull}26143[#26143] (issue: {issue}26136[#26136])

More Like This::
* Pass over _routing value with more_like_this items to be retrieved {pull}24679[#24679] (issue: {issue}23699[#23699])

NOT CLASSIFIED::
* DocumentMissingException during Logstash scripted upsert [ISSUE] {pull}27148[#27148]
* An assertion trips when master opens an index from before 5.x [ISSUE] {pull}24809[#24809]

Nested Docs::
* In case of a single type the _id field should be added to the nested document instead of _uid field {pull}25149[#25149]
* Inner hits source filtering not working [ISSUE] {pull}23090[#23090]

Network::
* Fixed ByteBuf leaking in org.elasticsearch.http.netty4.Netty4HttpRequestHandler {pull}27222[#27222] (issues: {issue}3[#3], {issue}4[#4], {issue}5[#5], {issue}6[#6])
* Check for closed connection while opening {pull}26932[#26932]
* Ensure pending transport handlers are invoked for all channel failures {pull}25150[#25150]
* Notify onConnectionClosed rather than onNodeDisconnect to prune transport handlers {pull}24639[#24639] (issues: {issue}24557[#24557], {issue}24575[#24575], {issue}24632[#24632])
* Release pipelined http responses on close {pull}26226[#26226]
* Fix error message if an incompatible node connects {pull}24884[#24884]

Packaging::
* Fix handling of Windows paths containing parentheses {pull}26916[#26916] (issue: {issue}26454[#26454])
* Exit Windows scripts promptly on failure {pull}25959[#25959]
* Pass config path as a system property {pull}25943[#25943]
* ES_HOME needs to be made absolute before attempt at traversal {pull}25865[#25865]
* Fix elasticsearch-keystore handling of path.conf {pull}25811[#25811]
* Stop disabling explicit GC {pull}25759[#25759]
* Avoid failing install if system-sysctl is masked {pull}25657[#25657] (issue: {issue}24234[#24234])
* Get short path name for native controllers {pull}25344[#25344]
* When stopping via systemd only kill the JVM, not its control group {pull}25195[#25195]
* remove remaining references to scripts directory {pull}24771[#24771]
* Handle parentheses in batch file path {pull}24731[#24731] (issue: {issue}24712[#24712])
* Detect modified keystore on package removal {pull}26300[#26300]
* Create keystore on RPM and Debian package install {pull}26282[#26282]
* Add safer empty variable checking for Windows {pull}26268[#26268] (issue: {issue}26261[#26261])
* Export HOSTNAME environment variable {pull}26262[#26262] (issues: {issue}25807[#25807], {issue}26255[#26255])
* Fix daemonization command status test {pull}26196[#26196] (issue: {issue}26080[#26080])
* Set RuntimeDirectory in systemd service {pull}23526[#23526]

Parent/Child::
* The default _parent field should not try to load global ordinals {pull}25851[#25851] (issue: {issue}25849[#25849])

Percolator::
* Also support query extraction for queries wrapped inside a ESToParentBlockJoinQuery {pull}26754[#26754]
* Fix range queries with date range based on current time in percolator queries. {pull}24666[#24666] (issue: {issue}23921[#23921])

Plugin Analysis Kuromoji::
* Fix kuromoji default stoptags {pull}26600[#26600] (issue: {issue}26519[#26519])

Plugin Analysis Phonetic::
* Fix beidermorse phonetic token filter for unspecified `languageset` {pull}27112[#27112] (issue: {issue}26771[#26771])

Plugin Discovery File::
* Fix discovery-file plugin to use custom config path {pull}26662[#26662] (issue: {issue}26660[#26660])

Plugin Ingest Attachment::
* Add missing mime4j library {pull}22764[#22764] (issue: {issue}22077[#22077])

Plugin Lang Painless::
* Painless: allow doubles to be casted to longs. {pull}25936[#25936]

Plugin Repository Azure::
* Azure snapshots can not be restored anymore {pull}26778[#26778] (issues: {issue}22858[#22858], {issue}26751[#26751], {issue}26777[#26777])
* Snapshot : azure module - accelerate the listing of files (used in delete snapshot) {pull}25710[#25710] (issue: {issue}25424[#25424])
* Use Azure upload method instead of our own implementation {pull}26751[#26751]
* Make calls to CloudBlobContainer#exists privileged {pull}25937[#25937] (issue: {issue}25931[#25931])

Plugin Repository GCS::
* Ensure that gcs client creation is privileged {pull}25938[#25938] (issue: {issue}25932[#25932])

Plugin Repository HDFS::
* Add Log4j to SLF4J binding for repository-hdfs {pull}26514[#26514] (issue: {issue}26512[#26512])
* Upgrading HDFS Repository Plugin to use HDFS 2.8.1 Client {pull}25497[#25497] (issue: {issue}25450[#25450])

Plugin Repository S3::
* Avoid SecurityException in repository-S3 on DefaultS3OutputStream.flush() {pull}25254[#25254] (issue: {issue}25192[#25192])
* Wrap getCredentials() in a doPrivileged() block {pull}23297[#23297] (issues: {issue}22534[#22534], {issue}23271[#23271])

Plugins::
* X-Pack plugin download fails on Windows desktop [ISSUE] {pull}24570[#24570]
* Fix plugin installation permissions {pull}24527[#24527] (issue: {issue}24480[#24480])

Query DSL::
* Fixed incomplete JSON body on count request making org.elasticsearch.rest.action.RestActions#parseTopLevelQueryBuilder go into endless loop {pull}26680[#26680] (issue: {issue}26083[#26083])
* SpanNearQueryBuilder should return the inner clause when a single clause is provided {pull}25856[#25856] (issue: {issue}25630[#25630])
* Refactor field expansion for match, multi_match and query_string query {pull}25726[#25726] (issues: {issue}25551[#25551], {issue}25556[#25556])
* WrapperQueryBuilder should also rewrite the parsed query {pull}25480[#25480]

REST::
* Rest test fixes {pull}27354[#27354]
* Fix inconsistencies in the rest api specs for cat.snapshots {pull}26996[#26996] (issues: {issue}25737[#25737], {issue}26923[#26923])
* Fix inconsistencies in the rest api specs for *_script {pull}26971[#26971] (issue: {issue}26923[#26923])
* exists template needs a template name {pull}25988[#25988]
* Fix handling of invalid error trace parameter {pull}25785[#25785] (issue: {issue}25774[#25774])
* Fix handling of exceptions thrown on HEAD requests {pull}25172[#25172] (issue: {issue}21125[#21125])
* Fixed NPEs caused by requests without content. {pull}23497[#23497] (issue: {issue}24701[#24701])
* Fix get mappings HEAD requests {pull}23192[#23192] (issue: {issue}21125[#21125])

Recovery::
* Close translog view after primary-replica resync {pull}25862[#25862] (issue: {issue}24841[#24841])

Reindex API::
* Fix update_by_query's default size parameter {pull}26784[#26784] (issue: {issue}26761[#26761])
* Reindex: don't duplicate _source parameter {pull}24629[#24629] (issue: {issue}24628[#24628])
* Add qa module that tests reindex-from-remote against pre-5.0 versions of Elasticsearch {pull}24561[#24561] (issues: {issue}23828[#23828], {issue}24520[#24520])

Scroll::
* Fix single shard scroll within a cluster with nodes in version `>= 5.3` and `<= 5.3` {pull}24512[#24512]

Search::
* Fail query when a sort is provided in conjunction with rescorers {pull}26510[#26510]
* Let search phases override max concurrent requests {pull}26484[#26484] (issue: {issue}26198[#26198])
* Avoid stack overflow on search phases {pull}27069[#27069] (issue: {issue}27042[#27042])
* Fix search_after with geo distance sorting {pull}26891[#26891]
* Fix serialization errors when cross cluster search goes to a single shard {pull}26881[#26881] (issue: {issue}26833[#26833])
* Early termination with index sorting should not set terminated_early in the response {pull}26597[#26597] (issue: {issue}26408[#26408])
* Format doc values fields. {pull}22146[#22146]
* Fix term(s) query for range field {pull}25918[#25918]
* Caching a MinDocQuery can lead to wrong results. {pull}25909[#25909]
* Fix random score generation when no seed is provided. {pull}25908[#25908]
* Merge FunctionScoreQuery and FiltersFunctionScoreQuery {pull}25889[#25889] (issues: {issue}15709[#15709], {issue}23628[#23628])
* Respect cluster alias in `_index` aggs and queries {pull}25885[#25885] (issue: {issue}25606[#25606])
* First increment shard stats before notifying and potentially sending response {pull}25818[#25818]
* Remove assertion about deviation when casting to a float. {pull}25806[#25806] (issue: {issue}25330[#25330])
* Prevent skipping shards if a suggest builder is present {pull}25739[#25739] (issue: {issue}25658[#25658])
* Ensure remote cluster alias is preserved in inner hits aggs {pull}25627[#25627] (issue: {issue}25606[#25606])
* Do not search locally if remote index pattern resolves to no indices {pull}25436[#25436] (issue: {issue}25426[#25426])
* Adds check for negative search request size {pull}25397[#25397] (issue: {issue}22530[#22530])
* Make sure range queries are correctly profiled. {pull}25108[#25108]
* Fix RangeFieldMapper rangeQuery to properly handle relations {pull}24808[#24808] (issue: {issue}24744[#24744])
* Fix ExpandSearchPhase when response contains no hits {pull}24688[#24688] (issue: {issue}24672[#24672])
* Refactor simple_query_string to handle text part like multi_match and query_string {pull}26145[#26145] (issue: {issue}25726[#25726])
* Fix `_exists_` in query_string on empty indices. {pull}25993[#25993] (issue: {issue}25956[#25956])
* Fix script field sort returning Double.MAX_VALUE for all documents {pull}24942[#24942] (issue: {issue}24940[#24940])
* Compute the took time of the query after the expand phase of field collapsing {pull}24902[#24902] (issue: {issue}24900[#24900])

Sequence IDs::
* Fire global checkpoint sync under system context {pull}26984[#26984]
* Fix pre-6.0 response to unknown replication actions {pull}25744[#25744] (issue: {issue}10708[#10708])
* Track local checkpoint on primary immediately {pull}25434[#25434] (issues: {issue}10708[#10708], {issue}25355[#25355], {issue}25415[#25415])
* Initialize max unsafe auto ID timestamp on shrink {pull}25356[#25356] (issues: {issue}10708[#10708], {issue}25355[#25355])
* Use correct primary term for replicating NOOPs {pull}25128[#25128]
* Handle already closed while filling gaps {pull}25021[#25021] (issue: {issue}24925[#24925])
* TranslogWriter.assertNoSeqNumberConflict failure [ISSUE] {pull}26710[#26710]
* Avoid losing ops in file-based recovery {pull}22945[#22945] (issue: {issue}22484[#22484])
* Handle primary failure handling replica response {pull}24926[#24926] (issue: {issue}24935[#24935])

Settings::
* Emit settings deprecation logging on empty update {pull}27017[#27017] (issue: {issue}26419[#26419])
* Fix filtering for ListSetting {pull}26914[#26914]
* Fix settings serialization to not serialize secure settings or not take the total size into account {pull}25323[#25323]
* Keystore CLI should use the AddFileKeyStoreCommand for files {pull}25298[#25298]
* Allow resetting settings that use an IP validator {pull}24713[#24713] (issue: {issue}24709[#24709])
* Updating an unrecognized setting should error out with that reason [ISSUE] {pull}25607[#25607]
* Settings: Fix setting groups to include secure settings {pull}25076[#25076] (issue: {issue}25069[#25069])

Similarities::
* Add boolean similarity to built in similarity types {pull}26613[#26613]

Snapshot/Restore::
* Snapshot/Restore: better handle incorrect chunk_size settings in FS repo {pull}26844[#26844] (issue: {issue}26843[#26843])
* Snapshot/Restore: Ensure that shard failure reasons are correctly stored in CS {pull}25941[#25941] (issue: {issue}25878[#25878])
* Output all empty snapshot info fields if in verbose mode {pull}25455[#25455] (issue: {issue}24477[#24477])
* Remove redundant and broken MD5 checksum from repository-s3 {pull}25270[#25270] (issue: {issue}25269[#25269])
* Consolidates the logic for cleaning up snapshots on master election {pull}24894[#24894] (issue: {issue}24605[#24605])
* Removes completed snapshot from cluster state on master change {pull}24605[#24605] (issue: {issue}24452[#24452])
* Keep snapshot restore state and routing table in sync {pull}20836[#20836] (issue: {issue}19774[#19774])
* Master failover during snapshotting could leave the snapshot incomplete [OPEN] [ISSUE] {pull}25281[#25281]
* Fix inefficient (worst case exponential) loading of snapshot repository {pull}24510[#24510] (issue: {issue}24509[#24509])

Stats::
* Fix RestGetAction name typo {pull}27266[#27266]
* Keep cumulative elapsed scroll time in microseconds {pull}27068[#27068] (issue: {issue}27046[#27046])
* _nodes/stats should not fail due to concurrent AlreadyClosedException {pull}25016[#25016] (issue: {issue}23099[#23099])
* Avoid double decrement on current query counter {pull}24922[#24922] (issues: {issue}22996[#22996], {issue}24872[#24872])
* Adjust available and free bytes to be non-negative on huge FSes {pull}24911[#24911] (issues: {issue}23093[#23093], {issue}24453[#24453])

Suggesters::
* Fix division by zero in phrase suggester that causes assertion to fail {pull}27149[#27149]
* Context suggester should filter doc values field {pull}25858[#25858] (issue: {issue}25404[#25404])
* Fix context suggester to read values from keyword type field {pull}24200[#24200] (issue: {issue}24129[#24129])

Templates::
* Tests: Fix FullClusterRestartIT.testSnapshotRestore test failing in 6.x {pull}27218[#27218] (issue: {issue}27213[#27213])

Translog::
* Fix Translog.Delete serialization for sequence numbers {pull}22543[#22543]

Upgrade API::
* Upgrade API: fix excessive logging and unnecessary template updates {pull}26698[#26698] (issue: {issue}26673[#26673])



[[regression-6.0.0]]
[float]
=== Regressions

Bulk::
* Only re-parse operation if a mapping update was needed {pull}23832[#23832] (issue: {issue}23665[#23665])

Highlighting::
* Fix Fast Vector Highlighter NPE on match phrase prefix {pull}25116[#25116] (issue: {issue}25088[#25088])

Search::
* Always use DisjunctionMaxQuery to build cross fields disjunction {pull}25115[#25115] (issue: {issue}23966[#23966])

Sequence IDs::
* Indexing performance degradation in 6.0.0-beta1 [ISSUE] {pull}26339[#26339]



[[upgrade-6.0.0]]
[float]
=== Upgrades

Core::
* Upgrade to Lucene 7.0.0 {pull}26744[#26744]
* Upgrade to lucene-7.0.0-snapshot-d94a5f0. {pull}26441[#26441]
* Upgrade to lucene-7.0.0-snapshot-a128fcb. {pull}26090[#26090]
* Upgrade to a Lucene 7 snapshot {pull}24089[#24089] (issues: {issue}23966[#23966], {issue}24086[#24086], {issue}24087[#24087], {issue}24088[#24088])

Logging::
* Upgrade to Log4j 2.9.1 {pull}26750[#26750] (issues: {issue}109[#109], {issue}26464[#26464], {issue}26467[#26467])
* Upgrade to Log4j 2.9.0 {pull}26450[#26450] (issue: {issue}23798[#23798])

Network::
* Upgrade to Netty 4.1.13.Final {pull}25581[#25581] (issues: {issue}24729[#24729], {issue}6866[#6866])
* Upgrade to Netty 4.1.11.Final {pull}24652[#24652]

Plugin Ingest Attachment::
* Update to Tika 1.14 {pull}21591[#21591] (issue: {issue}20390[#20390])

Upgrade API::
* Improve stability and logging of TemplateUpgradeServiceIT tests {pull}25386[#25386] (issue: {issue}25382[#25382])


