[[release-notes-6.2.0]]
== 6.2.0 Release Notes

Also see <<breaking-changes-6.0>>.

[[breaking-6.2.0]]
[float]
=== Breaking changes

Aggregations::
* Add a new cluster setting to limit the total number of buckets returned by a request {pull}27581[#27581] (issues: {issue}26012[#26012], {issue}27452[#27452])

Core::
* Forbid granting the all permission in production {pull}27548[#27548]

Highlighting::
* Limit the analyzed text for highlighting {pull}27934[#27934] (issue: {issue}27517[#27517])

Rollover::
* Fail rollover if duplicated alias found in templates {pull}28110[#28110] (issue: {issue}26976[#26976])

Search::
* Introduce limit to the number of terms in Terms Query {pull}27968[#27968] (issue: {issue}18829[#18829])



[[breaking-java-6.2.0]]
[float]
=== Breaking Java changes

Java API::
* Remove `operationThreaded` from Java API {pull}27836[#27836]

Java High Level REST Client::
* REST high-level client: remove index suffix from indices client method names {pull}28263[#28263]



[[deprecation-6.2.0]]
[float]
=== Deprecations

Analysis::
* Backport delimited payload filter renaming {pull}27535[#27535] (issue: {issue}26625[#26625])

Suggesters::
* deprecating `jarowinkler` in favor of `jaro_winkler` {pull}27526[#27526]
* Deprecating `levenstein` in favor of `levensHtein` {pull}27409[#27409] (issue: {issue}27325[#27325])



[[feature-6.2.0]]
[float]
=== New features

Plugin Ingest GeoIp::
* Enable ASN support for Ingest GeoIP plugin.  {pull}27958[#27958] (issue: {issue}27849[#27849])

Plugin Lang Painless::
* Painless: Add spi jar that will be published for extending whitelists {pull}28302[#28302]
* Painless: Add a simple cache for whitelist methods and fields. {pull}28142[#28142]

Plugins::
* Add the ability to bundle multiple plugins into a meta plugin {pull}28022[#28022] (issue: {issue}27316[#27316])

Rank Evaluation::
* Backport of ranking evaluation API (#27478) {pull}27844[#27844] (issue: {issue}27478[#27478])

Recovery::
* Backport for using lastSyncedGlobalCheckpoint in deletion policy {pull}27866[#27866] (issue: {issue}27826[#27826])

Reindex API::
* Add scroll parameter to _reindex API {pull}28041[#28041] (issue: {issue}27555[#27555])



[[enhancement-6.2.0]]
[float]
=== Enhancements

Allocation::
* Fix cluster.routing.allocation.enable and cluster.routing.rebalance.enable case {pull}28037[#28037] (issue: {issue}28007[#28007])
* Add node id to shard failure message {pull}28024[#28024] (issue: {issue}28018[#28018])

Analysis::
* Limit the analyzed text for highlighting (#27934) {pull}28176[#28176] (issue: {issue}27517[#27517])
* Allow TrimFilter to be used in custom normalizers {pull}27758[#27758] (issue: {issue}27310[#27310])

Circuit Breakers::
* Add accounting circuit breaker and track segment memory usage {pull}27116[#27116] (issue: {issue}27044[#27044])

Cluster::
* Adds wait_for_no_initializing_shards to cluster health API {pull}27489[#27489] (issue: {issue}25623[#25623])

Core::
* Introduce elasticsearch-core jar {pull}28191[#28191] (issue: {issue}27933[#27933])
* Rename core module to server {pull}28190[#28190] (issue: {issue}27933[#27933])
*  Rename core module to server {pull}28180[#28180] (issue: {issue}27933[#27933])
* Introduce elasticsearch-core jar {pull}28178[#28178] (issue: {issue}27933[#27933])
* Add Writeable.Reader support to TransportResponseHandler {pull}28010[#28010] (issue: {issue}26315[#26315])
* Simplify rejected execution exception {pull}27664[#27664] (issue: {issue}27663[#27663])
* Add node name to thread pool executor name {pull}27663[#27663] (issues: {issue}26007[#26007], {issue}26835[#26835])

Discovery::
* Add information when master node left to DiscoveryNodes' shortSummary() {pull}28197[#28197] (issue: {issue}28169[#28169])

Engine::
* Move uid lock into LiveVersionMap {pull}27905[#27905]
* Optimize version map for append-only indexing {pull}27752[#27752]

Geo::
* [GEO] Add WKT Support to GeoBoundingBoxQueryBuilder {pull}27692[#27692] (issues: {issue}27690[#27690], {issue}9120[#9120])
* [Geo] Add Well Known Text (WKT) Parsing Support to ShapeBuilders {pull}27417[#27417] (issue: {issue}9120[#9120])

Highlighting::
* Include all sentences smaller than fragment_size in the unified highlighter {pull}28132[#28132] (issue: {issue}28089[#28089])

Ingest::
* Enable convert processor to support Long and Double {pull}27891[#27891] (issues: {issue}23085[#23085], {issue}23423[#23423])

Internal::
* Make KeyedLock reentrant {pull}27920[#27920]
* Make AbstractQueryBuilder.declareStandardFields to be protected (#27865) {pull}27894[#27894] (issue: {issue}27865[#27865])
* Tighten the CountedBitSet class {pull}27632[#27632]
* Avoid doing redundant work when checking for self references. {pull}26927[#26927] (issue: {issue}26907[#26907])

Java API::
* Add missing delegate methods to NodeIndicesStats {pull}28092[#28092]
* Java api clean-up : consistency for `shards_acknowledged` getters  {pull}27819[#27819] (issue: {issue}27784[#27784])

Java High Level REST Client::
* add toString implementation for UpdateRequest. {pull}27997[#27997] (issue: {issue}27986[#27986])
* Add Close Index API to the high level REST client {pull}27734[#27734] (issue: {issue}27205[#27205])
* Add Open Index API to the high level REST client {pull}27574[#27574] (issue: {issue}27205[#27205])
* Added Create Index support to high-level REST client {pull}27351[#27351] (issue: {issue}27205[#27205])
* Add multi get api to the high level rest client {pull}27337[#27337] (issue: {issue}27205[#27205])
* Add msearch api to high level client {pull}27274[#27274]

Mapping::
* Allow `_doc` as a type. {pull}27816[#27816] (issues: {issue}27750[#27750], {issue}27751[#27751])

Network::
* Add NioGroup for use in different transports {pull}27737[#27737] (issue: {issue}27260[#27260])
* Add read timeouts to http module {pull}27713[#27713]
* Implement byte array reusage in `NioTransport` {pull}27696[#27696] (issue: {issue}27563[#27563])
* Introduce resizable inbound byte buffer {pull}27551[#27551] (issue: {issue}27563[#27563])
* Decouple nio constructs from the tcp transport {pull}27484[#27484] (issue: {issue}27260[#27260])

Packaging::
* Extend JVM options to support multiple versions {pull}27675[#27675] (issue: {issue}27646[#27646])
* Add explicit coreutils dependency {pull}27660[#27660] (issue: {issue}27609[#27609])
* Detect mktemp from coreutils {pull}27659[#27659] (issues: {issue}27609[#27609], {issue}27643[#27643])
* Enable GC logs by default {pull}27610[#27610]
* Use private directory for temporary files {pull}27609[#27609] (issues: {issue}14372[#14372], {issue}27144[#27144])

Percolator::
* also extract match_all queries when indexing percolator queries {pull}27585[#27585]

Plugin Lang Painless::
* Painless: Add whitelist extensions {pull}28161[#28161]
* Painless: Modify Loader to Load Classes Directly from Definition {pull}28088[#28088]
* Clean Up Painless Cast Object {pull}27794[#27794]
* Painless: Only allow Painless type names to be the same as the equivalent Java class. {pull}27264[#27264]

Plugins::
* Add client actions to action plugin {pull}28280[#28280] (issue: {issue}27759[#27759])
* Plugins: Add validation to plugin descriptor parsing {pull}27951[#27951]
* Plugins: Add plugin extension capabilities {pull}27881[#27881]
* Add support for filtering mappings fields {pull}27603[#27603]

Rank Evaluation::
* Simplify RankEvalResponse output {pull}28266[#28266]

Recovery::
* Truncate tlog cli should assign global checkpoint {pull}28192[#28192] (issue: {issue}28181[#28181])
* Replica starts peer recovery with safe commit {pull}28181[#28181] (issue: {issue}10708[#10708])
* Primary send safe commit in file-based recovery {pull}28038[#28038] (issue: {issue}10708[#10708])
* Fail resync-failed shards in subsequent writes {pull}28005[#28005]
* Introduce promoting index shard state {pull}28004[#28004] (issue: {issue}24841[#24841])
* Non-peer recovery should set the global checkpoint {pull}27965[#27965]
* Persist global checkpoint when finalizing a peer recovery {pull}27947[#27947] (issue: {issue}27861[#27861])
* Rollback a primary before recovering from translog {pull}27804[#27804] (issue: {issue}10708[#10708])

Search::
* Use typeName() to check field type in GeoShapeQueryBuilder {pull}27730[#27730]
* Optimize search_after when sorting in index sort order {pull}26401[#26401]

Sequence IDs::
* Do not keep 5.x commits when having 6.x commits {pull}28188[#28188] (issues: {issue}27606[#27606], {issue}28038[#28038])
* Use lastSyncedGlobalCheckpoint in deletion policy {pull}27826[#27826] (issue: {issue}27606[#27606])
* Use CountedBitSet in LocalCheckpointTracker {pull}27793[#27793]
* Only fsync global checkpoint if needed {pull}27652[#27652]
* Keep commits and translog up to the global checkpoint {pull}27606[#27606]
* Adjust CombinedDeletionPolicy for multiple commits {pull}27456[#27456] (issues: {issue}10708[#10708], {issue}27367[#27367])
* Keeps index commits up to the current global checkpoint {pull}27367[#27367] (issue: {issue}10708[#10708])
* Dedup translog operations by reading in reverse {pull}27268[#27268] (issue: {issue}10708[#10708])

Settings::
* Add validation of keystore setting names {pull}27626[#27626]

Snapshot/Restore::
* Use AmazonS3.doesObjectExist() method in S3BlobContainer {pull}27723[#27723]
* Remove XContentType auto detection in BlobStoreRepository {pull}27480[#27480]
* Include include_global_state in Snapshot status API (#22423) {pull}26853[#26853] (issue: {issue}22423[#22423])

Task Manager::
* Add ability to associate an ID with tasks  {pull}27764[#27764] (issue: {issue}23250[#23250])

Translog::
* Simplify MultiSnapshot#SeqNoset {pull}27547[#27547] (issue: {issue}27268[#27268])
* Enclose CombinedDeletionPolicy in SnapshotDeletionPolicy {pull}27528[#27528] (issues: {issue}27367[#27367], {issue}27456[#27456])



[[bug-6.2.0]]
[float]
=== Bug fixes

Aggregations::
* Adds metadata to rewritten aggregations {pull}28185[#28185] (issue: {issue}28170[#28170])
* Fix NPE on composite aggregation with sub-aggregations that need scores {pull}28129[#28129]
* StringTerms.Bucket.getKeyAsNumber detection type {pull}28118[#28118] (issue: {issue}28012[#28012])
* Fix incorrect results for aggregations nested under a nested aggregation {pull}27946[#27946] (issue: {issue}27912[#27912])
* Fix global aggregation that requires breadth first and scores {pull}27942[#27942] (issues: {issue}22321[#22321], {issue}27928[#27928])
* Fix composite aggregation when after term is missing in the shard {pull}27936[#27936]
* Fix preserving FiltersAggregationBuilder#keyed field on rewrite {pull}27900[#27900] (issue: {issue}27841[#27841])
* Using DocValueFormat::parseBytesRef for parsing missing value parameter {pull}27855[#27855] (issue: {issue}27788[#27788])
* Fix illegal cast of the "low cardinality" optimization of the `terms` aggregation. {pull}27543[#27543]
* Always include the _index and _id for nested search hits. {pull}27201[#27201] (issue: {issue}27053[#27053])

Allocation::
* Do not open indices with broken settings {pull}26995[#26995]

Core::
* Fix lock accounting in releasable lock {pull}28202[#28202]
* Fixes ByteSizeValue to serialise correctly {pull}27702[#27702] (issue: {issue}27568[#27568])
* Do not set data paths on no local storage required {pull}27587[#27587] (issue: {issue}27572[#27572])
* Ensure threadcontext is preserved when refresh listeners are invoked {pull}27565[#27565]
* Ensure logging is configured for CLI commands {pull}27523[#27523] (issue: {issue}27521[#27521])

Engine::
* Replica recovery could go into an endless flushing loop {pull}28350[#28350]
* Use `_refresh` to shrink the version map on inactivity {pull}27918[#27918] (issue: {issue}27852[#27852])
* Allow resize version map under lock even if there are pending operations {pull}27870[#27870] (issue: {issue}27852[#27852])
* Reset LiveVersionMap on sync commit {pull}27534[#27534] (issue: {issue}27516[#27516])

Geo::
* Correct two equality checks on incomparable types {pull}27688[#27688]
* Handle case where the hole vertex is south of the containing polygon(s) {pull}27685[#27685] (issue: {issue}25933[#25933])

Highlighting::
* Fix highlighting on a keyword field that defines a normalizer {pull}27604[#27604]

Inner Hits::
* Add version support for inner hits in field collapsing (#27822) {pull}27833[#27833] (issue: {issue}27822[#27822])

Internal::
* Never return null from Strings.tokenizeToStringArray {pull}28224[#28224] (issue: {issue}28213[#28213])
* Fallback to TransportMasterNodeAction for cluster health retries {pull}28195[#28195] (issue: {issue}28169[#28169])
* Retain originalIndex info when rewriting FieldCapabilities requests {pull}27761[#27761]

Java REST Client::
* Do not use system properties when building the HttpAsyncClient {pull}27829[#27829] (issue: {issue}27827[#27827])

Mapping::
* Ignore null value for range field (#27845) {pull}28116[#28116] (issue: {issue}27845[#27845])
* Pass `java.locale.providers=COMPAT` to Java 9 onwards {pull}28080[#28080] (issue: {issue}10984[#10984])
* Allow update of `eager_global_ordinals` on `_parent`. {pull}28014[#28014] (issue: {issue}24407[#24407])
* Fix merging of _meta field {pull}27352[#27352] (issue: {issue}27323[#27323])

Network::
* Only bind loopback addresses when binding to local {pull}28029[#28029] (issue: {issue}1877[#1877])
* Remove potential nio selector leak {pull}27825[#27825]
* Fix issue where the incorrect buffers are written {pull}27695[#27695] (issue: {issue}27551[#27551])
* Throw UOE from compressible bytes stream reset {pull}27564[#27564] (issue: {issue}24927[#24927])
* Bubble exceptions when closing compressible streams {pull}27542[#27542] (issue: {issue}27540[#27540])

Packaging::
* Allow custom service names when installing on windows {pull}25255[#25255] (issue: {issue}25231[#25231])

Percolator::
* Avoid TooManyClauses exception if number of terms / ranges is exactly equal to 1024 {pull}27519[#27519] (issue: {issue}1[#1])

Plugin Analysis ICU::
* Catch InvalidPathException in IcuCollationTokenFilterFactory {pull}27202[#27202]

Plugin Analysis Phonetic::
* Fix daitch_mokotoff phonetic filter to use the dedicated Lucene filter {pull}28225[#28225] (issue: {issue}28211[#28211])

Plugin Lang Painless::
* Painless: Fix variable scoping issue in lambdas {pull}27571[#27571] (issue: {issue}26760[#26760])
* Painless: Fix errors allowing void to be assigned to def. {pull}27460[#27460] (issue: {issue}27210[#27210])

Plugin Repository HDFS::
* Fix SecurityException when HDFS Repository used against HA Namenodes {pull}27196[#27196]

Plugins::
* Make sure that we don't detect files as maven coordinate when installing a plugin {pull}28163[#28163]
* Fix upgrading indices which use a custom similarity plugin. {pull}26985[#26985] (issue: {issue}25350[#25350])

Recovery::
* Open engine should keep only starting commit {pull}28228[#28228] (issues: {issue}27804[#27804], {issue}28181[#28181])
* Allow shrinking of indices from a previous major {pull}28076[#28076] (issue: {issue}28061[#28061])
* Set global checkpoint before open engine from store {pull}27972[#27972] (issues: {issue}27965[#27965], {issue}27970[#27970])
* Check and repair index under the store metadata lock {pull}27768[#27768] (issues: {issue}24481[#24481], {issue}24787[#24787], {issue}27731[#27731])
* Flush old indices on primary promotion and relocation {pull}27580[#27580] (issue: {issue}27536[#27536])

Rollover::
* Make index rollover action atomic {pull}28039[#28039] (issue: {issue}26976[#26976])

Scripting::
* Ensure we protect Collections obtained from scripts from self-referencing {pull}28335[#28335]

Scroll::
* Reject scroll query if size is 0 (#22552) {pull}27842[#27842] (issue: {issue}22552[#22552])
* Fix scroll query with a sort that is a prefix of the index sort {pull}27498[#27498]

Search::
* Fix simple_query_string on invalid input {pull}28219[#28219] (issue: {issue}28204[#28204])
* Use the underlying connection version for CCS connections  {pull}28093[#28093]
* Fix synonym phrase query expansion for cross_fields parsing {pull}28045[#28045]
* Carry forward weights, etc on rescore rewrite {pull}27981[#27981] (issue: {issue}27979[#27979])
* Fix routing with leading or trailing whitespace {pull}27712[#27712] (issue: {issue}27708[#27708])

Sequence IDs::
* Recovery from snapshot may leave seq# gaps {pull}27850[#27850]
* No longer unidle shard during recovery {pull}27757[#27757] (issue: {issue}26591[#26591])
* Obey translog durability in global checkpoint sync {pull}27641[#27641]

Settings::
* Settings: Introduce settings updater for a list of settings {pull}28338[#28338] (issue: {issue}28047[#28047])
*  Fix setting notification for complex setting (affixMap settings) that could cause transient settings to be ignored {pull}28317[#28317] (issue: {issue}28316[#28316])
* Fix environment variable substitutions in list setting {pull}28106[#28106] (issue: {issue}27926[#27926])
* Allow index settings to be reset by wildcards {pull}27671[#27671] (issue: {issue}27537[#27537])

Snapshot/Restore::
* Consistent updates of IndexShardSnapshotStatus {pull}28130[#28130] (issue: {issue}26480[#26480])
* Avoid concurrent snapshot finalizations when deleting an INIT snapshot {pull}28078[#28078] (issues: {issue}27214[#27214], {issue}27931[#27931], {issue}27974[#27974])
* Do not start snapshots that are deleted during initialization {pull}27931[#27931]
* Do not swallow exception in ChecksumBlobStoreFormat.writeAtomic() {pull}27597[#27597]
* Consistent update of stage and failure message in IndexShardSnapshotStatus {pull}27557[#27557] (issue: {issue}26480[#26480])
* Fail restore when the shard allocations max retries count is reached {pull}27493[#27493] (issue: {issue}26865[#26865])
* Delete shard store files before restoring a snapshot {pull}27476[#27476] (issues: {issue}20220[#20220], {issue}26865[#26865])

Stats::
* Fixes DocStats to properly deal with shards that report -1 index size {pull}27863[#27863]
* Include internal refreshes in refresh stats {pull}27615[#27615]

Term Vectors::
* Fix term vectors generator with keyword and normalizer {pull}27608[#27608] (issue: {issue}27320[#27320])



[[upgrade-6.2.0]]
[float]
=== Upgrades

Core::
* Dependencies: Update joda time to 2.9.9 {pull}28261[#28261]
* upgrade to lucene 7.2.1 {pull}28218[#28218] (issue: {issue}28044[#28044])
* Upgrade jna from 4.4.0-1 to 4.5.1 {pull}28183[#28183] (issue: {issue}28172[#28172])

Ingest::
* update ingest-attachment to use Tika 1.17 and newer deps {pull}27824[#27824]
