[[release-notes-6.2.4]]
== 6.2.4 Release Notes

Also see <<breaking-changes-6.2>>.

[[bug-6.2.4]]
[float]
=== Bug fixes

Engine::
* Harden periodically check to avoid endless flush loop {pull}29125[#29125] (issues: {issue}28350[#28350], {issue}29097[#29097])

Ingest::
* Don't allow referencing the pattern bank name in the pattern bank {pull}29295[#29295] (issue: {issue}29257[#29257])

Java High Level REST Client::
* Bulk processor#awaitClose to close scheduler {pull}29263[#29263]

Java Low Level REST Client::
* REST client: hosts marked dead for the first time should not be immediately retried {pull}29230[#29230]

Network::
* Cross-cluster search and default connections can get crossed [OPEN] [ISSUE] {pull}29321[#29321]

Percolator::
* Fixed bug when non percolator docs end up in the search hits {pull}29447[#29447] (issue: {issue}29429[#29429])
* Fixed a msm accounting error that can occur during analyzing a percolator query {pull}29415[#29415] (issue: {issue}29393[#29393])
* Fix more query extraction bugs. {pull}29388[#29388] (issues: {issue}28353[#28353], {issue}29376[#29376])
* Fix some query extraction bugs. {pull}29283[#29283]

Plugins::
* Plugins: Fix native controller confirmation for non-meta plugin {pull}29434[#29434]

Search::
* Propagate ignore_unmapped to inner_hits {pull}29261[#29261] (issue: {issue}29071[#29071])

Settings::
* Archive unknown or invalid settings on updates {pull}28888[#28888] (issue: {issue}28609[#28609])



