[[release-notes-6.8.18]]
== {es} version 6.8.18

No significant changes.

[[release-notes-6.8.17]]
== {es} version 6.8.17

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[discrete]
[[security-updates-6.8.17]]
=== Security updates

* An uncontrolled recursion vulnerability that could lead to a 
denial of service attack was identified in the {es} Grok parser. 
A user with the ability to submit arbitrary queries to {es} could create 
a malicious Grok query that will crash the {es} node.
All versions of {es} prior to 6.8.17 are affected by this flaw. 
You must upgrade to {es} version 6.8.17 to obtain the fix.  
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22144[CVE-2021-22144]


[[bug-6.8.17]]
[float]
=== Bug fixes

Features/Ingest::
* Improve circular reference detection in grok processor {es-pull}74581[#74581]

[[release-notes-6.8.16]]
== {es} version 6.8.16

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.16]]
[discrete]
=== Enhancements

Infra/Core::
* Update joda dependency to latest 2.10.10 {es-pull}72052[#72052] (issue: {es-issue}72028[#72028])

[[bug-6.8.16]]
[discrete]
=== Bug fixes

CCR::
* Handle failure to get remote client in unfollow {es-pull}71928[#71928] (issue: {es-issue}71885[#71885])

Features/Stats::
* Avoid return of negative value in `CounterMetric` {es-pull}71446[#71446] (issues: {es-issue}52411[#52411], {es-issue}70968[#70968])

Network::
* Validate IP filter settings {es-pull}72195[#72195] (issue: {es-issue}72192[#72192])

Search::
* Fix scroll contexts counter in `SearchService` {es-pull}71354[#71354] (issues: {es-issue}53449[#53449], {es-issue}56202[#56202])


[[release-notes-6.8.15]]
== {es} version 6.8.15

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[discrete]
[[security-updates-6-8-15]]
=== Security updates

* A document disclosure flaw was found in the {es} suggester and
profile API when Document and Field Level Security are enabled.
The suggester and profile API are normally disabled for an index when document
level security is enabled on the index. Certain queries are able to enable the
profiler and suggester which could lead to disclosing the existence of documents
and fields the attacker should not be able to view.
All versions of {es} before 6.8.15 and 7.11.2 are affected by this flaw.
You must upgrade to 6.8.15 or 7.11.2 to obtain the fix.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22137[CVE-2021-22137]

[[enhancement-6.8.15]]
[discrete]
=== Enhancements

Authorization::
* Improve shard-level request cache efficiency {es-pull}69505[#69505]

[[upgrade-6.8.15]]
[discrete]
=== Upgrades

Packaging::
* Upgrade to Java Native Access (JNA) 5.7.0-1 {es-pull}69653[#69653]

[[release-notes-6.8.14]]
== {es} version 6.8.14

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[discrete]
[[security-updates-6.8.14]]
=== Security updates

* {es} versions before 7.10.0 and 6.8.14 have an information
disclosure issue when audit logging and the `emit_request_body` option are
enabled. The {es} audit log could contain sensitive information,
such as password hashes or authentication tokens. This could allow an
{es} administrator to view these details.
You must upgrade to {es} version 6.8.14 to obtain the fix.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7021[CVE-2020-7021]


[[bug-6.8.14]]
[float]
=== Bug fixes

CCR::
* Stop renew retention leases when follow task fails {es-pull}65168[#65168]

Engine::
* Fix the version and term field initialization error of `NoOpResult` {es-pull}66269[#66269] (issue: {es-issue}66267[#66267])

Features/Monitoring::
* Do not report negative values for swap sizes {es-pull}57317[#57317] (issue: {es-issue}57312[#57312])

Infra/Core::
* Fix missing `QuotaPath.unwrap()` instances {es-pull}67165[#67165] (issue: {es-issue}67164[#67164])

Machine learning::
* Fixes missing state in persist and restore for anomaly detection. This caused
suboptimal modeling after a job was closed and reopened or failed over to a
different node {ml-pull}1668[#1668]

Network::
* Ensure notify when proxy connections disconnect {es-pull}65697[#65697] (issue: {es-issue}65443[#65443])

Search::
* Do not wrap `can_match` searchers {es-pull}64742[#64742]

[[upgrade-6.8.14]]
[float]
=== Upgrades

Packaging::
* Upgrade bundled jdk to 15.0.1 and switch back to `AdoptOpenJDK` {es-pull}64253[#64253] (issue: {es-issue}64026[#64026])

[[release-notes-6.8.13]]
== {es} version 6.8.13

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.13]]
[float]
=== Enhancements

Features/Java Low Level REST Client::
* Add simple support for gzip compression {es-pull}63230[#63230] (issue: {es-issue}62044[#62044])



[[bug-6.8.13]]
[float]
=== Bug fixes

Audit::
* Move RestRequestFilter to core {es-pull}63507[#63507]

Authorization::
* Ensure authz operation overrides transient authz headers {es-pull}61621[#61621]
* Relax the index access control check for scroll searches {es-pull}61446[#61446]

CCR::
* CCR should retry on CircuitBreakingException {es-pull}62013[#62013] (issue: {es-issue}55633[#55633])
* Retry CCR shard follow task when no seed node left {es-pull}63225[#63225]
* Set timeout of auto put-follow request to unbounded {es-pull}61679[#61679] (issue: {es-issue}56891[#56891])


Features/Java High Level REST Client::
* Add hlrc_rest_total_hits_as_int parameter in scroll request {es-pull}61685[#61685] (issue: {es-issue}61677[#61677])



[[upgrade-6.8.13]]
[float]
=== Upgrades

Infra/Packaging::
* Upgrade the bundled JDK to JDK 15 {es-pull}62580[#62580]



[[release-notes-6.8.12]]
== {es} version 6.8.12

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[security-updates-6.8.12]]
[float]
=== Security updates

* A field disclosure flaw was found in {es} when running a scrolling search with
field level security. If a user runs the same query another more privileged user
recently ran, the scrolling search can leak fields that should be hidden. This
could result in an attacker gaining additional permissions against a restricted
index. All versions of {es} before 7.9.0 and 6.8.12 are affected by this flaw.
You must upgrade to {es} version 7.9.0 or 6.8.12 to obtain the fix.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7019[CVE-2020-7019]

[[bug-6.8.12]]
[float]
=== Bug fixes

CCR::
* CCR recoveries using wrong setting for chunk sizes {es-pull}59597[#59597]
* Fix synchronization in ShardFollowNodeTask {es-pull}60490[#60490]
* Relax ShardFollowTasksExecutor validation {es-pull}60054[#60054] (issue: {es-issue}59625[#59625])
* Set timeout of master node requests on follower to unbounded {es-pull}60070[#60070] (issue: {es-issue}56891[#56891])

Distributed::
* Fix cluster health rest api wait_for_no_initializing_shards bug {es-pull}58379[#58379]

Machine Learning::
* Fix restoration of change detectors after seasonality change {ml-pull}1391[#1391]

[[release-notes-6.8.11]]
== {es} version 6.8.11

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[bug-6.8.11]]
[float]
=== Bug fixes

CCR::
* Ensure CCR partial reads never overuse buffer {es-pull}58620[#58620]

Infra/Core::
* Index name expression resolver bwc layer for date parsing {es-pull}58503[#58503] (issues: {es-issue}58481[#58481], {es-issue}58602[#58602])
* Week based parsing for ingest date processor {es-pull}58597[#58597] (issue: {es-issue}58479[#58479])

Machine Learning::
* Better interrupt handling during named pipe connection {ml-pull}1311[#1311]
* Trap potential cause of SIGFPE {ml-pull}1351[#1351] (issue: {ml-issue}1348[#1348])

Mapping::
* Fix types deprecation warning for put mapping. {es-pull}58764[#58764] (issues: {es-issue}38825[#38825], {es-issue}58675[#58675])

SQL::
* Introduce JDBC option for meta pattern escaping {es-pull}40661[#40661] (issue: {es-issue}40640[#40640])

Search::
* Prevent BigInteger serialization errors in term queries {es-pull}57987[#57987] (issue: {es-issue}57917[#57917])

Task Management::
* Remove ban tasks with the current thread context {es-pull}55404[#55404]



[[upgrade-6.8.11]]
[float]
=== Upgrades

Infra/Core::
* Upgrade to JNA 5.5.0 {es-pull}58183[#58183]


[[release-notes-6.8.10]]
== {es} version 6.8.10

[float]
=== Bug fixes

Infra/Logging::
* SlowLoggers using single logger {es-pull}56708[#56708] (issue: {es-issue}56171[#56171])

Machine Learning::
* Fix delete_expired_data/nightly maintenance when many model snapshots need deleting {es-pull}57041[#57041] (issue: {es-issue}47103[#47103])

Search::
* Ensure search contexts are removed on index delete {es-pull}56335[#56335]
* Fix validate query listener invocation bug {es-pull}56157[#56157]

[[upgrade-6.8.10]]
[float]
=== Upgrades

Infra/Packaging::
* Upgrade bundled jdk to 14.0.1 {es-pull}57233[#57233]

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[release-notes-6.8.9]]
== {es} version 6.8.9

[float]
=== Known issues
* Slow loggers can cause Log4j loggers to leak over time. When a new index is created, a new Log4j logger is associated with it. However, when an index is deleted, Log4j keeps an internal reference to its loggers that results in a memory leak {es-pull}57228[#57228] (issue: {es-issue}56171[#56171])
+
This issue is fixed in Elasticsearch 6.8.10 and 7.7.1.

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

* Java based - formats with '8' prefix - week based parsing and calculations are using JDK default calendar data provider which is Sunday,1.
Sunday is considered first day of a week and it requires only 1 day in a week to for the first week of the year.
It can be worked around by using locale which is based on ISO8601 rule (Monday,4) - for instance en-GB
This issue is fixed in Elasticsearch 7.7 https://github.com/elastic/elasticsearch/pull/48209

[[enhancement-6.8.9]]
[float]
=== Enhancements

Authorization::
* Remove synthetic role names of API keys as they confuse users {es-pull}56005[#56005]

Infra/Core::
* Enable helpful null pointer exceptions {es-pull}54853[#54853]

Snapshot/Restore::
* Update the HDFS version used by HDFS Repo {es-pull}53693[#53693]

[[bug-6.8.9]]
[float]
=== Bug fixes

CCR::
* Retry follow task when remote connection queue full {es-pull}55314[#55314]
* Clear recent errors when auto-follow successfully {es-pull}54997[#54997]
* Handle no such remote cluster exception in ccr {es-pull}53415[#53415] (issue: {es-issue}53225[#53225])

CRUD::
* Reduce deprecation warnings from bulk OCC {es-pull}53911[#53911]

Engine::
* Ensure no circular reference in translog tragic exception {es-pull}55959[#55959] (issue: {es-issue}55893[#55893])

Features/CAT APIs::
* Cat tasks output should respect time display settings {es-pull}54536[#54536]

Infra/Core::
* Avoid StackOverflowError if write circular reference exception {es-pull}54147[#54147] (issue: {es-issue}53589[#53589])
* Disallow negative TimeValues {es-pull}53913[#53913] (issue: {es-issue}54041[#54041])

Network::
* Fix use of password protected PKCS#8 keys for SSL {es-pull}55457[#55457] (issue: {es-issue}8[#8])
* Add support for more named curves {es-pull}55179[#55179] (issue: {es-issue}55031[#55031])

Reindex::
* Reindex negative TimeValue fix {es-pull}54057[#54057] (issue: {es-issue}53913[#53913])

[[upgrade-6.8.9]]
[float]
=== Upgrades

Engine::
* Upgrade to Lucene 7.7.3 {es-pull}55897[#55897]


[[release-notes-6.8.8]]
== {es} version 6.8.8


[float]
=== Known issues
* Slow loggers can cause Log4j loggers to leak over time. When a new index is created, a new Log4j logger is associated with it. However, when an index is deleted, Log4j keeps an internal reference to its loggers that results in a memory leak {es-pull}57228[#57228] (issue: {es-issue}56171[#56171])
+
This issue is fixed in Elasticsearch 6.8.10 and 7.7.1.

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[bug-6.8.8]]
[float]
=== Bug fixes

Authorization::
* Explicitly require that delegate API keys have no privileges {es-pull}53647[#53647]

Distributed::
* Avoid loading retention leases while writing them {es-pull}42620[#42620] (issue: {es-issue}41430[#41430])

Infra/Core::
* Avoid self-suppression on grouped action listener {es-pull}53262[#53262] (issue: {es-issue}53174[#53174])

Network::
* Invoke response handler on failure to send {es-pull}53631[#53631]

SQL::
* Fix column size for IP data type {es-pull}53056[#53056] (issue: {es-issue}52762[#52762])

Search::
* Fix concurrent requests race over scroll context limit {es-pull}53449[#53449]
* Fix potential NPE in FuzzyTermsEnum {es-pull}53231[#53231] (issue: {es-issue}52894[#52894])

[[upgrade-6.8.8]]
[float]
=== Upgrades

Features/Ingest::
* Ingest Attachment: Upgrade tika to v1.22 {es-pull}53418[#53418]

Infra/Core::
* Upgrade the bundled JDK to JDK 14 {es-pull}53748[#53748] (issue: {es-issue}53575[#53575])
* Update jackson-databind to 2.8.11.6 {es-pull}53522[#53522] (issue: {es-issue}45225[#45225])

[[release-notes-6.8.7]]
== {es} version 6.8.7

[float]
=== Known issues
* Slow loggers can cause Log4j loggers to leak over time. When a new index is created, a new Log4j logger is associated with it. However, when an index is deleted, Log4j keeps an internal reference to its loggers that results in a memory leak {es-pull}57228[#57228] (issue: {es-issue}56171[#56171])
+
This issue is fixed in Elasticsearch 6.8.10 and 7.7.1.

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[discrete]
[[bug-6.8.7]]
=== Bug fixes

Authentication::
* Preserve ApiKey credentials for async verification {es-pull}51244[#51244]

CCR::
* Fix shard follow task cleaner under security {es-pull}52347[#52347] (issues: {es-issue}44702[#44702], {es-issue}51971[#51971])

Engine::
* Account soft-deletes in FrozenEngine {es-pull}51192[#51192] (issue: {es-issue}50775[#50775])

Features/Java Low Level REST Client::
* Improve warning value extraction performance in Response {es-pull}50208[#50208] (issue: {es-issue}24114[#24114])

Infra/Core::
* Ignore virtual ethernet devices that disappear {es-pull}51581[#51581] (issue: {es-issue}49914[#49914])

Machine Learning::
* Include out-of-order as well as in-order terms in categorization reverse
searches {ml-pull}950[#950] (issue: {ml-issue}949[#949])

SQL::
* Fix ORDER BY on aggregates and GROUPed BY fields {es-pull}51894[#51894] (issue: {es-issue}50355[#50355])
* Fix ORDER BY YEAR() function {es-pull}51562[#51562] (issue: {es-issue}51224[#51224])
* Fix issue with CAST and NULL checking. {es-pull}50371[#50371] (issue: {es-issue}50191[#50191])

Search::
* Fix NPE bug inner_hits {es-pull}50709[#50709] (issue: {es-issue}50539[#50539])

[[enhancement-6.8.7]]
[float]
=== Enhancements

SQL::
* Verify Full-Text Search functions not allowed in SELECT {es-pull}51568[#51568] (issue: {es-issue}47446[#47446])

[[upgrade-6.8.7]]
[float]
=== Upgrades

Infra/Packaging::
* Upgrade the bundled JDK to JDK 13.0.2 {es-pull}51511[#51511]

[[release-notes-6.8.6]]
== {es} version 6.8.6

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[float]
=== Known issues
* Slow loggers can cause Log4j loggers to leak over time. When a new index is created, a new Log4j logger is associated with it. However, when an index is deleted, Log4j keeps an internal reference to its loggers that results in a memory leak {es-pull}57228[#57228] (issue: {es-issue}56171[#56171])
+
This issue is fixed in Elasticsearch 6.8.10 and 7.7.1.

[[enhancement-6.8.6]]
[float]
=== Enhancements

Features/Watcher::
* Log attachment generation failures {es-pull}50080[#50080]

Infra/Packaging::
* Restrict support for CMS to pre-JDK 14 {es-pull}49123[#49123] (issue: {es-issue}46973[#46973])

[[bug-6.8.6]]
[float]
=== Bug fixes

Aggregations::
* Avoid precision loss in DocValueFormat.RAW#parseLong {es-pull}49063[#49063] (issue: {es-issue}38692[#38692])

Audit::
* Audit log filter and marker {es-pull}45456[#45456] (issue: {es-issue}47251[#47251])

Authentication::
* Fix iterate-from-1 bug in smart realm order {es-pull}49473[#49473]

CCR::
* CCR should auto-retry rejected execution exceptions {es-pull}49213[#49213]

Features/Java High Level REST Client::
* Support es7 node http publish_address format {es-pull}49279[#49279] (issue: {es-issue}48950[#48950])

Machine Learning::
* Fixes for stop datafeed edge cases {es-pull}49191[#49191] (issues: {es-issue}43670[#43670], {es-issue}48931[#48931])

Recovery::
* Ignore Lucene index in peer recovery if translog corrupted {es-pull}49114[#49114]

Reindex::
* Fix delete- and update-by-query on indices without sequence numbers {es-pull}50077[#50077]


[[release-notes-6.8.5]]
== {es} version 6.8.5

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[float]
=== Known issues
* Slow loggers can cause Log4j loggers to leak over time. When a new index is created, a new Log4j logger is associated with it. However, when an index is deleted, Log4j keeps an internal reference to its loggers that results in a memory leak {es-pull}57228[#57228] (issue: {es-issue}56171[#56171])
+
This issue is fixed in Elasticsearch 6.8.10 and 7.7.1.

[[enhancement-6.8.5]]
[float]
=== Enhancements

Engine::
* Avoid unneeded refresh with concurrent realtime gets {es-pull}47895[#47895]

Infra/Settings::
* Do not reference values for filtered settings {es-pull}48066[#48066]

Machine Learning::
* The {ml} native processes are now arranged in a `.app` directory structure on
  macOS to allow for notarization on macOS Catalina {ml-pull}593[#593]


[[bug-6.8.5]]
[float]
=== Bug fixes

Allocation::
* Handle negative free disk space in deciders {es-pull}48392[#48392] (issue: {es-issue}48380[#48380])

Analysis::
* Actually close IndexAnalyzers contents {es-pull}43914[#43914]

CCR::
* Handle lower retaining sequence number retention lease error {es-pull}46420[#46420] (issues: {es-issue}46013[#46013], {es-issue}46416[#46416])

CRUD::
* Close query cache on index service creation failure {es-pull}48230[#48230] (issue: {es-issue}48186[#48186])

Engine::
* Fix refresh optimization for realtime get in mixed cluster {es-pull}48151[#48151] (issue: {es-issue}48114[#48114])

Features/Java High Level REST Client::
* Fix ILM HLRC Javadoc->documentation links {es-pull}48083[#48083]
* Prevent deadlock in BulkProcessor by using separate schedulers {es-pull}48697[#48697] (issue: {es-issue}47599[#47599])

Infra/Logging::
* Slow log must use separate underlying logger for each index {es-pull}47234[#47234] (issue: {es-issue}42432[#42432])

Machine Learning::
* Restore from checkpoint could damage seasonality modeling. For example, it could
  cause seasonal components to be overwritten in error {ml-pull}821[#821]

SQL::
* Fix issue with negative literels and parentheses {es-pull}48113[#48113] (issue: {es-issue}48009[#48009])
* Failing group by queries due to different ExpressionIds {es-pull}43072[#43072] (issues: {es-issue}33361[#33361], {es-issue}34543[#34543], {es-issue}36074[#36074], {es-issue}37044[#37044], {es-issue}40001[#40001], {es-issue}40240[#40240], {es-issue}41159[#41159], {es-issue}42041[#42041], {es-issue}46316[#46316])

Snapshot/Restore::
* Cleanup concurrent RepositoryData loading {es-pull}48329[#48329] (issue: {es-issue}48122[#48122])


[[release-notes-6.8.4]]
== {es} version 6.8.4

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.4]]
[float]
=== Enhancements

Engine::
* Limit number of retaining translog files for peer recovery {es-pull}47414[#47414]

Infra/Settings::
* Add more meaningful keystore version mismatch errors {es-pull}46291[#46291] (issue: {es-issue}44624[#44624])

Machine Learning::
* Throttle the delete-by-query of expired results {es-pull}47177[#47177] (issues: {es-issue}47003[#47003])



[[bug-6.8.4]]
[float]
=== Bug fixes

Authentication::
* Fallback to realm authc if ApiKey fails {es-pull}46538[#46538]

CRUD::
* Do not use ifSeqNo if doc does not have seq_no {es-pull}46198[#46198]

Distributed::
* Fix false positive out of sync warning in synced-flush {es-pull}46576[#46576] (issues: {es-issue}28464[#28464], {es-issue}30244[#30244])
* Suppress warning logs from background sync on relocated primary {es-pull}46247[#46247] (issues: {es-issue}40800[#40800], {es-issue}42241[#42241])

Engine::
* Improve translog corruption detection {es-pull}47873[#47873] (issues: {es-issue}41480[#41480], {es-issue}42744[#42744], {es-issue}42980[#42980], {es-issue}44217[#44217])
* Always rebuild checkpoint tracker for old indices {es-pull}46340[#46340] (issues: {es-issue}38879[#38879], {es-issue}46311[#46311])

Features/Indices APIs::
* Fix Rollover error when alias has closed indices {es-pull}47839[#47839] (issue: {es-issue}47148[#47148])

Features/Ingest::
* Allow dropping documents with auto-generated ID {es-pull}46773[#46773] (issue: {es-issue}46678[#46678])

Features/Watcher::
* Watcher - workaround for potential deadlock {es-pull}47603[#47603] (issues: {es-issue}41451[#41451], {es-issue}47599[#47599])
* Fix class used to initialize logger in Watcher {es-pull}46467[#46467]

Machine Learning::
* Reinstate ML daily maintenance actions {es-pull}47103[#47103] (issue: {es-issue}47003[#47003])
* Fix two datafeed flush lockup bugs {es-pull}46982[#46982]
* Throw an error when a datafeed needs CCS but it is not enabled for the node {es-pull}46044[#46044]
* Fix possibility of crash when calculating forecasts that overflow to disk {ml-pull}688[#688]

SQL::
* SQL: Allow whitespaces in escape patterns {es-pull}47577[#47577] (issue: {es-issue}47401[#47401])
* SQL: Fix issue with common type resolution {es-pull}46565[#46565] (issue: {es-issue}46551[#46551])
* SQL: wrong number of values for columns {es-pull}42122[#42122]

Snapshot/Restore::
* Fix Bug in Azure Repo Exception Handling {es-pull}47968[#47968]
* Fix Snapshot Corruption in Edge Case {es-pull}47552[#47552] (issues: {es-issue}46250[#46250], {es-issue}47550[#47550])
* Fix TransportSnapshotsStatusAction ThreadPool Use {es-pull}45824[#45824]



[[upgrade-6.8.4]]
[float]
=== Upgrades

Engine::
* Upgrade to lucene 7.7.2 {es-pull}47901[#47901]


[[release-notes-6.8.3]]
== {es} version 6.8.3

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.3]]
[float]
=== Enhancements

CCR::
* Include leases in error message when operations no longer available {es-pull}45681[#45681]

Infra/Core::
* Add OCI annotations and adjust existing annotations {es-pull}45167[#45167]

Infra/Settings::
* Normalize environment paths {es-pull}45179[#45179] (issue: {es-issue}45176[#45176])



[[bug-6.8.3]]
[float]
=== Bug fixes

Aggregations::
* Fix early termination of aggregators that run with breadth-first mode {es-pull}44963[#44963] (issue: {es-issue}44909[#44909])

Allocation::
* Avoid overshooting watermarks during relocation {es-pull}46079[#46079] (issue: {es-issue}45177[#45177])

CCR::
* Clean up ShardFollowTasks for deleted indices {es-pull}44702[#44702] (issue: {es-issue}34404[#34404])

CRUD::
* Allow _update on write alias {es-pull}45318[#45318] (issue: {es-issue}31520[#31520])

Distributed::
* Ensure AsyncTask#isScheduled remain false after close {es-pull}45687[#45687] (issue: {es-issue}45576[#45576])

Engine::
* Handle delete document level failures {es-pull}46100[#46100]
* Handle no-op document level failures {es-pull}46083[#46083]

Features/Indices APIs::
* Check shard limit after applying index templates {es-pull}44619[#44619] (issue: {es-issue}44567[#44567])
* Prevent NullPointerException in TransportRolloverAction {es-pull}43353[#43353] (issue: {es-issue}43296[#43296])

Features/Java High Level REST Client::
* Add rest_total_hits_as_int in HLRC's search requests {es-pull}46076[#46076] (issue: {es-issue}43925[#43925])

Infra/Core::
* Add default CLI JVM options {es-pull}44545[#44545] (issue: {es-issue}42021[#42021])

Infra/Plugins::
* Do not checksum all bytes at once in plugin install {es-pull}44649[#44649] (issue: {es-issue}44545[#44545])

SQL::
* Fix URI path being lost in case of hosted ES scenario {es-pull}44776[#44776] (issue: {es-issue}44721[#44721])
* Interval arithmetics failure {es-pull}42014[#42014] (issue: {es-issue}41200[#41200])

Search::
* Prevent Leaking Search Tasks on Exceptions in FetchSearchPhase and DfsQueryPhase {es-pull}45500[#45500]

Security::
* Use system context for looking up connected nodes {es-pull}43991[#43991] (issue: {es-issue}43974[#43974])


[[upgrade-6.8.3]]
[float]
=== Upgrades

Infra/Packaging::
* Upgrade to JDK 12.0.2 {es-pull}45172[#45172]

[[release-notes-6.8.2]]
== {es} version 6.8.2

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.2]]
[float]
=== Enhancements

Machine Learning::
* Improve message when native controller cannot connect {es-pull}43565[#43565] (issue: {es-issue}42341[#42341])
* Introduce a setting for the process connect timeout {es-pull}43234[#43234]

Ranking::
* Fix parameter value for calling `data.advanceExact` {es-pull}44205[#44205]

Snapshot/Restore::
* Add SAS token authentication support to Azure Repository plugin {es-pull}42982[#42982] (issue: {es-issue}42117[#42117])



[[bug-6.8.2]]
[float]
=== Bug fixes

Allocation::
* Do not copy initial recovery filter during an index split {es-pull}44053[#44053] (issue: {es-issue}43955[#43955])

Analysis::
* Fix varying responses for `<index>/_analyze` request {es-pull}44342[#44342] (issues: {es-issue}44078[#44078], {es-issue}44284[#44284])

CCR::
* Skip update if leader and follower settings are identical {es-pull}44535[#44535] (issue: {es-issue}44521[#44521])
* Avoid stack overflow in auto-follow coordinator {es-pull}44421[#44421] (issue: {es-issue}43251[#43251])
* Avoid NPE when checking for CCR index privileges {es-pull}44397[#44397] (issue: {es-issue}44172[#44172])

Engine::
* Preserve thread context in AsyncIOProcessor {es-pull}43729[#43729]

Features/ILM::
* Fix swapped variables in error message {es-pull}44300[#44300]
* Account for node versions during allocation in ILM shrink {es-pull}43300[#43300] (issue: {es-issue}41879[#41879])
* Narrow period of shrink action in which ILM prevents stopping {es-pull}43254[#43254] (issue: {es-issue}43253[#43253])

Features/Indices APIs::
* Validate index settings after applying templates {es-pull}44612[#44612] (issues: {es-issue}34021[#34021], {es-issue}44567[#44567])

Features/Stats::
* Return 0 for negative "free" and "total" memory reported by the OS {es-pull}42725[#42725] (issue: {es-issue}42157[#42157])

Machine Learning::
* Fix ML memory tracker lockup when inner step fails {es-pull}44158[#44158] (issue: {es-issue}44156[#44156])
* Fix datafeed checks when a concrete remote index is present {es-pull}43923[#43923] (issue: {es-issue}42113[#42113])
* Don't write model size stats when job is closed without any input {ml-pull}512[#512] (issue: {ml-issue}394[#394])
* Don't persist model state at the end of lookback if the lookback did not generate any input {ml-pull}521[#521] (issue: {ml-issue}519[#519])

Mapping::
* Prevent types deprecation warning for indices.exists requests {es-pull}43963[#43963] (issue: {es-issue}43905[#43905])
* Add `include_type_name` in `indices.exists` REST API specification {es-pull}43910[#43910] (issue: {es-issue}43905[#43905])

Network::
* Reconnect remote cluster when seeds are changed {es-pull}43379[#43379] (issue: {es-issue}37799[#37799])

SQL::
* Handle the edge case of an empty array of values to return from source {es-pull}43868[#43868] (issue: {es-issue}43863[#43863])
* Fix NPE in case of subsequent scrolled requests for a CSV/TSV formatted response {es-pull}43365[#43365] (issue: {es-issue}43327[#43327])
* Increase hard limit for sorting on aggregates {es-pull}43220[#43220] (issue: {es-issue}43168[#43168])

Search::
* Fix wrong logic in `match_phrase` query with multi-word synonyms {es-pull}43941[#43941] (issue: {es-issue}43308[#43308])

Security::
* Do not swallow I/O exception getting authentication {es-pull}44398[#44398] (issues: {es-issue}44172[#44172], {es-issue}44397[#44397])
* `SecurityIndexSearcherWrapper` doesn't always carry over caches and similarity {es-pull}43436[#43436]

[[release-notes-6.8.1]]
== {es} version 6.8.1

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.1]]
[float]
=== Enhancements

Java High Level REST Client::
* Added param ignore_throttled=false when indicesOptions.ignoreThrottle {es-pull}42393[#42393] (issue: {es-issue}42358[#42358])


[[bug-6.8.1]]
[float]
=== Bug fixes

Allocation::
* Avoid bubbling up failures from a shard that is recovering {es-pull}42287[#42287] (issues: {es-issue}30919[#30919], {es-issue}40107[#40107])

Authentication::
* Only index into "doc" type in security index {es-pull}42563[#42563] (issue: {es-issue}42562[#42562])

Distributed::
* Do not use ifSeqNo for update requests on mixed cluster {es-pull}42596[#42596] (issue: {es-issue}42561[#42561])
* Avoid unnecessary persistence of retention leases {es-pull}42299[#42299]
* Execute actions under permit in primary mode only {es-pull}42241[#42241] (issues: {es-issue}40386[#40386], {es-issue}41686[#41686])

Engine::
* Account soft deletes for committed segments {es-pull}43126[#43126] (issue: {es-issue}43103[#43103])

Infra/Core::
* scheduleAtFixedRate would hang {es-pull}42993[#42993] (issue: {es-issue}38441[#38441])
* Only ignore IOException when fsyncing on dirs {es-pull}42972[#42972] (issue: {es-issue}42950[#42950])
* Deprecation info for joda-java migration {es-pull}41956[#41956] (issue: {es-issue}42010[#42010])

Machine Learning::
* Fix possible race condition when closing an opening job {es-pull}42506[#42506]

Mapping::
* Fix possible NPE in put mapping validators {es-pull}43000[#43000] (issue: {es-issue}37675[#37675])

Percolator::
* Fixed ignoring name parameter for percolator queries {es-pull}42598[#42598] (issue: {es-issue}40405[#40405])
* Exclude nested documents {es-pull}42554[#42554] (issue: {es-issue}42361[#42361])

Recovery::
* Recovery with syncId should verify seqno infos {es-pull}41265[#41265]

Reindex::
* Remote reindex failure parse fix {es-pull}42928[#42928]

Rollup::
* Fix max boundary for rollup jobs that use a delay {es-pull}42158[#42158]

SQL::
* Fix wrong results when sorting on aggregate {es-pull}43154[#43154] (issue: {es-issue}42851[#42851])
* Cover the Integer type when extracting values from _source {es-pull}42859[#42859] (issue: {es-issue}42858[#42858])

Search::
* SearchRequest#allowPartialSearchResults does not handle successful retries {es-pull}43095[#43095] (issue: {es-issue}40743[#40743])
* Fix auto fuzziness in query_string query {es-pull}42897[#42897]
* Wire query cache into sorting nested-filter computation {es-pull}42906[#42906] (issue: {es-issue}42813[#42813])
* Fix sorting on nested field with unmapped {es-pull}42451[#42451] (issue: {es-issue}33644[#33644])
* Fixes a bug in AnalyzeRequest.toXContent() {es-pull}42795[#42795] (issues: {es-issue}39670[#39670], {es-issue}42197[#42197])
* Fix concurrent search and index delete {es-pull}42621[#42621] (issue: {es-issue}28053[#28053])

Snapshot/Restore::
* Fix Azure List by Prefix Bug {es-pull}42713[#42713]

[[release-notes-6.8.0]]
== {es} version 6.8.0

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.0]]
[float]
=== Enhancements

Security::
* Moved some security features to basic. See <<release-highlights-6.8.0, 6.8.0 Release highlights>>

Authentication::
* Log warning when unlicensed realms are skipped {es-pull}41778[#41778]

Infra/Settings::
* Drop distinction in entries for keystore {es-pull}41701[#41701]

[[bug-6.8.0]]
[float]
=== Bug fixes

Features/Watcher::
* Fix Watcher deadlock that can cause in-abilty to index documents. {es-pull}41418[#41418] (issue: {es-issue}41390[#41390])

Network::
* Enforce transport TLS on Basic with Security {es-pull}42150[#42150]

Reindex::
* Allow reindexing into write alias {es-pull}41677[#41677] (issue: {es-issue}41667[#41667])

SQL::
* SQL: Fix issue regarding INTERVAL * number {es-pull}42014[#42014] (issue: {es-issue}41239[#41239])
* SQL: Remove CircuitBreaker from parser {es-pull}41835[#41835] (issue: {es-issue}41471[#41471])

Security::
* Remove dynamic objects from security index {es-pull}40499[#40499] (issue: {es-issue}35460[#35460])
* Add granular API key privileges {es-pull}41488[#41488] (issue: {es-issue}40031[#40031])
