[[release-notes-6.8.1]]
== {es} version 6.8.1

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.1]]
[float]
=== Enhancements

Java High Level REST Client::
* Added param ignore_throttled=false when indicesOptions.ignoreThrottle {pull}42393[#42393] (issue: {issue}42358[#42358])



[[bug-6.8.1]]
[float]
=== Bug fixes

Allocation::
* Avoid bubbling up failures from a shard that is recovering {pull}42287[#42287] (issues: {issue}30919[#30919], {issue}40107[#40107])

Authentication::
* Only index into "doc" type in security index {pull}42563[#42563] (issue: {issue}42562[#42562])

Distributed::
* Do not use ifSeqNo for update requests on mixed cluster {pull}42596[#42596] (issue: {issue}42561[#42561])
* Avoid unnecessary persistence of retention leases {pull}42299[#42299]
* Execute actions under permit in primary mode only {pull}42241[#42241] (issues: {issue}40386[#40386], {issue}41686[#41686])

Engine::
* Account soft deletes for committed segments {pull}43126[#43126] (issue: {issue}43103[#43103])

Infra/Core::
* scheduleAtFixedRate would hang {pull}42993[#42993] (issue: {issue}38441[#38441])
* Only ignore IOException when fsyncing on dirs {pull}42972[#42972] (issue: {issue}42950[#42950])
* Deprecation info for joda-java migration {pull}41956[#41956] (issue: {issue}42010[#42010])

Machine Learning::
* [ML] Fix possible race condition when closing an opening job {pull}42506[#42506]

Mapping::
* Fix possible NPE in put mapping validators {pull}43000[#43000] (issue: {issue}37675[#37675])

Percolator::
* fixed ignoring name parameter for percolator queries {pull}42598[#42598] (issue: {issue}40405[#40405])
* Percolator: Exclude nested documents {pull}42554[#42554] (issue: {issue}42361[#42361])

Recovery::
* Recovery with syncId should verify seqno infos {pull}41265[#41265]

Reindex::
* Remote reindex failure parse fix {pull}42928[#42928]

Rollup::
* Fix max boundary for rollup jobs that use a delay {pull}42158[#42158]

SQL::
* SQL: Fix wrong results when sorting on aggregate {pull}43154[#43154] (issue: {issue}42851[#42851])
* SQL: cover the Integer type when extracting values from _source {pull}42859[#42859] (issue: {issue}42858[#42858])

Search::
* SearchRequest#allowPartialSearchResults does not handle successful retries {pull}43095[#43095] (issue: {issue}40743[#40743])
* Fix auto fuzziness in query_string query {pull}42897[#42897]
* Wire query cache into sorting nested-filter computation {pull}42906[#42906] (issue: {issue}42813[#42813])
* Fix sorting on nested field with unmapped {pull}42451[#42451] (issue: {issue}33644[#33644])
* Fixes a bug in AnalyzeRequest.toXContent() {pull}42795[#42795] (issues: {issue}39670[#39670], {issue}42197[#42197])
* Fix concurrent search and index delete {pull}42621[#42621] (issue: {issue}28053[#28053])

Snapshot/Restore::
* Fix Azure List by Prefix Bug {pull}42713[#42713]

[[release-notes-6.8.0]]
== {es} version 6.8.0

Also see <<breaking-changes-6.8,Breaking changes in 6.8>>.

[[enhancement-6.8.0]]
[float]
=== Enhancements

Security::
* Moved some security features to basic. See <<release-highlights-6.8.0, 6.8.0 Release highlights>>

Authentication::
* Log warning when unlicensed realms are skipped {pull}41778[#41778]

Infra/Settings::
* Drop distinction in entries for keystore {pull}41701[#41701]

[[bug-6.8.0]]
[float]
=== Bug fixes

Features/Watcher::
* Fix Watcher deadlock that can cause in-abilty to index documents. {pull}41418[#41418] (issue: {issue}41390[#41390])

Network::
* Enforce transport TLS on Basic with Security {pull}42150[#42150]

Reindex::
* Allow reindexing into write alias {pull}41677[#41677] (issue: {issue}41667[#41667])

SQL::
* SQL: Fix issue regarding INTERVAL * number {pull}42014[#42014] (issue: {issue}41239[#41239])
* SQL: Remove CircuitBreaker from parser {pull}41835[#41835] (issue: {issue}41471[#41471])

Security::
* Remove dynamic objects from security index {pull}40499[#40499] (issue: {issue}35460[#35460])
* Add granular API key privileges {pull}41488[#41488] (issue: {issue}40031[#40031])


