[[release-notes-7.7.0]]
== {es} version 7.7.0

coming[7.7.0]

[[breaking-7.7.0]]
[float]
=== Breaking changes

Mapping::
* Dynamic mappings in indices created on 8.0 and later have stricter validation at mapping update time and
  results in a deprecation warning for indices created in Elasticsearch 7.7.0 and later.
  (e.g. incorrect analyzer settings or unknown field types). {pull}51233[#51233]

Search::
* A regression that allowed negative scores in a script_score query was corrected.
  A behaviour is restored that throws an error if script_score query produces
  a negative score {pull}52478[#52478].
* Pipeline aggregation validation errors that used to return HTTP
  500s/Internal Server Errors now return 400/Bad Request {pull}53669[#53669].
  As a bonus we now return a list of validation errors rather than returning
  the first one we encounter.

[[bug-7.7.0]]
[float]
=== Bug fixes

* Fixed an index corruption bug that would occur when applying deletes or
updates on an index after it has been shrunk. More details can be found on the
https://issues.apache.org/jira/browse/LUCENE-9300[corresponding issue].
