[[release-notes-8.0.1]]
== {es} version 8.0.1

coming[8.0.1]

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[bug-8.0.1]]
[float]
=== Bug fixes

Aggregations::
* Fix: backward compatibility with version 7.17.0 {es-pull}83715[#83715]

Distributed::
* [GCE Discovery] Correcly handle large zones with 500 or more instances {es-pull}83785[#83785] (issue: {es-issue}83783[#83783])

ILM+SLM::
* Do not allow negative age in ILM explain {es-pull}84043[#84043]

Infra/Core::
* Always re-run Feature migrations which have encountered errors {es-pull}83918[#83918] (issue: {es-issue}83917[#83917])
* Copy `trace.id` in threadcontext stash {es-pull}83218[#83218]
* Preserve context in `ResultDeduplicator` {es-pull}84038[#84038] (issue: {es-issue}84036[#84036])
* Registration of `SystemIndexMigrationTask` named xcontent objects {es-pull}84192[#84192] (issue: {es-issue}84115[#84115])
* Update system index mappings if `_meta` is null {es-pull}83896[#83896] (issue: {es-issue}83890[#83890])

Ingest::
* Fix `GeoIpDownloader` startup during rolling upgrade {es-pull}84000[#84000]
* Short circuit date patterns after first match {es-pull}83764[#83764]

Machine Learning::
* Retry anomaly detection job recovery during relocation {es-pull}83456[#83456]

Packaging::
* Add log4j-slf4j-impl to repository-azure {es-pull}83661[#83661] (issue: {es-issue}83652[#83652])
* Restart ES after keystore upgrade in postinst {es-pull}84224[#84224] (issue: {es-issue}82433[#82433])

Recovery::
* Add missing `indices.recovery.internal_action_retry_timeout` to list of settings {es-pull}83354[#83354]

SQL::
* Fix txt format for empty result sets {es-pull}83376[#83376]

Search::
* Avoid eagerly loading `StoredFieldsReader` in fetch phase {es-pull}83693[#83693] (issue: {es-issue}82777[#82777])
* Returns valid PIT when no index matched {es-pull}83424[#83424]

Security::
* Upgrade jANSI dependency to 2.4.0 {es-pull}83566[#83566]

Snapshot/Restore::
* Move Get Snapshots Serialization to Management Pool {es-pull}83215[#83215]
* Preserve context in `snapshotDeletionListeners` {es-pull}84089[#84089] (issue: {es-issue}84036[#84036])

Transform::
* Fix condition on which the transform stops processing buckets {es-pull}82852[#82852]

Watcher::
* Tolerate empty types array in Watch definitions {es-pull}83524[#83524] (issue: {es-issue}83235[#83235])

[[enhancement-8.0.1]]
[float]
=== Enhancements

Infra/REST API::
* Update YAML Rest tests to check for product header on all responses {es-pull}83290[#83290]

Recovery::
* Adjust `indices.recovery.max_bytes_per_sec` according to external settings {es-pull}82819[#82819]

[[upgrade-8.0.1]]
[float]
=== Upgrades

Geo::
* Update vector tiles google protobuf to 3.16.1 {es-pull}83402[#83402]

Packaging::
* Bump bundled JDK to 17.0.2+8 {es-pull}83243[#83243] (issue: {es-issue}83242[#83242])


[[release-notes-8.0.0]]
== {es} version 8.0.0

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[bug-8.0.0]]
[float]
=== Bug fixes

Security::
* Bind to non-localhost for transport in some cases {es-pull}82973[#82973]
* Disable ANSI formatting for security autoconfiguration on Windows cmd line {es-pull}83326[#83326]

[[enhancement-8.0.0]]
[float]
=== Enhancements

Infra/Core::
* Enhancement/prevent 6.8 indices upgrade {es-pull}82689[#82689] (issue: {es-issue}81326[#81326])
* Prevent upgrades to 8.0 from 7.non-last {es-pull}82321[#82321] (issue: {es-issue}81865[#81865])

Infra/Plugins::
* Convert repository plugins to modules {es-pull}81870[#81870] (issue: {es-issue}81652[#81652])

[[feature-8.0.0]]
[float]
=== New features

Snapshot/Restore::
* [s3-repository] Support IAM roles for Kubernetes service accounts {es-pull}81255[#81255] (issue: {es-issue}52625[#52625])


[[release-notes-8.0.0]]
== {es} version 8.0.0

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[bug-8.0.0]]
[float]
=== Bug fixes

Infra/Logging::
* Add `doPrivileged` section in deprecation logger {es-pull}81819[#81819] (issue: {es-issue}81708[#81708])

Packaging::
* Add Docker support for enrollment tokens {es-pull}81082[#81082]

[[enhancement-8.0.0]]
[float]
=== Enhancements

Infra/Core::
* All system indices are hidden indices {es-pull}79512[#79512]

Packaging::
* Use Cloudflare's zlib in Docker images {es-pull}81245[#81245] (issue: {es-issue}81208[#81208])


[[release-notes-8.0.0]]
== {es} version 8.0.0

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[breaking-8.0.0]]
[float]
=== Breaking changes

Packaging::
* Require Java 17 for running Elasticsearch {es-pull}79873[#79873]

[[enhancement-8.0.0]]
[float]
=== Enhancements

Packaging::
* Allow total memory to be overridden {es-pull}78750[#78750] (issue: {es-issue}65905[#65905])

Security::
* CLI tool to reconfigure nodes to enroll {es-pull}79690[#79690]
* Security auto-configuration for packaged installations {es-pull}75144[#75144] (issue: {es-issue}78306[#78306])

[[feature-8.0.0]]
[float]
=== New features

Security::
* Auto configure TLS for new nodes of new clusters {es-pull}77231[#77231] (issues: {es-issue}75144[#75144], {es-issue}75704[#75704])


[[release-notes-8.0.0]]
== {es} version 8.0.0

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[enhancement-8.0.0]]
[float]
=== Enhancements

Security::
* Enroll additional nodes to cluster {es-pull}77292[#77292]


[[release-notes-8.0.0]]
== {es} version 8.0.0

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.



