[[release-notes-8.0.0-rc1]]
== {es} version 8.0.0-rc1

Also see <<breaking-changes-8.0,Breaking changes in 8.0>>.

[[known-issues-8.0.0-rc1]]
[float]
=== Known issues

* **Do not upgrade production clusters to {es} 8.0.0-rc1.** {es} 8.0.0-rc1 is
a pre-release of {es} 8.0 and is intended for testing purposes only.
+
Upgrades from pre-release builds are not supported and could result in errors or
data loss. If you upgrade from a released version, such as 7.16, to a
pre-release version for testing, discard the contents of the cluster when you are
done. Do not attempt to upgrade to the final 8.0 release.

* For {es} 8.0.0-rc1, the {ref}/sql-jdbc.html[{es} SQL JDBC driver] requires
Java 17 or newer. In {es} 8.0.0-rc2, the JDBC driver will only require Java 8
or newer. {es-pull}82325

[[breaking-8.0.0-rc1]]
[float]
=== Breaking changes

Infra/Core::
* All system indices are hidden indices {es-pull}79512[#79512]

Snapshot/Restore::
* Adjust snapshot index resolution behavior to be more intuitive {es-pull}79670[#79670] (issue: {es-issue}78320[#78320])

[[deprecation-8.0.0-rc1]]
[float]
=== Deprecations

Engine::
* Deprecate setting `max_merge_at_once_explicit` {es-pull}80574[#80574]

Machine Learning::
* Deprecate `estimated_heap_memory_usage_bytes` and replace with `model_size_bytes` {es-pull}80554[#80554]

Search::
* Configure `IndexSearcher.maxClauseCount()` based on node characteristics {es-pull}81525[#81525] (issue: {es-issue}46433[#46433])

Transform::
* Improve transform deprecation messages {es-pull}81847[#81847] (issues: {es-issue}81521[#81521], {es-issue}81523[#81523])

[[enhancement-8.0.0-rc1]]
[float]
=== Enhancements

Authorization::
* Granting `kibana_system` reserved role access to "all" privileges to `.internal.preview.alerts*` index {es-pull}80889[#80889] (issues: {es-issue}76624[#76624], {es-issue}80746[#80746], {es-issue}116374[#116374])
* Granting `kibana_system` reserved role access to "all" privileges to .preview.alerts* index {es-pull}80746[#80746]
* Granting editor and viewer roles access to alerts-as-data indices {es-pull}81285[#81285]

ILM+SLM::
* Make unchanged ILM policy updates into noop {es-pull}82240[#82240] (issue: {es-issue}82065[#82065])

Indices APIs::
* Batch rollover cluster state updates {es-pull}79945[#79945] (issues: {es-issue}77466[#77466], {es-issue}79782[#79782])
* Reuse `MappingMetadata` instances in Metadata class {es-pull}80348[#80348] (issues: {es-issue}69772[#69772], {es-issue}77466[#77466])

Infra/Settings::
* Implement setting deduplication via string interning {es-pull}80493[#80493] (issues: {es-issue}77466[#77466], {es-issue}78892[#78892])

Ingest::
* Extract more standard metadata from binary files {es-pull}78754[#78754] (issue: {es-issue}22339[#22339])

Machine Learning::
* Add `deployment_stats` to trained model stats {es-pull}80531[#80531]
* The setting `use_auto_machine_memory_percent` now defaults `max_model_memory_limit` {es-pull}80532[#80532] (issue: {es-issue}80415[#80415])

Monitoring::
* Adding default templates for Metricbeat ECS data {es-pull}81744[#81744]

Network::
* Improve slow inbound handling to include response type {es-pull}80425[#80425]

Recovery::
* Fix `PendingReplicationActions` submitting lots of `NOOP` tasks to `GENERIC` {es-pull}82092[#82092] (issues: {es-issue}77466[#77466], {es-issue}79837[#79837])

Reindex::
* Do not scroll if max docs is less than scroll size (update/delete by query) {es-pull}81654[#81654] (issue: {es-issue}54270[#54270])

Security::
* URL option for `BaseRunAsSuperuserCommand` {es-pull}81025[#81025] (issue: {es-issue}80481[#80481])

[[bug-8.0.0-rc1]]
[float]
=== Bug fixes

Autoscaling::
* Autoscaling use adjusted total memory {es-pull}80528[#80528] (issue: {es-issue}78750[#78750])

Data streams::
* Prohibit restoring a data stream alias with a conflicting write data stream {es-pull}81217[#81217] (issue: {es-issue}80976[#80976])

ILM+SLM::
* Less verbose serialization of snapshot failure in SLM metadata {es-pull}80942[#80942] (issue: {es-issue}77466[#77466])

Indices APIs::
* Fix `ComposableIndexTemplate` equals when `composed_of` is null {es-pull}80864[#80864]

Infra/REST API::
* Handle exceptions thrown from `RestCompatibleVersionHelper` {es-pull}80253[#80253] (issues: {es-issue}78214[#78214], {es-issue}79060[#79060])

Ingest::
* Adjust default geoip logging to be less verbose {es-pull}81404[#81404] (issue: {es-issue}81356[#81356])

Machine Learning::
* Set model state compatibility version to 8.0.0 {ml-pull}2139[#2139]
