[[release-notes-8.11.1]]
== {es} version 8.11.1

Also see <<breaking-changes-8.11,Breaking changes in 8.11>>.

[[bug-8.11.1]]
[float]
=== Bug fixes

Allocation::
* Avoid negative `DesiredBalanceStats#lastConvergedIndex` {es-pull}101998[#101998]

Authentication::
* Fix memory leak from JWT cache (and fix the usage of the JWT auth cache) {es-pull}101799[#101799]

Machine Learning::
* Fix inference timeout from the Inference Ingest Processor {es-pull}101971[#101971]

Mapping::
* Fix incorrect dynamic mapping for non-numeric-value arrays #101965 {es-pull}101967[#101967]

Network::
* Fail listener on exception in `TcpTransport#openConnection` {es-pull}101907[#101907] (issue: {es-issue}100510[#100510])

Search::
* Dry up `AsyncTaskIndexService` memory management and fix inefficient circuit breaker use {es-pull}101892[#101892]

Snapshot/Restore::
* Respect regional AWS STS endpoints {es-pull}101705[#101705] (issue: {es-issue}89175[#89175])

[[enhancement-8.11.1]]
[float]
=== Enhancements

Machine Learning::
* Add inference counts by model to the machine learning usage stats {es-pull}101915[#101915]


