[[release-notes-8.13.3]]
== {es} version 8.13.3

Also see <<breaking-changes-8.13,Breaking changes in 8.13>>.

[[breaking-8.13.3]]
[float]
=== Breaking changes

SQL::
* Limit how much space some string functions can use {es-pull}107333[#107333]

[[known-issues-8.13.3]]
[float]
=== Known issues
* When upgrading clusters with non-master-eligible nodes in them from versions before 8.13, information on new functionality
of the upgraded nodes may not be registered properly with the master. This can lead to some new functionality
added since 8.13.0 not being accessible on the upgraded cluster. The workaround is to perform a rolling restart
on the non-master-eligible nodes once the upgrade is complete. This is only necessary when upgrading from a version
prior to 8.13.0.

[[bug-8.13.3]]
[float]
=== Bug fixes

Data streams::
* Avoid unintentionally clearing the `DataStream.rolloverOnWrite` flag {es-pull}107122[#107122]

ES|QL::
* ESQL: Fix bug when combining projections {es-pull}107131[#107131] (issue: {es-issue}107083[#107083])
* ESQL: Fix missing refs due to pruning renamed grouping columns {es-pull}107328[#107328] (issues: {es-issue}107083[#107083], {es-issue}107166[#107166])

Indices APIs::
* GET /_all should return hidden indices with visible aliases {es-pull}106975[#106975]

Mapping::
* Fix merging component templates with a mix of dotted and nested object mapper definitions {es-pull}106077[#106077] (issue: {es-issue}105482[#105482])

Network::
* Handle exceptions thrown by HTTP header validation {es-pull}107355[#107355] (issue: {es-issue}107338[#107338])

Percolator::
* Percolator named queries: rewrite for matched info {es-pull}107432[#107432] (issue: {es-issue}107176[#107176])

Search::
* Fix `minimized_round_trips` in lookup runtime fields {es-pull}107785[#107785]

[[enhancement-8.13.3]]
[float]
=== Enhancements

ES|QL::
* ESQL: Introduce language versioning to REST API {es-pull}106824[#106824]


