[[release-notes-8.8.2]]
== {es} version 8.8.2

coming[8.8.2]

Also see <<breaking-changes-8.8,Breaking changes in 8.8>>.

[[bug-8.8.2]]
[float]
=== Bug fixes

Aggregations::
* Fix iteration of empty percentiles throwing Null Pointer Exception {es-pull}96668[#96668] (issue: {es-issue}96626[#96626])

Health::
* Uses `ClusterSettings` instead of Node `Settings` in `HealthMetadataService` {es-pull}96843[#96843] (issue: {es-issue}96219[#96219])

Ingest Node::
* Support dotted field notations in the reroute processor {es-pull}96243[#96243]

Machine Learning::
* Ensure NLP model inference queue is always cleared after shutdown or failure {es-pull}96738[#96738]

SQL::
* Fix translation of queries involving Version vals {es-pull}96540[#96540] (issue: {es-issue}96509[#96509])

Search::
* Increase concurrent request of opening point-in-time {es-pull}96782[#96782]

TSDB::
* The get data stream api incorrectly prints warning log for upgraded tsdb data streams {es-pull}96606[#96606]

[[enhancement-8.8.2]]
[float]
=== Enhancements

TSDB::
* Change rollup thread pool settings {es-pull}96821[#96821] (issue: {es-issue}96758[#96758])

Transform::
* Adding null check to fix potential NPE {es-pull}96785[#96785] (issue: {es-issue}96781[#96781])


