[[release-highlights]]
== What's new in {minor-version}

coming::[{minor-version}]

Here are the highlights of what's new and improved in {es} {minor-version}!
ifeval::[\{release-state}\"!=\"unreleased\"]
For detailed information about this release, see the <<es-release-notes>> and
<<breaking-changes>>.
endif::[]

// Add previous release to the list
Other versions:

{ref-bare}/8.5/release-highlights.html[8.5]
| {ref-bare}/8.4/release-highlights.html[8.4]
| {ref-bare}/8.3/release-highlights.html[8.3]
| {ref-bare}/8.2/release-highlights.html[8.2]
| {ref-bare}/8.1/release-highlights.html[8.1]
| {ref-bare}/8.0/release-highlights.html[8.0]

// tag::notable-highlights[]

[discrete]
[[make_categorize_text_aggregation_ga]]
=== Make `categorize_text` aggregation GA
The `categorize_text` aggregation has been moved from technical preview to general availability.

{es-pull}88600[#88600]

// end::notable-highlights[]


[discrete]
[[support_cartesian_centroid_aggregation_over_points_shapes]]
=== Support cartesian_centroid aggregation over points and shapes
Similar to the existing `geo_centroid` aggregation, this new metric aggregation, `cartesian_centroid`,
calculates the centroid over cartesian point and shape fields.

{es-pull}89216[#89216]

[discrete]
[[stack_monitoring_logstash_load_average_type_fixed_for_metricbeat_collection]]
=== Stack Monitoring: Logstash load average type fixed for metricbeat collection
Previously, the templates for ingesting logstash load average using metricbeat were set to `long`. This provides only an integer graph.

The type has been corrected to `half_float`. You can force a rollover to see the change immediately or wait for the next ILM rollover.

[source,console]
----
POST .monitoring-logstash-8-mb/_rollover
----
// TEST[skip:"quick changelog code snippet"]

{es-pull}90494[#90494]

[discrete]
[[support_cartesian_bounds_aggregation_over_points_shapes]]
=== Support cartesian_bounds aggregation over points and shapes
Similar to the existing `geo_bounds` aggregation, this new metric aggregation, `cartesian_bounds`,
calculates the bounds of cartesian point and shape fields.

{es-pull}91298[#91298]

