[[release-highlights]]
== What's new in {minor-version}

Here are the highlights of what's new and improved in {es} {minor-version}!

For detailed information about this release, see the <<es-release-notes>> and
<<breaking-changes>>.

// Add previous release to the list
Other versions:
{ref-bare}/7.14/release-highlights.html[7.14]
| {ref-bare}/7.13/release-highlights.html[7.13]
| {ref-bare}/7.11/release-highlights.html[7.12]
| {ref-bare}/7.11/release-highlights.html[7.11]
| {ref-bare}/7.10/release-highlights.html[7.10]
| {ref-bare}/7.9/release-highlights.html[7.9]
| {ref-bare}/7.8/release-highlights.html[7.8]
| {ref-bare}/7.7/release-highlights.html[7.7]
| {ref-bare}/7.6/release-highlights-7.6.0.html[7.6]
| {ref-bare}/7.5/release-highlights-7.5.0.html[7.5]
| {ref-bare}/7.4/release-highlights-7.4.0.html[7.4]
| {ref-bare}/7.3/release-highlights-7.3.0.html[7.3]
| {ref-bare}/7.2/release-highlights-7.2.0.html[7.2]
| {ref-bare}/7.1/release-highlights-7.1.0.html[7.1]
| {ref-bare}/7.0/release-highlights-7.0.0.html[7.0]

// tag::notable-highlights[]

[discrete]
=== Index disk usage API 
There's a new API that supports analyzing the disk usage of each field of an
index, including the entire index itself. The the API estimates the disk usage
of a field by iterating over its content and tracking the number of bytes read.
Refer to {ref}/indices-disk-usage.html[analyze index disk usage API].

[discrete]
=== Search vector tile API
There's a new endpoint for generating vector tiles from geospatial data stored
in {es}. This capability is useful for any application that wants to render
geospatial information stored in {es} on a map.
Refer to {ref}/search-vector-tile-api.html[search vector tile API].

[discrete]
=== Composite runtime fields
Runtime fields support both grok and dissect patterns, but previously emitted
values for a single field only. You can now emit multiple values from a single
field using `composite` runtime fields. 
Refer to {ref}/runtime-examples.html#runtime-examples-grok-composite[define a composite runtime field].

// end::notable-highlights[]

// Omit the notable highlights tag for entries that only need to appear in the ES ref:
// [discrete]
// === Heading
//
// Description.