[[release-highlights]]
== What's new in {minor-version}

Here are the highlights of what's new and improved in {es} {minor-version}!

For detailed information about this release, see the <<es-release-notes>> and
<<breaking-changes>>.

// Add previous release to the list
// Other versions: 
// {ref-bare}/7.last/release-highlights.html[7.last] 
// | {ref-bare}/8.0/release-highlights.html[8.0]

// Use the notable-highlights tag to mark entries that 
// should be featured in the Stack Installation and Upgrade Guide:

// tag::notable-highlights[] 
[discrete]
=== Security features are enabled and configured by default

Running {es} without security leaves your cluster exposed to anyone who can send
network traffic to {es}. In previous versions, you had to explicitly enable the {es}
security features such as authantication, authorization and network encryption (TLS).

Starting in {es} 8.0, security is
{ref}/configuring-stack-security.html[enabled and configured by default] when
you start {es} for the first time. We also generate an enrollment token at
startup for {kib} so that you can quickly and easily connect a {kib} instance to your
secured {es} cluster without having to generate security certificates or update
`yml` configuration files. Just by starting {es}, you’ll have password
protection, internode communication secured with TLS, and encrypted connections
between {es} and {kib}.

We're also shipping the
{ref}/create-enrollment-token.html[`elasticsearch-create-enrollment-token`] tool,
which you can use to generate enrollment tokens to enroll new {es} nodes with an
existing cluster, or configure {kib} instances to communicate with an existing
{es} cluster that has security features enabled. Just pass the enrollment token
when starting new nodes and {es} handles all of the security configuration for
you.


[discrete]
=== Storage savings for `keyword`, `match_only_text`, and `text` fields

We've updated inverted indices, an internal data structure, to use a more
space-efficient encoding. This change will benefit `keyword` fields,
`match_only_text` fields, and, to a lesser extent, `text` fields. In our
benchmarks using application logs, this translated into a 14.4% reduction of
the size of the index of the `message` field (mapped as `match_only_text`) and
an overall 3.5% reduction of the on-disk footprint.

This change will be picked up automatically by both new indices, and existing
indices for every new segment.

[discrete]
=== Faster indexing of `geo_point`, `geo_shape`, and range fields

We've optimized indexing speeds for multi-dimensional points, an internal data
structure used for `geo_point`, `geo_shape`, and range fields. Lucene-level
benchmarks reported 10-15% faster indexing for these fields types. {es} indices
and data streams that mostly consist of these fields may see noticeable
improvements to indexing speed.

// end::notable-highlights[]

// Omit the notable highlights tag for entries that only need to appear in the ES ref:
// [discrete] 
// === Heading
//
// Description. 
