### Create index (Run with IntelliJ IDEA; first `rm -rf build/runStatelessTask/repo/stateless; ./gradlew runStateless`)
PUT http://localhost:9200/demo-semantic
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

{
  "mappings": {
    "properties": {
      "text": {
        "type": "semantic_text"
      }
    }
  }
}

### Index a couple of documents
POST http://localhost:9200/demo-semantic/_doc/1
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

{
  "text": "Elasticsearch helps you build search and AI applications."
}

### Index a couple of documents
POST http://localhost:9200/demo-semantic/_doc/2
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

{
  "text": "Kibana is used to visualize and explore data."
}

### Refresh
POST http://localhost:9200/demo-semantic/_refresh
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

### Run semantic search
GET http://localhost:9200/demo-semantic/_search
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

{
  "query": {
    "match": {
      "text": "tools for AI-powered search"
    }
  }
}

### Cat nodes
GET http://localhost:9200/_cat/nodes?v&h=ip,heap.percent,ram.percent,cpu,disk.total,disk.used,disk.avail,dup,load_1m,node.role,master,name
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

### Get node settings
GET http://localhost:9200/_nodes/settings?flat_settings=true&filter_path=nodes.*.name,nodes.*.roles,nodes.*.settings.path*,nodes.*.settings.data_streams*,nodes.*.settings.stateless*
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

### Get shards
GET http://localhost:9200/_cat/shards?v=true
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk

### Get ML stats
GET http://localhost:9200/_ml/trained_models/_stats
Content-Type: application/json
Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk
