# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle ironbank bumps
    policy: ghcr.io/elastic/oblt-updatecli-policies/ironbank/templates:1.0.1@sha256:3da3235c59860414679bb358a135f7ea8bec91fc7e045b999b3ec9d950161372
    values:
      - .github/updatecli/values.d/scm.yml
      - .github/updatecli/values.d/ironbank.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.11.1@sha256:de145eea3f42312f4d1fdedb562adc36adcd54d7568f230ae71f931cc5288321
    values:
      - .github/updatecli/values.d/scm.yml
      - .github/updatecli/values.d/updatecli-compose.yml
