config:
  trigger-phrase: '.*run\W+elasticsearch-ci/bwc.*'
  skip-labels:
    - ">test-mute"
    - "test-full-bwc"
steps:
  - group: bwc-snapshots
    steps:
      - label: "{{matrix.BWC_VERSION}} / Part 1 / bwc-snapshots"
        key: "bwc-snapshots-part1"
        command: .ci/scripts/run-gradle.sh -Dignore.tests.seed v{{matrix.BWC_VERSION}}#bwcTestPart1
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
      - label: "{{matrix.BWC_VERSION}} / Part 2 / bwc-snapshots"
        key: "bwc-snapshots-part2"
        command: .ci/scripts/run-gradle.sh -Dignore.tests.seed v{{matrix.BWC_VERSION}}#bwcTestPart2
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
      - label: "{{matrix.BWC_VERSION}} / Part 3 / bwc-snapshots"
        key: "bwc-snapshots-part3"
        command: .ci/scripts/run-gradle.sh -Dignore.tests.seed v{{matrix.BWC_VERSION}}#bwcTestPart3
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
      - label: "{{matrix.BWC_VERSION}} / Part 4 / bwc-snapshots"
        key: "bwc-snapshots-part4"
        command: .ci/scripts/run-gradle.sh -Dignore.tests.seed v{{matrix.BWC_VERSION}}#bwcTestPart5
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
      - label: "{{matrix.BWC_VERSION}} / Part 5 / bwc-snapshots"
        key: "bwc-snapshots-part5"
        command: .ci/scripts/run-gradle.sh -Dignore.tests.seed v{{matrix.BWC_VERSION}}#bwcTestPart5
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
