config:
  allow-labels: test-windows
steps:
  - group: bwc-snapshots-windows
    steps:
      - label: "{{matrix.BWC_VERSION}} / bwc-snapshots-windows"
        key: "bwc-snapshots-windows"
        command: .\.buildkite\scripts\run-script.ps1 bash .buildkite/scripts/windows-run-gradle.sh
        env:
          GRADLE_TASK: "v{{matrix.BWC_VERSION}}#bwcTest"
        timeout_in_minutes: 300
        matrix:
          setup:
            BWC_VERSION: $SNAPSHOT_BWC_VERSIONS
        agents:
          provider: gcp
          image: family/elasticsearch-windows-2022
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
