steps:
  - label: eql-correctness
    command: .buildkite/scripts/eql-correctness.sh
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
