config:
  allow-labels: TODO-remove-me

steps:
  - group: "flakiness-detection"
    steps:
      - label: "detect changed tests"
        command: |
          npm install -g bun@1.3.13
          bun .buildkite/scripts/flakiness-detection/entrypoints/pr.ts
        timeout_in_minutes: 10
        soft_fail: true
