config:
  allow-labels: test-gpu
  skip-labels:
    - ">test-mute"
steps:
  - group: gpu-tests
    steps:
      - label: "{{matrix.GRADLE_TASK}} / gpu-tests"
        key: "packaging-tests-unix"
        command: .buildkite/scripts/cuvs-snapshot/run-gradle.sh -Dbwc.checkout.align=true -Dorg.elasticsearch.build.cache.push=true -Dignore.tests.seed -Dscan.capture-file-fingerprints {{matrix.GRADLE_TASK}}
        timeout_in_minutes: 300
        agents:
          provider: aws
          imagePrefix: elasticsearch-aws-ubuntu-2404-nvidia
          instanceType: g6.8xlarge
          diskSizeGb: 350
          diskType: gp3
          diskName: /dev/sda1
        env:
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
        matrix:
          setup:
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - checkPart4
              - checkPart5
              - checkPart6
