config:
  allow-labels: "test-arm"
steps:
  - label: native-vec-arm
    command: .ci/scripts/run-gradle.sh :libs:simdvec:check
    if_changed:
      include:
        - "libs/simdvec/native/**"
        - "build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/nativelibs/**"
        - "libs/native/libraries/build.gradle"
    env:
      VEC_NATIVE_BUILD: docker
      USE_PROD_DOCKER_CREDENTIALS: "true"
    timeout_in_minutes: 10
    agents:
      provider: aws
      imagePrefix: elasticsearch-ubuntu-2404-aarch64
      instanceType: m6g.8xlarge
      diskSizeGb: 350
      diskType: gp3
      diskName: /dev/sda1
