config:
  allow-labels: ":Delivery/Packaging"
steps:
  - group: packaging-tests-windows
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-windows"
        key: "packaging-tests-windows"
        command: .\.buildkite\scripts\run-script.ps1 .\.ci\scripts\packaging-test.ps1 -GradleTasks destructiveDistroTest.{{matrix.PACKAGING_TASK}}
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - windows-2022
              - windows-2025
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
