config:
  allow-labels: ":Delivery/Packaging"
steps:
  - group: packaging-tests-upgrade
    steps:
      - label: "{{matrix.image}} / $BWC_VERSION / packaging-tests-upgrade"
        key: "packaging-tests-upgrade:$BWC_VERSION_SNAKE"
        command: ./.ci/scripts/packaging-test.sh destructiveDistroUpgradeTest.v$BWC_VERSION
        timeout_in_minutes: 300
        bwc_template: true
        matrix:
          setup:
            image:
              - rocky-8
              - ubuntu-2404
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          diskSizeGb: 250
          buildDirectory: /dev/shm/bk
          preemptible: true
          spotZones: 'asia-south2-a,asia-south2-b,asia-south2-c,europe-west2-a,europe-west2-b,europe-west2-c,northamerica-northeast2-b,northamerica-northeast2-c,southamerica-east1-a,southamerica-east1-b,southamerica-east1-c'
        env:
          BWC_VERSION: $BWC_VERSION
