config:
  allow-labels: ":Delivery/Packaging"
steps:
  - group: packaging-tests-unix
    steps:
      - label: "{{matrix.image}} / docker / packaging-tests-unix"
        key: "packaging-tests-unix-docker"
        command: ./.ci/scripts/packaging-test.sh destructiveDistroTest.docker
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - centos-7
              - debian-10
              - debian-11
              - opensuse-leap-15
              - oraclelinux-7
              - oraclelinux-8
              - sles-12
              - sles-15
              - ubuntu-1804
              - ubuntu-2004
              - ubuntu-2204
              - rocky-8
              - rocky-9
              - rhel-7
              - rhel-8
              - rhel-9
              - almalinux-8
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          diskSizeGb: 350
          machineType: custom-16-32768
      - label: "{{matrix.image}} / packages / packaging-tests-unix"
        key: "packaging-tests-unix-packages"
        command: ./.ci/scripts/packaging-test.sh destructiveDistroTest.packages
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - centos-7
              - debian-10
              - debian-11
              - opensuse-leap-15
              - oraclelinux-7
              - oraclelinux-8
              - sles-12
              - sles-15
              - ubuntu-1804
              - ubuntu-2004
              - ubuntu-2204
              - rocky-8
              - rocky-9
              - rhel-7
              - rhel-8
              - rhel-9
              - almalinux-8
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          diskSizeGb: 350
          machineType: custom-16-32768
      - label: "{{matrix.image}} / archives / packaging-tests-unix"
        key: "packaging-tests-unix-archives"
        command: ./.ci/scripts/packaging-test.sh destructiveDistroTest.archives
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - centos-7
              - debian-10
              - debian-11
              - opensuse-leap-15
              - oraclelinux-7
              - oraclelinux-8
              - sles-12
              - sles-15
              - ubuntu-1804
              - ubuntu-2004
              - ubuntu-2204
              - rocky-8
              - rocky-9
              - rhel-7
              - rhel-8
              - rhel-9
              - almalinux-8
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          diskSizeGb: 350
          machineType: custom-16-32768
