steps:
  - label: part-3
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed checkPart3
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n4-standard-32
      diskType: hyperdisk-balanced
      buildDirectory: /dev/shm/bk
      preemptible: false
      spotZones: us-east1-b,us-east1-c,us-east1-d,us-central1-a,us-central1-b,us-central1-c,us-central1-f,us-west1-a,us-west1-b
