config:
  allow-labels: "test-arm"
steps:
  - label: part-6-arm
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed checkPart6
    timeout_in_minutes: 300
    agents:
      provider: aws
      imagePrefix: elasticsearch-ubuntu-2004-aarch64
      instanceType: m6g.8xlarge
      diskSizeGb: 350
      diskType: gp3
      diskName: /dev/sda1
