config:
  allow-labels:
    - Team:Security
    - test-fips
steps:
  - label: part-4-fips
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed -Dtests.fips.enabled=true checkPart4
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n1-standard-32
      buildDirectory: /dev/shm/bk
