steps:
  - label: part-2
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed -Dtests.jvm.argline="-Des.entitlements.enabled=false" checkPart2
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
