config:
  allow-labels:
    - test-fips
steps:
  - label: part-3-fips
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed -Dtests.fips.enabled=true -Dtests.fips.mode=140-2 checkPart3
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: e2-custom-32-98304
      diskType: pd-ssd
      buildDirectory: /dev/shm/bk
