config:
  allow-labels: "test-windows"
steps:
  - label: part-3-windows
    command: .\.buildkite\scripts\run-script.ps1 bash .buildkite/scripts/windows-run-gradle.sh
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
    env:
      GRADLE_TASK: checkPart3
