# This pipeline detects regressions in PromQL query coverage.

config:
  allow-labels: ":StorageEngine/PromQL"
  trigger-phrase: '.*run\W+elasticsearch-ci/promql-cov-bench.*'
steps:
  - label: "promql-cov setup"
    key: promql-cov-setup
    command: .buildkite/scripts/promql-cov.sh setup
    timeout_in_minutes: 10
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n1-standard-2
      buildDirectory: /dev/shm/bk
