config:
  allow-labels: test-release
steps:
  - group: release-tests
    steps:
      - label: "{{matrix.CHECK_TASK}} / release-tests"
        key: "packaging-tests-unix"
        command: .buildkite/scripts/release-tests.sh {{matrix.CHECK_TASK}}
        timeout_in_minutes: 120
        matrix:
          setup:
            CHECK_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - checkPart4
              - checkPart5
              - checkPart6
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          diskSizeGb: 350
          machineType: n4-standard-32
          diskType: hyperdisk-balanced
          preemptible: true
          spotZones: 'asia-south2-a,asia-south2-b,asia-south2-c,europe-west2-a,europe-west2-b,europe-west2-c,northamerica-northeast2-b,northamerica-northeast2-c,southamerica-east1-a,southamerica-east1-b,southamerica-east1-c'
