config:
  auto-retry: false
steps:
  - label: "windows-2025 / repro keystore CNF (#147204)"
    command: |
      .\.buildkite\scripts\run-script.ps1 bash .buildkite/scripts/windows-run-gradle.sh
    timeout_in_minutes: 60
    agents:
      provider: gcp
      image: family/elasticsearch-windows-2025
      machineType: n1-standard-16
      diskType: pd-ssd
      diskSizeGb: 350
    env:
      GRADLE_TASK: >-
        :x-pack:qa:reindex-tests-with-security:yamlRestTest
        :x-pack:qa:core-rest-tests-with-security:yamlRestTest
        --continue
