steps:
  - label: validate-changelogs
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed validateChangelogs
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
