/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.mixed;

import com.carrotsearch.randomizedtesting.annotations.ThreadLeakFilters;

import org.apache.http.HttpHost;
import org.elasticsearch.Version;
import org.elasticsearch.client.Request;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.core.IOUtils;
import org.elasticsearch.test.TestClustersThreadFilter;
import org.elasticsearch.test.cluster.ElasticsearchCluster;
import org.elasticsearch.xpack.esql.CsvSpecReader.CsvTestCase;
import org.elasticsearch.xpack.esql.CsvTestUtils;
import org.elasticsearch.xpack.esql.action.EsqlCapabilities;
import org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.ClassRule;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.elasticsearch.xpack.esql.CsvTestUtils.isEnabled;
import static org.elasticsearch.xpack.esql.action.EsqlCapabilities.Cap.JOIN_LOOKUP_V12;
import static org.elasticsearch.xpack.esql.qa.rest.RestEsqlTestCase.hasCapabilities;
import static org.hamcrest.Matchers.equalTo;

/**
 * Abstract base for per-csv-spec-file test classes generated by the Gradle build.
 * The cluster is shared across all generated subclasses via {@code shared(true)} in
 * {@link Clusters#mixedVersionCluster}, so it starts once for the whole JVM and data
 * is ingested exactly once (guarded by the {@code INGEST} lock in
 * {@link EsqlSpecTestCase}).
 */
// Each generated class covers one csv-spec file and should complete in a few minutes at most
@ThreadLeakFilters(filters = TestClustersThreadFilter.class)
public abstract class AbstractMixedClusterEsqlSpecIT extends EsqlSpecTestCase {
    private static final Path CSV_DATA_PATH = CsvTestUtils.createCsvDataDirectory();

    @ClassRule
    public static ElasticsearchCluster cluster = Clusters.mixedVersionCluster(CSV_DATA_PATH, true);

    private static boolean coordinatorVersionChecked = false;

    /**
     * Checks that the pinned coordinator really is a current-version node. Node 1 is current only because
     * {@link Clusters#mixedVersionCluster} declares its nodes as old, current, old, current, and that
     * ordering lives in a file shared with other suites. Reordering those {@code withNode} calls would
     * otherwise leave this suite quietly testing an old coordinator, duplicating
     * {@link AbstractMixedClusterEsqlOldCoordinatorSpecIT} while every test still passed.
     * <p>
     * Runs once per JVM, and the flag is set before the assertion so a broken invariant surfaces once
     * rather than repeating for every test sharing the cluster. Skipped for detached builds, where a node
     * built from a git ref reports the version it will become rather than what it contains.
     */
    @Before
    public void assertCoordinatorIsCurrentNode() throws IOException {
        if (coordinatorVersionChecked) {
            return;
        }
        coordinatorVersionChecked = true;
        Map<String, Object> info = entityAsMap(client().performRequest(new Request("GET", "/")));
        String coordinatorVersion = (String) ((Map<?, ?>) info.get("version")).get("number");
        logger.info("random-coordinator suite pinned to node [{}] version [{}]", info.get("name"), coordinatorVersion);
        if (System.getProperty("tests.bwc.refspec.main") != null) {
            return;
        }
        assertThat(
            "coordinator must be a current-version node; check the withNode order in Clusters.mixedVersionCluster",
            coordinatorVersion,
            equalTo(Version.CURRENT.toString())
        );
    }

    @Override
    protected Path getCsvDataPath() {
        return CSV_DATA_PATH;
    }

    /**
     * Pins the coordinator to node 1, which runs the current version, so this suite deterministically
     * exercises a new coordinator; {@link AbstractMixedClusterEsqlOldCoordinatorSpecIT} pins node 0 for
     * the old side. Between them both coordinator versions are covered on every run. Returning all four
     * addresses instead would leave each side to {@code RestClient}'s round-robin rotation, so for a given
     * seed a test could hit the same coordinator version every time and never exercise the other.
     * <p>
     * Node 1 is a current-version node only because {@link Clusters#mixedVersionCluster} declares its nodes
     * as old, current, old, current.
     */
    @Override
    protected String getTestRestCluster() {
        return cluster.getHttpAddress(1);
    }

    static final Version bwcVersion = Version.fromString(
        System.getProperty("tests.old_cluster_version") != null
            ? System.getProperty("tests.old_cluster_version").replace("-SNAPSHOT", "")
            : null
    );
    private static RestClient oldNodeClient = null;

    protected AbstractMixedClusterEsqlSpecIT(
        String fileName,
        String groupName,
        String testName,
        Integer lineNumber,
        CsvTestCase testCase,
        String instructions
    ) {
        super(fileName, groupName, testName, lineNumber, testCase, instructions);
    }

    @AfterClass
    public static void cleanUp() throws IOException {
        IOUtils.close(oldNodeClient);
        oldNodeClient = null;
    }

    // Slice indexing is unreleased and renamed its request parameter (`_slice` -> `slice`), so the older bwc node
    // cannot ingest data via the current parameter. Treat slice as unsupported whenever an older node is present.
    private static boolean slicesSupportedOnBwcNode() {
        return bwcVersion == null || bwcVersion.before(Version.CURRENT) == false;
    }

    @Override
    protected boolean clusterHasCapability(EsqlCapabilities.Cap capability) {
        // Skip loading the slice dataset in a mixed-version cluster: the older node cannot ingest it.
        if (capability == EsqlCapabilities.Cap.METADATA_SLICE && slicesSupportedOnBwcNode() == false) {
            return false;
        }
        return super.clusterHasCapability(capability);
    }

    @Override
    protected void shouldSkipTest(String testName) throws IOException {
        super.shouldSkipTest(testName);
        // Slice tests need the slice dataset, which is not loaded against an older node (see clusterHasCapability).
        CsvTestUtils.assumeTrueLogging(
            "Slice indexing is unreleased and unsupported on the older mixed-cluster node",
            slicesSupportedOnBwcNode()
                || testCase.requiredCapabilities.contains(EsqlCapabilities.Cap.METADATA_SLICE.capabilityName()) == false
        );
        CsvTestUtils.assumeTrueLogging(
            "Old mixed-cluster node does not support required capabilities for " + testName,
            testCase.requiredCapabilities.isEmpty() || hasCapabilities(oldNodeClient(), testCase.requiredCapabilities)
        );
        // This suite pins the coordinator to a current-version node, so a directive asserting that the coordinator
        // is missing a capability can never hold here. AbstractMixedClusterEsqlOldCoordinatorSpecIT pins the other
        // side and also skips these; see its shouldSkipTest for why.
        CsvTestUtils.assumeTrueLogging(
            "Mixed-cluster tests don't support local cluster capability requirements",
            testCase.missingCapabilitiesLocalCluster.isEmpty()
        );
        CsvTestUtils.assumeTrueLogging(
            "Mixed-cluster tests don't support remote cluster capability requirements",
            testCase.missingCapabilitiesRemoteCluster.isEmpty()
        );
        assumeTrue("Test " + testName + " is skipped on " + bwcVersion, isEnabled(testName, instructions, bwcVersion));
    }

    private RestClient oldNodeClient() throws IOException {
        if (oldNodeClient == null) {
            oldNodeClient = buildClient(restAdminSettings(), new HttpHost[] { HttpHost.create("http://" + cluster.getHttpAddress(0)) });
        }
        return oldNodeClient;
    }

    @Override
    protected boolean enableRoundingDoubleValuesOnAsserting() {
        return true;
    }

    @Override
    protected boolean supportsSemanticTextInference() {
        return false;
    }

    @Override
    protected boolean supportsInferenceTestServiceOnLocalCluster() {
        return false;
    }

    @Override
    protected boolean supportsIndexModeLookup() {
        return hasCapabilities(adminClient(), List.of(JOIN_LOOKUP_V12.capabilityName()));
    }

    @Override
    protected boolean supportsSourceFieldMapping() {
        return false;
    }

    @Override
    protected boolean deduplicateExactWarnings() {
        /*
         * In ESQL's main tests we shouldn't have to deduplicate but in
         * serverless, where we reuse this test case exactly with *slightly*
         * different configuration, we must deduplicate. So we do it here.
         * It's a bit of a loss of precision, but that's ok.
         */
        return true;
    }
}
