/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.mixed;

import com.carrotsearch.randomizedtesting.annotations.ThreadLeakFilters;

import org.apache.http.HttpHost;
import org.elasticsearch.Version;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.core.IOUtils;
import org.elasticsearch.test.TestClustersThreadFilter;
import org.elasticsearch.test.cluster.ElasticsearchCluster;
import org.elasticsearch.xpack.esql.CsvSpecReader.CsvTestCase;
import org.elasticsearch.xpack.esql.CsvTestUtils;
import org.elasticsearch.xpack.esql.action.EsqlCapabilities;
import org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase;
import org.junit.AfterClass;
import org.junit.ClassRule;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import static org.elasticsearch.xpack.esql.CsvTestUtils.isEnabled;
import static org.elasticsearch.xpack.esql.action.EsqlCapabilities.Cap.JOIN_LOOKUP_V12;
import static org.elasticsearch.xpack.esql.qa.rest.RestEsqlTestCase.hasCapabilities;

/**
 * Abstract base for per-csv-spec-file test classes generated by the Gradle build.
 * The cluster is shared across all generated subclasses via {@code shared(true)} in
 * {@link Clusters#mixedVersionCluster}, so it starts once for the whole JVM and data
 * is ingested exactly once (guarded by the {@code INGEST} lock in
 * {@link EsqlSpecTestCase}).
 */
// Each generated class covers one csv-spec file and should complete in a few minutes at most
@ThreadLeakFilters(filters = TestClustersThreadFilter.class)
public abstract class AbstractMixedClusterEsqlSpecIT extends EsqlSpecTestCase {
    private static final Path CSV_DATA_PATH = CsvTestUtils.createCsvDataDirectory();

    @ClassRule
    public static ElasticsearchCluster cluster = Clusters.mixedVersionCluster(CSV_DATA_PATH, true);

    @Override
    protected Path getCsvDataPath() {
        return CSV_DATA_PATH;
    }

    @Override
    protected String getTestRestCluster() {
        return cluster.getHttpAddresses();
    }

    static final Version bwcVersion = Version.fromString(
        System.getProperty("tests.old_cluster_version") != null
            ? System.getProperty("tests.old_cluster_version").replace("-SNAPSHOT", "")
            : null
    );
    private static RestClient oldNodeClient = null;

    protected AbstractMixedClusterEsqlSpecIT(
        String fileName,
        String groupName,
        String testName,
        Integer lineNumber,
        CsvTestCase testCase,
        String instructions
    ) {
        super(fileName, groupName, testName, lineNumber, testCase, instructions);
    }

    @AfterClass
    public static void cleanUp() throws IOException {
        IOUtils.close(oldNodeClient);
        oldNodeClient = null;
    }

    // Slice indexing is unreleased and renamed its request parameter (`_slice` -> `slice`), so the older bwc node
    // cannot ingest data via the current parameter. Treat slice as unsupported whenever an older node is present.
    private static boolean slicesSupportedOnBwcNode() {
        return bwcVersion == null || bwcVersion.before(Version.CURRENT) == false;
    }

    @Override
    protected boolean clusterHasCapability(EsqlCapabilities.Cap capability) {
        // Skip loading the slice dataset in a mixed-version cluster: the older node cannot ingest it.
        if (capability == EsqlCapabilities.Cap.METADATA_SLICE && slicesSupportedOnBwcNode() == false) {
            return false;
        }
        return super.clusterHasCapability(capability);
    }

    @Override
    protected void shouldSkipTest(String testName) throws IOException {
        super.shouldSkipTest(testName);
        // Slice tests need the slice dataset, which is not loaded against an older node (see clusterHasCapability).
        CsvTestUtils.assumeTrueLogging(
            "Slice indexing is unreleased and unsupported on the older mixed-cluster node",
            slicesSupportedOnBwcNode()
                || testCase.requiredCapabilities.contains(EsqlCapabilities.Cap.METADATA_SLICE.capabilityName()) == false
        );
        CsvTestUtils.assumeTrueLogging(
            "Old mixed-cluster node does not support required capabilities for " + testName,
            testCase.requiredCapabilities.isEmpty() || hasCapabilities(oldNodeClient(), testCase.requiredCapabilities)
        );
        // The request is sent to a random node, so at this stage it's undetermined which node is the coordinator or
        // data node. This means a real capability check here (asserting the capability is genuinely absent, the way
        // the other suites do) would be unsafe rather than just unnecessary: a real 2-old+2-new cluster would pass
        // such a check, but the query itself could still land on either an old or a new coordinator at random, so a
        // test asserting deterministic old-coordinator behavior would only be correct about half the time. Supporting
        // this properly needs the query itself pinned to a specific-version node, not just the capability gate.
        CsvTestUtils.assumeTrueLogging(
            "Mixed-cluster tests don't support local cluster capability requirements",
            testCase.missingCapabilitiesLocalCluster.isEmpty()
        );
        CsvTestUtils.assumeTrueLogging(
            "Mixed-cluster tests don't support remote cluster capability requirements",
            testCase.missingCapabilitiesRemoteCluster.isEmpty()
        );
        assumeTrue("Test " + testName + " is skipped on " + bwcVersion, isEnabled(testName, instructions, bwcVersion));
    }

    private RestClient oldNodeClient() throws IOException {
        if (oldNodeClient == null) {
            oldNodeClient = buildClient(restAdminSettings(), new HttpHost[] { HttpHost.create("http://" + cluster.getHttpAddress(0)) });
        }
        return oldNodeClient;
    }

    @Override
    protected boolean enableRoundingDoubleValuesOnAsserting() {
        return true;
    }

    @Override
    protected boolean supportsSemanticTextInference() {
        return false;
    }

    @Override
    protected boolean supportsInferenceTestServiceOnLocalCluster() {
        return false;
    }

    @Override
    protected boolean supportsIndexModeLookup() {
        return hasCapabilities(adminClient(), List.of(JOIN_LOOKUP_V12.capabilityName()));
    }

    @Override
    protected boolean supportsSourceFieldMapping() {
        return false;
    }

    @Override
    protected boolean deduplicateExactWarnings() {
        /*
         * In ESQL's main tests we shouldn't have to deduplicate but in
         * serverless, where we reuse this test case exactly with *slightly*
         * different configuration, we must deduplicate. So we do it here.
         * It's a bit of a loss of precision, but that's ok.
         */
        return true;
    }
}
