[[esql-version]]
=== {esql} language versions

++++
<titleabbrev>Language versions</titleabbrev>
++++

[discrete]
[[esql-versions-released]]
==== Released versions

{esql} is released at version `2024.04.01.🚀`.
This is the only available version for now.

[discrete]
[[esql-versions-explanation]]
=== How versions work

{esql} versions are separate from Elasticsearch versions.
Their goal is to make sure that queries that were once written
remain valid even as Elasticsearch and {esql} evolve.

For instance, the following query

[source,console]
----
POST /_query?format=txt
{
  "version": "2024.04.01.🚀",
  "query": """
    FROM library
    | EVAL release_month = DATE_TRUNC(1 month, release_date)
    | KEEP release_month
    | SORT release_month ASC
    | LIMIT 3
  """
}
----
// TEST[setup:library]

will remain valid, even if a future version of {esql} introduces
syntax changes or changes how the used commands or functions work.

A released {esql} version will not receive breaking changes and
will remain supported until it is deprecated.
Already released {esql} versions will still profit from new features,
bug fixes and performance improvements as long as those do not
require breaking changes.
