[[modules-threadpool]]
== Thread Pool

A node holds several thread pools in order to improve how threads memory consumption
are managed within a node. Many of these pools also have queues associated with them,
which allow pending requests to be held instead
of discarded.


There are several thread pools, but the important ones include:

`index`::
    For index/delete operations. Defaults to `fixed`
    with a size of `# of available processors`,
    queue_size of `200`.

`search`::
    For count/search operations. Defaults to `fixed`
    with a size of `int((# of available_processors * 3) / 2) + 1`,
    queue_size of `1000`.

`suggest`::
    For suggest operations. Defaults to `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`get`::
    For get operations. Defaults to `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`bulk`::
    For bulk operations. Defaults to `fixed`
    with a size of `# of available processors`,
    queue_size of `50`.

`percolate`::
    For percolate operations. Defaults to `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`snapshot`::
    For snapshot/restore operations. Defaults to `scaling` with a
    keep-alive of `5m` and a size of `min(5, (# of available processors)/2)`.

`warmer`::
    For segment warm-up operations. Defaults to `scaling` with a
    keep-alive of `5m` and a size of `min(5, (# of available processors)/2)`.

`refresh`::
    For refresh operations. Defaults to `scaling` with a
    keep-alive of `5m` and a size of `min(10, (# of available processors)/2)`.

`listener`::
    Mainly for java client executing of action when listener threaded is set to true.
    Default size of `(# of available processors)/2`, max at 10.

Changing a specific thread pool can be done by setting its type and
specific type parameters, for example, changing the `index` thread pool
to have more threads:

[source,js]
--------------------------------------------------
threadpool:
    index:
        type: fixed
        size: 30
--------------------------------------------------

NOTE: you can update threadpool settings live using
      <<cluster-update-settings>>.


[float]
[[types]]
=== Thread pool types

The following are the types of thread pools that can be used and their
respective parameters:

[float]
==== `cache`

The `cache` thread pool is an unbounded thread pool that will spawn a
thread if there are pending requests. Here is an example of how to set
it:

[source,js]
--------------------------------------------------
threadpool:
    index:
        type: cached
--------------------------------------------------

[float]
==== `fixed`

The `fixed` thread pool holds a fixed size of threads to handle the
requests with a queue (optionally bounded) for pending requests that
have no threads to service them.

The `size` parameter controls the number of threads, and defaults to the
number of cores times 5.

The `queue_size` allows to control the size of the queue of pending
requests that have no threads to execute them. By default, it is set to
`-1` which means its unbounded. When a request comes in and the queue is
full, it will abort the request.

[source,js]
--------------------------------------------------
threadpool:
    index:
        type: fixed
        size: 30
        queue_size: 1000
--------------------------------------------------

[float]
==== `scaling`

The `scaling` thread pool holds a dynamic number of threads. This number is
proportional to the workload and varies between 1 and the value of the
`size` parameter.

The `keep_alive` parameter determines how long a thread should be kept
around in the thread pool without it doing any work.

[source,js]
--------------------------------------------------
threadpool:
    warmer:
        type: scaling
        size: 8
        keep_alive: 2m
--------------------------------------------------

[float]
[[processors]]
=== Processors setting
The number of processors is automatically detected, and the thread pool
settings are automatically set based on it. Sometimes, the number of processors
are wrongly detected, in such cases, the number of processors can be
explicitly set using the `processors` setting.

In order to check the number of processors detected, use the nodes info
API with the `os` flag.
