/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.foreign.processor;

import org.elasticsearch.foreign.processor.model.NativeType;

import java.lang.classfile.CodeBuilder;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;

/**
 * Shared class descriptors and bytecode helpers used by all class writers in this package.
 */
final class ClassWriterUtil {

    // Standard Java types
    static final ClassDesc CD_void = ClassDesc.ofDescriptor("V");
    static final ClassDesc CD_Object = ClassDesc.of("java.lang.Object");
    static final ClassDesc CD_String = ClassDesc.of("java.lang.String");
    static final ClassDesc CD_long = ClassDesc.ofDescriptor("J");
    static final ClassDesc CD_boolean = ClassDesc.ofDescriptor("Z");

    // java.lang.foreign types
    static final ClassDesc CD_MemoryLayout = ClassDesc.of("java.lang.foreign.MemoryLayout");
    static final ClassDesc CD_MemoryLayoutArray = ClassDesc.ofDescriptor("[Ljava/lang/foreign/MemoryLayout;");
    static final ClassDesc CD_MemorySegment = ClassDesc.of("java.lang.foreign.MemorySegment");
    static final ClassDesc CD_StructLayout = ClassDesc.of("java.lang.foreign.StructLayout");
    static final ClassDesc CD_PaddingLayout = ClassDesc.of("java.lang.foreign.PaddingLayout");
    static final ClassDesc CD_MemoryLayoutPathElement = ClassDesc.of("java.lang.foreign.MemoryLayout$PathElement");
    static final ClassDesc CD_Arena = ClassDesc.of("java.lang.foreign.Arena");
    static final ClassDesc CD_VarHandle = ClassDesc.of("java.lang.invoke.VarHandle");
    private static final ClassDesc CD_ValueLayout = ClassDesc.of("java.lang.foreign.ValueLayout");

    // org.elasticsearch.foreign types
    static final ClassDesc CD_MemorySegmentAdapter = ClassDesc.of(org.elasticsearch.foreign.adapter.MemorySegmentAdapter.class.getName());
    static final ClassDesc CD_ArenaAdapter = ClassDesc.of(org.elasticsearch.foreign.adapter.ArenaAdapter.class.getName());
    static final ClassDesc CD_Addressable = ClassDesc.of(org.elasticsearch.foreign.Addressable.class.getName());

    // Widely-used java.lang.foreign method type descriptors
    static final MethodTypeDesc MTD_structLayout = MethodTypeDesc.of(CD_StructLayout, CD_MemoryLayoutArray);
    static final MethodTypeDesc MTD_groupElement = MethodTypeDesc.of(CD_MemoryLayoutPathElement, CD_String);
    static final MethodTypeDesc MTD_varHandleWithoutOffset = MethodTypeDesc.of(CD_VarHandle, CD_MemoryLayout, CD_MemoryLayoutPathElement);
    static final MethodTypeDesc MTD_Arena_ofAuto = MethodTypeDesc.of(CD_Arena);
    static final MethodTypeDesc MTD_allocate_layout = MethodTypeDesc.of(CD_MemorySegment, CD_MemoryLayout);
    static final MethodTypeDesc MTD_byteSize = MethodTypeDesc.of(CD_long);
    static final MethodTypeDesc MTD_asSlice = MethodTypeDesc.of(CD_MemorySegment, CD_long, CD_long);
    // ArenaAdapter.allocate(Arena, MemoryLayout, int) — bridges the JDK 21 -> JDK 22+ Arena API split.
    // JDK 21 has Arena.allocateArray(MemoryLayout, long); JDK 22+ has Arena.allocate(MemoryLayout, long).
    // The adapter handles the version delta so generated bytecode calls one stable signature.
    static final MethodTypeDesc MTD_ArenaAdapter_allocate = MethodTypeDesc.of(
        CD_MemorySegment,
        CD_Arena,
        CD_MemoryLayout,
        ClassDesc.ofDescriptor("I")
    );

    /**
     * Converts a Java release number (e.g. 21) to the corresponding class file major version
     * (e.g. 65) for use with {@link java.lang.classfile.ClassBuilder#withVersion}.
     */
    static int classFileVersion(int javaRelease) {
        return 44 + javaRelease;
    }

    private ClassWriterUtil() {}

    /**
     * Number of consecutive JVM local-variable slots a value of this type occupies: 2 for
     * {@code long}/{@code double} (JVMS §2.6.1), 1 for everything else.
     */
    static int slotWidth(NativeType type) {
        return (type == NativeType.LONG || type == NativeType.DOUBLE) ? 2 : 1;
    }

    /** Maps a primitive {@link NativeType} to its JVM {@link ClassDesc}. Throws on non-primitive types. */
    static ClassDesc primitiveClassDesc(NativeType type) {
        return switch (type) {
            case INT -> ClassDesc.ofDescriptor("I");
            case LONG -> ClassDesc.ofDescriptor("J");
            case SHORT -> ClassDesc.ofDescriptor("S");
            case BYTE -> ClassDesc.ofDescriptor("B");
            case BOOLEAN -> ClassDesc.ofDescriptor("Z");
            case FLOAT -> ClassDesc.ofDescriptor("F");
            case DOUBLE -> ClassDesc.ofDescriptor("D");
            case VOID, ADDRESS, STRING, ADDRESSABLE -> throw new AssertionError("not a primitive type: " + type);
        };
    }

    /** Pushes the {@code ValueLayout} constant for the given type onto the operand stack. */
    static void emitValueLayout(CodeBuilder cb, NativeType type) {
        record VLField(String name, ClassDesc type) {}
        VLField vl = switch (type) {
            case INT -> new VLField("JAVA_INT", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfInt;"));
            case LONG -> new VLField("JAVA_LONG", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfLong;"));
            case SHORT -> new VLField("JAVA_SHORT", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfShort;"));
            case BYTE -> new VLField("JAVA_BYTE", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfByte;"));
            case BOOLEAN -> new VLField("JAVA_BOOLEAN", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfBoolean;"));
            case FLOAT -> new VLField("JAVA_FLOAT", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfFloat;"));
            case DOUBLE -> new VLField("JAVA_DOUBLE", ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfDouble;"));
            case ADDRESS, STRING -> new VLField("ADDRESS", ClassDesc.ofDescriptor("Ljava/lang/foreign/AddressLayout;"));
            case ADDRESSABLE -> throw new AssertionError("ADDRESSABLE resolves through layoutType() before emitValueLayout");
            case VOID -> throw new AssertionError("void has no ValueLayout");
        };
        cb.getstatic(CD_ValueLayout, vl.name(), vl.type());
    }

    /** Returns the Java {@link ClassDesc} for a struct field's type. */
    static ClassDesc fieldClassDesc(NativeType type) {
        return switch (type) {
            case ADDRESS, STRING -> CD_MemorySegment;
            case VOID -> throw new AssertionError("void cannot be a struct field type");
            default -> primitiveClassDesc(type);
        };
    }

    /** Returns the specific {@code ValueLayout} subtype {@link ClassDesc} for a struct field's type. */
    static ClassDesc valueLayoutClassDesc(NativeType type) {
        return switch (type) {
            case INT -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfInt;");
            case LONG -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfLong;");
            case SHORT -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfShort;");
            case BYTE -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfByte;");
            case BOOLEAN -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfBoolean;");
            case FLOAT -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfFloat;");
            case DOUBLE -> ClassDesc.ofDescriptor("Ljava/lang/foreign/ValueLayout$OfDouble;");
            case ADDRESS, STRING -> ClassDesc.ofDescriptor("Ljava/lang/foreign/AddressLayout;");
            case ADDRESSABLE -> throw new AssertionError("ADDRESSABLE cannot be a struct field type");
            case VOID -> throw new AssertionError("void cannot be a field type");
        };
    }
}
