/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.foreign.processor;

import org.elasticsearch.core.SuppressForbidden;
import org.elasticsearch.foreign.LibraryProvider;

import java.lang.classfile.ClassFile;
import java.lang.classfile.attribute.ModuleAttribute;
import java.lang.classfile.attribute.ModuleProvideInfo;
import java.lang.constant.ClassDesc;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Post-processes a compiled {@code module-info.class} to inject {@code provides} entries for the
 * service classes generated by {@link LibraryProcessor}.
 *
 * <p>The generated {@code $Provider} classes are not present in the developer's
 * {@code module-info.java} source so that IDEs (and javac in {@code -proc:only} mode) do not flag
 * unresolved type references. After compilation, this tool reads the generated
 * {@code META-INF/services/org.elasticsearch.foreign.LibraryProvider} file and adds each listed
 * provider to the module's {@code Provides} attribute. If a {@code provides
 * org.elasticsearch.foreign.LibraryProvider} entry already exists, the listed providers are merged
 * into its {@code with} list (de-duplicated, preserving order).
 *
 * <p>Usage: {@code java ModuleInfoAugmenter <module-info.class> <services-file> <output-file>}
 */
public final class ModuleInfoAugmenter {

    private static final String LIBRARY_PROVIDER_FQN = LibraryProvider.class.getName();

    @SuppressForbidden(reason = "CLI entry point: System.exit() signals abnormal termination to the calling process")
    public static void main(String[] args) throws Exception {
        if (args.length != 3) {
            System.err.println("Usage: ModuleInfoAugmenter <module-info.class> <services-file> <output-file>");
            System.exit(1);
        }
        Path moduleInfoIn = Paths.get(args[0]);
        Path servicesFile = Paths.get(args[1]);
        Path moduleInfoOut = Paths.get(args[2]);

        List<String> providerFqns = readProviders(servicesFile);
        if (providerFqns.isEmpty()) {
            // No generated providers: copy the input unchanged so downstream tasks have an output to depend on.
            Files.createDirectories(moduleInfoOut.getParent());
            Files.copy(moduleInfoIn, moduleInfoOut, StandardCopyOption.REPLACE_EXISTING);
            return;
        }

        byte[] augmented = augment(Files.readAllBytes(moduleInfoIn), providerFqns);
        Files.createDirectories(moduleInfoOut.getParent());
        Files.write(moduleInfoOut, augmented);
    }

    private static List<String> readProviders(Path servicesFile) throws java.io.IOException {
        if (Files.exists(servicesFile) == false) {
            return List.of();
        }
        List<String> providers = new ArrayList<>();
        for (String line : Files.readAllLines(servicesFile)) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() == false && trimmed.startsWith("#") == false) {
                providers.add(trimmed);
            }
        }
        return providers;
    }

    static byte[] augment(byte[] moduleInfoBytes, List<String> providerFqns) {
        ClassFile cf = ClassFile.of();
        var classModel = cf.parse(moduleInfoBytes);
        return cf.transformClass(classModel, (classBuilder, element) -> {
            if (element instanceof ModuleAttribute oldAttr) {
                classBuilder.with(augmentProvides(oldAttr, providerFqns));
            } else {
                classBuilder.with(element);
            }
        });
    }

    private static ModuleAttribute augmentProvides(ModuleAttribute oldAttr, List<String> providerFqns) {
        ClassDesc libraryProviderDesc = ClassDesc.of(LIBRARY_PROVIDER_FQN);
        List<ModuleProvideInfo> newProvides = new ArrayList<>();
        boolean merged = false;

        for (ModuleProvideInfo p : oldAttr.provides()) {
            if (p.provides().asSymbol().equals(libraryProviderDesc)) {
                newProvides.add(mergeImplementations(p, providerFqns, libraryProviderDesc));
                merged = true;
            } else {
                newProvides.add(p);
            }
        }
        if (merged == false) {
            List<ClassDesc> impls = providerFqns.stream().map(ClassDesc::of).toList();
            newProvides.add(ModuleProvideInfo.of(libraryProviderDesc, impls));
        }

        return ModuleAttribute.of(
            oldAttr.moduleName(),
            oldAttr.moduleFlagsMask(),
            oldAttr.moduleVersion().orElse(null),
            oldAttr.requires(),
            oldAttr.exports(),
            oldAttr.opens(),
            oldAttr.uses(),
            newProvides
        );
    }

    private static ModuleProvideInfo mergeImplementations(ModuleProvideInfo existing, List<String> providerFqns, ClassDesc service) {
        Set<ClassDesc> impls = new LinkedHashSet<>();
        for (var impl : existing.providesWith()) {
            impls.add(impl.asSymbol());
        }
        for (String fqn : providerFqns) {
            impls.add(ClassDesc.of(fqn));
        }
        return ModuleProvideInfo.of(service, List.copyOf(impls));
    }

    private ModuleInfoAugmenter() {}
}
