[[increase-tier-capacity]]
== Not enough nodes to allocate all shard replicas

****
AutoOps is now available!
 
AutoOps for {es} significantly simplifies cluster management with performance recommendations, resource utilization and cost insights, real-time issue detection and resolution paths. By analyzing hundreds of {es} metrics, your configuration, and usage patterns, AutoOps offers operational and monitoring insights that can substantially reduce administration time and hardware costs. AutoOps is 
https://www.elastic.co/guide/en/cloud/current/ec-autoops-regions.html[rolling out] in phases across Elastic Cloud Hosted regions and CSP. It will be automatically activated for your deployment, with no installation required. For more information, check https://www.elastic.co/guide/en/cloud/current/ec-autoops.html[Monitor with AutoOps].
****

Distributing copies of the data (index shard replicas) on different nodes can 
parallelize processing requests thus speeding up search queries. This can be 
achieved by increasing the number of replica shards up to the maximum value
(total number of nodes minus one) which also serves the purpose to protect
against hardware failure. If the index has a preferred tier, Elasticsearch will
only place the copies of the data for that index on nodes in the target tier.

If a warning is encountered with not enough nodes to allocate all shard 
replicas, you can influence this behavior by adding more nodes to the cluster
(or tier if tiers are in use), or by reducing the
<<dynamic-index-number-of-replicas,`index.number_of_replicas`>> index setting.

In order to fix this follow the next steps:

include::{es-ref-dir}/tab-widgets/troubleshooting/data/increase-tier-capacity-widget.asciidoc[]



