Vagrant.configure("2") do |config|

  config.vm.define "test.ad.elastic.local" do |config|
    config.vm.box = "elastic/ubuntu-16.04-x86_64"
  end

  config.vm.hostname = "ad.test.elastic.local"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 389, host: 61389, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 636, host: 61636, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 3268, host: 63268, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 3269, host: 63269, protocol: "tcp"

  config.vm.provision "shell", path: "src/main/resources/provision/installsmb.sh"

end
