/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

apply plugin: 'elasticsearch.internal-java-rest-test'

dependencies {
  javaRestTestImplementation project(':modules:repository-s3')
  javaRestTestImplementation project(':test:fixtures:aws-fixture-utils')
  javaRestTestImplementation project(':test:fixtures:s3-fixture')
  javaRestTestImplementation project(':test:fixtures:testcontainer-utils')
  javaRestTestImplementation project(':test:fixtures:tls-utils')
  javaRestTestImplementation project(':test:framework')
  javaRestTestRuntimeOnly "org.slf4j:slf4j-simple:${versions.slf4j}"

  clusterModules project(':modules:repository-s3')
  clusterModules project(':x-pack:plugin:deprecation')
  clusterModules project(':x-pack:plugin:ilm')
  clusterModules project(':x-pack:plugin:mapper-constant-keyword')
  clusterModules project(':x-pack:plugin:stack')
  clusterModules project(':x-pack:plugin:transform')
}
