#!/usr/bin/env bash
#
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the "Elastic License
# 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
# Public License v 1"; you may not use this file except in compliance with, at
# your election, the "Elastic License 2.0", the "GNU Affero General Public
# License v3.0 only", or the "Server Side Public License, v 1".
#

# Assembles a Darwin arm64 sysroot for cross-compiling the native libraries, using only
# open-source sources: Apple's own open-source distributions for the C headers and
# upstream LLVM for the C++ headers. No macOS SDK content is downloaded or redistributed.
#
# This script is run at image build time (see Dockerfile.cross-toolchain). Versions are pinned in
# versions.env. Requires: curl, bash, perl, python3, unifdef, ed, dpkg-deb, clang++.
#
#   ./assemble.sh /opt/darwin-sysroot
#
# The result is consumed as:
#   -nostdinc -isystem <sysroot>/usr/include/c++/v1
#             -isystem $(clang++ -print-resource-dir)/include
#             -isystem <sysroot>/usr/include
#
# That order matters: libc++ must precede the clang resource directory, or libc++'s
# <cstddef> fails to find its own <stddef.h>. The resource directory must precede
# usr/include so that clang supplies the target/builtin headers (arm_neon.h, stdarg.h).

set -euo pipefail

SYSROOT=${1:?usage: assemble.sh <output-sysroot>}
HERE=$(cd "$(dirname "$0")" && pwd)
# shellcheck disable=SC1091
source "$HERE/versions.env"

CLANGXX=${CLANGXX:-clang++-21}
TARGET=arm64-apple-macos14
GITHUB=https://github.com/apple-oss-distributions
LLVM_POOL=https://apt.llvm.org/bookworm/pool/main/l/llvm-toolchain-$LIBCXX_MAJOR

INC=$SYSROOT/usr/include
WORK=$(mktemp -d)
STAGE=$WORK/xnu-stage
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$INC" "$STAGE"

# Downloads and unpacks an Apple component, echoing the unpacked directory. GitHub archive
# tarballs are prefixed <repo>-<tag>/
fetch() {
    local repo=$1 tag=$2
    curl -fsSL -o "$WORK/$tag.tar.gz" "$GITHUB/$repo/archive/refs/tags/$tag.tar.gz"
    tar -C "$WORK" -xzf "$WORK/$tag.tar.gz"
    echo "$WORK/$repo-$tag"
}

echo "== fetching Apple open-source components =="
LIBC_SRC=$(fetch Libc "$LIBC_TAG")
XNU_SRC=$(fetch xnu "$XNU_TAG")
LIBM_SRC=$(fetch Libm "$LIBM_TAG")
LIBPTHREAD_SRC=$(fetch libpthread "$LIBPTHREAD_TAG")
LIBPLATFORM_SRC=$(fetch libplatform "$LIBPLATFORM_TAG")
LIBMALLOC_SRC=$(fetch libmalloc "$LIBMALLOC_TAG")
AVAILABILITY_SRC=$(fetch AvailabilityVersions "$AVAILABILITY_TAG")

# --- C headers -------------------------------------------------------------------------
#
# Libc, libpthread, libplatform, libmalloc and Libm are taken wholesale.
# xnu is different and is handled further down.

echo "== Libc, via Apple's own public-header installer =="
# headers.sh is authoritative: it carries the list of headers Apple publishes, strips the
# //Begin-Libc blocks, and runs unifdef to remove the internal-only regions -- so the
# result matches what the real SDK ships, without us curating anything.
( cd "$LIBC_SRC" \
    && SRCROOT="$LIBC_SRC" DSTROOT="$SYSROOT" DEPLOYMENT_LOCATION=YES \
       PLATFORM_NAME=macosx SDK_INSTALL_HEADERS_ROOT="" \
       bash xcodescripts/headers.sh ) > "$WORK/libc-headers.log" 2>&1 \
    || { echo "FAILED: Libc headers.sh"; tail -40 "$WORK/libc-headers.log"; exit 1; }
# headers.sh installs read-only (mode 444) when run as root, and also produces a
# System.framework PrivateHeaders tree that is not part of usr/include.
chmod -R u+w "$SYSROOT"
rm -rf "$SYSROOT/System"

echo "== Libm =="
install -m 644 "$LIBM_SRC/Source/ARM/math.h" "$INC/math.h"
install -m 644 "$LIBM_SRC/Source/ARM/fenv.h" "$INC/fenv.h"
install -m 644 "$LIBM_SRC/Source/complex.h" "$INC/complex.h"

echo "== libpthread =="
mkdir -p "$INC/pthread" "$INC/sys/_pthread"
install -m 644 "$LIBPTHREAD_SRC"/include/pthread/*.h "$INC/pthread/"
install -m 644 "$LIBPTHREAD_SRC"/include/sys/_pthread/*.h "$INC/sys/_pthread/"
install -m 644 "$LIBPTHREAD_SRC/include/sys/qos.h" "$INC/sys/qos.h"
install -m 644 "$LIBPTHREAD_SRC/include/pthread/pthread.h" "$INC/pthread.h"
install -m 644 "$LIBPTHREAD_SRC/include/pthread/sched.h" "$INC/sched.h"

echo "== libplatform =="
install -m 644 "$LIBPLATFORM_SRC/include/setjmp.h" "$INC/setjmp.h"
install -m 644 "$LIBPLATFORM_SRC/include/ucontext.h" "$INC/ucontext.h"

echo "== libmalloc =="
# Required: Libc's _stdlib.h includes <malloc/_malloc.h>.
mkdir -p "$INC/malloc"
install -m 644 "$LIBMALLOC_SRC"/include/malloc/*.h "$INC/malloc/"

echo "== Availability headers, generated by AvailabilityVersions =="
# These must be generated, not copied from xnu's EXTERNAL_HEADERS. That copy defines only
# __API_AVAILABLE1..4, while xnu's own bsd/sys headers make five-platform calls such as
#   __API_AVAILABLE(macos(13.0), ios(16.0), tvos(16.0), watchos(9.0), bridgeos(7.0))
# in bsd/sys/unistd.h. With the four-platform macro that expands to something that is not
# an attribute, and the declaration fails to parse. The generated header defines __API_AVAILABLE0..9.
# The generator is a plain python3 script.
mkdir -p "$INC/os"
for template in Availability.h AvailabilityInternal.h AvailabilityInternalLegacy.h \
                AvailabilityMacros.h AvailabilityVersions.h; do
    ( cd "$AVAILABILITY_SRC" \
        && python3 ./availability --preprocess "templates/$template" "$INC/$template" )
done
( cd "$AVAILABILITY_SRC" \
    && python3 ./availability --preprocess templates/os_availability.h "$INC/os/availability.h" )
grep -q '__API_AVAILABLE9' "$INC/Availability.h" \
    || { echo "FAILED: generated Availability.h lacks __API_AVAILABLE9"; exit 1; }

# --- C++ headers -----------------------------------------------------------------------

echo "== libc++ $LIBCXX_MAJOR headers =="
# Unpacked from the .deb rather than apt-installed: libc++-16-dev depends on libc++1-16
# and libunwind-16-dev, and we want neither those runtime libraries nor a bookworm apt
# source in a trixie image. Only the headers are needed.
for package in "libc++-$LIBCXX_MAJOR-dev" "libc++abi-$LIBCXX_MAJOR-dev"; do
    deb="${package}_${LIBCXX_DEB_VERSION}_${LIBCXX_DEB_ARCH}.deb"
    curl -fsSL -o "$WORK/$deb" "$LLVM_POOL/$deb"
    dpkg-deb -x "$WORK/$deb" "$WORK/libcxx-root"
done
mkdir -p "$INC/c++"
cp -a "$WORK/libcxx-root/usr/lib/llvm-$LIBCXX_MAJOR/include/c++/v1" "$INC/c++/v1"
chmod -R u+w "$INC/c++/v1"

CONFIG_SITE=$INC/c++/v1/__config_site
# Assert the ABI-relevant configuration rather than trusting it. The layouts must match
# the libc++ the target OS ships, and hardening must stay off: libc++ 16's assertions call
# the out-of-line std::__libcpp_verbose_abort, which carries no availability annotation and
# so would become a runtime dependency that no compile-time check could catch.
grep -q '^#define _LIBCPP_ABI_VERSION 1$' "$CONFIG_SITE" \
    || { echo "FAILED: unexpected _LIBCPP_ABI_VERSION"; exit 1; }
grep -q '^#define _LIBCPP_ABI_NAMESPACE __1$' "$CONFIG_SITE" \
    || { echo "FAILED: unexpected _LIBCPP_ABI_NAMESPACE"; exit 1; }
grep -q '^#define _LIBCPP_ENABLE_ASSERTIONS_DEFAULT 0$' "$CONFIG_SITE" \
    || { echo "FAILED: libc++ assertions are not default-off"; exit 1; }
# Enable libc++'s vendor availability annotations. Upstream builds disable them; with them
# on, referencing a libc++ symbol that the deployment target's dylib does not export is a
# compile error instead of a load-time failure.
sed -i 's|^#define _LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS|// disabled by assemble.sh: &|' \
    "$CONFIG_SITE"
grep -q '^// disabled by assemble.sh' "$CONFIG_SITE" \
    || { echo "FAILED: could not enable libc++ availability annotations"; exit 1; }

# --- xnu -------------------------------------------------------------------------------
#
# xnu is the one component that needs selecting: we have no use for most of its kernel and networking
# headers, and a handful of files carry no licence grant. Nothing in our sources (or a cross-platform
# library) includes an xnu header directly: they arrive transitively via Libc and libc++.
# Rather than curate a list by hand, get the whole set, then let the compiler tell us which are reachable
# from probe.cpp, and keep exactly those.

echo "== staging xnu =="
stage_dir() {
    [ -d "$XNU_SRC/$1" ] || return 0
    mkdir -p "$STAGE/$2"
    cp -a "$XNU_SRC/$1/." "$STAGE/$2/"
}
stage_dir bsd/sys sys
stage_dir bsd/machine machine
stage_dir bsd/arm arm
stage_dir bsd/i386 i386
stage_dir bsd/bsm bsm
stage_dir bsd/net net
stage_dir bsd/netinet netinet
stage_dir bsd/netinet6 netinet6
stage_dir bsd/uuid uuid
stage_dir bsd/miscfs miscfs
stage_dir libkern/libkern libkern
stage_dir libkern/os os
stage_dir osfmk/mach mach
mkdir -p "$STAGE/arm" "$STAGE/i386"
cp -a "$XNU_SRC/osfmk/arm/arch.h" "$STAGE/arm/arch.h"
cp -a "$XNU_SRC/osfmk/i386/eflags.h" "$STAGE/i386/eflags.h"
# Libc's unistd.h includes <gethostuuid.h>, which lives in xnu's libsyscall.
cp -a "$XNU_SRC/libsyscall/wrappers/gethostuuid.h" "$STAGE/gethostuuid.h"
chmod -R u+w "$STAGE"

echo "== generating sys/_symbol_aliasing.h and sys/_posix_availability.h =="
# xnu's sys/cdefs.h includes both, and both are generated by xnu's own scripts.
# make_symbol_aliasing.sh needs an executable availability.pl under the SDK root. That
# file is a five-line shell wrapper that execs the sibling "availability" python3 tool
# (the .pl name is historical), which in turn reads availability.dsl -- so all three have
# to be installed together. With only the wrapper present the script still exits zero but
# emits a stub with no version macros at all, hence the assertions below.
mkdir -p "$WORK/sdk/usr/local/libexec"
install -m 755 "$AVAILABILITY_SRC/availability.pl" "$AVAILABILITY_SRC/availability" \
    "$WORK/sdk/usr/local/libexec/"
install -m 644 "$AVAILABILITY_SRC/availability.dsl" "$WORK/sdk/usr/local/libexec/"
bash "$STAGE/sys/make_symbol_aliasing.sh" "$WORK/sdk" "$STAGE/sys/_symbol_aliasing.h"
bash "$STAGE/sys/make_posix_availability.sh" "$STAGE/sys/_posix_availability.h"
grep -q '__DARWIN_ALIAS_STARTING_MAC_' "$STAGE/sys/_symbol_aliasing.h" \
    || { echo "FAILED: _symbol_aliasing.h has no version macros"; exit 1; }
grep -q '_POSIX_C_SOURCE\|__DARWIN_C_LEVEL\|__POSIX_' "$STAGE/sys/_posix_availability.h" \
    || { echo "FAILED: _posix_availability.h looks empty"; exit 1; }
rm -f "$STAGE"/sys/make_*.sh

echo "== regenerating the unlicensed bsd/arm headers from their licensed i386 twins =="
# xnu's bsd/arm/{_types,_limits,_param,signal}.h carry a bare copyright with no licence
# grant, so they cannot be redistributed. Their bsd/i386 counterparts are licensed under
# the APSL and are identical apart from the include guard and the architecture condition,
# so the arm variants are derived from the licensed originals instead.
for header in _types.h _limits.h _param.h signal.h; do
    {
        echo "/*"
        echo " * Generated by assemble.sh from xnu/bsd/i386/$header ($XNU_TAG), which is"
        echo " * licensed under the Apple Public Source License. xnu's bsd/arm/$header is"
        echo " * identical apart from the include guard and the architecture condition, but"
        echo " * ships without a licence grant, so the arm variant is derived from the"
        echo " * licensed i386 file rather than copied."
        echo " */"
        sed -e 's/__i386__/__arm__/g' \
            -e 's/__x86_64__/__arm64__/g' \
            -e 's/_I386_/_ARM_/g' \
            -e 's|i386/|arm/|g' \
            -e 's/I386/ARM/g' \
            "$STAGE/i386/$header"
    } > "$STAGE/arm/$header.derived"
    mv "$STAGE/arm/$header.derived" "$STAGE/arm/$header"
done

echo "== computing the xnu transitive closure =="
RESOURCE_INC=$($CLANGXX -print-resource-dir)/include
SYSROOT_INCS="-nostdinc -isystem $INC/c++/v1 -isystem $RESOURCE_INC -isystem $INC"
# -march is the highest used by any consumer, so that arm_sve.h and friends are reachable.
PROBE_FLAGS="--target=$TARGET -std=c++17 -march=armv8.4-a+sve+bf16"
if ! $CLANGXX $PROBE_FLAGS $SYSROOT_INCS -isystem "$STAGE" \
        -fsyntax-only -MD -MF "$WORK/probe.d" "$HERE/probe.cpp" 2> "$WORK/probe.log"; then
    echo "FAILED: probe.cpp does not compile even with the full xnu staging tree"
    sed -n '1,60p' "$WORK/probe.log"
    exit 1
fi
tr ' ' '\n' < "$WORK/probe.d" | grep "^$STAGE/" | sed "s|^$STAGE/||" | sort -u \
    > "$WORK/xnu-closure.txt"
while read -r relative; do
    mkdir -p "$INC/$(dirname "$relative")"
    cp -a "$STAGE/$relative" "$INC/$relative"
done < "$WORK/xnu-closure.txt"
cp "$WORK/xnu-closure.txt" "$SYSROOT/xnu-closure.txt"
rm -rf "$STAGE"
echo "   $(wc -l < "$SYSROOT/xnu-closure.txt") xnu headers"

echo "== verifying the sysroot is self-contained =="
# Same compile with staging off the include path. This also means a sysroot that cannot
# build the consumers fails the image build, so a broken one is never published.
$CLANGXX $PROBE_FLAGS $SYSROOT_INCS -fsyntax-only "$HERE/probe.cpp" \
    || { echo "FAILED: sysroot is not self-contained"; exit 1; }

echo "== licence scan =="
# Keep the image publishable: check that any file we add  has a compatible license.
#
# Detection is done via licensecheck. licensecheck reports one licence per file, or a
# dual-licence expression joined by "and/or" when a file carries more than one grant.
#
# libc++ is excluded: it is upstream LLVM and carries an SPDX identifier.
APPROVED_LICENCES='APSL-2.0
APSL-1.1
Apache-2.0
BSD-2-Clause
BSD-2-Clause-NetBSD
BSD-3-Clause
BSD-4-Clause
BSD-4-Clause-UC
ISC
public-domain'

# licensecheck cannot classify these four, so they are excluded and reviewed by hand:
#   stdint.h    bare Apple copyright
#   search.h    "Written by J.T. Conklin <jtc@netbsd.org> / Public domain."
#   strhash.h   permission-to-use grant, Terry Jones & Jordan Hubbard / PCS Computer Systeme, 1990
#   wordexp.h   permission-to-use grant, University Corporation for Atmospheric Research, 1994
HAND_REVIEWED='stdint.h
search.h
strhash.h
wordexp.h'

( cd "$INC" && find . -type f -not -path './c++/v1/*' | sed 's|^\./||' | sort ) \
    | grep -vxF "$HAND_REVIEWED" > "$WORK/scan-files.txt"
( cd "$INC" && xargs -a "$WORK/scan-files.txt" \
    licensecheck --machine --shortname-scheme=spdx --lines 0 ) > "$WORK/licences.tsv"
# A file licensecheck silently skipped would otherwise pass unexamined.
[ "$(wc -l < "$WORK/licences.tsv")" -eq "$(wc -l < "$WORK/scan-files.txt")" ] \
    || { echo "FAILED: licensecheck did not report on every file"; exit 1; }

# Every licence present must be approved; "A and/or B" is split so both are checked.
cut -f2 "$WORK/licences.tsv" | sed 's| and/or |\n|g' | sort -u \
    | grep -vxF "$APPROVED_LICENCES" > "$WORK/unapproved.txt" || true
if [ -s "$WORK/unapproved.txt" ]; then
    echo "FAILED: licences not in the approved set:"
    sed 's/^/  /' "$WORK/unapproved.txt"
    grep -Ff "$WORK/unapproved.txt" "$WORK/licences.tsv" | cut -f1 | sed 's/^/    in /'
    exit 1
fi
echo "   $(wc -l < "$WORK/scan-files.txt") files scanned, all licences approved"

echo "== manifest =="
{
    echo "Darwin arm64 sysroot for cross-compiling Elasticsearch native libraries."
    echo "Assembled by libs/simdvec/native/darwin-sysroot/assemble.sh."
    echo
    echo "Components:"
    grep -E '^[A-Z_]+=' "$HERE/versions.env" | sed 's/^/  /'
    echo
    echo "Licences:"
    echo "  Libc, xnu, Libm, libpthread, libplatform, libmalloc  Apple Public Source License"
    echo "  AvailabilityVersions                                 Apache License 2.0"
    echo "  libc++ / libc++abi                                   Apache License 2.0 with LLVM exception"
    echo "  (Only Libc, xnu and libplatform ship a top-level licence file, collected under"
    echo "   LICENSES/. The rest carry their notices per file, which the licence scan checks.)"
    echo
    echo "Headers: $(cd "$SYSROOT" && find usr/include -type f -not -path 'usr/include/c++/*' | wc -l)"
    echo "         $(cd "$SYSROOT" && find usr/include/c++/v1 -type f | wc -l) libc++"
    echo
    echo "xnu headers, computed as the transitive closure of probe.cpp:"
    sed 's/^/  /' "$SYSROOT/xnu-closure.txt"
} > "$SYSROOT/MANIFEST"

mkdir -p "$SYSROOT/LICENSES"
for src in "$LIBC_SRC" "$XNU_SRC" "$LIBM_SRC" "$LIBPTHREAD_SRC" "$LIBPLATFORM_SRC" \
           "$LIBMALLOC_SRC" "$AVAILABILITY_SRC"; do
    for name in APPLE_LICENSE LICENSE LICENSE.txt LICENSE.TXT COPYING; do
        if [ -f "$src/$name" ]; then
            cp "$src/$name" "$SYSROOT/LICENSES/$(basename "$src").$name"
            break
        fi
    done
done
cp "$WORK/libcxx-root/usr/share/doc/libc++-$LIBCXX_MAJOR-dev/copyright" \
    "$SYSROOT/LICENSES/libc++-$LIBCXX_MAJOR.copyright" 2> /dev/null || true

echo "== done: $SYSROOT =="
