[#es-connectors-google-cloud]
=== Google Cloud Storage Connector
++++
<titleabbrev>Google Cloud Storage</titleabbrev>
++++

// Attributes used in this file
:service-name: Google Cloud Storage
:service-name-stub: google_cloud_storage

The _Elastic Google Cloud Storage connector_ is a <<es-connectors,connector>> for https://cloud.google.com/storage[Google Cloud Storage^] data sources.


// //////// //// //// //// //// //// //// ////////
// //////// NATIVE CONNECTOR REFERENCE (MANAGED SERVICE) ///////
// //////// //// //// //// //// //// //// ////////

[discrete#es-connectors-google-cloud-native-connector-reference]
==== *Elastic managed connector reference*

.View *Elastic managed connector* reference
[%collapsible]
===============

[discrete#es-connectors-google-cloud-availability-prerequisites]
===== Availability and prerequisites

This connector is available natively in Elastic Cloud since *8.12.0.*
To use this connector in Elastic Cloud, satisfy all <<es-native-connectors,managed connector requirements>>.

[discrete#es-connectors-google-cloud-usage]
===== Usage

The Google Cloud Storage service account must have (at least) the following scopes and roles:

* `resourcemanager.projects.get`
* `serviceusage.services.use`
* `storage.buckets.list`
* `storage.objects.list`
* `storage.objects.get`

Google Cloud Storage service account credentials are stored in a JSON file.

[discrete#es-connectors-google-cloud-configuration]
===== Configuration

The following configuration field is required to set up the connector:

Buckets::
List of buckets to index.
`*` will index all buckets.

Google Cloud service account JSON::
The service account credentials generated from Google Cloud Storage (JSON string).
Refer to the https://developers.google.com/workspace/guides/create-credentials#create_credentials_for_a_service_account[Google Cloud documentation^] for more information.

[discrete#es-connectors-google-cloud-documents-syncs]
===== Documents and syncs

The connector will fetch all buckets and paths the service account has access to.

The `Owner` field is not fetched as `read_only` scope doesn’t allow the connector to fetch IAM information.

[NOTE]
====
* Content from files bigger than 10 MB won't be extracted. (Self-managed connectors can use the <<es-connectors-content-extraction-local, self-managed local extraction service>> to handle larger binary files.)
* Permission are not synced. All documents indexed to an Elastic deployment will be visible to all users with access to that Elastic Deployment.
====

[discrete#es-connectors-google-cloud-sync-types]
====== Sync types

<<es-connectors-sync-types-full,Full syncs>> are supported by default for all connectors.

This connector also supports <<es-connectors-sync-types-incremental,incremental syncs>>.

[discrete#es-connectors-google-cloud-sync-rules]
===== Sync rules

<<es-sync-rules-basic,Basic sync rules>> are identical for all connectors and are available by default.

Advanced sync rules are not available for this connector in the present version.
Currently filtering is controlled by ingest pipelines.

[discrete#es-connectors-google-cloud-content-extraction]
===== Content extraction

See <<es-connectors-content-extraction>>.

[source,shell]
----
$ make ftest NAME=google_cloud_storage
----

For faster tests, add the `DATA_SIZE=small` flag:

[source,shell]
----
make ftest NAME=google_cloud_storage DATA_SIZE=small
----

[discrete#es-connectors-google-cloud-known-issues]
===== Known issues

There are currently no known issues for this connector.

[discrete#es-connectors-google-cloud-troubleshooting]
===== Troubleshooting

See <<es-connectors-troubleshooting>>.

[discrete#es-connectors-google-cloud-security]
===== Security

See <<es-connectors-security>>.

[discrete#es-connectors-google-cloud-source]
===== Framework and source

This connector is built with the {connectors-python}[Elastic connector framework^].

View the {connectors-python}/connectors/sources/google_cloud_storage.py[source code for this connector^] (branch _{connectors-branch}_, compatible with Elastic _{minor-version}_).

// Closing the collapsible section 
===============


// //////// //// //// //// //// //// //// ////////
// //////// CONNECTOR CLIENT REFERENCE (SELF-MANAGED) ///////
// //////// //// //// //// //// //// //// ////////

[discrete#es-connectors-google-cloud-connector-client-reference]
==== *Self-managed connector reference*

.View *self-managed connector* reference
[%collapsible]
===============

[discrete#es-connectors-google-cloud-client-availability-prerequisites]
===== Availability and prerequisites

This connector is available as a self-managed *self-managed connector*.
This self-managed connector is compatible with Elastic versions *8.6.0+*.
To use this connector, satisfy all <<es-build-connector,self-managed connector requirements>>.

[discrete#es-connectors-google-cloud-client-usage]
===== Usage

The Google Cloud Storage service account must have (at least) the following scopes and roles:

* `resourcemanager.projects.get`
* `serviceusage.services.use`
* `storage.buckets.list`
* `storage.objects.list`
* `storage.objects.get`

Google Cloud Storage service account credentials are stored in a JSON file.

[discrete#es-connectors-google-cloud-client-configuration]
===== Configuration

[TIP]
====
When using the <<es-build-connector, self-managed connector>> workflow, initially these fields will use the default configuration set in the {connectors-python}/connectors/sources/google_cloud_storage.py[connector source code^].
These are set in the `get_default_configuration` function definition.

These configurable fields will be rendered with their respective *labels* in the Kibana UI.
Once connected, you'll be able to update these values in Kibana.
====

The following configuration fields are required to set up the connector:

`buckets`::
List of buckets to index.
`*` will index all buckets.

`service_account_credentials`::
The service account credentials generated from Google Cloud Storage (JSON string).
Refer to the https://developers.google.com/workspace/guides/create-credentials#create_credentials_for_a_service_account[Google Cloud documentation^] for more information.

`retry_count`::
The number of retry attempts after a failed call to Google Cloud Storage.
Default value is `3`.

[discrete#es-connectors-google-cloud-client-docker]
===== Deployment using Docker

include::_connectors-docker-instructions.asciidoc[]

[discrete#es-connectors-google-cloud-client-documents-syncs]
===== Documents and syncs

The connector will fetch all buckets and paths the service account has access to.

The `Owner` field is not fetched as `read_only` scope doesn’t allow the connector to fetch IAM information.

[NOTE]
====
* Content from files bigger than 10 MB won't be extracted by default. You can use the <<es-connectors-content-extraction-local, self-managed local extraction service>> to handle larger binary files.
* Permission are not synced. All documents indexed to an Elastic deployment will be visible to all users with access to that Elastic Deployment.
====

[discrete#es-connectors-google-cloud-client-sync-types]
====== Sync types

<<es-connectors-sync-types-full,Full syncs>> are supported by default for all connectors.

This connector also supports <<es-connectors-sync-types-incremental,incremental syncs>>.

[discrete#es-connectors-google-cloud-client-sync-rules]
===== Sync rules

<<es-sync-rules-basic,Basic sync rules>> are identical for all connectors and are available by default.

Advanced sync rules are not available for this connector in the present version.
Currently filtering is controlled by ingest pipelines.

[discrete#es-connectors-google-cloud-client-content-extraction]
===== Content extraction

See <<es-connectors-content-extraction>>.

[discrete#es-connectors-google-cloud-client-client-operations-testing]
===== End-to-end testing

The connector framework enables operators to run functional tests against a real data source.
Refer to <<es-build-connector-testing>> for more details.

To perform E2E testing for the Google Cloud Storage connector, run the following command:

[source,shell]
----
$ make ftest NAME=google_cloud_storage
----

For faster tests, add the `DATA_SIZE=small` flag:

[source,shell]
----
make ftest NAME=google_cloud_storage DATA_SIZE=small
----

[discrete#es-connectors-google-cloud-client-known-issues]
===== Known issues

There are currently no known issues for this connector.

[discrete#es-connectors-google-cloud-client-troubleshooting]
===== Troubleshooting

See <<es-connectors-troubleshooting>>.

[discrete#es-connectors-google-cloud-client-security]
===== Security

See <<es-connectors-security>>.

[discrete#es-connectors-google-cloud-client-source]
===== Framework and source

This connector is built with the {connectors-python}[Elastic connector framework^].

View the {connectors-python}/connectors/sources/google_cloud_storage.py[source code for this connector^] (branch _{connectors-branch}_, compatible with Elastic _{minor-version}_).

// Closing the collapsible section 
===============
