[[reference-architectures]]
= Reference architectures

Elasticsearch reference architectures are blueprints for deploying Elasticsearch clusters tailored to different use cases. Whether you're handling logs or metrics these reference architectures focus on scalability, reliability, and efficient resource utilization. Use these guidelines to deploy Elasticsearch for your use case.

These architectures are designed by architects and engineers to provide standardized, proven solutions that help users follow best practices when deploying Elasticsearch. Some of the key areas of focus are listed below. 

* High availability 
* Scalability

TIP: These architectures are specific to running your deployment on-premises or cloud. If you are using Elastic serverless your Elasticsearch clusters are autoscaled and fully managed by Elastic. For all the deployment options, see https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro-deploy.html[Run Elasticsearch].

These reference architectures are recommendations and should be adapted to fit your specific environment and needs. Each solution can vary based on the unique requirements and conditions of your deployment. In these architectures we discuss about how to deploy cluster components. For information about designing ingest architectures to feed content into your cluster, refer to https://www.elastic.co/guide/en/ingest/current/use-case-arch.html[Ingest architectures]

[discrete]
[[reference-architectures-time-series-2]]
=== Architectures

[cols="50, 50"]
|===
| *Architecture* | *When to use*
| <<elastic-cloud-architecture>>

This architecture uses the Elasticsearch Service to simplify deployment and management. It uses a multi-availability zone architecture and is optimized for time-series datasets.

a| 
* You want to use the best practices Elastic Cloud implements to run your cluster.
* You want to leverage cloud provider hardware that have been extensively tested.
* You need long retention periods with the ability to search indices in an object store cost-effectively.
* Use cloud provider's highly available object stores for data integrity so you don't have to depend on your own.

| <<three-availability-zones>>

This architecture is derived from the Elasticsearch Service - High Availability - Single Region architecture. It defines additional considerations required when self-deploying. It uses multi-availability zone architecture and is optimized for time-series.

a| 
* When you need an architecture that is resilient to unplanned outages
|
|===

include::elastic-cloud-architecture.asciidoc[]

include::three-availability-zones.asciidoc[]
