[role="xpack"]
[testenv="platinum"]
[[ccr-auto-follow]]
=== Manage auto-follow patterns
To replicate time series indices, you configure an auto-follow pattern so that
each new index in the series is replicated automatically. Whenever the name of
a new index on the remote cluster matches the auto-follow pattern, a
corresponding follower index is added to the local cluster.

[[ccr-auto-follow-create]]
==== Create auto-follow patterns
When you create an auto-follow pattern, you are configuring a collection of
patterns against a single remote cluster. When an index is created in the
remote cluster with a name that matches one of the patterns in the collection,
a follower index is configured in the local cluster. The follower
index uses the new index as its leader index.

include::{es-repo-dir}/ccr/getting-started.asciidoc[tag=ccr-create-auto-follow-pattern-tag]

[%collapsible]
.Use the API
====
Use the <<ccr-put-auto-follow-pattern,create auto-follow pattern API>> to add a
new auto-follow pattern configuration.
====

[[ccr-auto-follow-retrieve]]
==== Retrieve auto-follow patterns
To view existing auto-follow patterns and make changes to the backing
patterns, access {kib} on your _remote_ cluster and go to *Management > Stack Management*. In the left navigation, select *Cross Cluster Replication* and
choose the *Auto-follow patterns* tab.

Select the auto-follow pattern that you want to view details about. From there,
you can make changes to the auto-follow pattern. You can also view your
follower indices included in the auto-follow pattern.

[%collapsible]
.Use the API
====
Use the <<ccr-get-auto-follow-pattern,get auto-follow pattern API>> to inspect
all configured auto-follow pattern collections.
====

[[ccr-auto-follow-pause]]
==== Pause and resume auto-follow patterns
To pause and resume replication of auto-follow pattern collections, access {kib} and go to *Management > Stack Management*. In
the left navigation, select *Cross Cluster Replication* and choose the
*Auto-follow patterns* tab.

Select the auto-follow pattern and pause replication.

To resume replication, select the pattern and choose
*Manage pattern > Resume replication*.

[%collapsible]
.Use the API
====
Use the <<ccr-pause-auto-follow-pattern,pause auto-follow pattern API>> to
pause auto-follow patterns.
Use the <<ccr-resume-auto-follow-pattern,resume auto-follow pattern API>> to
resume auto-follow patterns.
====

[[ccr-auto-follow-delete]]
==== Delete auto-follow patterns
To delete an auto-follow pattern collection, access {kib} and go to
*Management > Stack Management*. In the left navigation,
select *Cross Cluster Replication* and choose the *Auto-follow patterns* tab.

Select the auto-follow pattern and pause replication.

When the pattern status changes to Paused, choose
*Manage pattern > Delete pattern*.

[%collapsible]
.Use the API
====
Use the <<ccr-delete-auto-follow-pattern,delete auto-follow pattern API>> to
delete a configured auto-follow pattern collection.
====
