[role="xpack"]
[testenv="platinum"]
[[ccr-auto-follow]]
=== Manage auto-follow patterns

In time series use cases where you want to follow new indices that are
periodically created (such as daily {beats} indices), manually configuring
follower indices for each new leader index can be an operational burden.
Instead, use {ccr} to automatically follow indices in a remote cluster when
the name matches a pattern.

[[ccr-auto-follow-create]]
==== Create auto-follow patterns
When you create an auto-follow pattern, you are configuring a collection of
patterns against a single remote cluster. When an index is created in the
remote cluster with a name that matches one of the patterns in the collection,
a follower index is configured in the local cluster. The follower
index uses the new index as its leader index.

include::{es-repo-dir}/ccr/getting-started.asciidoc[tag=ccr-create-auto-follow-pattern-tag]

[%collapsible]
.Use the API
====
Use the <<ccr-put-auto-follow-pattern,create auto-follow pattern API>> to add a
new auto-follow pattern configuration.
====

[[ccr-auto-follow-retrieve]]
==== Retrieve auto-follow patterns
You can view existing auto-follow patterns and make changes to the backing
patterns:

. Open a browser to access {kib} on your _remote_ cluster.
. From the {kib} menu, click *Management -> Stack Management*.
. Under *Data*, select *Cross Cluster Replication*.
. Choose the *Auto-follow patterns* tab.
. Select the auto-follow pattern that you want to view details about.
  * To make changes to the auto-follow pattern, choose
  *Manage pattern -> Edit pattern*.
  * To view the follower indices included in the auto-follow pattern, choose
  *View your follower indices in Index Management*.

[%collapsible]
.Use the API
====
Use the <<ccr-get-auto-follow-pattern,get auto-follow pattern API>> to inspect
all configured auto-follow pattern collections.
====

[[ccr-auto-follow-pause]]
==== Pause and resume auto-follow patterns
Pause and resume replication of auto-follow pattern collections:

. Open a browser to access {kib} on your _local_ cluster.
. From the {kib} menu, click *Management -> Stack Management*.
. Under *Data*, select *Cross Cluster Replication*.
  . Choose the *Auto-follow patterns* tab.
  . Select the pattern you want to pause and
  choose *Manage pattern -> Pause replication*.

The pattern status changes to *Paused*.

To resume replication, select the pattern and choose
*Manage pattern -> Resume replication*.

[%collapsible]
.Use the API
====
Use the <<ccr-pause-auto-follow-pattern,pause auto-follow pattern API>> to
pause auto-follow patterns.
Use the <<ccr-resume-auto-follow-pattern,resume auto-follow pattern API>> to
resume auto-follow patterns.
====

[[ccr-auto-follow-delete]]
==== Delete auto-follow patterns
Delete an auto-follow pattern collection:

. Open a browser to access {kib} on your _local_ cluster.
. From the {kib} menu, click *Management -> Stack Management*.
. Under *Data*, select *Cross Cluster Replication*.
  . Choose the *Auto-follow patterns* tab.
  . Select the pattern you want to delete and
  choose *Manage pattern -> Pause Replication*.
  . When the pattern status changes to *Paused*, choose
  *Manage pattern -> Delete pattern*.

Confirm that you want to delete the pattern.

[%collapsible]
.Use the API
====
Use the <<ccr-delete-auto-follow-pattern,delete auto-follow pattern API>> to
delete a configured auto-follow pattern collection.
====
