[role="xpack"]
[testenv="platinum"]

//////////////////////////

[source,console]
--------------------------------------------------
PUT /follower_index/_ccr/follow?wait_for_active_shards=1
{
  "remote_cluster" : "remote_cluster",
  "leader_index" : "leader_index"
}
--------------------------------------------------
// TESTSETUP
// TEST[setup:remote_cluster_and_leader_index]

[source,console]
--------------------------------------------------
POST /follower_index/_ccr/pause_follow
--------------------------------------------------
// TEARDOWN

//////////////////////////

[[ccr-managing]]
=== Manage {ccr}
Use the following information to manage {ccr} tasks, such as inspecting
replication progress, pausing and resuming replication, and terminating
replication.

[[ccr-inspect-progress]]
==== Inspecting replication progress

[%collapsible]
.Use the API
====
You can inspect the progress of replication at the shard level with the
<<ccr-get-follow-stats,get follower stats API>>. This API gives you
insight into the read and writes managed by the follower shard task. It also
reports read exceptions that can be retried and fatal exceptions that require
user intervention.
====

[[ccr-pause-replication]]
==== Pausing and resuming replication

[%collapsible]
.Use the API
====
You can pause replication with the
<<ccr-post-pause-follow,pause follower API>> and then later resume
replication with the <<ccr-post-resume-follow,resume follower API>>.
Using these APIs in tandem enables you to adjust the read and write parameters
on the follower shard task if your initial configuration is not suitable for
your use case.
====

[[ccr-recreate-follower-index]]
==== Recreating a follower index
When a document is updated or deleted, the underlying operation is retained in
the Lucene index for a period of time defined by the
<<ccr-index-soft-deletes-retention-period,`index.soft_deletes.retention_lease.period`>> parameter. You configure
this setting on the <<ccr-leader-requirements,leader index>>.

When a follower index starts, it acquires a retention lease from
the leader index. This lease informs the leader that it should not allow a soft
delete to be pruned until either the follower indicates that it has received
the operation, or until the lease expires.

If a follower index falls sufficiently behind a leader and cannot
replicate operations, {es} reports an `indices[].fatal_exception` error. To
resolve the issue, recreate the follower index. When the new follow index
starts, the <<ccr-remote-recovery, remote recovery>> process recopies the
Lucene segment files from the leader.

IMPORTANT: Recreating the follower index is a destructive action. All existing
Lucene segment files are deleted on the cluster containing the follower index.

. Open a browser to access {kib} on your _local_ cluster.
. From the {kib} menu, click *Management -> Stack Management*.
. Under *Data*, select *Cross Cluster Replication*.
  . Choose the *Follower indices* tab.
  . Choose the follower index you want to pause and
  select *Manage -> Pause Replication*.
  . When the follower index status changes to *Paused*, select the follower index and choose *Unfollow leader index*.
  . When prompted to unfollow the leader index, choose *Unfollow leader*.
  +
  The follower index will be converted to a standard index and will no longer appear in *Cross-Cluster Replication*.
. From the {kib} menu, under *Data*, click *Index Management*.
  . Select the follower index from the previous steps and choose
  *Manage index -> Close index* to close the follower index.
. <<ccr-getting-started-follower-index,Recreate the follower index>> to restart
the replication process.

[%collapsible]
.Use the API
====
Use the <<ccr-post-pause-follow,pause follow API>> to pause the replication
process. Then, close the follower index and recreate it. For example:

[source,console]
----------------------------------------------------------------------
POST /follower_index/_ccr/pause_follow

POST /follower_index/_close

PUT /follower_index/_ccr/follow?wait_for_active_shards=1
{
  "remote_cluster" : "remote_cluster",
  "leader_index" : "leader_index"
}
----------------------------------------------------------------------
====

[[ccr-terminate-replication]]
==== Terminating replication

[%collapsible]
.Use the API
====
You can terminate replication with the
<<ccr-post-unfollow,unfollow API>>. This API converts a follower index
to a regular (non-follower) index.
====
