steps:
  - trigger: elasticsearch-serverless-validate-submodule
    label: ":elasticsearch: Check elasticsearch changes against serverless"
    build:
      message: "Validate latest elasticsearch changes"
      env:
        ELASTICSEARCH_SUBMODULE_COMMIT: "${BUILDKITE_COMMIT}"
        UPDATE_SUBMODULE: "false"

