[role="xpack"]
[[delete-analytics-collection]]
=== Delete Analytics Collection

deprecated:[9.0.0]
beta::[]

++++
<titleabbrev>Delete Analytics Collection</titleabbrev>
++++

.New API reference
[sidebar]
--
For the most up-to-date API details, refer to {api-es}/group/endpoint-analytics[Behavioral analytics APIs].
--

Removes a <<behavioral-analytics-overview,Behavioral Analytics>> Collection and its associated data stream.

[[delete-analytics-collection-request]]
==== {api-request-title}

`DELETE _application/analytics/<name>`

[[delete-analytics-collection-prereq]]
==== {api-prereq-title}

Requires the `manage_behavioral_analytics` cluster privilege.

[[delete-analytics-collection-path-params]]
==== {api-path-parms-title}

`<name>`::
(Required, string)

[[delete-analytics-collection-response-codes]]
==== {api-response-codes-title}

`400`::
The `name` was not provided.

`404` (Missing resources)::
No Analytics Collection matching `name` could be found.

[[delete-analytics-collection-example]]
==== {api-examples-title}

The following example deletes the Analytics Collection named `my_analytics_collection`:

[source,console]
----
DELETE _application/analytics/my_analytics_collection/
----
// TEST[skip:Behavioral Analytics APIs emit deprecation warnings and will not be updated]
