/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import org.elasticsearch.gradle.internal.precommit.CheckForbiddenApisTask

apply plugin: 'elasticsearch.publish'
apply plugin: 'elasticsearch.build'
apply plugin: 'elasticsearch.foreign-api'

dependencies {
  api "org.apache.lucene:lucene-core:${versions.lucene}"
  implementation project(':libs:core')
  implementation project(':libs:foreign-adapter')

  // test:framework reaches this project again transitively (via server), which puts our own jar on a
  // classpath that already has our main classes: excluding it keeps jarHell happy.
  testImplementation(project(":test:framework")) {
    exclude group: 'org.elasticsearch', module: 'lucene-store'
  }
}

tasks.withType(CheckForbiddenApisTask).configureEach {
  replaceSignatureFiles 'jdk-signatures'
}
