[role="xpack"]
[testenv="platinum"]
[[get-ml-info]]
=== Get machine learning info API

[subs="attributes"]
++++
<titleabbrev>Get {ml} info</titleabbrev>
++++

Returns defaults and limits used by machine learning.

[[get-ml-info-request]]
==== {api-request-title}

`GET _ml/info`

[[get-ml-info-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have `monitor_ml`,
`monitor`, `manage_ml`, or `manage` cluster privileges to use this API. The
`machine_learning_admin` and `machine_learning_user` roles provide these
privileges. See {stack-ov}/security-privileges.html[Security privileges] and
{stack-ov}/built-in-roles.html[Built-in roles].

[[get-ml-info-desc]]
==== {api-description-title}

This endpoint is designed to be used by a user interface that needs to fully
understand machine learning configurations where some options are not specified,
meaning that the defaults should be used.  This endpoint may be used to find out
what those defaults are.

[[get-ml-info-example]]
==== {api-examples-title}

The endpoint takes no arguments:

[source,console]
--------------------------------------------------
GET _ml/info
--------------------------------------------------
// TEST

This is a possible response:

[source,console-result]
----
{
  "defaults" : {
    "anomaly_detectors" : {
      "model_memory_limit" : "1gb",
      "categorization_examples_limit" : 4,
      "model_snapshot_retention_days" : 1
    },
    "datafeeds" : {
      "scroll_size" : 1000
    }
  },
  "upgrade_mode": false,
  "native_code" : {
    "version": "7.0.0",
    "build_hash": "99a07c016d5a73"
  },
  "limits" : { }
}
----
// TESTRESPONSE[s/"upgrade_mode": false/"upgrade_mode": $body.upgrade_mode/]
// TESTRESPONSE[s/"version": "7.0.0",/"version": "$body.native_code.version",/]
// TESTRESPONSE[s/"build_hash": "99a07c016d5a73"/"build_hash": "$body.native_code.build_hash"/]
