[role="xpack"]
[testenv="platinum"]
[[ml-valid-detector]]
=== Validate detectors API
++++
<titleabbrev>Validate detectors</titleabbrev>
++++

Validates detector configuration information.

[[ml-valid-detector-request]]
==== {api-request-title}

`POST _ml/anomaly_detectors/_validate/detector`

[[ml-valid-detector-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have `manage_ml` or
`manage` cluster privileges to use this API. See
{stack-ov}/security-privileges.html[Security privileges].

[[ml-valid-detector-desc]]
==== {api-description-title}

This API enables you validate the detector configuration
before you create an {anomaly-job}.

[[ml-valid-detector-request-body]]
==== {api-request-body-title}

For a list of the properties that you can specify in the body of this API,
see <<ml-detectorconfig,detector configuration objects>>.

[[ml-valid-detector-example]]
==== {api-examples-title}

The following example validates detector configuration information:

[source,js]
--------------------------------------------------
POST _ml/anomaly_detectors/_validate/detector
{
  "function": "metric",
  "field_name": "responsetime",
  "by_field_name": "airline"
}
--------------------------------------------------
// CONSOLE
// TEST[skip:needs-licence]

When the validation completes, you receive the following results:

[source,console-result]
----
{
  "acknowledged": true
}
----
