/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.optimizer.rules.logical;

import org.elasticsearch.xpack.esql.core.expression.Alias;
import org.elasticsearch.xpack.esql.core.expression.AttributeMap;
import org.elasticsearch.xpack.esql.core.expression.NamedExpression;
import org.elasticsearch.xpack.esql.plan.logical.Eval;
import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
import org.elasticsearch.xpack.esql.plan.logical.MvExpand;
import org.elasticsearch.xpack.esql.plan.logical.Project;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public final class PushDownMvExpandPastProject extends OptimizerRules.OptimizerRule<MvExpand> {
    @Override
    protected LogicalPlan rule(MvExpand mvExpand) {
        if (mvExpand.child() instanceof Project pj) {
            List<NamedExpression> projections = new ArrayList<>(pj.projections());

            // Skip if any projection alias shadows an input field name, as injecting an Eval would cause
            // duplicate output attributes. This can happen with aliases generated by ResolveUnionTypesInUnionAll.
            // Example:
            // MvExpand[salary{r}#168,salary{r}#175]
            // \_Project[[$$salary$converted_to$keyword{r$}#178 AS salary#168]]
            //   \_Limit[1000[INTEGER],false,false]
            //     \_UnionAll[[salary{r}#174, $$salary$converted_to$keyword{r$}#178]]
            Set<String> inputNames = pj.inputSet().stream().map(NamedExpression::name).collect(Collectors.toSet());
            if (projections.stream().anyMatch(e -> e instanceof Alias alias && inputNames.contains(alias.toAttribute().name()))) {
                return mvExpand;
            }

            // Find if the target is aliased in the project and create an alias with temporary names for it.
            for (int i = 0; i < projections.size(); i++) {
                NamedExpression projection = projections.get(i);
                if (projection instanceof Alias alias) {
                    if (alias.toAttribute().semanticEquals(mvExpand.target().toAttribute())) {
                        // for query like: row a = 2 | eval b = a ｜ keep * | mv_expand b
                        Alias aliasAlias = new Alias(
                            alias.source(),
                            TemporaryNameUtils.temporaryName(alias.child(), alias.toAttribute(), 0),
                            alias.child()
                        );
                        projections.set(i, mvExpand.expanded());
                        pj = new Project(pj.source(), new Eval(aliasAlias.source(), pj.child(), List.of(aliasAlias)), projections);
                        mvExpand = new MvExpand(mvExpand.source(), pj, aliasAlias.toAttribute(), mvExpand.expanded());
                        break;
                    } else if (alias.child().semanticEquals(mvExpand.target().toAttribute())) {
                        // for query like: row a = 2 | eval b = a ｜ keep * | mv_expand a
                        Alias aliasAlias = new Alias(
                            alias.source(),
                            TemporaryNameUtils.temporaryName(alias.child(), alias.toAttribute(), 0),
                            alias.child()
                        );
                        projections.set(i, alias.replaceChild(aliasAlias.toAttribute()));
                        pj = new Project(pj.source(), new Eval(aliasAlias.source(), pj.child(), List.of(aliasAlias)), projections);
                        mvExpand = mvExpand.replaceChild(pj);
                        break;
                    }
                }
            }

            Project project = PushDownUtils.pushDownPastProject(mvExpand);
            return PushDownUtils.resolveRenamesFromMap(project, AttributeMap.of(mvExpand.target().toAttribute(), mvExpand.expanded()));
        }
        return mvExpand;
    }
}
