/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.optimizer.rules.logical;

import org.elasticsearch.compute.operator.InsertEmptyBucketsOperator.DefaultValue;
import org.elasticsearch.xpack.esql.core.expression.Alias;
import org.elasticsearch.xpack.esql.core.expression.Attribute;
import org.elasticsearch.xpack.esql.core.expression.NamedExpression;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Count;
import org.elasticsearch.xpack.esql.expression.function.aggregate.CountDistinct;
import org.elasticsearch.xpack.esql.plan.logical.Aggregate;
import org.elasticsearch.xpack.esql.plan.logical.Eval;
import org.elasticsearch.xpack.esql.plan.logical.InsertEmptyBuckets;
import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
import org.elasticsearch.xpack.esql.plan.logical.Project;
import org.elasticsearch.xpack.esql.plan.logical.UnaryPlan;
import org.elasticsearch.xpack.esql.plan.logical.UnpackDims;
import org.elasticsearch.xpack.esql.planner.PlannerUtils;

import java.util.HashMap;
import java.util.Map;

/**
 * Swaps an {@link InsertEmptyBuckets} node (inserted during analysis by {@link InsertEmptyBucketsAfterAggregate}) with the
 * {@code EVAL}s and {@code PROJECT}s generated by optimizer rules until it reaches the {@link Aggregate} node.
 * Next, default values are determined (zero for Count, null otherwise). It needs to be pushed to the Aggregate to
 * accommodate STATS 10*COUNT()+7, which is unrolled by {@link ReplaceAggregateAggExpressionWithEval}.
 */
public final class PushdownInsertEmptyBucketsAndSetDefaultValues extends OptimizerRules.OptimizerRule<InsertEmptyBuckets> {

    @Override
    protected LogicalPlan rule(InsertEmptyBuckets insertEmptyBuckets) {
        return switch (insertEmptyBuckets.child()) {
            case Eval eval -> swapOrStop(insertEmptyBuckets, eval);
            case Project project -> swapOrStop(insertEmptyBuckets, project);
            case UnpackDims unpackDims -> setDefaultValues(insertEmptyBuckets, unpackDims);
            case Aggregate aggregate -> setDefaultValues(insertEmptyBuckets, aggregate);
            default -> throw new IllegalStateException("Unexpected child class [" + insertEmptyBuckets.child().getClass() + "]");
        };
    }

    private static LogicalPlan swapOrStop(InsertEmptyBuckets insertEmptyBuckets, UnaryPlan child) {
        if (child.child().outputSet().containsAll(insertEmptyBuckets.groups())
            && child.child().outputSet().containsAll(insertEmptyBuckets.buckets().keySet())) {
            return child.replaceChild(insertEmptyBuckets.replaceChild(child.child()));
        } else {
            return insertEmptyBuckets;
        }
    }

    private static LogicalPlan setDefaultValues(InsertEmptyBuckets insertEmptyBuckets, UnaryPlan plan) {
        // The node cannot be pushed any further down. This happens for time-series aggregations with an extra dimension, where
        // TranslateTimeSeriesAggregate packs the dimension into a single grouping so the underlying Aggregate no longer exposes the
        // dimension attribute (it is only unpacked again by UnpackDims), but we still must set the default values.
        LogicalPlan aggregate = plan;
        while (aggregate instanceof UnaryPlan && aggregate instanceof Aggregate == false) {
            aggregate = ((UnaryPlan) aggregate).child();
        }
        if (aggregate instanceof Aggregate == false) {
            throw new IllegalStateException("Cannot find aggregate expression [" + insertEmptyBuckets + "]");
        }
        Map<Attribute, DefaultValue> defaultValues = new HashMap<>();
        for (NamedExpression aggregateExpression : ((Aggregate) aggregate).aggregates()) {
            Attribute attribute = aggregateExpression.toAttribute();
            if (insertEmptyBuckets.buckets().containsKey(attribute) || insertEmptyBuckets.groups().contains(attribute)) {
                // Grouping field: the operator sources its value/type from the bucket cursor / representative row, not a default.
                continue;
            }
            Object value = (Alias.unwrap(aggregateExpression) instanceof Count)
                || (Alias.unwrap(aggregateExpression) instanceof CountDistinct) ? 0L : null;
            defaultValues.put(attribute, new DefaultValue(PlannerUtils.toElementType(attribute.dataType()), value));
        }
        return defaultValues.equals(insertEmptyBuckets.defaultValues())
            ? insertEmptyBuckets
            : new InsertEmptyBuckets(
                insertEmptyBuckets.source(),
                insertEmptyBuckets.child(),
                insertEmptyBuckets.buckets(),
                insertEmptyBuckets.groups(),
                defaultValues
            );
    }
}
