/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.optimizer.rules.logical;

import org.elasticsearch.compute.operator.InsertEmptyBucketsOperator.DefaultValue;
import org.elasticsearch.xpack.esql.core.expression.Alias;
import org.elasticsearch.xpack.esql.core.expression.Attribute;
import org.elasticsearch.xpack.esql.core.expression.AttributeSet;
import org.elasticsearch.xpack.esql.core.expression.NamedExpression;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Count;
import org.elasticsearch.xpack.esql.expression.function.aggregate.CountDistinct;
import org.elasticsearch.xpack.esql.plan.logical.Aggregate;
import org.elasticsearch.xpack.esql.plan.logical.Eval;
import org.elasticsearch.xpack.esql.plan.logical.InsertEmptyBuckets;
import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
import org.elasticsearch.xpack.esql.plan.logical.Project;
import org.elasticsearch.xpack.esql.plan.logical.UnaryPlan;
import org.elasticsearch.xpack.esql.plan.logical.UnpackDims;
import org.elasticsearch.xpack.esql.planner.PlannerUtils;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Swaps an {@link InsertEmptyBuckets} node (inserted during analysis by {@link InsertEmptyBucketsAfterAggregate}) with the
 * plans generated by optimizer rules until it reaches the {@link Aggregate} node.
 * Next, default values are determined (zero for Count, null otherwise). It needs to be pushed to the Aggregate to
 * accommodate STATS 10*COUNT()+7, which is unrolled by {@link ReplaceAggregateAggExpressionWithEval}.
 * <p>
 * For time-series aggregations with an extra dimension, {@link TranslateTimeSeriesAggregate} inserts an
 * {@link UnpackDims} above the second-pass {@link Aggregate}. The dimension attributes only exist above that node
 * (packed into a single grouping below it), so this rule remaps those groups onto the packed attribute and pushes
 * {@link InsertEmptyBuckets} below {@link UnpackDims} so it can still reach the Aggregate.
 */
public final class PushdownInsertEmptyBucketsAndSetDefaultValues extends OptimizerRules.OptimizerRule<InsertEmptyBuckets> {

    @Override
    protected LogicalPlan rule(InsertEmptyBuckets insertEmptyBuckets) {
        return switch (insertEmptyBuckets.child()) {
            case Eval eval -> pushDown(insertEmptyBuckets, eval);
            case Project project -> pushDown(insertEmptyBuckets, project);
            case UnpackDims unpackDims -> pushBelowUnpackDims(insertEmptyBuckets, unpackDims);
            case Aggregate aggregate -> setDefaultValues(insertEmptyBuckets, aggregate);
            default -> throw new IllegalStateException("Unexpected child class [" + insertEmptyBuckets.child().getClass() + "]");
        };
    }

    /**
     * Pushes {@link InsertEmptyBuckets} below {@link UnaryPlan} that known its groupings/buckets.
     */
    private static LogicalPlan pushDown(InsertEmptyBuckets insertEmptyBuckets, UnaryPlan child) {
        if (child.child().outputSet().containsAll(insertEmptyBuckets.groups())
            && child.child().outputSet().containsAll(insertEmptyBuckets.buckets().keySet())) {
            return child.replaceChild(insertEmptyBuckets.replaceChild(child.child()));
        } else {
            throw new IllegalStateException("Can't push [" + insertEmptyBuckets + "] below [" + child + "]");
        }
    }

    /**
     * Pushes {@link InsertEmptyBuckets} below {@link UnpackDims}, remapping any grouping attributes that are unpacked
     * dimensions onto the single packed grouping attribute that exists in the Aggregate below.
     */
    private static LogicalPlan pushBelowUnpackDims(InsertEmptyBuckets insertEmptyBuckets, UnpackDims unpackDims) {
        AttributeSet dims = AttributeSet.of(unpackDims.dims());
        List<Attribute> remappedGroups = new ArrayList<>(insertEmptyBuckets.groups().size());
        boolean addedPacked = false;
        for (Attribute group : insertEmptyBuckets.groups()) {
            if (dims.contains(group)) {
                if (addedPacked == false) {
                    remappedGroups.add(unpackDims.packed());
                    addedPacked = true;
                }
            } else {
                remappedGroups.add(group);
            }
        }
        if (unpackDims.child().outputSet().containsAll(remappedGroups)
            && unpackDims.child().outputSet().containsAll(insertEmptyBuckets.buckets().keySet())) {
            InsertEmptyBuckets pushed = new InsertEmptyBuckets(
                insertEmptyBuckets.source(),
                unpackDims.child(),
                insertEmptyBuckets.buckets(),
                remappedGroups,
                insertEmptyBuckets.defaultValues()
            );
            return unpackDims.replaceChild(pushed);
        } else {
            throw new IllegalStateException("Can't push [" + insertEmptyBuckets + "] below [" + unpackDims + "]");
        }
    }

    private static LogicalPlan setDefaultValues(InsertEmptyBuckets insertEmptyBuckets, Aggregate aggregate) {
        AttributeSet bucketAttrs = AttributeSet.of(insertEmptyBuckets.buckets().keySet());
        AttributeSet groupAttrs = AttributeSet.of(insertEmptyBuckets.groups());
        Map<Attribute, DefaultValue> defaultValues = new LinkedHashMap<>();
        for (NamedExpression aggregateExpression : aggregate.aggregates()) {
            Attribute attribute = aggregateExpression.toAttribute();
            if (bucketAttrs.contains(attribute) || groupAttrs.contains(attribute)) {
                // Grouping field: the operator sources its value/type from the bucket cursor / representative row, not a default.
                continue;
            }
            Object value = (Alias.unwrap(aggregateExpression) instanceof Count)
                || (Alias.unwrap(aggregateExpression) instanceof CountDistinct) ? 0L : null;
            defaultValues.put(attribute, new DefaultValue(PlannerUtils.toElementType(attribute.dataType()), value));
        }
        return defaultValues.equals(insertEmptyBuckets.defaultValues())
            ? insertEmptyBuckets
            : new InsertEmptyBuckets(
                insertEmptyBuckets.source(),
                insertEmptyBuckets.child(),
                insertEmptyBuckets.buckets(),
                insertEmptyBuckets.groups(),
                defaultValues
            );
    }
}
