/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.optimizer.rules.logical;

import org.elasticsearch.xpack.esql.core.expression.Alias;
import org.elasticsearch.xpack.esql.core.expression.Attribute;
import org.elasticsearch.xpack.esql.core.expression.NamedExpression;
import org.elasticsearch.xpack.esql.plan.logical.Eval;
import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
import org.elasticsearch.xpack.esql.plan.logical.MvExpand;
import org.elasticsearch.xpack.esql.plan.logical.Project;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public final class PushDownMvExpandPastProject extends OptimizerRules.OptimizerRule<MvExpand> {
    @Override
    protected LogicalPlan rule(MvExpand mvExpand) {
        if (mvExpand.child() instanceof Project pj) {
            List<NamedExpression> projections = new ArrayList<>(pj.projections());

            // Skip if the expanded field has the same name as a field in the projection's input set, and
            // the projection shadows that specific field from the projection input set.
            // Pushing down the MvExpand in such cases would cause duplicate output attributes.
            // This can happen with aliases generated by ResolveUnionTypesInUnionAll.
            // Example:
            // MvExpand[salary{r}#168,salary{r}#175]
            // \_Project[[$$salary$converted_to$keyword{r$}#178 AS salary#168]]
            //   \_UnionAll[[salary{r}#174, $$salary$converted_to$keyword{r$}#178]]
            String expandedFieldName = mvExpand.expanded().name();
            Set<String> inputNames = pj.inputSet().stream().map(NamedExpression::name).collect(Collectors.toSet());
            if (projections.stream()
                .anyMatch(
                    e -> e instanceof Alias alias
                        && inputNames.contains(expandedFieldName)
                        && inputNames.contains(alias.toAttribute().name())
                )) {
                return mvExpand;
            }

            // Find if the target is aliased in the project and create an alias with temporary names for it.
            for (int i = 0; i < projections.size(); i++) {
                NamedExpression projection = projections.get(i);
                if (projection instanceof Alias alias) {
                    if (alias.toAttribute().semanticEquals(mvExpand.target().toAttribute())) {
                        // Check if the alias's original field (child) is referenced elsewhere in the projections.
                        // If the original field is not referenced by any other projection or alias,
                        // we don't need to inject an Eval to preserve it, and can safely resolve renames and push down.
                        if (projections.stream()
                            .anyMatch(
                                ne -> ne.semanticEquals(alias.child())
                                    || ne instanceof Alias as && as.child().semanticEquals(alias.child()) && as != alias
                            ) == false) {
                            // The alias's original field is not referenced elsewhere, no need to preserve it,
                            mvExpand = PushDownUtils.resolveRenamesFromProject(mvExpand, pj);
                            break;
                        }

                        // for query like: row a = 2 | eval b = a | keep * | mv_expand b
                        Alias aliasAlias = new Alias(
                            alias.source(),
                            TemporaryNameUtils.temporaryName(alias.child(), alias.toAttribute(), 0),
                            alias.child()
                        );
                        projections.set(i, mvExpand.expanded());
                        pj = pj.replaceChild(new Eval(aliasAlias.source(), pj.child(), List.of(aliasAlias)));
                        mvExpand = new MvExpand(mvExpand.source(), pj, aliasAlias.toAttribute(), mvExpand.expanded());
                        break;
                    } else if (alias.child().semanticEquals(mvExpand.target().toAttribute())) {
                        // for query like: row a = 2 | eval b = a | keep * | mv_expand a
                        Alias aliasAlias = new Alias(
                            alias.source(),
                            TemporaryNameUtils.temporaryName(alias.child(), alias.toAttribute(), 0),
                            alias.child()
                        );
                        projections.set(i, alias.replaceChild(aliasAlias.toAttribute()));
                        pj = pj.replaceChild(new Eval(aliasAlias.source(), pj.child(), List.of(aliasAlias)));
                        mvExpand = mvExpand.replaceChild(pj);
                        break;
                    }
                }
            }

            // Push down the MvExpand past the Project
            MvExpand pushedDownMvExpand = mvExpand.replaceChild(pj.child());

            // Update projections to point to the expanded attribute
            Attribute target = mvExpand.target().toAttribute();
            Attribute expanded = mvExpand.expanded();
            for (int i = 0; i < projections.size(); i++) {
                NamedExpression ne = projections.get(i);
                if (ne instanceof Alias alias && alias.child().semanticEquals(target)) {
                    projections.set(i, alias.replaceChild(expanded));
                } else if (ne.semanticEquals(target)) {
                    projections.set(i, expanded);
                }
            }

            return new Project(pj.source(), pushedDownMvExpand, projections);
        }
        return mvExpand;
    }
}
