/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.approximation;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.lucene.util.SetOnce;
import org.elasticsearch.common.util.set.Sets;
import org.elasticsearch.compute.data.LongBlock;
import org.elasticsearch.index.IndexMode;
import org.elasticsearch.xpack.esql.VerificationException;
import org.elasticsearch.xpack.esql.common.Failure;
import org.elasticsearch.xpack.esql.core.expression.Alias;
import org.elasticsearch.xpack.esql.core.expression.Literal;
import org.elasticsearch.xpack.esql.core.expression.NamedExpression;
import org.elasticsearch.xpack.esql.core.tree.Source;
import org.elasticsearch.xpack.esql.core.util.Holder;
import org.elasticsearch.xpack.esql.core.util.StringUtils;
import org.elasticsearch.xpack.esql.expression.function.aggregate.AggregateFunction;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Avg;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Count;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Median;
import org.elasticsearch.xpack.esql.expression.function.aggregate.MedianAbsoluteDeviation;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Percentile;
import org.elasticsearch.xpack.esql.expression.function.aggregate.StdDev;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Sum;
import org.elasticsearch.xpack.esql.expression.function.aggregate.Variance;
import org.elasticsearch.xpack.esql.expression.function.aggregate.WeightedAvg;
import org.elasticsearch.xpack.esql.expression.function.scalar.approximate.ConfidenceInterval;
import org.elasticsearch.xpack.esql.optimizer.rules.logical.SubstituteApproximationPlan;
import org.elasticsearch.xpack.esql.plan.logical.Aggregate;
import org.elasticsearch.xpack.esql.plan.logical.ChangePoint;
import org.elasticsearch.xpack.esql.plan.logical.Dissect;
import org.elasticsearch.xpack.esql.plan.logical.Enrich;
import org.elasticsearch.xpack.esql.plan.logical.EsRelation;
import org.elasticsearch.xpack.esql.plan.logical.Eval;
import org.elasticsearch.xpack.esql.plan.logical.Filter;
import org.elasticsearch.xpack.esql.plan.logical.Grok;
import org.elasticsearch.xpack.esql.plan.logical.Insist;
import org.elasticsearch.xpack.esql.plan.logical.LeafPlan;
import org.elasticsearch.xpack.esql.plan.logical.Limit;
import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
import org.elasticsearch.xpack.esql.plan.logical.MvExpand;
import org.elasticsearch.xpack.esql.plan.logical.OrderBy;
import org.elasticsearch.xpack.esql.plan.logical.Project;
import org.elasticsearch.xpack.esql.plan.logical.RegexExtract;
import org.elasticsearch.xpack.esql.plan.logical.RegisteredDomain;
import org.elasticsearch.xpack.esql.plan.logical.Row;
import org.elasticsearch.xpack.esql.plan.logical.Sample;
import org.elasticsearch.xpack.esql.plan.logical.SampledAggregate;
import org.elasticsearch.xpack.esql.plan.logical.TopN;
import org.elasticsearch.xpack.esql.plan.logical.UriParts;
import org.elasticsearch.xpack.esql.plan.logical.inference.Completion;
import org.elasticsearch.xpack.esql.plan.logical.inference.Rerank;
import org.elasticsearch.xpack.esql.session.Result;

import java.util.List;
import java.util.Set;

/**
 * This class computes approximate results for certain classes of ES|QL queries.
 * Approximate results are usually much faster to compute than exact results.
 * <p>
 * A query is currently suitable for approximation if:
 * <ul>
 *   <li> it contains exactly one {@code STATS} command
 *   <li> the other processing commands are from the supported set
 *        ({@link Approximation#SUPPORTED_COMMANDS}); this set contains almost all
 *        unary commands, but most notably not {@code FORK} or {@code JOIN}.
 *   <li> the aggregate functions are from the supported set
 *        ({@link Approximation#SUPPORTED_SINGLE_VALUED_AGGS} and
 *         {@link Approximation#SUPPORTED_MULTIVALUED_AGGS})
 * </ul>
 * Some of these restrictions may be lifted in the future.
 * <p>
 * When these conditions are met, the query is replaced by an approximation query
 * that samples documents before the STATS, and extrapolates the aggregate
 * functions if needed. This new logical plan is generated by
 * {@link ApproximationPlan#get}. The substitution of the original query by the
 * approximation query happens during logical plan optimization, in the rule
 * {@link SubstituteApproximationPlan}.
 * <p>
 * In addition to approximate results, confidence intervals are also computed.
 * This is done by dividing the sampled rows {@link ApproximationPlan#TRIAL_COUNT}
 * times into {@link ApproximationPlan#BUCKET_COUNT} buckets, computing the aggregate
 * functions for each bucket, and using these sampled values to compute
 * confidence intervals with the bias-corrected and accelerated (BCa) bootstrap
 * method, see also {@link ConfidenceInterval}.
 * <p>
 * The initial approximation plan contains a placeholder for the sample probability,
 * which is determined during subplan execution, and is based on results set size.
 * To obtain an appropriate sample probability, first a target number of rows
 * is set. This is determined via the {@link ApproximationSettings}.
 * Next, the total number of rows in the source index is counted via the subplan
 * {@link Approximation#sourceCountSubPlan}. This plan always executes fast. When
 * there are no commands that can change the number of rows, the sample
 * probability can be directly computed as a ratio of the target number of rows
 * and this total number.
 * <p>
 * In the presence of commands that can change the number of rows (e.g. filtering),
 * another step is needed. The first goal is to find a sample probability that
 * leads to approximately {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} rows,
 * and when this probability is found, a sample probability leading to the target
 * number of rows is computed.
 * <p>
 * This is done by setting the initial sample probability to the ratio of
 * {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} and the total number
 * of rows in the source index, and a number of rows is sampled with the subplan
 * {@link Approximation#countSubPlan}. As long as the sampled number of rows is too
 * small, the probability is increased until a good probability is reached. This
 * final probability is used to compute the probability using for approximating
 * the original query.
 */
public class Approximation {

    public record QueryProperties(boolean hasGrouping, boolean canDecreaseRowCount, boolean canIncreaseRowCount) {}

    /**
     * These processing commands are supported.
     * <p>
     * When a command is not supported, it should be added to
     * ApproximationSupportTests.UNSUPPORTED_COMMANDS
     * to make sure all commands are captured.
     */
    static final Set<Class<? extends LogicalPlan>> SUPPORTED_COMMANDS = Set.of(
        Aggregate.class,
        ChangePoint.class,
        Completion.class,
        Dissect.class,
        Enrich.class,
        EsRelation.class,
        Eval.class,
        Filter.class,
        Grok.class,
        Insist.class,
        Limit.class,
        MvExpand.class,
        OrderBy.class,
        Project.class,
        RegexExtract.class,
        RegisteredDomain.class,
        Rerank.class,
        Row.class,
        Sample.class,
        SampledAggregate.class,
        TopN.class,
        UriParts.class
    );

    /**
     * These index modes of EsRelation are supported.
     * <p>
     * Note: LOOKUP is added to make query validation output nicer messages
     * ("query with [LOOKUP JOIN ...] ..." instead of "query with [test_lookup] ...").
     */
    private static final Set<IndexMode> SUPPORTED_INDEX_MODES = Set.of(IndexMode.STANDARD, IndexMode.LOOKUP);

    /**
     * These commands preserve all rows, making it easy to predict the number of output rows.
     */
    private static final Set<Class<? extends LogicalPlan>> ROW_PRESERVING_COMMANDS = Set.of(
        Completion.class,
        Dissect.class,
        Enrich.class,
        Eval.class,
        Grok.class,
        Insist.class,
        OrderBy.class,
        Project.class,
        RegexExtract.class,
        Rerank.class
    );

    /**
     * These commands never increase the number of all rows, making it easier to predict the number of output rows.
     */
    private static final Set<Class<? extends LogicalPlan>> ROW_NON_INCREASING_COMMANDS = Sets.union(
        Set.of(Filter.class, Limit.class, Sample.class, TopN.class),
        ROW_PRESERVING_COMMANDS
    );

    /**
     * These commands never decrease the number of all rows, making it easier to predict the number of output rows.
     */
    private static final Set<Class<? extends LogicalPlan>> ROW_NON_DECREASING_COMMANDS = Sets.union(
        Set.of(MvExpand.class),
        ROW_PRESERVING_COMMANDS
    );

    /**
     * These aggregate functions behave well with random sampling, in the sense
     * that they converge to the true value as the sample size increases.
     * <p>
     * Aggregation functions that depend on the value of many or all of the
     * individual rows (like AVG, COUNT, MEDIAN) will generally satisfy the CLT
     * and are suitable for approximation.
     * On the other hand, aggregation functions that depend on a small subset of
     * rows (like COUNT DISTINCT, MAX, PRESENT) are not.
     * Aggregation function that depend on all values, but are very sensitive to
     * some (outlier) values (like STDDEV, PERCENTILE for low/high percentiles)
     * are challenging to approximate. They are supported, but may require a
     * larger sample size to obtain good accuracy.
     * <p>
     * When an aggregation is not supported, it should be added to
     * ApproximationSupportTests.UNSUPPORTED_AGGS
     * to make sure all aggregations are captured.
     */
    static final Set<Class<? extends AggregateFunction>> SUPPORTED_SINGLE_VALUED_AGGS = Set.of(
        Avg.class,
        Count.class,
        Median.class,
        MedianAbsoluteDeviation.class,
        Percentile.class,
        StdDev.class,
        Sum.class,
        Variance.class,
        WeightedAvg.class
    );

    /**
     * These multivalued aggregate functions work well with random sampling.
     * However, confidence intervals make no sense anymore and are dropped.
     */
    static final Set<Class<? extends AggregateFunction>> SUPPORTED_MULTIVALUED_AGGS = Set.of(
        org.elasticsearch.xpack.esql.expression.function.aggregate.Sample.class
    );

    /**
     * The target number of sampled rows to estimate the total number of rows
     * reaching the STATS function. This is only relevant when there are commands
     * that can change the number of rows. This value leads to an error of about
     * 1% in the estimated count.
     */
    private static final int ROW_COUNT_FOR_COUNT_ESTIMATION = 10_000;

    /**
     * Default number of rows to sample for approximation without grouping.
     * 100_000 rows is enough to accurately estimate most single aggregates.
     */
    private static final int DEFAULT_ROW_COUNT_WITHOUT_GROUPING = 100_000;

    /**
     * Default number of rows to sample for approximation with grouping.
     * To accurately estimate aggregates for each group, more rows are needed.
     */
    private static final int DEFAULT_ROW_COUNT_WITH_GROUPING = 1_000_000;

    /**
     * Don't sample with a probability higher than this threshold. The cost of
     * tracking confidence intervals doesn't outweigh the benefits of sampling.
     */
    private static final double SAMPLE_PROBABILITY_THRESHOLD = 0.1;

    private static final Logger logger = LogManager.getLogger(Approximation.class);

    private static final AggregateFunction COUNT_ALL_ROWS = new Count(Source.EMPTY, Literal.keyword(Source.EMPTY, StringUtils.WILDCARD));

    private final LogicalPlan logicalPlan;
    private final ApproximationSettings settings;
    private final QueryProperties queryProperties;

    private Double nextSubPlanSampleProbability;
    private int subPlanIterationCount;
    private final SetOnce<Long> sourceRowCount;

    public Approximation(LogicalPlan logicalPlan, ApproximationSettings settings) {
        this.logicalPlan = logicalPlan;
        this.settings = settings;
        this.queryProperties = verifyPlan(logicalPlan);

        nextSubPlanSampleProbability = null;
        subPlanIterationCount = 0;
        sourceRowCount = new SetOnce<>();
    }

    /**
     * Verifies that a plan is suitable for approximation.
     *
     * @return the query properties relevant for approximation
     * @throws VerificationException if the plan is not suitable for approximation
     */
    public static QueryProperties verifyPlan(LogicalPlan logicalPlan) throws VerificationException {
        // The plan must contain a STATS command.
        if (logicalPlan.anyMatch(plan -> plan instanceof Aggregate) == false) {
            throw new VerificationException(
                List.of(Failure.fail(logicalPlan.collectLeaves().getFirst(), "query without [STATS] cannot be approximated"))
            );
        }
        // Verify that all commands are supported.
        logicalPlan.forEachUp(plan -> {
            if (SUPPORTED_COMMANDS.contains(plan.getClass()) == false
                || (plan instanceof EsRelation esRelation && SUPPORTED_INDEX_MODES.contains(esRelation.indexMode()) == false)) {
                // TODO: ideally just return the command from the source
                throw new VerificationException(
                    List.of(Failure.fail(plan, "query with [" + plan.sourceText() + "] cannot be approximated"))
                );
            }
        });

        Holder<Boolean> encounteredStats = new Holder<>(false);
        Holder<Boolean> hasGrouping = new Holder<>();
        Holder<Boolean> canIncreaseRowCount = new Holder<>(false);
        Holder<Boolean> canDecreaseRowCount = new Holder<>(false);

        logicalPlan.forEachUp(plan -> {
            if (encounteredStats.get() == false) {
                if (plan instanceof Aggregate aggregate) {
                    // Verify that the aggregate functions are supported.
                    encounteredStats.set(true);
                    hasGrouping.set(aggregate.groupings().isEmpty() == false);
                    plan.forEachExpression(AggregateFunction.class, aggFn -> {
                        if (SUPPORTED_SINGLE_VALUED_AGGS.contains(aggFn.getClass()) == false
                            && SUPPORTED_MULTIVALUED_AGGS.contains(aggFn.getClass()) == false) {
                            // TODO: ideally just return aggregate function from the source
                            throw new VerificationException(
                                List.of(Failure.fail(aggFn, "aggregation function [" + aggFn.sourceText() + "] cannot be approximated"))
                            );
                        }
                    });
                } else if (plan instanceof LeafPlan == false) {
                    if (ROW_NON_DECREASING_COMMANDS.contains(plan.getClass()) == false) {
                        canDecreaseRowCount.set(true);
                    }
                    if (ROW_NON_INCREASING_COMMANDS.contains(plan.getClass()) == false) {
                        canIncreaseRowCount.set(true);
                    }
                }
            } else {
                // Multiple STATS commands are not supported.
                if (plan instanceof Aggregate) {
                    throw new VerificationException(List.of(Failure.fail(plan, "query with multiple [STATS] cannot be approximated")));
                }
            }
        });

        return new QueryProperties(hasGrouping.get(), canDecreaseRowCount.get(), canIncreaseRowCount.get());
    }

    /**
     * Returns the first subplan to execute for approximation, or null if the main plan can be executed directly.
     */
    public LogicalPlan firstSubPlan() {
        if (sourceRowCount.get() == null) {
            return sourceCountSubPlan();
        } else if (nextSubPlanSampleProbability != null) {
            return countSubPlan(nextSubPlanSampleProbability);
        } else {
            return null;
        }
    }

    /**
     * Returns the new main plan to execute for approximation after executing a subplan, based on the result of the subplan.
     */
    public LogicalPlan newMainPlan(Result result) {
        if (sourceRowCount.get() == null) {
            return processSourceCount(rowCount(result));
        } else {
            return processCount(rowCount(result));
        }
    }

    /**
     * Plan that counts the number of rows in the source index.
     * This is the ES|QL query:
     * <pre>
     * {@code FROM index | STATS COUNT(*)}
     * </pre>
     */
    private LogicalPlan sourceCountSubPlan() {
        LogicalPlan leaf = logicalPlan.collectLeaves().getFirst();
        LogicalPlan sourceCountPlan = new Aggregate(
            Source.EMPTY,
            leaf,
            List.of(),
            List.of(new Alias(Source.EMPTY, "$source_count", COUNT_ALL_ROWS))
        );
        sourceCountPlan.setOptimized();
        return sourceCountPlan;
    }

    /**
     * Determines either the final sample probability or whether more subplans
     * need to the executed, based on the total number of rows in the source
     * index and the query properties.
     */
    private LogicalPlan processSourceCount(long sourceRowCount) {
        logger.debug("total number of source rows: [{}] rows", sourceRowCount);
        this.sourceRowCount.set(sourceRowCount);
        if (sourceRowCount == 0) {
            // If there are no rows, run the original query.
            nextSubPlanSampleProbability = null;
            return ApproximationPlan.substituteSampleProbability(logicalPlan, 1.0);
        }
        double sampleProbability = Math.min(1.0, (double) sampleRowCount() / sourceRowCount);
        if (queryProperties.canIncreaseRowCount == false && sampleProbability > SAMPLE_PROBABILITY_THRESHOLD) {
            // If the query cannot increase the number of rows, and the sample probability is large,
            // we can directly run the original query without sampling.
            logger.debug("using original plan (too few rows)");
            nextSubPlanSampleProbability = null;
            return ApproximationPlan.substituteSampleProbability(logicalPlan, 1.0);
        } else if (queryProperties.canIncreaseRowCount == false && queryProperties.canDecreaseRowCount == false) {
            // If the query preserves all rows, we can directly approximate with the sample probability.
            nextSubPlanSampleProbability = null;
            return ApproximationPlan.substituteSampleProbability(logicalPlan, sampleProbability);
        } else {
            // Otherwise, we need to sample the number of rows first to obtain a good sample probability.
            nextSubPlanSampleProbability = Math.min(1.0, (double) ROW_COUNT_FOR_COUNT_ESTIMATION / sourceRowCount);
            return logicalPlan;
        }
    }

    /**
     * Plan that counts a sampled number of rows reaching the STATS function.
     * This is the ES|QL query
     * <pre>
     * {@code FROM index | SAMPLE prob | (...) | STATS COUNT(*)}
     * </pre>
     * where {@code prob} is the given sample probability.
     */
    private LogicalPlan countSubPlan(double sampleProbability) {
        Holder<Boolean> encounteredStats = new Holder<>(false);
        LogicalPlan countPlan = logicalPlan.transformUp(plan -> {
            if (encounteredStats.get() == false) {
                if (plan instanceof Aggregate aggregate) {
                    // The STATS function should be replaced by a STATS COUNT(*).
                    encounteredStats.set(true);
                    List<NamedExpression> aggregations = List.of(new Alias(Source.EMPTY, "$count_p=" + sampleProbability, COUNT_ALL_ROWS));
                    if (sampleProbability == 1.0) {
                        plan = new Aggregate(Source.EMPTY, aggregate.child(), List.of(), aggregations);
                    } else {
                        plan = new SampledAggregate(
                            Source.EMPTY,
                            aggregate.child(),
                            List.of(),
                            aggregations,
                            aggregations,
                            Literal.fromDouble(Source.EMPTY, sampleProbability)
                        );
                    }
                }
            } else {
                // Strip everything after the STATS command.
                plan = plan.children().getFirst();
            }
            return plan;
        });

        countPlan.setOptimized();
        return countPlan;
    }

    /**
     * Receives the sampled number of rows reaching the STATS function and determines
     * whether the next iteration should run the main approximation plan (if a good
     * sample probability is found), or another {@link Approximation#countSubPlan}
     * with higher sample probability,
     * <p>
     * The first iteration uses a probability of
     * <pre>
     * {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} / {@link Approximation#sourceRowCount}
     * </pre>
     * which is set by the {@link Approximation#processSourceCount}.
     * <p>
     * If the sampled row count is high enough, the approximation plan is run next.
     * <p>
     * If the sampled row count is low the probability is multiplied by
     * <pre>
     * {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} / Math.max(1, rowCount)
     * </pre>
     * and the count plan is run again.
     * <p>
     * For positive rowCount this means the next iteration aims for
     * approximately {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} rows.
     * The iteration stops when a rowCount larger than {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} / 2
     * is encountered. The division by 2 is to stop when the random sampling
     * returns a few less rows than aimed for.
     * <p>
     * For zero rowCount the sample probability is multiplied by
     * {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION}. That means the next
     * iteration can sample a number of rows between 0 and the target count,
     * but can never overshoot by much.
     * <p>
     * Regarding the iteration count: in the worst case (very large index, very few
     * matching docs), the first few iterations return zero rows, and the sample probability
     * is multiplied by {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} each time.
     * Next, there's one iteration that returns a positive small row count, and the
     * probability is scaled up the correct value. Next, there's one final iteration
     * with approximately {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} rows.
     * <p>
     * This result in a maximum iteration count of about:
     * <pre>
     * log(sourceRowCount, {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION}) + 2
     * </pre>
     * which is at most 7 when sourceRowCount=MAX_LONG (huge!) and
     * {@link Approximation#ROW_COUNT_FOR_COUNT_ESTIMATION} = 10000.
     * To be safe, the maximum iteration count is capped at 10, and an exception is thrown
     * when this count is exceeded.
     */
    private LogicalPlan processCount(long rowCount) {
        subPlanIterationCount += 1;
        if (subPlanIterationCount > 10) {
            throw new IllegalStateException("Approximation count iteration limit exceeded");
        }
        double sampleProbability = nextSubPlanSampleProbability;
        logger.debug("estimated number of rows reaching STATS (p=[{}]): [{}] rows", sampleProbability, rowCount);
        double newSampleProbability = Math.min(1.0, sampleProbability * sampleRowCount() / Math.max(1, rowCount));
        if (newSampleProbability > SAMPLE_PROBABILITY_THRESHOLD) {
            // If the new sample probability is large, run the original query.
            logger.debug("using original plan (too few rows)");
            nextSubPlanSampleProbability = null;
            return ApproximationPlan.substituteSampleProbability(logicalPlan, 1.0);
        } else if (rowCount <= ROW_COUNT_FOR_COUNT_ESTIMATION / 2) {
            // Not enough rows are sampled yet; increase the sample probability and try again.
            nextSubPlanSampleProbability = Math.min(1.0, sampleProbability * ROW_COUNT_FOR_COUNT_ESTIMATION / Math.max(1, rowCount));
            return logicalPlan;
        } else {
            // A good sample probability is found; run the approximation plan.
            nextSubPlanSampleProbability = null;
            return ApproximationPlan.substituteSampleProbability(logicalPlan, newSampleProbability);
        }
    }

    /**
     * Returns the target number of rows to sample for approximation.
     */
    private int sampleRowCount() {
        if (settings.rows() != null) {
            return settings.rows();
        } else if (queryProperties.hasGrouping) {
            return DEFAULT_ROW_COUNT_WITH_GROUPING;
        } else {
            return DEFAULT_ROW_COUNT_WITHOUT_GROUPING;
        }
    }

    /**
     * Returns the row count in the result and closes the result.
     */
    private long rowCount(Result countResult) {
        assert countResult.pages().size() == 1;
        assert countResult.pages().getFirst().getBlockCount() == 1;
        assert countResult.pages().getFirst().getPositionCount() == 1;

        long rowCount = ((LongBlock) (countResult.pages().getFirst().getBlock(0))).getLong(0);
        countResult.pages().getFirst().close();
        return rowCount;
    }
}
