CREATE TABLE mock (
  TABLE_SCHEM VARCHAR,
  TABLE_NAME VARCHAR,
  TABLE_TYPE VARCHAR,
  REMARKS VARCHAR,
  TYPE_CAT VARCHAR,
  TYPE_SCHEM VARCHAR,
  TYPE_NAME VARCHAR,
  SELF_REFERENCING_COL_NAME VARCHAR,
  REF_GENERATION VARCHAR
) AS SELECT '', 'test', 'TABLE', '', null, null, null, null, null FROM DUAL;
