[role="xpack"]
[[xes-6.2.0]]
== {es} {xpack} 6.2.0 Release Notes
++++
<titleabbrev>6.2.0 Release Notes</titleabbrev>
++++

[[xes-feature-6.2.0]]
[float]
=== New features

Machine Learning::
* Added the ability to identify scheduled events and prevent anomaly detection
during these periods. For more information, see
{xpack-ref}/ml-calendars.html[Calendars and Scheduled Events].
//Repo: x-pack-elasticsearch
//Pull: 2930, 3258, 3267, 3320, 3365, 3401, 3485, 3388, 3473, 3521, 3714, 3513, 464
//514, 519, 3690

Security::
* {security} now supports user authentication using SAML Single Sign on. For
more information, see {xpack-ref}/saml-realm.html[SAML Authentication].
//Repo: x-pack-elasticsearch
//Pull: 3648, 3646

Watcher::
* Added a transform input for chained input. For more information, see
{xpack-ref}/input-chain.html#_transforming_chained_input_data[Transforming Chained Input Data].
//Repo: x-pack-elasticsearch
//Pull: 2861

[[xes-enhancement-6.2.0]]
[float]
=== Enhancements

Machine Learning::
* Increased tokenization flexibility for categorization. Now all {es} analyzer
functionality is available, which opens up the possibility of sensibly
categorizing non-English log messages. For more information, see {xpack-ref}/ml-configuring-categories.html#ml-configuring-analyzer[Customizing the Categorization Analyzer].
//Repo: x-pack-elasticsearch
//Pull: 3372
* Improved the sensitivity of the analysis to high variance data with lots of
values near zero.
//Repo: machine-learning-cpp
//Pull: 456
* Improved the decay rate of the model memory by using a weighted moving average.
//Repo: machine-learning-cpp
//Pull: 440
* Machine learning indices created after upgrading to 6.2 have the
`auto_expand_replicas: 0-1` setting rather than a fixed setting of 1 replica.
As a result, {ml} indices created after upgrading to 6.2 can have a green
status on single node clusters. There is no impact in multi-node clusters.
//Repo: x-pack-elasticsearch
//Pull: 3375
* Changed the credentials that are used by {dfeeds}. When {security} is enabled,
a {dfeed} stores the roles of the user who created or updated the {dfeed}
**at that time**. This means that if those roles are updated, the {dfeed}
subsequently runs with the new permissions that are associated with the roles.
However, if the user's roles are adjusted after creating or updating the {dfeed}
then the {dfeed} continues to run with the permissions that are associated with
the original roles. For more information, see
{xpack-ref}/ml-dfeeds.html[Datafeeds].
//Repo: x-pack-elasticsearch
//Pull: 3254
* Added a new `scheduled` forecast status, which indicates that the forecast
has not started yet.
//Repo: machine-learning-cpp
//Pull: 506

Monitoring::
* {monitoring} indices (`.monitoring`) created after upgrading to 6.2 have the
`auto_expand_replicas: 0-1` setting rather than a fixed setting of 1 replica.
As a result, monitoring indices created after upgrading to 6.2 can have a green
status on single node clusters. There is no impact in multi-node clusters.
//Repo: x-pack-elasticsearch
//Pull: 3282, 3373
* Added a cluster alert that triggers whenever a node is added, removed, or
restarted.
//Repo: x-pack-elasticsearch
//Pull: 3504

Security::
* Added the ability to refresh tokens that were created by the token API. The
API provides information about a refresh token, which you can use within 24
hours of its creation to extend the life of a token. For more information, see
<<security-api-tokens>>.
//Repo: x-pack-elasticsearch
//Pull: 3468
* Added principal and role information to `access_granted`, `access_denied`,
`run_as_granted`, and `run_as_denied` audit events. For more information about
these events, see {xpack-ref}/auditing.html[Auditing Security Events].
//Repo: x-pack-elasticsearch
//Pull: 3100
* Added audit event ignore policies, which are a way to tune the verbosity of an
audit trail. These policies define rules for ignoring audit events that match
specific attribute values. For more information, see
{xpack-ref}/auditing.html#audit-log-ignore-policy[Logfile Audit Events Ignore Policies].
//Repo: x-pack-elasticsearch
//Pull: 3005
* Added a certificates API, which enables you to retrieve information about the
X.509 certificates that are used to encrypt communications in your {es} cluster.
For more information, see <<security-api-ssl>>.
//Repo: x-pack-elasticsearch
//Pull: 3088

Watcher::
* Added the ability to set the `index` and `doc_type` dynamically in an index
action. For more information, see {xpack-ref}/actions-index.html[Index Action].
//Repo: x-pack-elasticsearch
//Pull: 3264
* Added a `refresh` index action attribute, which enables you to set the
refresh policy of the write request. For more information, see
{xpack-ref}/actions-index.html[Index Action].
//Repo: x-pack-elasticsearch
//Pull: 3350
* Added support for actions in slack attachments, which enables you to add
buttons that can be clicked in slack messages. For more information, see
{xpack-ref}/actions-slack.html[Slack Action].
//Repo: x-pack-elasticsearch
//Pull: 3355
* {watcher} indices (`.watch*` and `triggered_watches`) created after upgrading
to 6.2 have the `auto_expand_replicas: 0-1` setting rather than a fixed setting
of 1 replica. As a result, {watcher} indices created after upgrading to 6.2 can
have a green status on single node clusters. There is no impact in multi-node
clusters.
//Repo: x-pack-elasticsearch
//Pull: 3284, 3371

[[xes-bug-6.2.0]]
[float]
=== Bug fixes
////
License::
* Fix license messaging for Logstash functionality
//Repo: x-pack-elasticsearch
//Pull: 3268
////

Machine Learning::
* Improved error reporting for crashes and resource problems on Linux.
//Repo: machine-learning-cpp
//Pull: 510
* Improved the detection of seasonal trends in bucket spans longer than 1 hour.
//Repo: machine-learning-cpp
//Pull: 525
* Updated the forecast API to wait for validation and return an error if the
validation fails.
//Repo: x-pack-elasticsearch
//Pull: 3399
* Set the actual bucket value to 0 in model plots for empty buckets for count
and sum functions. The count and sum functions treat empty buckets as 0 rather
than unknown for anomaly detection, so it was inconsistent not to do the same
for model plots. This inconsistency resulted in problems plotting these buckets
in {kib}.
//Repo: machine-learning-cpp
//Pull: 518

Security::
* Updated the `setup-passwords` command to generate passwords with characters
`A-Z`, `a-z`, and `0-9`, so that they are safe to use in shell scripts. For more
information about this command, see <<setup-passwords>>.
//Repo: x-pack-elasticsearch
//Pull: 3253
* Improved the error messages that occur if the `x-pack` directory is missing
when you run <<users-command,`users` commands>>.
//Repo: x-pack-elasticsearch
//Pull: 3271
* Fixed the ordering of realms in a realm chain, which determines the order in
which the realms are consulted. For more information, see
{xpack-ref}/how-authc-works.html[How Authentication Works].
//Repo: x-pack-elasticsearch
//Pull: 3533

Watcher::
* Replaced group settings with affix key settings where filters are needed.
For more information, see https://github.com/elastic/elasticsearch/pull/28338.
//Repo: x-pack-elasticsearch
//Pull: 3685
////
X-Pack::
* Introduce plugin-specific env scripts
//Repo: x-pack-elasticsearch
//Pull: 3649
* Drop native controller from descriptors (except ML)
//Repo: x-pack-elasticsearch
//Pull: 3650
* Simplify security manager permissions
// //Repo: x-pack-elasticsearch
//Pull: 3651
////
