name: Feature Request
description: Request a new feature we haven't thought of
labels: [">enhancement", "needs:triage"]
body:
  - type: markdown
    attributes:
      value: | 
        Please first search existing issues for the feature you are requesting;
        it may already exist, even as a closed issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give us as much context as possible about the feature. For example,
        you could include a story about a time when you wanted to use the feature,
        and also tell us what you had to do instead. The last part is helpful
        because it gives us an idea of how much harder your life is without the
        feature.
