/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.versionfield;

/**
 * {@code @allocates} estimator for the {@code new Version(String)} constructor in this module's allowlist. The
 * {@code public static long} method matches the constructor's parameters and returns the heap cost of the object it
 * allocates. Invoked from generated bytecode on the allocation pre-check path, so it must be cheap, must not allocate, and
 * must not throw.
 *
 * <p>The trivial sizing math is reimplemented locally rather than shared from {@code lang-painless}, which exposes it only
 * as non-SPI implementation detail; this module depends on {@code painless-spi} alone.
 */
public final class VersionAllocationEstimators {

    private static final int OBJECT_HEADER = 12;
    private static final int ARRAY_HEADER = 16;
    private static final int REFERENCE_SIZE = 8;

    private VersionAllocationEstimators() {}

    /** Signed add saturating to {@link Long#MAX_VALUE} on overflow. */
    private static long addSat(long a, long b) {
        try {
            return Math.addExact(a, b);
        } catch (ArithmeticException overflow) {
            return (a < 0) ? Long.MIN_VALUE : Long.MAX_VALUE;
        }
    }

    /** Rounds {@code bytes} up to the nearest 8-byte alignment boundary, saturating rather than overflowing. */
    private static long pad8(long bytes) {
        return addSat(bytes, 7L) & ~7L;
    }

    /** Heap size of a one-byte-element array of {@code length} elements: header plus payload, 8-byte aligned. */
    private static long byteArrayBytes(long length) {
        return pad8(addSat(ARRAY_HEADER, Math.max(0L, length)));
    }

    /** {@code new Version(String)}: the wrapper object plus the version encoded to bytes, sized by the source length. */
    public static long versionBytes(String value) {
        long len = value == null ? 0 : value.length();
        return pad8(OBJECT_HEADER + REFERENCE_SIZE) + byteArrayBytes(len);
    }
}
