/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.datasources;

import org.elasticsearch.common.settings.Setting;

import java.util.List;

/**
 * Cluster settings for controlling ESQL external source behavior; all node-scoped. The concurrency guardrail
 * ({@link #MAX_CONNECTIONS}) and the throttle retry budget are read when the storage-provider registry initializes
 * on a node, so a change to them takes effect after a node restart, not on already-built providers.
 * <p>
 * Covers three areas: a local-resource concurrency guardrail ({@link #MAX_CONNECTIONS}); reactive throttle
 * handling for object stores (the retry duration budget — throttling is handled by backoff, not a concurrency
 * cap); and glob/listing safety limits (max discovered files, max brace expansion) to prevent degenerate queries
 * from overwhelming storage backends.
 */
public final class ExternalSourceSettings {

    private ExternalSourceSettings() {}

    /**
     * Maximum number of concurrent in-flight storage reads per storage scheme per node — a deliberate
     * local-resource guardrail (connections, buffers, file handles), not a throttle defense. Object-store
     * throttling is handled reactively by retry + adaptive backoff on 503/SlowDown; this bound exists to protect
     * our own node and backends that cannot signal backpressure (the local filesystem). It blocks (queues) when
     * reached rather than failing a query. Set to 0 to disable the guardrail entirely.
     * <p>
     * Default: 256 — sized to local resources, generous enough that S3/GCS/Azure parallelism is not artificially
     * capped (the old default of 50 mirrored the AWS SDK's connection-pool default and throttled throughput). The
     * S3 async client's connection pool is sized above this setting's maximum so the guardrail, not the SDK pool,
     * is always the binding constraint.
     */
    public static final Setting<Integer> MAX_CONNECTIONS = Setting.intSetting(
        "esql.external.max_connections",
        256,
        0,
        500,
        Setting.Property.NodeScope
    );

    /**
     * Maximum total time (in seconds) to spend retrying throttled cloud API requests
     * before giving up. Bounds the cumulative retry duration regardless of the retry count,
     * ensuring queries fail cleanly when throttling is persistent rather than blocking
     * until the HTTP request timeout fires.
     * Default: 30 seconds. Set to 0 to disable the duration budget (retry count only).
     */
    public static final Setting<Integer> THROTTLE_MAX_RETRY_DURATION = Setting.intSetting(
        "esql.external.throttle_max_retry_duration",
        30,
        0,
        300,
        Setting.Property.NodeScope
    );

    /**
     * Hard cap on the number of files that glob expansion will collect before aborting.
     * Protects against degenerate globs (e.g. {@code s3://bucket/*}) on large buckets.
     * Default: 10,000 — generous for legitimate use, catches truly degenerate cases.
     */
    public static final Setting<Integer> MAX_DISCOVERED_FILES = Setting.intSetting(
        "esql.external.max_discovered_files",
        10000,
        1,
        1000000,
        Setting.Property.NodeScope,
        Setting.Property.Dynamic
    );

    /**
     * Cap on the number of concrete paths generated by brace expansion before falling
     * back to listing. Prevents patterns like {@code {1,2,...,10000}} from generating
     * excessive HeadObject calls.
     * Default: 100 — above this, the system uses normal listing instead of per-key checks.
     */
    public static final Setting<Integer> MAX_GLOB_EXPANSION = Setting.intSetting(
        "esql.external.max_glob_expansion",
        100,
        1,
        10000,
        Setting.Property.NodeScope,
        Setting.Property.Dynamic
    );

    /**
     * Enables {@code auth=workload_identity} for EXTERNAL cloud reads, which resolves credentials from the node's
     * workload identity (IAM instance profile / IMDS on AWS and Azure, GCE metadata server on GCP)
     * rather than requiring explicit credentials in the query or datasource.
     * <p>
     * Disabled by default. Must be explicitly enabled by an operator on self-hosted, single-cloud,
     * single-tenant deployments where the node's workload identity is the intended credential.
     * Never enable in serverless or multi-tenant deployments: workload identity credentials bypass tenant isolation.
     * <p>
     * This is an operator-dynamic setting: changes take effect immediately without a node restart.
     */
    public static final Setting<Boolean> WORKLOAD_IDENTITY_ENABLED = Setting.boolSetting(
        "esql.datasource.workload_identity.enabled",
        false,
        Setting.Property.NodeScope,
        Setting.Property.OperatorDynamic
    );

    public static List<Setting<?>> settings() {
        return List.of(MAX_CONNECTIONS, THROTTLE_MAX_RETRY_DURATION, MAX_DISCOVERED_FILES, MAX_GLOB_EXPANSION, WORKLOAD_IDENTITY_ENABLED);
    }
}
