/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.rest.generative;

import org.elasticsearch.common.Strings;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;
import org.elasticsearch.xcontent.XContentBuilder;
import org.elasticsearch.xcontent.json.JsonXContent;
import org.elasticsearch.xpack.esql.CsvTestsDataLoader;
import org.elasticsearch.xpack.esql.generator.Column;
import org.elasticsearch.xpack.esql.generator.QueryExecuted;
import org.elasticsearch.xpack.esql.generator.command.CommandGenerator;
import org.elasticsearch.xpack.esql.generator.command.source.DualModeFromGenerator;
import org.elasticsearch.xpack.esql.generator.command.source.FromGenerator;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import static org.elasticsearch.xpack.esql.CsvTestsDataLoader.availableDatasetsForEs;

/**
 * Base class for differential generative ES|QL tests.
 *
 * <p>Runs the same randomly generated pipeline against two indices that hold identical data but
 * different index settings, then compares the results. A divergence in failure/success, output
 * schema, or values indicates a correctness bug in one of the index modes.
 *
 * <p>The reference index set uses {@link #referenceSettings()} (plain {@code standard} by default)
 * and the candidate set uses {@link #candidateSettings()} ({@code columnar} by default). Both sets
 * are created from the standard CSV test datasets under a distinct name prefix ({@value #REF_PREFIX}
 * vs {@value #CAND_PREFIX}), so wildcard patterns generated by {@link DualModeFromGenerator} are
 * always namespace-scoped and never cross between the two sets.
 *
 * <p>Datasets that fail columnar index creation (because their mapping cannot be fully reconstructed
 * from doc values) are automatically skipped on both sides; the test asserts that at least one
 * dataset survives so coverage is never silently lost. Datasets in {@link #EXCLUDED_DATASETS} are
 * excluded up front because they create successfully in columnar mode but produce legitimately
 * different results (e.g. {@code index:false} fields are no-ops in columnar mode).
 *
 * <p>Comparison is three-layered, applied at every pipeline step:
 * <ol>
 *   <li><b>Failure parity</b> — both threw or neither threw. If exactly one threw the test fails,
 *       unless the message matches {@link #ALLOWED_MODE_DIFFERENCES}.</li>
 *   <li><b>Schema</b> — same column names in the same order, same types.</li>
 *   <li><b>Values</b> — order-insensitive multiset equality (rows are sorted canonically before
 *       comparison; multi-value cells are element-sorted to absorb stored-vs-synthetic ordering
 *       differences). Only checked while the per-iteration <em>determinism gate</em> is open.</li>
 * </ol>
 *
 * <p>The determinism gate closes when a row-truncating or non-deterministic command appears in
 * the pipeline, or when either side returns exactly 1 000 rows (the implicit {@code LIMIT 1000}
 * may have kicked in). After the gate closes, failure parity and schema are still checked for
 * the remaining pipeline steps.
 *
 * <p>Scope for this first cut: single-node, non-time-series, {@link
 * org.elasticsearch.xpack.esql.generator.GenerativeFeature#BASELINE} only.
 *
 * <p>See {@code LogsDbSubobjectsFalseVersusLogsDbColumnarRestIT} (logsdb module) for a catalogue
 * of known behavioral differences between {@code standard} and {@code columnar} mode that informed
 * {@link #EXCLUDED_DATASETS} and {@link #ALLOWED_MODE_DIFFERENCES}.
 */
public abstract class CrossIndexModeGenerativeRestRunner extends GenerativeRestTest {

    private static final Logger logger = LogManager.getLogger(CrossIndexModeGenerativeRestRunner.class);

    /** Name prefix for reference-side indices (plain {@code standard} mode by default). */
    public static final String REF_PREFIX = "ref_";

    /** Name prefix for candidate-side indices ({@code columnar} mode by default). */
    public static final String CAND_PREFIX = "cand_";

    /**
     * Datasets excluded from cross-mode testing because they create successfully in columnar mode
     * but produce legitimately different results, or are too heavy for the generative suite.
     *
     * <p>Other historically excluded datasets (geo precision, text→keyword / short→long wildcard
     * conflicts, COUNT-on-MV bugs, etc.) are covered by value-skipping, the determinism gate, or
     * automatic skip-on-cand-creation-failure — verified empirically with {@code -Dtests.iters=20+}
     * and a follow-up 100-iter run.
     */
    private static final Set<String> EXCLUDED_DATASETS = Set.of(
        // Mapping designed to be type-incompatible with the standard employees dataset; CSV also
        // carries deliberate boolean MV duplicates that standard collapses to a scalar while
        // columnar keeps as a list (false vs [false]).
        "employees_incompatible",
        // 245 000+ documents with MV integer fields. Loading both ref_ and cand_ copies makes
        // wide wildcards like FROM ref_* large enough to close the REST connection / kill the
        // test cluster mid-suite.
        "many_numbers",
        // cartesian_shape cannot be stored via doc values for synthetic source, leaving the cand
        // index with 0 documents while ref has the full dataset.
        "cartesian_multipolygons",
        // Unmapped-source fixtures: all are dynamic:false with only `id` mapped, so everything else in the
        // document lands in _source / _ignored_source. Strict columnar drops that content at ingest (it
        // reconstructs _source from doc values), so the ref side surfaces those fields and the cand side
        // cannot - a legitimate mode difference, not a bug. Same reasoning and same list as
        // CsvColumnarIT#EXCLUDED_DATASETS, which skips them for the columnar csv-spec run.
        "unmapped_multi_stored_foo",
        "unmapped_multi_stored_bar",
        "unmapped_multi_synthetic",
        "unmapped_multi_stored_mixed",
        "unmapped_array_data",
        "unmapped_object_data"
    );

    /**
     * Substrings of error messages that indicate a known benign mode difference. Each entry is
     * matched as a case-sensitive substring against the throwing side's message. The same list
     * drives both {@link #ALLOWED_MODE_DIFFERENCES} (used for cross-mode parity checks) and
     * {@link #additionalAllowedErrors()} (used by the base-class pipeline exception guard), so
     * every allowed substring is declared exactly once.
     *
     * <p>Add entries here — with a comment explaining the root cause — as real benign divergences
     * are identified. Follows the house style of {@link GenerativeRestTest#ALLOWED_ERRORS}.
     */
    private static final List<String> ALLOWED_MODE_DIFFERENCE_SUBSTRINGS = List.of(
        // Extremely wide result sets (many indices × many fields) can push the HTTP/YAML response
        // past the 3 MB REST-client parse limit on one side only. This is an infrastructure size
        // limit, not a correctness divergence.
        "YAML document exceeds the limit",
        // Long-running queries on very large synthetic result sets may time out on the cand side
        // while completing on the ref side. Known performance difference, not a correctness bug.
        "milliseconds timeout on connection",
        // Columnar mode can throw a query_shard_exception when a WHERE clause tries to match a
        // string literal against a numeric field (Lucene NumberFormatException: "For input string:
        // \"hello\""). Standard mode silently returns no rows; query-execution path difference.
        "For input string:",
        // semantic_text fields reject full-text match queries (qstr/MATCH) in columnar mode with
        // "does not support match queries", while standard mode handles them. Known mode difference.
        "does not support match queries",
        // Columnar mode has no inverted index for date fields, so a qstr/MATCH query that searches
        // a date field with a non-date string fails with a date-parse error surfaced as unexpected
        // partial results. Standard mode handles this gracefully. Known mode-level difference.
        "failed to parse date field",
        // Columnar mode throws when a qstr/MATCH query is applied to an IP-range field and the
        // search string is not a valid IP literal (e.g. "ring"). Standard mode silently returns
        // no results. Same root cause as "For input string:" for numeric fields.
        "is not an IP string literal",
        // DateExtract.resolveType incorrectly handles null field types (server-side bug). Produces
        // a 500 error on any shard that encounters a null-typed unmapped field in a date_extract()
        // expression. Affects both modes equally but can surface as partial results on one side
        // only due to shard-level execution order differences.
        "Unsupported field type [NULL]",
        // USER_AGENT / REPLACE can produce a NullPointerException ("Cannot invoke
        // String.isEmpty() because this.pattern is null") when applied to certain field
        // combinations. Server-side bug; both modes are equally affected but shard-level execution
        // order means partial results may be reported on one side only.
        "this.pattern\" is null"
    );

    /**
     * Compiled patterns derived from {@link #ALLOWED_MODE_DIFFERENCE_SUBSTRINGS}. Used by
     * {@link #isAllowedModeDifference(String)} to check the throwing side's error message.
     */
    private static final List<Pattern> ALLOWED_MODE_DIFFERENCES;
    static {
        List<Pattern> patterns = new ArrayList<>(ALLOWED_MODE_DIFFERENCE_SUBSTRINGS.size());
        for (String s : ALLOWED_MODE_DIFFERENCE_SUBSTRINGS) {
            patterns.add(Pattern.compile(".*" + Pattern.quote(s) + ".*", Pattern.DOTALL));
        }
        ALLOWED_MODE_DIFFERENCES = Collections.unmodifiableList(patterns);
    }

    /**
     * Matches numbers (including negatives and scientific notation) inside WKT geometry strings.
     * Used by {@link #normalizeSpatialCoords} to round coordinates to 5 significant figures so
     * that doc-values reconstruction precision loss ({@code POINT (5.0 5.0)} vs
     * {@code POINT (4.999999953... 4.999999995...)}) does not produce false value divergences.
     */
    private static final Pattern WKT_NUMBER = Pattern.compile("-?\\d+(?:\\.\\d+)?(?:[Ee][+-]?\\d+)?");

    /** Surviving reference-side index names, set once per JVM by {@link #setupCrossModeIndices}. */
    private static volatile List<String> crossModeRefIndices;

    /** Guards {@link #setupCrossModeIndices} so it runs at most once per JVM. */
    private static volatile boolean crossModeSetupDone;

    // Per-iteration candidate state. Reset in runCommand when prevRef == null (the source command).
    private QueryExecuted candidatePreviousResult;
    private boolean determinismGateOpen;

    /** Number of pipeline steps where the determinism gate was open and value comparison was attempted. */
    private int valueComparedSteps;

    // -----------------------------------------------------------------------------------------
    // Overridable mode pair
    // -----------------------------------------------------------------------------------------

    /**
     * Returns the settings applied on top of each dataset's own settings when creating the
     * reference-side index. Default: plain standard (no extra settings).
     */
    protected Settings referenceSettings() {
        return Settings.EMPTY;
    }

    /**
     * Returns the settings applied on top of each dataset's own settings when creating the
     * candidate-side index. Default: {@code index.mode=columnar}.
     */
    protected Settings candidateSettings() {
        return Settings.builder().put("index.mode", "columnar").build();
    }

    // -----------------------------------------------------------------------------------------
    // REST client settings — extended timeout for setup
    // -----------------------------------------------------------------------------------------

    /**
     * Increases the REST client socket timeout from the default 60 s to 5 minutes.
     *
     * <p>The cross-mode test loads the standard CSV datasets (via the parent {@code @Before
     * setup()}) <em>and</em> the reference and candidate index copies (via {@link
     * #setupCrossModeIndices()}). On a freshly started cluster the combined loading, bulk-indexing,
     * and force-merge of all datasets can take several minutes — well beyond the default 60-second
     * REST-client socket timeout. A system-property override ({@code -Dtests.client.socket.timeout})
     * takes precedence over this default.
     */
    @Override
    protected Settings restClientSettings() {
        Settings base = super.restClientSettings();
        if (base.hasValue(CLIENT_SOCKET_TIMEOUT) == false) {
            return Settings.builder().put(base).put(CLIENT_SOCKET_TIMEOUT, "600s").build();
        }
        return base;
    }

    // -----------------------------------------------------------------------------------------
    // Setup and teardown
    // -----------------------------------------------------------------------------------------

    /**
     * Creates the reference and candidate index sets once per JVM. Datasets that fail columnar
     * index creation are silently skipped on both sides.
     *
     * <p>Runs after (or interleaved with) {@link GenerativeRestTest#setup}, which loads the
     * canonical CSV dataset that provides the shared enrich policies and lookup indices.
     */
    @Before
    public void setupCrossModeIndices() throws IOException {
        synchronized (CrossIndexModeGenerativeRestRunner.class) {
            if (crossModeSetupDone) {
                return;
            }
            List<String> surviving = new ArrayList<>();
            for (CsvTestsDataLoader.TestDataset dataset : availableDatasetsForEs(
                // Lookup indices are excluded: they are used for LOOKUP JOIN, not FROM queries.
                // They are shared (un-prefixed) and already loaded by the parent setup().
                false,
                supportsSourceFieldMapping(),
                false,
                false,
                cap -> false
            )) {
                if (dataset.inferenceEndpoints().isEmpty() == false) {
                    continue;
                }
                if (EXCLUDED_DATASETS.contains(dataset.indexName())) {
                    logger.info("Cross-mode: skipping excluded dataset [{}]", dataset.indexName());
                    continue;
                }
                // TSDB (time_series) datasets have routing_path, counter, and dimension fields
                // that only work in time_series mode. Running them in columnar mode (where the
                // mode overrides their settings) gives a structurally different index, so they
                // are excluded upfront rather than discovered at comparison time.
                if ("time_series".equalsIgnoreCase(dataset.loadSettings().get("index.mode"))) {
                    logger.info("Cross-mode: skipping TSDB dataset [{}]", dataset.indexName());
                    continue;
                }
                CsvTestsDataLoader.TestDataset ref = dataset.withIndex(REF_PREFIX + dataset.indexName());
                CsvTestsDataLoader.TestDataset cand = dataset.withIndex(CAND_PREFIX + dataset.indexName());
                Settings refExtra = referenceSettings();
                Settings candExtra = candidateSettings();
                try {
                    CsvTestsDataLoader.loadDataSetIntoEs(
                        client(),
                        List.of(ref),
                        (c, name, mapping, baseSettings) -> createIndex(
                            name,
                            Settings.builder().put(baseSettings).put(refExtra).build(),
                            mapping
                        )
                    );
                } catch (Exception e) {
                    logger.info("Cross-mode: skipping dataset [{}] (ref creation failed): {}", dataset.indexName(), e.getMessage());
                    continue;
                }
                try {
                    CsvTestsDataLoader.loadDataSetIntoEs(
                        client(),
                        List.of(cand),
                        (c, name, mapping, baseSettings) -> createIndex(
                            name,
                            Settings.builder().put(baseSettings).put(candExtra).build(),
                            // Strict columnar modes reject `store: true` on any field. Strip the
                            // attribute so datasets that carry it (e.g. hosts/mapping-hosts.json)
                            // can be created in columnar mode. Values remain accessible via doc
                            // values and synthetic source, so query results are unaffected.
                            stripStoredFields(mapping)
                        )
                    );
                    surviving.add(REF_PREFIX + dataset.indexName());
                    logger.info("Cross-mode: loaded dataset [{}] as ref+cand", dataset.indexName());
                } catch (Exception e) {
                    // Delete the ref_ index so it does not appear in wildcard patterns like
                    // ref_* and cause schema divergences with the cand_ side.
                    logger.info(
                        "Cross-mode: skipping dataset [{}] (cand creation failed), deleting orphaned ref index: {}",
                        dataset.indexName(),
                        e.getMessage()
                    );
                    try {
                        deleteIndex(ref.indexName());
                    } catch (Exception de) {
                        logger.warn("Cross-mode: failed to delete orphaned ref index [{}]: {}", ref.indexName(), de.getMessage());
                    }
                }
            }
            assertTrue("No datasets survived candidate index creation — cross-mode test has no coverage", surviving.isEmpty() == false);
            logger.info("Cross-mode: {} datasets loaded (ref+cand)", surviving.size());
            crossModeRefIndices = Collections.unmodifiableList(surviving);
            crossModeSetupDone = true;
        }
    }

    /** Resets per-JVM state so a fresh run always re-creates indices. */
    @AfterClass
    public static void resetCrossModeState() {
        crossModeRefIndices = null;
        crossModeSetupDone = false;
    }

    /**
     * Logs how many pipeline steps performed value comparison this run.
     *
     * <p>A count of zero is not a hard failure: it legitimately occurs when every FROM query
     * produced exactly 1 000 rows (the implicit {@code LIMIT 1000} closed the determinism gate
     * at step 0), which happens when a wide wildcard pattern matches enough loaded datasets to
     * saturate the limit. It is logged as a warning so that a persistent zero across many seeds
     * is visible and worth investigating, but it does not fail the test.
     */
    @After
    public void logValueComparisonCount() {
        if (valueComparedSteps == 0) {
            logger.debug(
                "Cross-mode: no pipeline steps were value-compared this run (valueComparedSteps=0). "
                    + "The determinism gate may be closing too early — check updateDeterminismGate()."
            );
        } else {
            logger.info("Cross-mode value-compared steps this run: {}", valueComparedSteps);
        }
    }

    // -----------------------------------------------------------------------------------------
    // Allowed errors — transient infrastructure errors that are acceptable on either side
    // -----------------------------------------------------------------------------------------

    /**
     * Extra error patterns beyond {@link GenerativeRestTest#ALLOWED_ERRORS} that are acceptable in
     * cross-mode runs. These cover infrastructure transients (timeouts, connection drops) and
     * engine-level differences (Lucene {@code NumberFormatException}) that are already guarded by
     * {@link #ALLOWED_MODE_DIFFERENCES} at the cross-mode parity layer but must also be listed here
     * so that the base-class {@code checkPipelineException} does not fail the test when only one side
     * throws.
     */
    @Override
    protected Set<String> additionalAllowedErrors() {
        Set<String> errors = new HashSet<>(super.additionalAllowedErrors());
        // All mode-difference substrings are acceptable on either side of the pipeline.
        errors.addAll(ALLOWED_MODE_DIFFERENCE_SUBSTRINGS);
        return errors;
    }

    // -----------------------------------------------------------------------------------------
    // Generator hooks
    // -----------------------------------------------------------------------------------------

    @Override
    protected FromGenerator sourceCommand() {
        return new DualModeFromGenerator(REF_PREFIX, CAND_PREFIX);
    }

    @Override
    protected List<String> availableIndices() {
        return crossModeRefIndices;
    }

    // -----------------------------------------------------------------------------------------
    // Execution hook — runs both sides and compares
    // -----------------------------------------------------------------------------------------

    @Override
    protected QueryExecuted runCommand(QueryExecuted prevRef, CommandGenerator.CommandDescription current) {
        // Reset per-iteration candidate state when this is the pipeline's source command.
        if (prevRef == null) {
            candidatePreviousResult = null;
            determinismGateOpen = true;
        }

        // Determine the reference and candidate command strings.
        Object mirror = current.context().get(DualModeFromGenerator.MIRROR_COMMAND);
        String refCmd;
        String candCmd;
        if (mirror != null) {
            // Source command: each side has its own FROM clause.
            refCmd = current.commandString();
            candCmd = (String) mirror;
        } else {
            // Pipe command: the same text applies to both sides.
            refCmd = current.commandString();
            candCmd = current.commandString();
        }

        // Execute the reference side.
        QueryExecuted refResult = prevRef == null ? execute(refCmd, 0) : execute(prevRef.query() + refCmd, prevRef.depth());

        // Execute the candidate side.
        QueryExecuted candResult = candidatePreviousResult == null
            ? execute(candCmd, 0)
            : execute(candidatePreviousResult.query() + candCmd, candidatePreviousResult.depth());

        // Update the determinism gate before comparing.
        determinismGateOpen = updateDeterminismGate(determinismGateOpen, current, refResult, prevRef);

        // Compare the two sides.
        compareSides(current, refResult, candResult, determinismGateOpen);

        // Advance the candidate state for the next step.
        candidatePreviousResult = candResult;

        return refResult;
    }

    // -----------------------------------------------------------------------------------------
    // Determinism gate
    // -----------------------------------------------------------------------------------------

    /**
     * Returns {@code false} if value comparison can no longer be trusted for the remaining steps
     * in this pipeline iteration. The gate latches to {@code false} and never re-opens.
     */
    private static boolean updateDeterminismGate(
        boolean currentGate,
        CommandGenerator.CommandDescription current,
        QueryExecuted refResult,
        QueryExecuted prevRef
    ) {
        if (currentGate == false) {
            return false;
        }
        String cmdText = current.commandString().toUpperCase(Locale.ROOT);
        String cmdName = current.commandName();

        // Non-deterministic built-in functions. SAMPLE(field,n) draws a random subset and
        // can return different rows from the two physically different index layouts.
        if (cmdText.contains("NOW(") || cmdText.contains("RANDOM(") || cmdText.contains("SAMPLE(")) {
            return false;
        }
        // Full-text search functions and the `:` operator rely on the inverted index. Columnar
        // mode stores keyword fields exclusively via doc values (index_disabled_by_default=true
        // disables the inverted index for fields that lack an explicit "index: true" mapping), so
        // full-text / term queries on those fields return different rows compared to standard mode
        // where the inverted index is always present. Value comparison is not meaningful once
        // these appear.
        if (cmdText.contains("MATCH_PHRASE(")
            || cmdText.contains("MATCH(")
            || cmdText.contains("QSTR(")
            || cmdText.contains("KQL(")
            || cmdText.contains("SCORE(")
            || cmdText.contains(": \"")) {
            return false;
        }
        // Order-sensitive MV functions: columnar mode preserves the original source-insertion order
        // of multi-value fields (via the array-order block loader), while standard mode returns them
        // in ascending doc-values order (SortedNumericDocValues / SortedSetDocValues). These
        // functions either select, slice, concatenate, or compute differences between consecutive
        // elements in field order — all produce different output when the input ordering differs.
        // See also: ints.csv-spec:795+, string.csv-spec:696+, mv_expand.csv-spec:104+
        // (skip_columnar markers that document the same ordering divergence for each function).
        if (cmdText.contains("MV_SLICE(")
            || cmdText.contains("MV_FIRST(")
            || cmdText.contains("MV_LAST(")
            || cmdText.contains("MV_CONCAT(")
            || cmdText.contains("MV_DIFFERENCE(")) {
            return false;
        }
        // LEAST / GREATEST applied to multi-value fields are element-wise: they pair up values by
        // position across their arguments and return MV results whose element order depends on the
        // insertion / doc-values order of the input fields. Close the gate whenever either appears.
        if (cmdText.contains("LEAST(") || cmdText.contains("GREATEST(")) {
            return false;
        }
        // FIRST() / LAST() pick the search-field value from the row with the minimum (FIRST) or
        // maximum (LAST) sort value. Two effects make cross-mode value comparison unreliable, and
        // both are expected divergences rather than correctness bugs:
        // 1. Ties in the sort column: when several rows share the winning sort value, either
        // physical layout may legitimately pick a different row's search-field value.
        // 2. Multi-value search field: the returned cell keeps source element order, which
        // differs between the two modes (columnar source-insertion order vs standard ascending
        // doc-values order). The multiset is identical but e.g. [false, true] vs [true, false]
        // compares unequal. Same ordering artifact already gated for MV_FIRST/MV_LAST/MV_SLICE.
        // Correct columnar behavior for boolean MV fields (no spurious null) is covered by the
        // stats_first_last.csv-spec "Test retrieval of multi-values" case, which CsvColumnarIT runs
        // against voyager's low_power_mode field.
        // Note: contains("FIRST(") also matches MV_FIRST(, and contains("LAST(") matches MV_LAST(;
        // both share the same ordering-sensitivity rationale. The generator never emits a bare
        // last(...) aggregate, so LAST( here only catches MV_LAST(.
        if (cmdText.contains("FIRST(") || cmdText.contains("LAST(")) {
            return false;
        }
        // Commands whose output order depends on per-segment or per-shard execution order.
        if ("sample".equals(cmdName) || "fork".equals(cmdName) || "change_point".equals(cmdName)) {
            return false;
        }
        // DEDUP deduplicates rows by all column values. Columnar mode preserves MV fields in
        // source-insertion order, while standard mode returns them in ascending doc-values order.
        // Two rows that appear identical under standard-mode ordering (both MV cells sorted) may
        // differ in columnar (one cell [a,b], another [b,a]), so DEDUP can remove a different
        // number of rows in each mode. Close the gate once DEDUP appears to prevent false-positive
        // row-count divergences.
        if ("dedup".equals(cmdName)) {
            return false;
        }
        // HIGHLIGHT returns a highlighted snippet from stored source (standard mode) versus
        // synthetic source / doc-values (columnar mode). For MV fields the highlighted value
        // is selected by position — doc-values order (sorted) in standard, source-insertion order
        // in columnar — so the returned snippet can legitimately differ between the two modes.
        if ("highlight".equals(cmdName)) {
            return false;
        }
        // Truncating commands: close the gate only if the row count actually decreased,
        // indicating that the top-N selection was applied and may differ between index modes.
        if (("limit".equals(cmdName) || "limit_by".equals(cmdName))
            && prevRef != null
            && prevRef.result() != null
            && refResult.result() != null
            && refResult.result().size() < prevRef.result().size()) {
            return false;
        }
        // The implicit LIMIT 1000 may have kicked in and selected an arbitrary top-1000.
        if (refResult.result() != null && refResult.result().size() == 1000) {
            return false;
        }
        return true;
    }

    // -----------------------------------------------------------------------------------------
    // Comparison
    // -----------------------------------------------------------------------------------------

    /**
     * Compares the reference and candidate results for one pipeline step.
     *
     * <p>Always checks: failure parity (§1) and output schema (§2).
     * When {@code deterministic} is {@code true}, also checks values (§3).
     */
    private void compareSides(CommandGenerator.CommandDescription current, QueryExecuted ref, QueryExecuted cand, boolean deterministic) {
        boolean refThrew = ref.exception() != null;
        boolean candThrew = cand.exception() != null;

        // 1. Failure parity
        if (refThrew != candThrew) {
            String refMsg = refThrew ? ref.exception().getMessage() : null;
            String candMsg = candThrew ? cand.exception().getMessage() : null;
            // Check both messages: either side's error may be the pattern we allow.
            if (isAllowedModeDifference(refMsg) || isAllowedModeDifference(candMsg)) {
                return;
            }
            fail(
                "Cross-mode failure parity divergence at ["
                    + current.commandName()
                    + "]:\n"
                    + "  reference "
                    + (refThrew ? "THREW" : "succeeded")
                    + ": "
                    + refMsg
                    + "\n"
                    + "  candidate "
                    + (candThrew ? "THREW" : "succeeded")
                    + ": "
                    + candMsg
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
        }

        // Both threw — nothing more to compare.
        if (refThrew) {
            return;
        }

        // 2. Schema
        List<Column> refSchema = ref.outputSchema();
        List<Column> candSchema = cand.outputSchema();
        if (refSchema == null && candSchema == null) {
            return;
        }
        if (refSchema == null || candSchema == null || refSchema.size() != candSchema.size()) {
            fail(
                "Cross-mode schema divergence at ["
                    + current.commandName()
                    + "]:\n"
                    + "  reference schema: "
                    + refSchema
                    + "\n"
                    + "  candidate schema: "
                    + candSchema
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        for (int col = 0; col < refSchema.size(); col++) {
            Column rCol = refSchema.get(col);
            Column cCol = candSchema.get(col);
            if (rCol.name().equals(cCol.name()) == false || rCol.type().equals(cCol.type()) == false) {
                fail(
                    "Cross-mode schema divergence at column "
                        + col
                        + " in ["
                        + current.commandName()
                        + "]:\n"
                        + "  reference column: "
                        + rCol
                        + "\n"
                        + "  candidate column: "
                        + cCol
                        + "\n"
                        + "  reference query: "
                        + ref.query()
                        + "\n"
                        + "  candidate query: "
                        + cand.query()
                );
            }
        }

        // 3. Values (only while the determinism gate is open)
        if (deterministic == false) {
            return;
        }
        valueComparedSteps++;
        List<List<Object>> refRows = ref.result();
        List<List<Object>> candRows = cand.result();
        if (refRows == null && candRows == null) {
            return;
        }
        if (refRows == null || candRows == null) {
            fail(
                "Cross-mode values divergence: one side returned null rows at ["
                    + current.commandName()
                    + "]\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        if (refRows.size() != candRows.size()) {
            fail(
                "Cross-mode values divergence: row count differs at ["
                    + current.commandName()
                    + "]: reference="
                    + refRows.size()
                    + " candidate="
                    + candRows.size()
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        List<String> refCanon = toCanonical(refRows, refSchema);
        List<String> candCanon = toCanonical(candRows, refSchema);
        Collections.sort(refCanon);
        Collections.sort(candCanon);
        for (int row = 0; row < refCanon.size(); row++) {
            if (refCanon.get(row).equals(candCanon.get(row)) == false) {
                fail(
                    "Cross-mode values divergence at sorted row "
                        + row
                        + " in ["
                        + current.commandName()
                        + "]:\n"
                        + "  reference: "
                        + refCanon.get(row)
                        + "\n"
                        + "  candidate: "
                        + candCanon.get(row)
                        + "\n"
                        + "  reference query: "
                        + ref.query()
                        + "\n"
                        + "  candidate query: "
                        + cand.query()
                );
            }
        }
    }

    private static boolean isAllowedModeDifference(String errorMessage) {
        if (errorMessage == null) {
            return false;
        }
        for (Pattern p : ALLOWED_MODE_DIFFERENCES) {
            if (p.matcher(errorMessage).matches()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Column types whose values are skipped in the row comparison.
     *
     * <ul>
     *   <li>{@code geo_point}, {@code cartesian_point}: read from stored {@code _source} (standard
     *       mode) versus synthetic source (columnar mode) can differ at the last displayed decimal
     *       place due to Lucene's 32-bit integer encoding. Values that sit exactly on a rounding
     *       boundary (e.g. {@code -171.75 → "-171.7"} vs {@code "-171.8"}) produce differences
     *       that no fixed significant-figure rounding can reconcile without becoming too coarse to
     *       catch real bugs.</li>
     *   <li>{@code flattened}: object values contain nested arrays (e.g. {@code host.ip}) whose
     *       element order differs between columnar mode (source-insertion order, via the array-order
     *       block loader) and standard mode (ascending doc-values order). Skipping prevents
     *       false-positive failures while schema divergence (missing or renamed column) is still
     *       caught by the schema check.</li>
     * </ul>
     */
    private static final Set<String> SKIP_VALUE_COLUMN_TYPES = Set.of("geo_point", "cartesian_point", "flattened");

    /**
     * Column types backed by {@code SortedSetDocValues} in standard mode: ES|QL loads these via
     * an ordinality-based block loader that returns values in ascending sorted order and drops
     * duplicates. In columnar mode the array-order block loader is used instead, returning values
     * in source-insertion order with duplicates preserved.
     *
     * <p>When comparing MV cells of these types the two sides can therefore differ in both ordering
     * and cardinality: a keyword field stored as {@code ["b","a","a"]} yields {@code ["a","b"]} in
     * standard mode but {@code ["b","a","a"]} in columnar mode. The canonical form renders such
     * cells as a sorted, distinct (set-like) list so both representations compare equal.
     *
     * <p>Numeric and boolean types use {@code SortedNumericDocValues}, which sorts but does
     * <em>not</em> deduplicate — the two sides differ only in ordering, which is already absorbed
     * by the element-sort in {@link #toCanonical}. Those types are therefore <em>not</em> listed
     * here; collapsing their duplicates would mask a real data-loss bug.
     *
     * <p>References: {@code keyword.md:137} ("may sort keyword fields and remove duplicates"),
     * {@code ip.md:130}, {@code version.md:51}, and
     * {@link org.elasticsearch.index.mapper.KeywordFieldMapper} {@code preservesArrayOrder()}.
     */
    static final Set<String> SORTED_SET_BACKED_TYPES = Set.of("keyword", "text", "ip", "version", "wildcard");

    /**
     * Converts a result set to a list of canonical row strings for order-insensitive comparison.
     *
     * <p>Each cell is rendered by {@link #canonicalValue}. List-valued cells (multi-value fields)
     * have their elements sorted before rendering to absorb the ordering difference: columnar mode
     * returns MV fields in source-insertion order while standard mode returns them in ascending
     * doc-values order. For types in {@link #SORTED_SET_BACKED_TYPES} (e.g. {@code keyword}),
     * standard mode also deduplicates; cells of those types are additionally deduplicated here so
     * that e.g. columnar's {@code ["b","a","a"]} and standard's {@code ["a","b"]} compare equal.
     *
     * <p>Columns whose type is in {@link #SKIP_VALUE_COLUMN_TYPES} are replaced by a constant
     * placeholder so that inherent precision differences (stored vs synthetic source coordinate
     * encoding) do not produce false-positive failures.
     */
    @SuppressWarnings("unchecked")
    static List<String> toCanonical(List<List<Object>> rows, List<Column> schema) {
        List<String> result = new ArrayList<>(rows.size());
        for (List<Object> row : rows) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < row.size(); i++) {
                if (i > 0) {
                    sb.append('\t');
                }
                String colType = i < schema.size() ? schema.get(i).type() : null;
                if (SKIP_VALUE_COLUMN_TYPES.contains(colType)) {
                    sb.append("~");
                    continue;
                }
                Object val = row.get(i);
                if (val instanceof List) {
                    List<String> strs = new ArrayList<>();
                    for (Object v : (List<Object>) val) {
                        strs.add(canonicalValue(v));
                    }
                    Collections.sort(strs);
                    if (SORTED_SET_BACKED_TYPES.contains(colType)) {
                        // Deduplicate after sorting: standard mode's SortedSetDocValues removes
                        // duplicates, while columnar mode preserves them. Collapsing them here lets
                        // ["a","b"] (standard) == ["b","a","a"] (columnar) after sort+dedup.
                        strs = strs.stream().distinct().toList();
                    }
                    sb.append(strs);
                } else {
                    sb.append(canonicalValue(val));
                }
            }
            result.add(sb.toString());
        }
        return result;
    }

    /**
     * Renders a single cell value as a canonical string.
     *
     * <p>Doubles are rounded to 5 significant figures to absorb tiny floating-point differences
     * that arise when re-encoding values through doc values in columnar mode, and from Welford-style
     * variance / std_dev merges whose residuals can differ by ~1 ULP across index layouts (e.g.
     * {@code -1.43178} vs {@code -1.43177}). Additionally, values whose absolute magnitude is below
     * {@code 1e-9} are snapped to {@code 0.0} to absorb the residual that can leave one side at
     * {@code 0.0} and the other at {@code ~1e-32} when the true result is zero (see
     * <a href="https://github.com/elastic/elasticsearch/issues/156988">#156988</a>). The threshold
     * is many orders of magnitude above the residual ({@code ~1e-32}) and many orders of magnitude
     * below any meaningful small result in the CSV test datasets.
     *
     * <p>Strings that look like WKT geometry ({@code POINT (…)}, {@code POLYGON (…)}, etc.) have
     * their coordinate numbers rounded to the same 5 significant figures. Doc-values-based
     * reconstruction of geo/cartesian points introduces ~1e-7 relative precision loss — for
     * example a stored {@code POINT (5.0 5.0)} can come back as
     * {@code POINT (4.999999953433871 4.999999995343387)} in columnar mode.
     */
    static String canonicalValue(Object val) {
        if (val instanceof Double d) {
            if (Double.isNaN(d) || Double.isInfinite(d)) {
                return String.valueOf(d);
            }
            // Snap near-zero values before relative rounding, which is meaningless at zero.
            if (Math.abs(d) < 1e-9) {
                return "0.0";
            }
            return String.valueOf(new BigDecimal(d).round(new MathContext(5, RoundingMode.HALF_DOWN)).doubleValue());
        }
        String s = String.valueOf(val);
        if (isWktString(s)) {
            return normalizeSpatialCoords(s);
        }
        return s;
    }

    /** Returns true when {@code s} is a WKT geometry string (starts with a known geometry type keyword). */
    private static boolean isWktString(String s) {
        return s.startsWith("POINT (")
            || s.startsWith("LINESTRING (")
            || s.startsWith("POLYGON (")
            || s.startsWith("MULTIPOINT (")
            || s.startsWith("MULTILINESTRING (")
            || s.startsWith("MULTIPOLYGON (")
            || s.startsWith("GEOMETRYCOLLECTION (");
    }

    /**
     * Removes all {@code "store": true} attributes from a mapping JSON string.
     *
     * <p>Strict columnar index modes (e.g. {@code index.mode=columnar}) reject any field that has
     * {@code store: true} at mapping-parse time. The ES|QL CSV test fixtures retain that attribute
     * in some mappings (e.g. {@code mapping-hosts.json}) for use in non-columnar test suites. To
     * allow those datasets to be created in columnar mode, the candidate-side index creator strips
     * the attribute before forwarding the mapping to the server. Field values are still readable
     * via doc values and synthetic source, so all ES|QL CSV tests exercise the same query paths.
     */
    private static String stripStoredFields(String mapping) throws IOException {
        Map<String, Object> map = XContentHelper.convertToMap(JsonXContent.jsonXContent, mapping, false);
        removeKey(map, "store");
        try (XContentBuilder builder = JsonXContent.contentBuilder()) {
            builder.map(map);
            return Strings.toString(builder);
        }
    }

    @SuppressWarnings("unchecked")
    private static void removeKey(Map<String, Object> map, String key) {
        map.remove(key);
        for (Object value : map.values()) {
            if (value instanceof Map) {
                removeKey((Map<String, Object>) value, key);
            }
        }
    }

    /**
     * Rounds every numeric coordinate within a WKT geometry string to 5 significant figures,
     * absorbing doc-values reconstruction precision loss for geo/cartesian point types.
     */
    private static String normalizeSpatialCoords(String wkt) {
        return WKT_NUMBER.matcher(wkt).replaceAll(mr -> {
            String coord = mr.group();
            try {
                double d = Double.parseDouble(coord);
                return String.valueOf(new BigDecimal(d).round(new MathContext(5, RoundingMode.HALF_DOWN)).doubleValue());
            } catch (NumberFormatException e) {
                return coord;
            }
        });
    }

}
