/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.rest.generative;

import org.elasticsearch.common.Strings;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;
import org.elasticsearch.xcontent.XContentBuilder;
import org.elasticsearch.xcontent.json.JsonXContent;
import org.elasticsearch.xpack.esql.CsvTestsDataLoader;
import org.elasticsearch.xpack.esql.generator.Column;
import org.elasticsearch.xpack.esql.generator.QueryExecuted;
import org.elasticsearch.xpack.esql.generator.command.CommandGenerator;
import org.elasticsearch.xpack.esql.generator.command.source.DualModeFromGenerator;
import org.elasticsearch.xpack.esql.generator.command.source.FromGenerator;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import static org.elasticsearch.xpack.esql.CsvTestsDataLoader.availableDatasetsForEs;

/**
 * Base class for differential generative ES|QL tests.
 *
 * <p>Runs the same randomly generated pipeline against two indices that hold identical data but
 * different index settings, then compares the results. A divergence in failure/success, output
 * schema, or values indicates a correctness bug in one of the index modes.
 *
 * <p>The reference index set uses {@link #referenceSettings()} (plain {@code standard} by default)
 * and the candidate set uses {@link #candidateSettings()} ({@code columnar} by default). Both sets
 * are created from the standard CSV test datasets under a distinct name prefix ({@value #REF_PREFIX}
 * vs {@value #CAND_PREFIX}), so wildcard patterns generated by {@link DualModeFromGenerator} are
 * always namespace-scoped and never cross between the two sets.
 *
 * <p>Datasets that fail columnar index creation (because their mapping cannot be fully reconstructed
 * from doc values) are automatically skipped on both sides; the test asserts that at least one
 * dataset survives so coverage is never silently lost. Datasets in {@link #EXCLUDED_DATASETS} are
 * excluded up front because they create successfully in columnar mode but produce legitimately
 * different results (e.g. {@code index:false} fields are no-ops in columnar mode).
 *
 * <p>Comparison is three-layered, applied at every pipeline step:
 * <ol>
 *   <li><b>Failure parity</b> — both threw or neither threw. If exactly one threw the test fails,
 *       unless the message matches {@link #ALLOWED_MODE_DIFFERENCES}.</li>
 *   <li><b>Schema</b> — same column names in the same order, same types.</li>
 *   <li><b>Values</b> — order-insensitive multiset equality (rows are sorted canonically before
 *       comparison; multi-value cells are element-sorted to absorb stored-vs-synthetic ordering
 *       differences). Only checked while the per-iteration <em>determinism gate</em> is open.</li>
 * </ol>
 *
 * <p>The determinism gate closes when a row-truncating or non-deterministic command appears in
 * the pipeline, or when either side returns exactly 1 000 rows (the implicit {@code LIMIT 1000}
 * may have kicked in). After the gate closes, failure parity and schema are still checked for
 * the remaining pipeline steps.
 *
 * <p>Scope for this first cut: single-node, non-time-series, {@link
 * org.elasticsearch.xpack.esql.generator.GenerativeFeature#BASELINE} only.
 *
 * <p>See {@code LogsDbSubobjectsFalseVersusLogsDbColumnarRestIT} (logsdb module) for a catalogue
 * of known behavioral differences between {@code standard} and {@code columnar} mode that informed
 * {@link #EXCLUDED_DATASETS} and {@link #ALLOWED_MODE_DIFFERENCES}.
 */
public abstract class CrossIndexModeGenerativeRestTest extends GenerativeRestTest {

    private static final Logger logger = LogManager.getLogger(CrossIndexModeGenerativeRestTest.class);

    /** Name prefix for reference-side indices (plain {@code standard} mode by default). */
    public static final String REF_PREFIX = "ref_";

    /** Name prefix for candidate-side indices ({@code columnar} mode by default). */
    public static final String CAND_PREFIX = "cand_";

    /**
     * Datasets excluded from cross-mode testing because they create successfully in columnar mode
     * but produce legitimately different results. Derived from the catalogue in
     * {@code LogsDbSubobjectsFalseVersusLogsDbColumnarRestIT} (logsdb module) and
     * {@link org.elasticsearch.xpack.esql.qa.rest.AllSupportedFieldsTestCase}.
     *
     * <ul>
     *   <li>{@code airports_not_indexed}, {@code airports_no_doc_values},
     *       {@code airports_not_indexed_nor_doc_values}: {@code index:false} / {@code doc_values:false}
     *       are effectively no-ops in strict columnar mode — every field gets doc values and is
     *       searchable — so query results differ by design from a standard index where those settings
     *       are honoured.</li>
     *   <li>{@code addresses_text}, {@code employees_gender_text}: keyword-to-text variant datasets.
     *       Columnar mode auto-converts text fields to keyword, so the ref_ variant (text) and the
     *       base ref_ index (keyword) produce a type conflict ({@code [keyword, text] → unsupported})
     *       under wildcard {@code ref_*} queries, while the cand_ side sees no conflict (all keyword).
     *       This structural divergence is not a correctness bug.</li>
     * </ul>
     */
    private static final Set<String> EXCLUDED_DATASETS = Set.of(
        // index:false / doc_values:false are no-ops in columnar — searchability and loadability
        // differ by design from a standard index that honours those settings.
        "airports_not_indexed",
        "airports_no_doc_values",
        "airports_not_indexed_nor_doc_values",
        // geo_point fields (city_location) are stored at different precision in columnar mode:
        // to_string(city_location) returns e.g. "POINT (116.073 5.975)" on standard but
        // "POINT (116.072 5.975)" on columnar — a known encoding precision difference.
        "airports",
        "airports_web",
        // Mapping designed to be type-incompatible with the standard employees dataset; its CSV
        // data contains deliberate duplicates in boolean MV fields (e.g. [false,true,true]).
        // SortedSetDocValues deduplicates those in standard mode while columnar may preserve them,
        // producing spurious divergences that are not meaningful correctness signals.
        "employees_incompatible",
        // Multi-value double fields (rows carry [1.1], [1.1,2.2], …, [1.1,…,5.5]) cause COUNT to
        // diverge: standard mode counts individual MV values whereas columnar mode counts documents.
        // Excluded until the COUNT-on-MV behaviour is reconciled between the two modes.
        "all_types_mv",
        // The all_types family uses mapping-all-types.json which contains `semantic_text` and
        // `dense_vector` field types. These types appear in field_caps for standard mode but are
        // absent from columnar mode's field_caps, causing a schema-size divergence whenever any
        // wildcard pattern matches ref_all_types* indices. The mapping also has a `short`-typed
        // field named "short"; columnar normalises short → long, so wildcard queries that combine
        // an all_types index (short: short) with any other index that has a "short: long" field
        // produce type-conflict unsupported[long, short] on the reference side but a clean "long"
        // on the candidate side.
        "all_types",
        "all_types_no_short",
        "all_types_short_as_long",
        // Variant of `apps` with `id` overridden to type short. Standard mode returns the field as
        // short in field_caps; when combined with the base `apps` index (id: integer) under a
        // wildcard pattern, ref_* sees type-conflict unsupported[integer, short], while cand_*
        // normalises short → integer (no conflict). Not a correctness bug.
        "apps_short",
        // Contains a plain `txt: text` field that has no doc_values. Columnar mode requires all
        // fields to be reconstructable from doc values for synthetic source, so this dataset either
        // fails cand_ index creation or produces a schema divergence (txt absent from the
        // columnar-side schema). Excluded to prevent wildcard patterns from matching an orphaned
        // ref_text_state_mapped index.
        "text_state_mapped",
        // 245 000+ documents with MV integer fields. Bulk indexing and force-merge of this volume
        // in columnar mode can time out or exceed REST client limits, leaving an orphaned ref_
        // index that pollutes wildcard schema resolution.
        "many_numbers",
        // Variant of `addresses` that overrides keyword fields (street, city.name,
        // city.country.name, city.country.continent.name, …) to text. Columnar mode auto-converts
        // those text fields to keyword (doc_values), so ref_addresses_text ends up with text while
        // cand_addresses_text ends up with keyword. A wildcard query like `from ref_*` matches both
        // ref_addresses (keyword) and ref_addresses_text (text), making field_caps report type
        // conflict [keyword, text] → unsupported; cand_* sees no conflict (all keyword). This
        // structural schema divergence is not a correctness bug.
        "addresses_text",
        // Variant of `employees` with the `gender` field overridden to text. Same root cause as
        // addresses_text: ref_employees (keyword) and ref_employees_gender_text (text) produce a
        // type conflict under ref_* wildcards, while cand_* consistently sees keyword in columnar.
        "employees_gender_text",
        // Contains a `payload: text` field that survives columnar index creation (other fields
        // provide doc_values) but causes the server to crash when queried in columnar mode.
        // Until root-caused, exclude to prevent cluster instability during the generative test run.
        "json_logs",
        // Contains a `notes: text` field with the same issue as json_logs: cand_voyager creates
        // successfully but querying it in columnar mode crashes the server.
        "voyager",
        // Multi-value date fields (rows carry [1952,1962] and [2003,1998]) cause COUNT to diverge:
        // standard mode counts individual MV values while columnar mode counts documents. Same root
        // cause as all_types_mv. Excluded until COUNT-on-MV behaviour is reconciled.
        "mv_decades",
        // Cartesian multi-polygon shape data fails to bulk-index in columnar mode (the cartesian_shape
        // field cannot be stored via doc_values for synthetic source), leaving cand_cartesian_multipolygons
        // with 0 documents while ref_cartesian_multipolygons has the full dataset. Any WHERE clause then
        // returns 21 rows on the reference side and 0 on the candidate side.
        "cartesian_multipolygons",
        // ul_logs has unsigned_long fields named `bytes_in` and `bytes_out`. A known columnar bug
        // causes STATS output aliases with the same names to read from the wrong source when the
        // alias name conflicts with an existing index field, producing incorrect aggregate values.
        // Excluded until the columnar alias-resolution bug is fixed.
        "ul_logs",
        // conv_from_keyword contains keyword fields (geotile_str, geohash_str, etc.) that are not
        // indexed in columnar mode (index.mapping.index_disabled_by_default=true disables the
        // inverted index for fields without an explicit "index: true"). Full-text queries (`:`)
        // on those fields return different results between the two modes.
        "conv_from_keyword"
    );

    /**
     * Substrings of error messages that indicate a known benign mode difference. Each entry is
     * matched as a case-sensitive substring against the throwing side's message. The same list
     * drives both {@link #ALLOWED_MODE_DIFFERENCES} (used for cross-mode parity checks) and
     * {@link #additionalAllowedErrors()} (used by the base-class pipeline exception guard), so
     * every allowed substring is declared exactly once.
     *
     * <p>Add entries here — with a comment explaining the root cause — as real benign divergences
     * are identified. Follows the house style of {@link GenerativeRestTest#ALLOWED_ERRORS}.
     */
    private static final List<String> ALLOWED_MODE_DIFFERENCE_SUBSTRINGS = List.of(
        // Extremely wide result sets (many indices × many fields) can push the HTTP/YAML response
        // past the 3 MB REST-client parse limit on one side only. This is an infrastructure size
        // limit, not a correctness divergence.
        "YAML document exceeds the limit",
        // Long-running queries on very large synthetic result sets may time out on the cand side
        // while completing on the ref side. Known performance difference, not a correctness bug.
        "milliseconds timeout on connection",
        // Columnar mode can throw a query_shard_exception when a WHERE clause tries to match a
        // string literal against a numeric field (Lucene NumberFormatException: "For input string:
        // \"hello\""). Standard mode silently returns no rows; query-execution path difference.
        "For input string:",
        // semantic_text fields reject full-text match queries (qstr/MATCH) in columnar mode with
        // "does not support match queries", while standard mode handles them. Known mode difference.
        "does not support match queries",
        // Columnar mode has no inverted index for date fields, so a qstr/MATCH query that searches
        // a date field with a non-date string fails with a date-parse error surfaced as unexpected
        // partial results. Standard mode handles this gracefully. Known mode-level difference.
        "failed to parse date field",
        // Columnar mode throws when a qstr/MATCH query is applied to an IP-range field and the
        // search string is not a valid IP literal (e.g. "ring"). Standard mode silently returns
        // no results. Same root cause as "For input string:" for numeric fields.
        "is not an IP string literal",
        // Columnar mode FORK execution has a known array-bounds bug (Index N out of bounds for
        // length N) that surfaces as HTTP 500 on the candidate side while the reference succeeds.
        // TODO: remove once the columnar FORK array-bounds bug is fixed.
        "out of bounds for length",
        // DateExtract.resolveType incorrectly handles null field types (server-side bug). Produces
        // a 500 error on any shard that encounters a null-typed unmapped field in a date_extract()
        // expression. Affects both modes equally but can surface as partial results on one side
        // only due to shard-level execution order differences.
        "Unsupported field type [NULL]",
        // USER_AGENT / REPLACE can produce a NullPointerException ("Cannot invoke
        // String.isEmpty() because this.pattern is null") when applied to certain field
        // combinations. Server-side bug; both modes are equally affected but shard-level execution
        // order means partial results may be reported on one side only.
        "this.pattern\" is null"
    );

    /**
     * Compiled patterns derived from {@link #ALLOWED_MODE_DIFFERENCE_SUBSTRINGS}. Used by
     * {@link #isAllowedModeDifference(String)} to check the throwing side's error message.
     */
    private static final List<Pattern> ALLOWED_MODE_DIFFERENCES;
    static {
        List<Pattern> patterns = new ArrayList<>(ALLOWED_MODE_DIFFERENCE_SUBSTRINGS.size());
        for (String s : ALLOWED_MODE_DIFFERENCE_SUBSTRINGS) {
            patterns.add(Pattern.compile(".*" + Pattern.quote(s) + ".*", Pattern.DOTALL));
        }
        ALLOWED_MODE_DIFFERENCES = Collections.unmodifiableList(patterns);
    }

    /**
     * Matches numbers (including negatives and scientific notation) inside WKT geometry strings.
     * Used by {@link #normalizeSpatialCoords} to round coordinates to 6 significant figures so
     * that doc-values reconstruction precision loss ({@code POINT (5.0 5.0)} vs
     * {@code POINT (4.999999953... 4.999999995...)}) does not produce false value divergences.
     */
    private static final Pattern WKT_NUMBER = Pattern.compile("-?\\d+(?:\\.\\d+)?(?:[Ee][+-]?\\d+)?");

    /** Surviving reference-side index names, set once per JVM by {@link #setupCrossModeIndices}. */
    private static volatile List<String> crossModeRefIndices;

    /** Guards {@link #setupCrossModeIndices} so it runs at most once per JVM. */
    private static volatile boolean crossModeSetupDone;

    // Per-iteration candidate state. Reset in runCommand when prevRef == null (the source command).
    private QueryExecuted candidatePreviousResult;
    private boolean determinismGateOpen;

    /** Number of pipeline steps where the determinism gate was open and value comparison was attempted. */
    private int valueComparedSteps;

    // -----------------------------------------------------------------------------------------
    // Overridable mode pair
    // -----------------------------------------------------------------------------------------

    /**
     * Returns the settings applied on top of each dataset's own settings when creating the
     * reference-side index. Default: plain standard (no extra settings).
     */
    protected Settings referenceSettings() {
        return Settings.EMPTY;
    }

    /**
     * Returns the settings applied on top of each dataset's own settings when creating the
     * candidate-side index. Default: {@code index.mode=columnar}.
     */
    protected Settings candidateSettings() {
        return Settings.builder().put("index.mode", "columnar").build();
    }

    // -----------------------------------------------------------------------------------------
    // REST client settings — extended timeout for setup
    // -----------------------------------------------------------------------------------------

    /**
     * Increases the REST client socket timeout from the default 60 s to 5 minutes.
     *
     * <p>The cross-mode test loads the standard CSV datasets (via the parent {@code @Before
     * setup()}) <em>and</em> the reference and candidate index copies (via {@link
     * #setupCrossModeIndices()}). On a freshly started cluster the combined loading, bulk-indexing,
     * and force-merge of all datasets can take several minutes — well beyond the default 60-second
     * REST-client socket timeout. A system-property override ({@code -Dtests.client.socket.timeout})
     * takes precedence over this default.
     */
    @Override
    protected Settings restClientSettings() {
        Settings base = super.restClientSettings();
        if (base.hasValue(CLIENT_SOCKET_TIMEOUT) == false) {
            return Settings.builder().put(base).put(CLIENT_SOCKET_TIMEOUT, "600s").build();
        }
        return base;
    }

    // -----------------------------------------------------------------------------------------
    // Setup and teardown
    // -----------------------------------------------------------------------------------------

    /**
     * Creates the reference and candidate index sets once per JVM. Datasets that fail columnar
     * index creation are silently skipped on both sides.
     *
     * <p>Runs after (or interleaved with) {@link GenerativeRestTest#setup}, which loads the
     * canonical CSV dataset that provides the shared enrich policies and lookup indices.
     */
    @Before
    public void setupCrossModeIndices() throws IOException {
        synchronized (CrossIndexModeGenerativeRestTest.class) {
            if (crossModeSetupDone) {
                return;
            }
            List<String> surviving = new ArrayList<>();
            for (CsvTestsDataLoader.TestDataset dataset : availableDatasetsForEs(
                // Lookup indices are excluded: they are used for LOOKUP JOIN, not FROM queries.
                // They are shared (un-prefixed) and already loaded by the parent setup().
                false,
                supportsSourceFieldMapping(),
                false,
                false,
                cap -> false
            )) {
                if (dataset.inferenceEndpoints().isEmpty() == false) {
                    continue;
                }
                if (EXCLUDED_DATASETS.contains(dataset.indexName())) {
                    logger.info("Cross-mode: skipping excluded dataset [{}]", dataset.indexName());
                    continue;
                }
                // TSDB (time_series) datasets have routing_path, counter, and dimension fields
                // that only work in time_series mode. Running them in columnar mode (where the
                // mode overrides their settings) gives a structurally different index, so they
                // are excluded upfront rather than discovered at comparison time.
                if ("time_series".equalsIgnoreCase(dataset.loadSettings().get("index.mode"))) {
                    logger.info("Cross-mode: skipping TSDB dataset [{}]", dataset.indexName());
                    continue;
                }
                CsvTestsDataLoader.TestDataset ref = dataset.withIndex(REF_PREFIX + dataset.indexName());
                CsvTestsDataLoader.TestDataset cand = dataset.withIndex(CAND_PREFIX + dataset.indexName());
                Settings refExtra = referenceSettings();
                Settings candExtra = candidateSettings();
                try {
                    CsvTestsDataLoader.loadDataSetIntoEs(
                        client(),
                        List.of(ref),
                        (c, name, mapping, baseSettings) -> createIndex(
                            name,
                            Settings.builder().put(baseSettings).put(refExtra).build(),
                            mapping
                        )
                    );
                } catch (Exception e) {
                    logger.info("Cross-mode: skipping dataset [{}] (ref creation failed): {}", dataset.indexName(), e.getMessage());
                    continue;
                }
                try {
                    CsvTestsDataLoader.loadDataSetIntoEs(
                        client(),
                        List.of(cand),
                        (c, name, mapping, baseSettings) -> createIndex(
                            name,
                            Settings.builder().put(baseSettings).put(candExtra).build(),
                            // Strict columnar modes reject `store: true` on any field. Strip the
                            // attribute so datasets that carry it (e.g. hosts/mapping-hosts.json)
                            // can be created in columnar mode. Values remain accessible via doc
                            // values and synthetic source, so query results are unaffected.
                            stripStoredFields(mapping)
                        )
                    );
                    surviving.add(REF_PREFIX + dataset.indexName());
                    logger.info("Cross-mode: loaded dataset [{}] as ref+cand", dataset.indexName());
                } catch (Exception e) {
                    // Delete the ref_ index so it does not appear in wildcard patterns like
                    // ref_* and cause schema divergences with the cand_ side.
                    logger.info(
                        "Cross-mode: skipping dataset [{}] (cand creation failed), deleting orphaned ref index: {}",
                        dataset.indexName(),
                        e.getMessage()
                    );
                    try {
                        deleteIndex(ref.indexName());
                    } catch (Exception de) {
                        logger.warn("Cross-mode: failed to delete orphaned ref index [{}]: {}", ref.indexName(), de.getMessage());
                    }
                }
            }
            assertTrue("No datasets survived candidate index creation — cross-mode test has no coverage", surviving.isEmpty() == false);
            logger.info("Cross-mode: {} datasets loaded (ref+cand)", surviving.size());
            crossModeRefIndices = Collections.unmodifiableList(surviving);
            crossModeSetupDone = true;
        }
    }

    /** Resets per-JVM state so a fresh run always re-creates indices. */
    @AfterClass
    public static void resetCrossModeState() {
        crossModeRefIndices = null;
        crossModeSetupDone = false;
    }

    /**
     * Logs how many pipeline steps performed value comparison this run.
     *
     * <p>A count of zero is not a hard failure: it legitimately occurs when every FROM query
     * produced exactly 1 000 rows (the implicit {@code LIMIT 1000} closed the determinism gate
     * at step 0), which happens when a wide wildcard pattern matches enough loaded datasets to
     * saturate the limit. It is logged as a warning so that a persistent zero across many seeds
     * is visible and worth investigating, but it does not fail the test.
     */
    @After
    public void logValueComparisonCount() {
        if (valueComparedSteps == 0) {
            logger.debug(
                "Cross-mode: no pipeline steps were value-compared this run (valueComparedSteps=0). "
                    + "The determinism gate may be closing too early — check updateDeterminismGate()."
            );
        } else {
            logger.info("Cross-mode value-compared steps this run: {}", valueComparedSteps);
        }
    }

    // -----------------------------------------------------------------------------------------
    // Allowed errors — transient infrastructure errors that are acceptable on either side
    // -----------------------------------------------------------------------------------------

    /**
     * Extra error patterns beyond {@link GenerativeRestTest#ALLOWED_ERRORS} that are acceptable in
     * cross-mode runs. These cover infrastructure transients (timeouts, connection drops) and
     * engine-level differences (Lucene {@code NumberFormatException}) that are already guarded by
     * {@link #ALLOWED_MODE_DIFFERENCES} at the cross-mode parity layer but must also be listed here
     * so that the base-class {@code checkPipelineException} does not fail the test when only one side
     * throws.
     */
    @Override
    protected Set<String> additionalAllowedErrors() {
        Set<String> errors = new HashSet<>(super.additionalAllowedErrors());
        // All mode-difference substrings are acceptable on either side of the pipeline.
        errors.addAll(ALLOWED_MODE_DIFFERENCE_SUBSTRINGS);
        return errors;
    }

    // -----------------------------------------------------------------------------------------
    // Generator hooks
    // -----------------------------------------------------------------------------------------

    @Override
    protected FromGenerator sourceCommand() {
        return new DualModeFromGenerator(REF_PREFIX, CAND_PREFIX);
    }

    @Override
    protected List<String> availableIndices() {
        return crossModeRefIndices;
    }

    // -----------------------------------------------------------------------------------------
    // Execution hook — runs both sides and compares
    // -----------------------------------------------------------------------------------------

    @Override
    protected QueryExecuted runCommand(QueryExecuted prevRef, CommandGenerator.CommandDescription current) {
        // Reset per-iteration candidate state when this is the pipeline's source command.
        if (prevRef == null) {
            candidatePreviousResult = null;
            determinismGateOpen = true;
        }

        // Determine the reference and candidate command strings.
        Object mirror = current.context().get(DualModeFromGenerator.MIRROR_COMMAND);
        String refCmd;
        String candCmd;
        if (mirror != null) {
            // Source command: each side has its own FROM clause.
            refCmd = current.commandString();
            candCmd = (String) mirror;
        } else {
            // Pipe command: the same text applies to both sides.
            refCmd = current.commandString();
            candCmd = current.commandString();
        }

        // Execute the reference side.
        QueryExecuted refResult = prevRef == null ? execute(refCmd, 0) : execute(prevRef.query() + refCmd, prevRef.depth());

        // Execute the candidate side.
        QueryExecuted candResult = candidatePreviousResult == null
            ? execute(candCmd, 0)
            : execute(candidatePreviousResult.query() + candCmd, candidatePreviousResult.depth());

        // Update the determinism gate before comparing.
        determinismGateOpen = updateDeterminismGate(determinismGateOpen, current, refResult, prevRef);

        // Compare the two sides.
        compareSides(current, refResult, candResult, determinismGateOpen);

        // Advance the candidate state for the next step.
        candidatePreviousResult = candResult;

        return refResult;
    }

    // -----------------------------------------------------------------------------------------
    // Determinism gate
    // -----------------------------------------------------------------------------------------

    /**
     * Returns {@code false} if value comparison can no longer be trusted for the remaining steps
     * in this pipeline iteration. The gate latches to {@code false} and never re-opens.
     */
    private static boolean updateDeterminismGate(
        boolean currentGate,
        CommandGenerator.CommandDescription current,
        QueryExecuted refResult,
        QueryExecuted prevRef
    ) {
        if (currentGate == false) {
            return false;
        }
        String cmdText = current.commandString().toUpperCase(Locale.ROOT);
        String cmdName = current.commandName();

        // Non-deterministic built-in functions. SAMPLE(field,n) draws a random subset and
        // can return different rows from the two physically different index layouts.
        if (cmdText.contains("NOW(") || cmdText.contains("RANDOM(") || cmdText.contains("SAMPLE(")) {
            return false;
        }
        // BYTE_LENGTH on keyword fields returns 0 in columnar mode due to a known columnar
        // doc-values read bug. Affects both WHERE predicates (wrong row count) and aggregations
        // like TOP/STATS (wrong computed values). Close the gate whenever BYTE_LENGTH appears.
        // TODO: remove once the columnar BYTE_LENGTH doc-values bug is fixed.
        if (cmdText.contains("BYTE_LENGTH(")) {
            return false;
        }
        // Full-text search functions and the `:` operator rely on the inverted index. Columnar
        // mode stores keyword fields exclusively via doc values (index_disabled_by_default=true
        // disables the inverted index for fields that lack an explicit "index: true" mapping), so
        // full-text / term queries on those fields return different rows compared to standard mode
        // where the inverted index is always present. Value comparison is not meaningful once
        // these appear.
        if (cmdText.contains("MATCH_PHRASE(")
            || cmdText.contains("MATCH(")
            || cmdText.contains("QSTR(")
            || cmdText.contains("KQL(")
            || cmdText.contains("SCORE(")
            || cmdText.contains(": \"")) {
            return false;
        }
        // Order-sensitive MV functions: standard mode returns multi-value fields in original
        // insertion order; columnar mode (synthetic source from doc values) returns them in sorted
        // order. These functions either select, slice, concatenate, or compute differences between
        // consecutive elements in field order — all produce different output when the input ordering
        // differs.
        if (cmdText.contains("MV_SLICE(")
            || cmdText.contains("MV_FIRST(")
            || cmdText.contains("MV_LAST(")
            || cmdText.contains("MV_CONCAT(")
            || cmdText.contains("MV_DIFFERENCE(")) {
            return false;
        }
        // MV_MAX / MV_MIN / MV_MEDIAN / MV_PERCENTILE on numeric fields: columnar mode stores
        // doc-values in ascending order, and the current columnar execution path returns the first
        // doc-value element rather than scanning for the true extremum or median. This means mv_max
        // returns the minimum, mv_median returns the first element, etc. — a known columnar bug.
        // TODO: remove once the columnar MV scalar-aggregate block-execution bug is fixed.
        if (cmdText.contains("MV_MAX(")
            || cmdText.contains("MV_MIN(")
            || cmdText.contains("MV_MEDIAN(")
            || cmdText.contains("MV_PERCENTILE(")) {
            return false;
        }
        // LEAST / GREATEST applied to multi-value fields are element-wise: they pair up values by
        // position across their arguments and return MV results whose element order depends on the
        // insertion / doc-values order of the input fields. Close the gate whenever either appears.
        if (cmdText.contains("LEAST(") || cmdText.contains("GREATEST(")) {
            return false;
        }
        // FIRST() / LAST() aggregation functions pick a value from the row with the minimum or
        // maximum sort-column value. They can be non-deterministic when there are ties in the sort
        // column. Additionally, columnar mode has a known issue where FIRST() returns null for
        // boolean MV fields instead of the correct multi-value boolean.
        // TODO: remove once the columnar FIRST/LAST boolean bug is fixed.
        if (cmdText.contains("FIRST(") || cmdText.contains("LAST(")) {
            return false;
        }
        // VARIANCE / STD_DEV are computed with Welford's algorithm, whose parallel-merge step
        // (WelfordAlgorithm#add(mean, m2, count)) is not associative in floating point: it
        // recombines the mean as (mean*count + meanValue*countValue)/(count+countValue), which
        // rounds for non-power-of-two partial counts and leaves a residual delta. The streaming
        // add(double) is exact for a constant column, so the result depends on how a group's rows
        // are split across partial states and on the order those partials are merged — and that
        // order is page arrival order out of ExchangeBuffer (a ConcurrentLinkedQueue), which is
        // not pinned by the data. For a group whose values are all equal the true result is 0,
        // but one side can return 0.0 while the other returns ~1e-32 — a difference that the
        // 6-significant-figure rounding in canonicalValue cannot absorb, because relative rounding
        // is meaningless at zero.
        // See: https://github.com/elastic/elasticsearch/issues/156988
        if (cmdText.contains("VARIANCE(") || cmdText.contains("STD_DEV(")) {
            return false;
        }
        // DISSECT and GROK applied to multi-value string fields: standard mode expands each element
        // of the MV field into a separate row before matching, while columnar mode processes only
        // the first element. This produces a different row count after the command, which then
        // propagates into any subsequent aggregation (e.g. COUNT). Gate to prevent false value
        // divergences that stem from this row-count difference rather than an incorrect result.
        if ("dissect".equals(cmdName) || "grok".equals(cmdName)) {
            return false;
        }
        // Commands whose output order or aggregate semantics depend on per-segment or per-shard
        // execution order, or whose aggregation behaviour differs between standard and columnar mode.
        // INLINE STATS without BY has a mode-specific COUNT discrepancy on multi-index wildcard
        // queries (standard returns a different global count than columnar); gated until root-caused.
        // STATS without BY (global aggregate): when a STATS alias reuses an original field name,
        // a subsequent EVAL can cause the optimizer to incorrectly re-resolve the alias to the
        // original field, silently corrupting the aggregated value (returns 0 instead of N). Close
        // the gate for global STATS to prevent these false positives; gated until root-caused.
        if ("sample".equals(cmdName)
            || "fork".equals(cmdName)
            || "change_point".equals(cmdName)
            || (("inline_stats".equals(cmdName) || "stats".equals(cmdName)) && cmdText.contains(" BY ") == false)) {
            return false;
        }
        // DEDUP deduplicates rows by all column values. Multi-value fields are returned in
        // insertion order in standard mode but in sorted order in columnar mode (synthetic source
        // from doc values). Two rows that appear identical in columnar (both MV cells normalised
        // to sorted order) may differ in standard (one cell [a,b], another [b,a]), so DEDUP can
        // remove a different number of rows in each mode. Close the gate once DEDUP appears to
        // prevent false-positive row-count divergences.
        if ("dedup".equals(cmdName)) {
            return false;
        }
        // HIGHLIGHT returns a highlighted snippet from stored source (standard mode) versus
        // synthetic source / doc-values (columnar mode). For MV fields the highlighted value
        // is selected by position — insertion order in standard, sorted order in columnar —
        // so the returned snippet can legitimately differ between the two modes.
        if ("highlight".equals(cmdName)) {
            return false;
        }
        // Truncating commands: close the gate only if the row count actually decreased,
        // indicating that the top-N selection was applied and may differ between index modes.
        if (("limit".equals(cmdName) || "limit_by".equals(cmdName))
            && prevRef != null
            && prevRef.result() != null
            && refResult.result() != null
            && refResult.result().size() < prevRef.result().size()) {
            return false;
        }
        // The implicit LIMIT 1000 may have kicked in and selected an arbitrary top-1000.
        if (refResult.result() != null && refResult.result().size() == 1000) {
            return false;
        }
        return true;
    }

    // -----------------------------------------------------------------------------------------
    // Comparison
    // -----------------------------------------------------------------------------------------

    /**
     * Compares the reference and candidate results for one pipeline step.
     *
     * <p>Always checks: failure parity (§1) and output schema (§2).
     * When {@code deterministic} is {@code true}, also checks values (§3).
     */
    private void compareSides(CommandGenerator.CommandDescription current, QueryExecuted ref, QueryExecuted cand, boolean deterministic) {
        boolean refThrew = ref.exception() != null;
        boolean candThrew = cand.exception() != null;

        // 1. Failure parity
        if (refThrew != candThrew) {
            String refMsg = refThrew ? ref.exception().getMessage() : null;
            String candMsg = candThrew ? cand.exception().getMessage() : null;
            // Check both messages: either side's error may be the pattern we allow.
            if (isAllowedModeDifference(refMsg) || isAllowedModeDifference(candMsg)) {
                return;
            }
            fail(
                "Cross-mode failure parity divergence at ["
                    + current.commandName()
                    + "]:\n"
                    + "  reference "
                    + (refThrew ? "THREW" : "succeeded")
                    + ": "
                    + refMsg
                    + "\n"
                    + "  candidate "
                    + (candThrew ? "THREW" : "succeeded")
                    + ": "
                    + candMsg
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
        }

        // Both threw — nothing more to compare.
        if (refThrew) {
            return;
        }

        // 2. Schema
        List<Column> refSchema = ref.outputSchema();
        List<Column> candSchema = cand.outputSchema();
        if (refSchema == null && candSchema == null) {
            return;
        }
        if (refSchema == null || candSchema == null || refSchema.size() != candSchema.size()) {
            fail(
                "Cross-mode schema divergence at ["
                    + current.commandName()
                    + "]:\n"
                    + "  reference schema: "
                    + refSchema
                    + "\n"
                    + "  candidate schema: "
                    + candSchema
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        for (int col = 0; col < refSchema.size(); col++) {
            Column rCol = refSchema.get(col);
            Column cCol = candSchema.get(col);
            if (rCol.name().equals(cCol.name()) == false || rCol.type().equals(cCol.type()) == false) {
                fail(
                    "Cross-mode schema divergence at column "
                        + col
                        + " in ["
                        + current.commandName()
                        + "]:\n"
                        + "  reference column: "
                        + rCol
                        + "\n"
                        + "  candidate column: "
                        + cCol
                        + "\n"
                        + "  reference query: "
                        + ref.query()
                        + "\n"
                        + "  candidate query: "
                        + cand.query()
                );
            }
        }

        // 3. Values (only while the determinism gate is open)
        if (deterministic == false) {
            return;
        }
        valueComparedSteps++;
        List<List<Object>> refRows = ref.result();
        List<List<Object>> candRows = cand.result();
        if (refRows == null && candRows == null) {
            return;
        }
        if (refRows == null || candRows == null) {
            fail(
                "Cross-mode values divergence: one side returned null rows at ["
                    + current.commandName()
                    + "]\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        if (refRows.size() != candRows.size()) {
            fail(
                "Cross-mode values divergence: row count differs at ["
                    + current.commandName()
                    + "]: reference="
                    + refRows.size()
                    + " candidate="
                    + candRows.size()
                    + "\n"
                    + "  reference query: "
                    + ref.query()
                    + "\n"
                    + "  candidate query: "
                    + cand.query()
            );
            return;
        }
        List<String> refCanon = toCanonical(refRows, refSchema);
        List<String> candCanon = toCanonical(candRows, refSchema);
        Collections.sort(refCanon);
        Collections.sort(candCanon);
        for (int row = 0; row < refCanon.size(); row++) {
            if (refCanon.get(row).equals(candCanon.get(row)) == false) {
                fail(
                    "Cross-mode values divergence at sorted row "
                        + row
                        + " in ["
                        + current.commandName()
                        + "]:\n"
                        + "  reference: "
                        + refCanon.get(row)
                        + "\n"
                        + "  candidate: "
                        + candCanon.get(row)
                        + "\n"
                        + "  reference query: "
                        + ref.query()
                        + "\n"
                        + "  candidate query: "
                        + cand.query()
                );
            }
        }
    }

    private static boolean isAllowedModeDifference(String errorMessage) {
        if (errorMessage == null) {
            return false;
        }
        for (Pattern p : ALLOWED_MODE_DIFFERENCES) {
            if (p.matcher(errorMessage).matches()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Column types whose values are skipped in the row comparison.
     *
     * <ul>
     *   <li>{@code geo_point}, {@code cartesian_point}: read from stored {@code _source} (standard
     *       mode) versus synthetic source (columnar mode) can differ at the last displayed decimal
     *       place due to Lucene's 32-bit integer encoding. Values that sit exactly on a rounding
     *       boundary (e.g. {@code -171.75 → "-171.7"} vs {@code "-171.8"}) produce differences
     *       that no fixed significant-figure rounding can reconcile without becoming too coarse to
     *       catch real bugs.</li>
     *   <li>{@code flattened}: object values contain nested arrays (e.g. {@code host.ip}) whose
     *       element order differs between stored source (original insertion order) and synthetic
     *       source (doc-values order). Skipping prevents false-positive failures while schema
     *       divergence (missing or renamed column) is still caught by the schema check.</li>
     * </ul>
     */
    private static final Set<String> SKIP_VALUE_COLUMN_TYPES = Set.of("geo_point", "cartesian_point", "flattened");

    /**
     * Converts a result set to a list of canonical row strings for order-insensitive comparison.
     *
     * <p>Each cell is rendered by {@link #canonicalValue}. List-valued cells (multi-value fields)
     * have their elements sorted before rendering to absorb ordering differences between stored and
     * synthetic source — e.g. a keyword MV stored as {@code ["b","a"]} in the standard index and
     * returned as {@code ["a","b"]} in the columnar (synthetic-source) index will compare equal.
     *
     * <p>Columns whose type is in {@link #SKIP_VALUE_COLUMN_TYPES} are replaced by a constant
     * placeholder so that inherent precision differences (stored vs synthetic source coordinate
     * encoding) do not produce false-positive failures.
     */
    @SuppressWarnings("unchecked")
    private static List<String> toCanonical(List<List<Object>> rows, List<Column> schema) {
        List<String> result = new ArrayList<>(rows.size());
        for (List<Object> row : rows) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < row.size(); i++) {
                if (i > 0) {
                    sb.append('\t');
                }
                String colType = i < schema.size() ? schema.get(i).type() : null;
                if (SKIP_VALUE_COLUMN_TYPES.contains(colType)) {
                    sb.append("~");
                    continue;
                }
                Object val = row.get(i);
                if (val instanceof List) {
                    List<String> strs = new ArrayList<>();
                    for (Object v : (List<Object>) val) {
                        strs.add(canonicalValue(v));
                    }
                    Collections.sort(strs);
                    sb.append(strs);
                } else {
                    sb.append(canonicalValue(val));
                }
            }
            result.add(sb.toString());
        }
        return result;
    }

    /**
     * Renders a single cell value as a canonical string.
     *
     * <p>Doubles are rounded to 6 significant figures to absorb tiny floating-point differences
     * that arise when re-encoding values through doc values in columnar mode.
     *
     * <p>Strings that look like WKT geometry ({@code POINT (…)}, {@code POLYGON (…)}, etc.) have
     * their coordinate numbers rounded to the same 6 significant figures. Doc-values-based
     * reconstruction of geo/cartesian points introduces ~1e-7 relative precision loss — for
     * example a stored {@code POINT (5.0 5.0)} can come back as
     * {@code POINT (4.999999953433871 4.999999995343387)} in columnar mode.
     */
    private static String canonicalValue(Object val) {
        if (val instanceof Double d) {
            if (Double.isNaN(d) || Double.isInfinite(d)) {
                return String.valueOf(d);
            }
            return String.valueOf(new BigDecimal(d).round(new MathContext(6, RoundingMode.HALF_DOWN)).doubleValue());
        }
        String s = String.valueOf(val);
        if (isWktString(s)) {
            return normalizeSpatialCoords(s);
        }
        return s;
    }

    /** Returns true when {@code s} is a WKT geometry string (starts with a known geometry type keyword). */
    private static boolean isWktString(String s) {
        return s.startsWith("POINT (")
            || s.startsWith("LINESTRING (")
            || s.startsWith("POLYGON (")
            || s.startsWith("MULTIPOINT (")
            || s.startsWith("MULTILINESTRING (")
            || s.startsWith("MULTIPOLYGON (")
            || s.startsWith("GEOMETRYCOLLECTION (");
    }

    /**
     * Removes all {@code "store": true} attributes from a mapping JSON string.
     *
     * <p>Strict columnar index modes (e.g. {@code index.mode=columnar}) reject any field that has
     * {@code store: true} at mapping-parse time. The ES|QL CSV test fixtures retain that attribute
     * in some mappings (e.g. {@code mapping-hosts.json}) for use in non-columnar test suites. To
     * allow those datasets to be created in columnar mode, the candidate-side index creator strips
     * the attribute before forwarding the mapping to the server. Field values are still readable
     * via doc values and synthetic source, so all ES|QL CSV tests exercise the same query paths.
     */
    private static String stripStoredFields(String mapping) throws IOException {
        Map<String, Object> map = XContentHelper.convertToMap(JsonXContent.jsonXContent, mapping, false);
        removeKey(map, "store");
        try (XContentBuilder builder = JsonXContent.contentBuilder()) {
            builder.map(map);
            return Strings.toString(builder);
        }
    }

    @SuppressWarnings("unchecked")
    private static void removeKey(Map<String, Object> map, String key) {
        map.remove(key);
        for (Object value : map.values()) {
            if (value instanceof Map) {
                removeKey((Map<String, Object>) value, key);
            }
        }
    }

    /**
     * Rounds every numeric coordinate within a WKT geometry string to 6 significant figures,
     * absorbing doc-values reconstruction precision loss for geo/cartesian point types.
     */
    private static String normalizeSpatialCoords(String wkt) {
        return WKT_NUMBER.matcher(wkt).replaceAll(mr -> {
            String coord = mr.group();
            try {
                double d = Double.parseDouble(coord);
                return String.valueOf(new BigDecimal(d).round(new MathContext(6, RoundingMode.HALF_DOWN)).doubleValue());
            } catch (NumberFormatException e) {
                return coord;
            }
        });
    }

}
