CREATE TABLE mock (
  PROCEDURE_CAT VARCHAR,
  PROCEDURE_SCHEM VARCHAR,
  PROCEDURE_NAME VARCHAR,
  NUM_INPUT_PARAMS INTEGER,
  NUM_OUTPUT_PARAMS INTEGER,
  NUM_RESULT_SETS INTEGER,
  REMARKS VARCHAR,
  PROCEDURE_TYPE SMALLINT,
  SPECIFIC_NAME VARCHAR
);
