[role="xpack"]
[[autoscaling-deciders]]
== Autoscaling deciders

<<autoscaling-reactive-storage-decider,Reactive storage decider>>::
Estimates required storage capacity of current data set. Available for policies
governing data nodes.

<<autoscaling-proactive-storage-decider,Proactive storage decider>>::
Estimates required storage capacity based on current ingestion into hot nodes.
Available for policies governing hot data nodes.

<<autoscaling-frozen-shards-decider,Frozen shards decider>>::
Estimates required memory capacity based on the number of partially mounted shards.
Available for policies governing frozen data nodes.

<<autoscaling-frozen-storage-decider,Frozen storage decider>>::
Estimates required storage capacity as a percentage of the total data set of
partially mounted indices.
Available for policies governing frozen data nodes.

<<autoscaling-frozen-existence-decider,Frozen existence decider>>::
Estimates a minimum require frozen memory and storage capacity when any index is
in the frozen <<index-lifecycle-management,ILM>> phase.

<<autoscaling-machine-learning-decider,Machine learning decider>>::
Estimates required memory capacity based on machine learning jobs.
Available for policies governing machine learning nodes.

<<autoscaling-fixed-decider,Fixed decider>>::
Responds with a fixed required capacity. This decider is intended for testing only.

include::deciders/reactive-storage-decider.asciidoc[]
include::deciders/proactive-storage-decider.asciidoc[]
include::deciders/frozen-shards-decider.asciidoc[]
include::deciders/frozen-storage-decider.asciidoc[]
include::deciders/frozen-existence-decider.asciidoc[]
include::deciders/machine-learning-decider.asciidoc[]
include::deciders/fixed-decider.asciidoc[]
