[role="xpack"]
[[pki-realm]]
=== PKI user authentication

You can configure {es} to use Public Key Infrastructure (PKI) certificates to
authenticate users. This requires clients connecting directly to {es} to
present X.509 certificates. The certificates must first be accepted for
authentication on the SSL/TLS layer on {es}. Only then they are optionally
further validated by a PKI realm.

You can also use PKI certificates to authenticate to {kib}, however this
requires some <<pki-realm-for-proxied-clients,additional configuration>>. On
{es}, this configuration enables {kib} to act as a proxy for SSL/TLS
authentication and to submit the client certificates to {es} for further
validation by a PKI realm.

To use PKI in {es}, you configure a PKI realm, enable client authentication on
the desired network layers (transport or http), and map the Distinguished Names
(DNs) from the user certificates to roles. You create the mappings in a
<<pki-role-mapping, role mapping file>> or use the
<<security-api-put-role-mapping,create role mappings API>>. If you want the same
users to also be authenticated using certificates when they connect to {kib},
you must configure the {es} PKI realm to
<<pki-realm-for-proxied-clients,allow delegation>> and to
{kibana-ref}/kibana-authentication.html#pki-authentication[enable PKI authentication in {kib}].

include::configuring-pki-realm.asciidoc[]
