[role="xpack"]
[[unfreeze-index-api]]
=== Unfreeze index API
++++
<titleabbrev>Unfreeze index</titleabbrev>
++++

[WARNING]
.Deprecated in 7.14
====
In 8.0, we removed the ability to freeze an index. In previous versions,
freezing an index reduced its memory overhead. However, frozen indices are no
longer useful due to
https://www.elastic.co/blog/significantly-decrease-your-elasticsearch-heap-memory-usage[recent
improvements in heap memory usage].
You can use this API to unfreeze indices that were frozen in 7.x. Frozen indices
are not related to the frozen data tier.
====

Unfreezes an index.

[[unfreeze-index-api-request]]
==== {api-request-title}

`POST /<index>/_unfreeze`

[[unfreeze-index-api-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have the `manage`
<<privileges-list-indices,index privilege>> for the target index or index alias.

[[unfreeze-index-api-desc]]
==== {api-description-title}

When a frozen index is unfrozen, the index goes through the normal recovery
process and becomes writeable again.

[[unfreeze-index-api-path-parms]]
==== {api-path-parms-title}

`<index>`::
  (Required, string) Identifier for the index.

[[unfreeze-index-api-examples]]
==== {api-examples-title}

The following example unfreezes an index:

[source,console]
--------------------------------------------------
POST /my-index-000001/_unfreeze
--------------------------------------------------
// TEST[s/^/PUT my-index-000001\n/]
// TEST[skip:unable to ignore deprecation warning]
