/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.action.support;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.elasticsearch.ElasticsearchTimeoutException;
import org.elasticsearch.action.ActionListener;
import org.elasticsearch.action.support.replication.StaleRequestException;
import org.elasticsearch.cluster.ClusterState;
import org.elasticsearch.cluster.ClusterStateObserver;
import org.elasticsearch.cluster.metadata.ProjectMetadata;
import org.elasticsearch.cluster.project.ProjectResolver;
import org.elasticsearch.cluster.routing.SplitShardCountSummary;
import org.elasticsearch.cluster.service.ClusterService;
import org.elasticsearch.common.settings.Setting;
import org.elasticsearch.core.TimeValue;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.node.NodeClosedException;
import org.elasticsearch.threadpool.ThreadPool;

import java.util.Map;

public class ReshardingActionHelper {
    // How long to wait to see a shard routing update after receiving a stale request failure
    // Deliberately is not registered in ClusterSettings.BUILT_IN_CLUSTER_SETTINGS because it is only for tests
    public static final Setting<TimeValue> ROUTE_REFRESH_TIMEOUT = Setting.timeSetting(
        "single_shard_action.route_refresh_timeout",
        TimeValue.timeValueSeconds(30),
        Setting.Property.NodeScope
    );

    private final ClusterService clusterService;
    private final ProjectResolver projectResolver;
    private final ThreadPool threadPool;

    private static final Logger logger = LogManager.getLogger(ReshardingActionHelper.class);

    public ReshardingActionHelper(ClusterService clusterService, ProjectResolver projectResolver, ThreadPool threadPool) {
        this.clusterService = clusterService;
        this.projectResolver = projectResolver;
        this.threadPool = threadPool;
    }

    /// Waits for routing information to be updated in preparation to execute a multi-read operation.
    /// Provided [StaleRequestException]s are used to identify if routing information is recent enough.
    public void waitForRoutingUpdate(Map<ShardId, StaleRequestException> exceptions, ActionListener<Void> listener) {
        ClusterStateObserver.waitForState(clusterService, threadPool.getThreadContext(), new ClusterStateObserver.Listener() {
            @Override
            public void onNewClusterState(ClusterState state) {
                listener.onResponse(null);
            }

            @Override
            public void onClusterServiceClose() {
                listener.onFailure(new NodeClosedException(clusterService.localNode()));
            }

            @Override
            public void onTimeout(TimeValue timeout) {
                listener.onFailure(
                    new ElasticsearchTimeoutException("gave up waiting for routing to refresh", exceptions.values().iterator().next())
                );

            }
        }, (state) -> {
            ProjectMetadata project = projectResolver.getProjectMetadata(state);
            int newerSummaries = 0;
            for (var entry : exceptions.entrySet()) {
                final var shardId = entry.getKey();
                // BWC: the summary may be UNSET if the exception is generated by an older node.
                // We'll do one potentially early retry in that case.
                final var staleSummary = entry.getValue().getStaleSummary();
                final var indexMetadata = project.index(shardId.getIndex());
                final var currentSummary = SplitShardCountSummary.forSearch(indexMetadata, shardId.getId());
                if (currentSummary.equals(staleSummary) == false) {
                    newerSummaries++;
                }
            }
            return newerSummaries == exceptions.size();
        }, ROUTE_REFRESH_TIMEOUT.get(clusterService.getSettings()), logger);
    }
}
