/*
 *
 *  * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 *  * or more contributor license agreements. Licensed under the Elastic License;
 *  * you may not use this file except in compliance with the Elastic License.
 *
 */

package org.elasticsearch.integration;

import org.elasticsearch.client.Request;
import org.elasticsearch.common.settings.SecureString;
import org.elasticsearch.xpack.core.security.authc.support.Hasher;
import org.junit.Before;

import java.io.IOException;

public class AppendOnlyIndexPrivilegeTests extends AbstractPrivilegeTestCase {
    private static final String INDEX_NAME = "index-1";
    private static final String APPEND_ONLY_USER = "append_only_user";
    private String jsonDoc = "{ \"name\" : \"elasticsearch\", \"body\": \"foo bar\" }";
    private static final String ROLES =
        "all_indices_role:\n" +
            "  indices:\n" +
            "    - names: '*'\n" +
            "      privileges: [ all ]\n" +
        "append_only_role:\n" +
            "  indices:\n" +
            "    - names: '*'\n" +
            "      privileges: [ append_only ]\n";

    private static final String USERS_ROLES =
        "all_indices_role:admin\n" +
        "append_only_role:" + APPEND_ONLY_USER + "\n";

    @Override
    protected boolean addMockHttpTransport() {
        return false; // enable http
    }

    @Override
    protected String configRoles() {
        return super.configRoles() + "\n" + ROLES;
    }

    @Override
    protected String configUsers() {
        final String usersPasswdHashed = new String(Hasher.resolve(
            randomFrom("pbkdf2", "pbkdf2_1000", "bcrypt", "bcrypt9")).hash(new SecureString("passwd".toCharArray())));

        return super.configUsers() +
            "admin:" + usersPasswdHashed + "\n" +
            "append_only_user:" + usersPasswdHashed + "\n";
    }

    @Override
    protected String configUsersRoles() {
        return super.configUsersRoles() + USERS_ROLES;
    }

    @Before
    public void insertBaseDocumentsAsAdmin() throws Exception {
        Request request = new Request("PUT", "/" + INDEX_NAME + "/_doc/1");
        request.setJsonEntity(jsonDoc);
        request.addParameter("refresh", "true");
        assertAccessIsAllowed("admin", request);
    }

    public void testAppendOnlyUserCanIndexNewDocumentsWithAutoGeneratedId() throws IOException {
        assertAccessIsAllowed(APPEND_ONLY_USER, "POST", "/" + INDEX_NAME + "/_doc", "{ \"foo\" : \"bar\" }");
    }

    public void testAppendOnlyUserCanIndexNewDocumentsWithExternalIdAndOpTypeIsCreate() throws IOException {
        assertAccessIsAllowed(APPEND_ONLY_USER, "PUT", "/" + INDEX_NAME + "/_doc/2?op_type=create", "{ \"foo\" : \"bar\" }");
    }

    public void testAppendOnlyUserIsDeniedToIndexNewDocumentsWithExternalIdAndOpTypeIsIndex() throws IOException {
        assertAccessIsDenied(APPEND_ONLY_USER, "PUT", "/" + INDEX_NAME + "/_doc/3", "{ \"foo\" : \"bar\" }");
    }

    public void testAppendOnlyUserIsDeniedToIndexUpdatesToExistingDocument() throws IOException {
        assertAccessIsDenied(APPEND_ONLY_USER, "POST", "/" + INDEX_NAME + "/_doc/1/_update", "{ \"doc\" : { \"foo\" : \"baz\" } }");
        assertAccessIsDenied(APPEND_ONLY_USER, "PUT", "/" + INDEX_NAME + "/_doc/1", "{ \"foo\" : \"baz\" }");
    }

    public void testAppendOnlyUserCanIndexNewDocumentsWithAutoGeneratedIdUsingBulkApi() throws IOException {
        assertAccessIsAllowed(APPEND_ONLY_USER, randomFrom("PUT", "POST"),
            "/" + INDEX_NAME + "/_bulk", "{ \"index\" : { } }\n{ \"foo\" : \"bar\" }\n");
    }

    public void testAppendOnlyUserCanIndexNewDocumentsWithExternalIdAndOpTypeIsCreateUsingBulkApi() throws IOException {
        assertAccessIsAllowed(APPEND_ONLY_USER, randomFrom("PUT", "POST"),
            "/" + INDEX_NAME + "/_bulk", "{ \"create\" : { \"_id\" : \"4\" } }\n{ \"foo\" : \"bar\" }\n");
    }

    public void testAppendOnlyUserIsDeniedToIndexNewDocumentsWithExternalIdAndOpTypeIsIndexUsingBulkApi() throws IOException {
        assertBodyHasAccessIsDenied(APPEND_ONLY_USER, randomFrom("PUT", "POST"),
            "/" + INDEX_NAME + "/_bulk", "{ \"index\" : { \"_id\" : \"5\" } }\n{ \"foo\" : \"bar\" }\n");
    }

    public void testAppendOnlyUserIsDeniedToIndexUpdatesToExistingDocumentUsingBulkApi() throws IOException {
        assertBodyHasAccessIsDenied(APPEND_ONLY_USER, randomFrom("PUT", "POST"),
            "/" + INDEX_NAME + "/_bulk", "{ \"index\" : { \"_id\" : \"1\" } }\n{ \"doc\" : {\"foo\" : \"bazbaz\"} }\n");
        assertBodyHasAccessIsDenied(APPEND_ONLY_USER, randomFrom("PUT", "POST"),
            "/" + INDEX_NAME + "/_bulk", "{ \"update\" : { \"_id\" : \"1\" } }\n{ \"doc\" : {\"foo\" : \"bazbaz\"} }\n");
    }

}
