#!/bin/sh
set -e

case "$1" in
    remove)
        # Remove logs
        rm -rf /var/log/elasticsearch
       
        # disable elasticsearch service on systemd systems
        if [ -x /bin/systemctl ] ; then
            /bin/systemctl --no-reload disable elasticsearch.service > /dev/null 2>&1 || :
        fi

        # Remove plugin directory and all plugins
        rm -rf /usr/share/elasticsearch/plugins

        # Remove **only** empty data dir
        rmdir --ignore-fail-on-non-empty /var/lib/elasticsearch
    ;;

    purge)
    	# Remove service
        # disable elasticsearch service on systemd systems
        if [ -x /bin/systemctl ] ; then
            /bin/systemctl --no-reload disable elasticsearch.service > /dev/null 2>&1 || :
        else
            update-rc.d elasticsearch remove >/dev/null || true
        fi
    
        # Remove logs, data and plugins
        rm -rf /var/log/elasticsearch /var/lib/elasticsearch /usr/share/elasticsearch/plugins

        # Remove user/group
        deluser elasticsearch || true
        delgroup elasticsearch || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
