/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import org.elasticsearch.jdk.ModuleQualifiedExportsService;
import org.elasticsearch.nativeaccess.exports.NativeAccessModuleExportsService;

module org.elasticsearch.nativeaccess {
    requires org.elasticsearch.base;
    requires org.elasticsearch.logging;
    requires transitive org.elasticsearch.foreign;
    requires org.elasticsearch.foreign.adapter;
    requires java.management; // for access to heap size

    exports org.elasticsearch.nativeaccess
        to
            org.elasticsearch.server,
            org.elasticsearch.blobcache,
            org.elasticsearch.parquetrs,
            org.elasticsearch.searchablesnapshots,
            org.elasticsearch.simdvec,
            org.elasticsearch.systemd,
            org.elasticsearch.xpack.stateless,
            // ESQL data source compression-libs plugin: hosts PanamaZstd, the thin Panama
            // FFI wrapper that ESQL data source plugins (parquet today, orc/iceberg later)
            // route their direct-buffer zstd decompression through. Targeting only this
            // narrow ESQL-scoped module keeps the rest of the native-access surface
            // (process limits, mlock, exec sandbox, systemd hooks, raw memory mapping)
            // invisible to other plugins.
            org.elasticsearch.xpack.esql.datasource.compress;

    uses org.elasticsearch.nativeaccess.lib.NativeLibraryProvider;

    provides org.elasticsearch.nativeaccess.lib.NativeLibraryProvider with org.elasticsearch.nativeaccess.jdk.JdkNativeLibraryProvider;

    // `provides org.elasticsearch.foreign.LibraryProvider ...` entries are NOT declared here.
    // They reference $Provider classes generated by the annotation processor; the build's
    // `augmentModuleInfo` task injects the directive into module-info.class after compilation.

    provides ModuleQualifiedExportsService with NativeAccessModuleExportsService;

}
