[[fix-data-node-out-of-disk]]
== Fix data nodes out of disk

{es} is using data nodes to distribute your data inside the cluster. If one or more of these nodes are running
out of space, {es} takes action to redistribute your data within the nodes so all nodes have enough available
disk space. If {es} cannot facilitate enough available space in a node, then you will need to intervene in one
of two ways:

. <<increase-capacity-data-node, Increase the disk capacity of your cluster>>
. <<decrease-disk-usage-data-node, Reduce the disk usage by decreasing your data volume>>

[[increase-capacity-data-node]]
=== Increase the disk capacity of data nodes
include::{es-repo-dir}/tab-widgets/troubleshooting/disk/increase-data-node-capacity-widget.asciidoc[]

[[decrease-disk-usage-data-node]]
=== Decrease the disk usage of data nodes
In order to decrease the disk usage in your cluster without losing any data, you can try reducing the replicas of indices.

NOTE: Reducing the replicas of an index can potentially reduce search throughput and data redundancy. However, it
can quickly give the cluster breathing room until a more permanent solution is in place.

include::{es-repo-dir}/tab-widgets/troubleshooting/disk/decrease-data-node-disk-usage-widget.asciidoc[]
