/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.inference.services.ocigenai.request;

import java.io.ByteArrayOutputStream;
import java.security.GeneralSecurityException;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;

/**
 * Parses the PEM encoded RSA private key of an OCI API signing key pair into a {@link PrivateKey}.
 * <p>
 * Both encodings produced by the OCI tooling are accepted: PKCS#8 ({@code -----BEGIN PRIVATE KEY-----}, the format generated by the
 * OCI Console and recent OpenSSL versions) and the legacy PKCS#1 ({@code -----BEGIN RSA PRIVATE KEY-----}, generated by
 * {@code openssl genrsa} with older OpenSSL versions). Passphrase protected keys are not supported.
 */
public final class OciGenAiPrivateKeyParser {

    private static final String PKCS8_HEADER = "-----BEGIN PRIVATE KEY-----";
    private static final String PKCS8_FOOTER = "-----END PRIVATE KEY-----";
    private static final String PKCS1_HEADER = "-----BEGIN RSA PRIVATE KEY-----";
    private static final String PKCS1_FOOTER = "-----END RSA PRIVATE KEY-----";
    private static final String ENCRYPTED_PKCS8_HEADER = "-----BEGIN ENCRYPTED PRIVATE KEY-----";
    private static final String ENCRYPTED_PKCS1_MARKER = "Proc-Type: 4,ENCRYPTED";

    static final String UNSUPPORTED_FORMAT_MESSAGE =
        "Unsupported private key format. Expected an unencrypted PEM encoded RSA private key in PKCS#8 (BEGIN PRIVATE KEY) "
            + "or PKCS#1 (BEGIN RSA PRIVATE KEY) format";
    static final String ENCRYPTED_KEY_MESSAGE = "Passphrase protected private keys are not supported, provide an unencrypted private key";

    /**
     * ASN.1 DER encoding of {@code AlgorithmIdentifier { rsaEncryption (1.2.840.113549.1.1.1), NULL }}, used to wrap a PKCS#1 key
     * into a PKCS#8 {@code PrivateKeyInfo} structure that {@link KeyFactory} can consume.
     */
    private static final byte[] RSA_ALGORITHM_IDENTIFIER = {
        0x30,
        0x0d,
        0x06,
        0x09,
        0x2a,
        (byte) 0x86,
        0x48,
        (byte) 0x86,
        (byte) 0xf7,
        0x0d,
        0x01,
        0x01,
        0x01,
        0x05,
        0x00 };
    private static final byte[] PKCS8_VERSION_ZERO = { 0x02, 0x01, 0x00 };

    public static PrivateKey parse(String pem) throws GeneralSecurityException {
        if (pem == null) {
            throw new InvalidKeyException(UNSUPPORTED_FORMAT_MESSAGE);
        }
        var trimmed = pem.strip();
        if (trimmed.startsWith(ENCRYPTED_PKCS8_HEADER) || trimmed.contains(ENCRYPTED_PKCS1_MARKER)) {
            throw new InvalidKeyException(ENCRYPTED_KEY_MESSAGE);
        }

        final byte[] pkcs8;
        if (trimmed.startsWith(PKCS8_HEADER)) {
            pkcs8 = decodeBody(trimmed, PKCS8_HEADER, PKCS8_FOOTER);
        } else if (trimmed.startsWith(PKCS1_HEADER)) {
            pkcs8 = wrapPkcs1InPkcs8(decodeBody(trimmed, PKCS1_HEADER, PKCS1_FOOTER));
        } else {
            throw new InvalidKeyException(UNSUPPORTED_FORMAT_MESSAGE);
        }

        return KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(pkcs8));
    }

    private static byte[] decodeBody(String pem, String header, String footer) throws InvalidKeyException {
        var footerIndex = pem.indexOf(footer);
        if (footerIndex < 0) {
            throw new InvalidKeyException(UNSUPPORTED_FORMAT_MESSAGE);
        }
        var body = pem.substring(header.length(), footerIndex).replaceAll("\\s", "");
        try {
            return Base64.getDecoder().decode(body);
        } catch (IllegalArgumentException e) {
            throw new InvalidKeyException("Private key is not valid base64 encoded PEM content", e);
        }
    }

    /**
     * Wraps a PKCS#1 {@code RSAPrivateKey} DER structure into a PKCS#8 {@code PrivateKeyInfo}:
     * {@code SEQUENCE { INTEGER 0, AlgorithmIdentifier, OCTET STRING <pkcs1> }}.
     */
    static byte[] wrapPkcs1InPkcs8(byte[] pkcs1) {
        var content = new ByteArrayOutputStream();
        content.writeBytes(PKCS8_VERSION_ZERO);
        content.writeBytes(RSA_ALGORITHM_IDENTIFIER);
        content.writeBytes(derElement(0x04, pkcs1));
        return derElement(0x30, content.toByteArray());
    }

    private static byte[] derElement(int tag, byte[] content) {
        var out = new ByteArrayOutputStream();
        out.write(tag);
        var length = content.length;
        if (length < 0x80) {
            out.write(length);
        } else {
            var lengthBytes = new ByteArrayOutputStream();
            for (int shift = 24; shift >= 0; shift -= 8) {
                int b = (length >>> shift) & 0xff;
                if (b != 0 || lengthBytes.size() > 0) {
                    lengthBytes.write(b);
                }
            }
            out.write(0x80 | lengthBytes.size());
            out.writeBytes(lengthBytes.toByteArray());
        }
        out.writeBytes(content);
        return out.toByteArray();
    }

    private OciGenAiPrivateKeyParser() {}
}
