/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.Vocabulary;
import org.elasticsearch.core.PathUtils;
import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;
import org.elasticsearch.test.ESTestCase;
import org.elasticsearch.xpack.esql.expression.function.DocsV3Support;
import org.elasticsearch.xpack.esql.parser.EsqlBaseLexer;
import org.junit.AfterClass;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Pattern;

/**
 * Generates reserved-keywords.md from the tokenizer (best-effort).
 * Add tokens to {@code TOKENS_WHITELIST} or {@code TOKENS_BLACKLIST} if needed.
 */
public class ReservedKeywordsDocsTests extends ESTestCase {
    private static final Pattern IDENTIFIER_SHAPED = Pattern.compile("[A-Za-z][A-Za-z0-9_]*");
    /**
     * Snapshot-only tokens; omit from release docs.
     */
    private static final Pattern DEV_TOKEN = Pattern.compile("^DEV_");
    /**
     * Extra keywords the tokenizer misses.
     */
    private static final Set<String> TOKENS_WHITELIST = Set.of();
    /**
     * Tokens to omit from the generated list.
     */
    private static final Set<String> TOKENS_BLACKLIST = Set.of("UNKNOWN_CMD");

    public void testReservedKeywordsAreIdentifierShapedAndSorted() {
        List<String> keywords = reservedKeywords();
        assertFalse("lexer vocabulary should yield identifier-shaped keywords", keywords.isEmpty());
        assertTrue("expression keyword IN should be in the dump", keywords.contains("IN"));
        assertTrue("command name FROM should be in the dump", keywords.contains("FROM"));
        assertTrue("STATS is recovered by lexing its symbolic name", keywords.contains("STATS"));
        assertFalse("WS is not a keyword", keywords.contains("WS"));
        assertFalse("UNKNOWN_CMD is a catch-all regex, not a keyword", keywords.contains("UNKNOWN_CMD"));
        for (int i = 0; i < keywords.size(); i++) {
            String keyword = keywords.get(i);
            assertTrue("not identifier-shaped: " + keyword, IDENTIFIER_SHAPED.matcher(keyword).matches());
            assertEquals("keywords should be upper-case: " + keyword, keyword.toUpperCase(Locale.ROOT), keyword);
            if (i > 0) {
                assertTrue(
                    "keywords should be alphabetical: " + keywords.get(i - 1) + " before " + keyword,
                    keywords.get(i - 1).compareTo(keyword) < 0
                );
            }
        }
    }

    public void testDevTokensAreOmitted() {
        Vocabulary vocabulary = EsqlBaseLexer.VOCABULARY;
        List<String> keywords = reservedKeywords();
        for (int tokenType = 0; tokenType <= vocabulary.getMaxTokenType(); tokenType++) {
            String symbolic = vocabulary.getSymbolicName(tokenType);
            if (symbolic == null || DEV_TOKEN.matcher(symbolic).matches() == false) {
                continue;
            }
            String literal = vocabulary.getLiteralName(tokenType);
            if (literal == null) {
                continue;
            }
            String word = unquoteAntlrLiteral(literal).toUpperCase(Locale.ROOT);
            assertFalse(symbolic + " is snapshot-only", keywords.contains(word));
        }
    }

    public void testRenderedSnippetIsCommaSeparatedBackticks() {
        String rendered = renderSnippet();
        assertTrue(rendered.startsWith("% This is generated by ESQL's ReservedKeywordsDocsTests."));
        assertTrue(rendered.contains("`IN`"));
        assertTrue(rendered.contains("`FROM`"));
        assertTrue(rendered.contains("`STATS`"));
        int listStart = rendered.indexOf('`');
        assertTrue(listStart >= 0);
        String list = rendered.substring(listStart).strip();
        assertTrue("expected a comma-separated list, got: " + list, list.contains(", "));
        assertFalse("first version is a single inline list", list.contains("\n"));
    }

    @AfterClass
    public static void renderDocs() throws IOException {
        if (System.getProperty("generateDocs") == null) {
            return;
        }
        new ReservedKeywordsDocsSupport().renderDocs();
    }

    static List<String> reservedKeywords() {
        Vocabulary vocabulary = EsqlBaseLexer.VOCABULARY;
        Set<String> keywords = new TreeSet<>();
        for (int tokenType = 0; tokenType <= vocabulary.getMaxTokenType(); tokenType++) {
            String symbolic = vocabulary.getSymbolicName(tokenType);
            if (symbolic != null && (DEV_TOKEN.matcher(symbolic).matches() || TOKENS_BLACKLIST.contains(symbolic))) {
                continue;
            }
            String word = keywordText(vocabulary, tokenType, symbolic);
            if (word != null && IDENTIFIER_SHAPED.matcher(word).matches()) {
                keywords.add(word.toUpperCase(Locale.ROOT));
            }
        }
        for (String extra : TOKENS_WHITELIST) {
            keywords.add(extra.toUpperCase(Locale.ROOT));
        }
        return new ArrayList<>(keywords);
    }

    static String renderSnippet() {
        StringBuilder builder = new StringBuilder();
        builder.append("% This is generated by ESQL's ")
            .append(ReservedKeywordsDocsTests.class.getSimpleName())
            .append(". Do not edit it. See docs/reference/query-languages/esql/README.md for how to regenerate it.\n\n");
        List<String> keywords = reservedKeywords();
        for (int i = 0; i < keywords.size(); i++) {
            if (i > 0) {
                builder.append(", ");
            }
            builder.append('`').append(keywords.get(i).toUpperCase(Locale.ROOT)).append('`');

        }
        builder.append('\n');
        return builder.toString();
    }

    private static String keywordText(Vocabulary vocabulary, int tokenType, String symbolic) {
        String literal = vocabulary.getLiteralName(tokenType);
        if (literal != null) {
            return unquoteAntlrLiteral(literal);
        }
        // ANTLR drops a literal when two rules share it (STATS and INLINE_STATS both use 'stats').
        if (symbolic != null && IDENTIFIER_SHAPED.matcher(symbolic).matches() && lexesAs(symbolic, tokenType)) {
            return symbolic;
        }
        return null;
    }

    private static boolean lexesAs(String word, int tokenType) {
        EsqlBaseLexer lexer = new EsqlBaseLexer(CharStreams.fromString(word.toLowerCase(Locale.ROOT)));
        lexer.removeErrorListeners();
        Token token = lexer.nextToken();
        if (token.getType() != tokenType) {
            return false;
        }
        return lexer.nextToken().getType() == Token.EOF;
    }

    private static String unquoteAntlrLiteral(String literal) {
        if (literal.length() >= 2 && literal.charAt(0) == '\'' && literal.charAt(literal.length() - 1) == '\'') {
            return literal.substring(1, literal.length() - 1);
        }
        return literal;
    }

    /**
     * Writes the reserved-keyword snippet through the generateDocs callbacks.
     */
    public static class ReservedKeywordsDocsSupport extends DocsV3Support {
        private static final Logger logger = LogManager.getLogger(ReservedKeywordsDocsSupport.class);

        public ReservedKeywordsDocsSupport() {
            super("syntax", "reserved-keywords", ReservedKeywordsDocsTests.class, Set::of, callbacksFromSystemProperty());
        }

        @Override
        protected void renderDocs() throws IOException {
            String rendered = renderSnippet();
            logger.info("Writing reserved keywords snippet:\n{}", rendered);
            Path dir = PathUtils.get(System.getProperty("java.io.tmpdir")).resolve("esql").resolve("_snippets").resolve(category);
            callbacks.write(dir, name, "md", rendered, false);
        }
    }
}
