apply plugin: 'elasticsearch.internal-es-plugin'

esplugin {
  name = 'x-pack-query-sampling'
  description = 'Elasticsearch Expanded Pack Plugin - Query sampling for kNN search'
  classname = 'org.elasticsearch.xpack.querysampling.QuerySamplingPlugin'
  extendedPlugins = ['x-pack-core']
}

base {
  archivesName = 'x-pack-query-sampling'
}

dependencies {
  compileOnly project(path: xpackModule('core'))
  testImplementation(testArtifact(project(xpackModule('core'))))
}
