[[synonyms-apis]]
== Synonyms APIs

beta::[]

++++
<titleabbrev>Synonyms APIs</titleabbrev>
++++

---

The synonyms management API provides a convenient way to define and manage synonyms in an internal system index. Related synonyms can be grouped in a "synonyms set".
Create as many synonym sets as you need.

This provides an alternative to:
- Defining inline synonyms in an analyzer definition, which impacts mapping size and can lead to performance issues.
- Using synonyms files, which implies uploading and managing file consistency on all cluster nodes.

Synonyms sets can be used to configure <<analysis-synonym-graph-tokenfilter,synonym graph token filters>> and <<analysis-synonym-tokenfilter,synonym token filters>>.

Once a synonyms set is used in a synonym token filter, these token filters are used as part of a <<search-analyzer,search analyzers>>.
You can dynamically change the synonyms used at search time using these APIs to update the synonyms sets.
Your search results will immediately reflect the synonyms set change.

The following APIs can be used to manage synonyms sets:

* <<put-synonyms-set>>
* <<get-synonyms-set>>
* <<list-synonyms-sets>>
* <<delete-synonyms-set>>

include::put-synonyms-set.asciidoc[]
include::get-synonyms-set.asciidoc[]
include::list-synonyms-sets.asciidoc[]
include::delete-synonyms-set.asciidoc[]

