[[get-ip-location-database-api]]
=== Get IP geolocation database configuration API
++++
<titleabbrev>Get IP geolocation database configuration</titleabbrev>
++++

.New API reference
[sidebar]
--
For the most up-to-date API details, refer to {api-es}/group/endpoint-ingest[Ingest APIs].
--

Returns information about one or more IP geolocation database configurations.

[source,console]
----
GET /_ingest/ip_location/database/my-database-id
----
// TEST[skip:we don't want to leak the enterprise-geoip-downloader task, which touching these APIs would cause. Therefore, skip this test.]



[[get-ip-location-database-api-request]]
==== {api-request-title}

`GET /_ingest/ip_location/database/<database>`

`GET /_ingest/ip_location/database`

[[get-ip-location-database-api-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have the
 `manage` <<privileges-list-cluster,cluster privilege>> to use this API.

[[get-ip-location-database-api-path-params]]
==== {api-path-parms-title}

`<database>`::
(Optional, string)
Comma-separated list of database configuration IDs to retrieve. Wildcard (`*`) expressions are
supported.
+
To get all database configurations, omit this parameter or use `*`.


[[get-ip-location-database-api-query-params]]
==== {api-query-parms-title}

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=master-timeout]


[[get-ip-location-database-api-example]]
==== {api-examples-title}


[[get-ip-location-database-api-specific-ex]]
===== Get information for a specific IP geolocation database configuration

[source,console]
----
GET /_ingest/ip_location/database/my-database-id
----
// TEST[skip:we don't want to leak the enterprise-geoip-downloader task, which touching these APIs would cause. Therefore, skip this test.]

The API returns the following response:

[source,console-result]
----
{
  "databases" : [
    {
      "id" : "my-database-id",
      "version" : 1,
      "modified_date_millis" : 1723040276114,
      "database" : {
        "name" : "GeoIP2-Domain",
        "maxmind" : {
          "account_id" : "1234567"
        }
      }
    }
  ]
}
----
// TEST[skip:we don't want to leak the enterprise-geoip-downloader task, which touching these APIs would cause. Therefore, skip this test.]
