import org.elasticsearch.gradle.internal.info.BuildParams

apply plugin: 'elasticsearch.internal-java-rest-test'

dependencies {
  clusterModules(project(':modules:lang-mustache'))
}

tasks.named("javaRestTest").configure {
  usesDefaultDistribution("ml disabled tests require the default distribution to test xpack.ml.enabled=false behaviour")
}

if (buildParams.inFipsJvm){
  // Test clusters run with security disabled
  tasks.named("javaRestTest").configure{enabled = false }
}
