[[installing-watcher]]
== Installing Watcher

The <<getting-started, Getting Started Guide>> steps through a basic Watcher installation. This
section provides some additional information about the installation prerequisites, deployment
options, and the installation process for RPM/DEB package installations.

[float]
[[installation-prerequisites]]
=== Watcher Installation Prerequisites

All you need to use Watcher is:

* Java 7 or later
* Elasticsearch 1.5 or later
* Elasticsearch License plugin

For information about installing the latest Oracle JDK, see
http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html[Java SE Downloads].
For information about installing Elasticsearch, see {ref}/_installation.html[Installation] in the
Elasticsearch Reference.

If you are using Shield, you’ve already installed the License plugin. If you haven't, installing
Shield is part of the basic installation instructions in the <<getting-started, Getting Started>>
guide. 

[float]
[[deploying-existing-cluster]]
=== Deploying Watcher on an Existing Cluster
Deploying watcher directly to the nodes of an existing cluster is generally the easiest way to get
started with Watcher. Keep in mind, however, that this requires stopping and starting all of the
nodes in your cluster. For larger clusters, we recommend
<<deploying-separate-cluster, deploying Watcher to a separate cluster>>.

When you deploy Watcher on an existing cluster, you use the <<input-search, search input>> to
search the cluster's indexes and load the results into a watch's payload. 

To deploy to an existing cluster, you need to install the License and Watcher plugins on every
node in the cluster. For general installation instructions, see the
<<getting-started, Getting Started>> guide. If you are using the Elasticsearch DEB/RPM packages,
see <<package-installation, Installing Watcher on a DEB/RPM Package Installation>> for more
information.

[float]
[[deploying-separate-cluster]]
=== Deploying Watcher as a Separate Cluster

If you have a larger cluster, we recommend running Watcher on a separate monitoring cluster. If
you're using a separate cluster for Marvel, you can install Watcher on the nodes you're using to
store your Marvel data. 

When you deploy watcher on a separate cluster, you use the <<input-http, HTTP input>> to send
search requests to the cluster you are monitoring and load the results into a watch's payload. 

To deploy to a separate monitoring cluster, you need to install the License and Watcher plugins
on every node in the monitoring cluster. For general installation instructions, see the
<<getting-started, Getting Started>> guide. If you are using the Elasticsearch DEB/RPM packages,
see <<package-installation, Installing Watcher on a DEB/RPM Package Installation>> for more
information.

[float]
[[package-installation]]
=== Installing Watcher on a DEB/RPM Package Installation

If you use the DEB/RPM packages to install Elasticsearch, the installation process for Watcher
is slightly different. You need to install the License and Watcher plugins from the
`/usr/share/elasticsearch` directory using superuser permissions:

[source,shell]
----------------------------------------------------------
cd /usr/share/elasticsearch
sudo bin/plugin -i elasticsearch/license/latest
sudo bin/plugin -i  elasticsearch/watcher/latest
----------------------------------------------------------

[float]
[[offline-installation]]
=== Installing Watcher on Offline Machines

To install Watcher on a machine that doesn't have Internet access:

. Manually download the Watcher binaries from: 
https://download.elastic.co/elasticsearch/watcher/watcher-1.0.0.zip[
https://download.elastic.co/elasticsearch/watcher/watcher-1.0.0.zip].

. Transfer the Watcher zip file to the offline machine.

. Run `bin/plugin` with the `-u` option:

[source,shell]
----------------------------------------------------------
bin/plugin -i watcher -u file://<path_to_zip_file>
----------------------------------------------------------










