config:
  trigger-phrase: '.*run\W+elasticsearch-ci/fwc.*'
  skip-target-branches:
    - "main"
    - "8.19"
  skip-labels:
    - ">test-mute"
steps:
  - group: fwc-snapshots
    steps:
      - label: "{{matrix.LATER_BRANCH}} / Part {{matrix.PART}} / fwc-snapshots"
        key: "fwc-snapshots"
        command: .buildkite/scripts/fwc-snapshots.sh
        timeout_in_minutes: 300
        env:
          FWC_LATER_BRANCH: "{{matrix.LATER_BRANCH}}"
          FWC_PART: "{{matrix.PART}}"
        matrix:
          setup:
            LATER_BRANCH: $FWC_LATER_BRANCHES
            PART: ["1", "2", "3", "4", "5", "6"]
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-16
          buildDirectory: /dev/shm/bk
