/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.publicdata.oracle;

import org.elasticsearch.core.SuppressForbidden;
import org.elasticsearch.xpack.esql.qa.publicdata.catalog.VariantSpec;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * The authoring-time second opinion behind the same SPI. Use it on any expectation whose SQL
 * needed non-trivial dialect work — two independent engines agreeing on an answer is the cheapest
 * review there is. The binary is resolved from {@code $DUCKDB_BIN}, falling back to
 * {@code duckdb} on the PATH.
 */
public class DuckDbOracle implements Oracle {

    private final String binary;

    public DuckDbOracle() {
        this(resolveBinary());
    }

    public DuckDbOracle(String binary) {
        this.binary = binary;
    }

    static String resolveBinary() {
        String fromEnvironment = System.getenv("DUCKDB_BIN");
        return fromEnvironment == null || fromEnvironment.isEmpty() ? "duckdb" : fromEnvironment;
    }

    @Override
    public String name() {
        try {
            OracleResult version = execute(List.of(binary, "--version"), null);
            return "duckdb " + version.stdout().trim();
        } catch (IOException e) {
            return "duckdb (version unavailable: " + e.getMessage() + ")";
        }
    }

    @Override
    public boolean canRead(VariantSpec variant) {
        return true;
    }

    @Override
    public String renderScript(List<OracleQuery> queries) {
        StringBuilder script = new StringBuilder("-- generated by OracleScriptGenerator; authoring aid only, never checked in\n");
        script.append(".mode tabs\n.headers on\n");
        for (OracleQuery query : queries) {
            script.append("-- test: ").append(query.testName()).append('\n');
            String sql = query.sql().trim();
            script.append(sql).append(sql.endsWith(";") ? "" : ";").append("\n\n");
        }
        return script.toString();
    }

    @Override
    public OracleResult run(Path script) throws IOException {
        return execute(List.of(binary, "-init", "/dev/null"), script);
    }

    @SuppressForbidden(reason = "authoring-only process wrapper: ProcessBuilder redirection requires java.io.File, and the JVM-default"
        + " temp location is exactly right for transient oracle output outside any test framework")
    private OracleResult execute(List<String> command, Path stdinFile) throws IOException {
        Path stdout = Files.createTempFile("oracle-stdout", ".out");
        Path stderr = Files.createTempFile("oracle-stderr", ".err");
        try {
            ProcessBuilder builder = new ProcessBuilder(command).redirectOutput(stdout.toFile()).redirectError(stderr.toFile());
            if (stdinFile != null) {
                builder.redirectInput(stdinFile.toFile());
            }
            Process process = builder.start();
            boolean finished = process.waitFor(30, TimeUnit.MINUTES);
            if (finished == false) {
                process.destroyForcibly();
                throw new IOException("oracle run timed out: " + String.join(" ", command));
            }
            return new OracleResult(
                process.exitValue(),
                Files.readString(stdout, StandardCharsets.UTF_8),
                Files.readString(stderr, StandardCharsets.UTF_8)
            );
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException("interrupted while running the oracle", e);
        } finally {
            Files.deleteIfExists(stdout);
            Files.deleteIfExists(stderr);
        }
    }
}
