Vagrant.configure("2") do |config|

  config.vm.define "test.shibboleth.elastic.local" do |config|
    config.vm.box = "elastic/ubuntu-16.04-x86_64"
  end

  config.vm.hostname = "localhost"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 389, host: 60389, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 636, host: 60636, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8080, host: 60080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8443, host: 60443, protocol: "tcp"

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "src/main/resources/provision/playbook.yml"
    ansible.install_mode = "pip"
  end

end
