Vagrant.configure("2") do |config|

  config.vm.define "test.shibboleth.elastic.local" do |config|
    config.vm.box = "elastic/ubuntu-16.04-x86_64"
  end

  config.vm.hostname = "localhost"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  TCP_PORTS_LIST = { "389" => 60389, "636" => 60636, "8080" => 60080, "8443" => "60443"}

  TCP_PORTS_LIST.each do |guest, host|
    config.vm.network "forwarded_port", guest: "#{guest}", host: "{host}", protocol: "tcp",
    config.vm.usable_port_range = 389..8443,
    auto_correct: true

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "src/main/resources/provision/playbook.yml"
    ansible.install_mode = "pip"
    ansible.extra_vars = {
      ports_list: TCP_PORTS_LIST
    }
  end

end
