[role="xpack"]
[[ilm-rollup]]
=== Rollup

Phases allowed: hot, cold.

Aggregates an index's time series data and stores the results in a new read-only
index. For example, you can roll up hourly data into daily or weekly summaries.

This action corresponds to the <<rollup-api,rollup API>>. The name of the
resulting rollup index is `rollup-<original-index-name>`. If {ilm-init} performs
the `rollup` action on a backing index for a data stream, the rollup index is a
backing index for the same stream.

To use the `rollup` action in the hot phase, the <<ilm-rollover,`rollover`>>
action must be present. If no `rollover` action is configured, {ilm-init} will
reject the policy.

[role="child_attributes"]
[[ilm-rollup-options]]
==== Options

`config`::
(Required, object)
Configures the rollup action.
+
.Properties of `config`
[%collapsible%open]
====
include::{es-repo-dir}/rollup/apis/rollup-api.asciidoc[tag=rollup-config]
====

`rollup_policy`::
(Optional, string)
Lifecycle policy for the resulting rollup index. If you don't specify a policy,
{ilm-init} will not manage the rollup index.

[[ilm-rollup-ex]]
==== Example

////
[source,console]
----
PUT _ilm/policy/my-rollup-ilm-policy
{
  "policy": {
    "phases": {
      "delete": {
        "actions": {
          "delete" : { }
        }
      }
    }
  }
}
----
////

[source,console]
----
PUT _ilm/policy/my-policy
{
  "policy": {
    "phases": {
      "cold": {
        "actions": {
          "rollup": {
            "config": {
              "groups": {
                "date_histogram": {
                  "field": "@timestamp",
                  "calendar_interval": "1y"
                }
              },
              "metrics": [
                {
                  "field": "my-numeric-field",
                  "metrics": [
                    "avg"
                  ]
                }
              ]
            },
            "rollup_policy": "my-rollup-ilm-policy"
          }
        }
      }
    }
  }
}
----
// TEST[continued]
