/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.stateless;

import org.elasticsearch.action.DocWriteResponse;
import org.elasticsearch.action.bulk.BulkItemResponse;
import org.elasticsearch.common.blobstore.OperationPurpose;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.core.CheckedRunnable;
import org.elasticsearch.index.IndexSettings;
import org.elasticsearch.plugins.Plugin;
import org.elasticsearch.test.transport.MockTransportService;
import org.elasticsearch.xpack.stateless.action.TransportNewCommitNotificationAction;
import org.elasticsearch.xpack.stateless.commits.StatelessCommitService;
import org.elasticsearch.xpack.stateless.objectstore.ObjectStoreService;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;

import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoFailures;

public class StatelessUpdateIT extends AbstractStatelessPluginIntegTestCase {
    public void testUpdateDoesNotRequireFlush() {
        testUpdate(false);
    }

    public void testBulkUpdateDoesNotRequireFlush() {
        testUpdate(true);
    }

    public void testUpdatesWithUnsafeVersionMap() {
        var indexNode = startMasterAndIndexNode();
        startSearchNode();
        ensureStableCluster(2);

        final String indexName = randomIndexName();
        createIndex(indexName, indexSettings(1, 1).put(IndexSettings.INDEX_REFRESH_INTERVAL_SETTING.getKey(), -1).build());
        ensureGreen(indexName);

        var bulkRequest = client().prepareBulk();
        int requestsInBulk = randomIntBetween(5, 10);
        for (int i = 0; i < requestsInBulk; i++) {
            // Note usage of autogenerated ids so that live version map is unsafe.
            var indexRequest = client().prepareIndex(indexName).setSource("field", "value1");
            bulkRequest.add(indexRequest);
        }
        var bulkResponse = bulkRequest.get();
        assertNoFailures(bulkResponse);

        var commitNotificationsBlocked = new CountDownLatch(1);

        var indexNodeTransportService = MockTransportService.getInstance(indexNode);
        indexNodeTransportService.addSendBehavior((connection, requestId, action, request, options) -> {
            if (TransportNewCommitNotificationAction.NAME.equals(action)) {
                safeAwait(commitNotificationsBlocked);
            }
            connection.sendRequest(requestId, action, request, options);
        });

        var initialStats = Arrays.stream(indicesAdmin().prepareStats(indexName).get().getIndex(indexName).getShards())
            .filter(s -> s.getShardRouting().isPromotableToPrimary())
            .findFirst()
            .get();
        // Two refreshes happen during recovery: "recovery_finalization" and "post_recovery".
        assertEquals(2, initialStats.getStats().getRefresh().getTotal());

        var idToUpdate = randomFrom(Arrays.stream(bulkResponse.getItems()).map(BulkItemResponse::getId).toList());

        var update = client().prepareUpdate(indexName, idToUpdate).setDoc(Map.of("field", "value2"));
        assertEquals(DocWriteResponse.Result.UPDATED, update.execute().actionGet().getResult());

        // At this point the live version map should be safe and we should be able to perform an update without a refresh.
        var update2 = client().prepareUpdate(indexName, idToUpdate).setDoc(Map.of("field", "value3"));
        assertEquals(DocWriteResponse.Result.UPDATED, update2.execute().actionGet().getResult());

        var stats = Arrays.stream(indicesAdmin().prepareStats(indexName).get().getIndex(indexName).getShards())
            .filter(s -> s.getShardRouting().isPromotableToPrimary())
            .findFirst()
            .get();
        /// We should see two refreshes:
        /// one happened during the transition of live version map from unsafe to safe when executing `update`
        /// second one happened because we have found the id that is being updated in the live version map when executing `update2`
        /// (see [org.elasticsearch.index.engine.InternalEngine#realtimeGetUnderLock]).
        assertEquals(2, stats.getStats().getRefresh().getTotal() - initialStats.getStats().getRefresh().getTotal());
    }

    private void testUpdate(boolean useBulkApi) {
        var indexNode = startMasterAndIndexNode();
        startSearchNode();
        ensureStableCluster(2);

        final String indexName = randomIndexName();
        createIndex(indexName, indexSettings(1, 1).put(IndexSettings.INDEX_REFRESH_INTERVAL_SETTING.getKey(), -1).build());
        ensureGreen(indexName);

        var bulkRequest = client().prepareBulk();
        int requestsInBulk = randomIntBetween(2, 5);
        for (int i = 0; i < requestsInBulk; i++) {
            var indexRequest = client().prepareIndex(indexName).setSource("field", "value1").setId(String.valueOf(i));
            bulkRequest.add(indexRequest);
        }
        assertNoFailures(bulkRequest.get());

        var commitUploads = new AtomicInteger(0);
        setNodeRepositoryStrategy(indexNode, new StatelessMockRepositoryStrategy() {
            @Override
            public void blobContainerWriteBlobAtomic(
                CheckedRunnable<IOException> originalRunnable,
                OperationPurpose purpose,
                String blobName,
                InputStream inputStream,
                long blobSize,
                boolean failIfAlreadyExists
            ) throws IOException {
                commitUploads.incrementAndGet();
                super.blobContainerWriteBlobAtomic(originalRunnable, purpose, blobName, inputStream, blobSize, failIfAlreadyExists);
            }
        });

        var idToUpdate = String.valueOf(randomIntBetween(0, requestsInBulk - 1));

        // At this point, translog locations are not tracked in the live version map since there were no realtime gets.
        // During the update, we'll perform a refresh since there are no translog location to read from
        // but it is not required to do a flush.
        // Flush is undesirable since it can take significant amount of time with write thread blocked
        // and holding a primary operation permit.
        var update = client().prepareUpdate(indexName, idToUpdate).setDoc(Map.of("field", "value2"));
        if (useBulkApi) {
            var bulkWithUpdate = client().prepareBulk().add(update).execute().actionGet();
            assertNoFailures(bulkWithUpdate);
        } else {
            update.execute().actionGet();
        }

        // This is a trick to catch any possible commit uploads that are in flight (if this test is about to fail).
        // We should only see one upload that is produced by the flush below.
        flush(indexName);
        assertEquals(1, commitUploads.get());
    }

    @Override
    protected Collection<Class<? extends Plugin>> nodePlugins() {
        var plugins = new ArrayList<>(super.nodePlugins());
        plugins.add(StatelessMockRepositoryPlugin.class);
        return plugins;
    }

    @Override
    protected Settings.Builder nodeSettings() {
        return super.nodeSettings().put(ObjectStoreService.TYPE_SETTING.getKey(), ObjectStoreService.ObjectStoreType.MOCK)
            .put(StatelessCommitService.STATELESS_UPLOAD_MAX_SIZE.getKey(), ByteSizeValue.ofBytes(1))
            .put(disableIndexingDiskAndMemoryControllersNodeSettings());
    }

    @Override
    protected boolean addMockFsRepository() {
        return false;
    }
}
