/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

// Elasticsearch-specific conventions on top of the `elasticsearch.jmh` binary plugin:
// wires the shared benchmark helpers, JMH extra-param annotation processor, and the
// test framework used by benchmark correctness tests.
apply plugin: 'elasticsearch.jmh'

dependencies {
  benchmarkImplementation project(':benchmarks:common')
  benchmarkAnnotationProcessor project(':benchmarks:processor')
  benchmarkTestImplementation project(':test:framework')
}
