/*
 * Licensed to Elasticsearch under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.elasticsearch.smoketest;

import org.apache.http.HttpHost;
import org.apache.lucene.util.BytesRef;

import com.carrotsearch.randomizedtesting.annotations.Name;
import com.carrotsearch.randomizedtesting.annotations.ParametersFactory;
import org.elasticsearch.Version;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.common.ParseField;
import org.elasticsearch.common.xcontent.ConstructingObjectParser;
import org.elasticsearch.common.xcontent.NamedXContentRegistry;
import org.elasticsearch.common.xcontent.XContentLocation;
import org.elasticsearch.common.xcontent.XContentParser;
import org.elasticsearch.common.xcontent.XContentParser.Token;
import org.elasticsearch.test.rest.yaml.ClientYamlDocsTestClient;
import org.elasticsearch.test.rest.yaml.ClientYamlTestCandidate;
import org.elasticsearch.test.rest.yaml.ClientYamlTestClient;
import org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext;
import org.elasticsearch.test.rest.yaml.ClientYamlTestResponse;
import org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase;
import org.elasticsearch.test.rest.yaml.restspec.ClientYamlSuiteRestSpec;
import org.elasticsearch.test.rest.yaml.section.ExecutableSection;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import static org.elasticsearch.common.xcontent.ConstructingObjectParser.constructorArg;

import static java.util.Collections.emptyMap;
import static java.util.Collections.singletonList;
import static java.util.Collections.singletonMap;

public class DocsClientYamlTestSuiteIT extends ESClientYamlSuiteTestCase {

    public DocsClientYamlTestSuiteIT(@Name("yaml") ClientYamlTestCandidate testCandidate) {
        super(testCandidate);
    }

    @ParametersFactory
    public static Iterable<Object[]> parameters() throws Exception {
        List<NamedXContentRegistry.Entry> entries = new ArrayList<>(ExecutableSection.DEFAULT_EXECUTABLE_CONTEXTS.size() + 1);
        entries.addAll(ExecutableSection.DEFAULT_EXECUTABLE_CONTEXTS);
        entries.add(new NamedXContentRegistry.Entry(ExecutableSection.class, new ParseField("test_analyzer"), TestAnalyzer::parse));
        NamedXContentRegistry executeableSectionRegistry = new NamedXContentRegistry(entries);
        return ESClientYamlSuiteTestCase.createParameters(executeableSectionRegistry);
    }

    @Override
    protected void afterIfFailed(List<Throwable> errors) {
        super.afterIfFailed(errors);
        String name = getTestName().split("=")[1];
        name = name.substring(0, name.length() - 1);
        name = name.replaceAll("/([^/]+)$", ".asciidoc:$1");
        logger.error("This failing test was generated by documentation starting at {}. It may include many snippets. "
                + "See docs/README.asciidoc for an explanation of test generation.", name);
    }

    @Override
    protected boolean randomizeContentType() {
        return false;
    }

    @Override
    protected ClientYamlTestClient initClientYamlTestClient(ClientYamlSuiteRestSpec restSpec, RestClient restClient,
                                                            List<HttpHost> hosts, Version esVersion) throws IOException {
        return new ClientYamlDocsTestClient(restSpec, restClient, hosts, esVersion);
    }

    private static class TestAnalyzer implements ExecutableSection {
        private static ConstructingObjectParser<TestAnalyzer, XContentLocation> PARSER =
            new ConstructingObjectParser<>("test_analyzer", false, (a, location) -> {
                String index = (String) a[0];
                String builtIn = (String) a[1];
                String rebuilt = (String) a[2];
                return new TestAnalyzer(location, index, builtIn, rebuilt);
            });
        static {
            PARSER.declareString(constructorArg(), new ParseField("index"));
            PARSER.declareString(constructorArg(), new ParseField("built_in"));
            PARSER.declareString(constructorArg(), new ParseField("rebuilt"));
        }
        private static TestAnalyzer parse(XContentParser parser) throws IOException {
            XContentLocation location = parser.getTokenLocation();
            TestAnalyzer section = PARSER.parse(parser, location);
            assert parser.currentToken() == Token.END_OBJECT;
            parser.nextToken(); // throw out the END_OBJECT to conform with other ExecutableSections
            return section;
        }

        private final XContentLocation location;
        private final String index;
        private final String builtIn;
        private final String rebuilt;

        private TestAnalyzer(XContentLocation location, String index, String builtIn, String rebuilt) {
            this.location = location;
            this.index = index;
            this.builtIn = builtIn;
            this.rebuilt = rebuilt;
        }

        @Override
        public XContentLocation getLocation() {
            return location;
        }

        @Override
        public void execute(ClientYamlTestExecutionContext executionContext) throws IOException {
            int size = 100;
            List<String> testText = new ArrayList<>(size);
            for (int i = 0; i < size; i++) {
                testText.add(randomRealisticUnicodeOfCodepointLength(between(1, 15))
                    // Don't look up stashed values
                    .replace("$", "\\$"));
            }
            Map<String, Object> body = new HashMap<>(2);
            body.put("analyzer", builtIn);
            body.put("text", testText);
            ClientYamlTestResponse response = executionContext.callApi("indices.analyze", singletonMap("index", index),
                    singletonList(body), emptyMap());
            Iterator<?> builtInTokens = ((List<?>) response.evaluate("tokens")).iterator();
            body.put("analyzer", rebuilt);
            response = executionContext.callApi("indices.analyze", singletonMap("index", index),
                    singletonList(body), emptyMap());
            Iterator<?> rebuiltTokens = ((List<?>) response.evaluate("tokens")).iterator();

            Object previousRebuilt = null;
            Object previousBuiltIn = null;
            while (builtInTokens.hasNext()) {
                if (false == rebuiltTokens.hasNext()) {
                    fail("rebuilt token filter has fewer tokens. built in has [" + builtInTokens.next()
                        + "]. Previous built in was [" + previousBuiltIn + "] and previous rebuilt was ["
                        + previousRebuilt + "]");
                }
                Map<?, ?> builtInToken = (Map<?, ?>) builtInTokens.next();
                Map<?, ?> rebuiltToken = (Map<?, ?>) rebuiltTokens.next();
                String builtInText = (String) builtInToken.get("token");
                String rebuiltText = (String) rebuiltToken.get("token");
                // Check the text and produce an error message with the utf8 sequence if they don't match.
                if (false == rebuiltText.equals(builtInText)) {
                    fail("text differs. built in was [" + builtInText + "] but rebuilt was [" + rebuiltText + "]. In utf8 those are\n"
                        + new BytesRef(builtInText) + " and\n" + new BytesRef(rebuiltText));
                }
                // Now check the whole map just in case the text matches but something else differs
                assertEquals(builtInToken, rebuiltToken);
            }
            if (rebuiltTokens.hasNext()) {
                fail("rebuilt token filter has more tokens. it has [" + rebuiltTokens.next() + "]. Previous built in was ["
                    + previousBuiltIn + "] and previous rebuilt was [" + previousRebuilt + "]");
            }
        }
    }
}
