/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

/**
 * Annotation-driven bindings for native libraries via the Java Foreign Function and Memory (FFM)
 * API. A native library binding is declared as a Java interface annotated with
 * {@link org.elasticsearch.foreign.LibrarySpecification @LibrarySpecification}; the annotation
 * processor in {@code libs/foreign-library/processor} generates an FFM-backed implementation plus the
 * {@link org.elasticsearch.foreign.LibraryProvider} that loads it.
 *
 * <p>A minimal example binding two symbols from the system C library:
 *
 * <pre>{@code
 * @LibrarySpecification(name = "c")
 * public interface CLibrary {
 *
 *     @Function("getpid")
 *     int getpid();
 *
 *     @Function("strlen")
 *     long strlen(MemorySegment str);
 * }
 * }</pre>
 *
 * <p>Callers obtain an instance through {@link org.elasticsearch.foreign.LibraryProvider#lookupLibrary(Class)},
 * which resolves the generated provider via {@link java.util.ServiceLoader}:
 *
 * <pre>{@code
 * CLibrary c = LibraryProvider.lookupLibrary(CLibrary.class);
 * int pid = c.getpid();
 * }</pre>
 *
 * <h2>Wiring</h2>
 *
 * Apply the {@code elasticsearch.foreign-library} Gradle plugin to a module that contains
 * {@code @LibrarySpecification} interfaces. The plugin runs the annotation processor during
 * compilation and injects the generated {@code $Provider} classes into the compiled
 * {@code module-info.class} as {@code provides org.elasticsearch.foreign.LibraryProvider with ...}
 * directives. The source {@code module-info.java} should not declare these provides clauses — they
 * reference classes that exist only as generated bytecode.
 *
 * <h2>Method binding</h2>
 *
 * Every method on a {@code @LibrarySpecification} interface must be annotated with
 * {@link org.elasticsearch.foreign.Function @Function} naming the exact C symbol. Symbols are
 * never inferred from Java method names, so multiple Java overloads can bind to the same C function
 * with different linker options (for example, a heap-friendly variant marked
 * {@link org.elasticsearch.foreign.Critical @Critical}).
 */
package org.elasticsearch.foreign;
