[float]
[[breaking_70_mappings_changes]]
=== Mapping changes

[float]
==== The `_all` meta field is removed

The `_all` field deprecated in 6 have now been removed.

[float]
==== The `_uid` meta field is removed

This field used to index a composite key formed of the `_type` and the `_id`.
Now that indices cannot have multiple types, this has been removed in favour
of `_id`.

[float]
==== The `_default_` mapping is no longer allowed

The `_default_` mapping has been deprecated in 6.0 and is now no longer allowed
in 7.0. Trying to configure a `_default_` mapping on 7.x indices will result in
an error.

[float]
==== `index_options` for numeric fields has been removed

The `index_options` field for numeric  fields has been deprecated in 6 and has now been removed.

[float]
==== Limiting the number of `nested` json objects

To safeguard against out of memory errors, the number of nested json objects within a single
document across all fields has been limited to 10000. This default limit can be changed with
the index setting `index.mapping.nested_objects.limit`.

[float]
==== The `update_all_types` option has been removed

This option is useless now that all indices have at most one type.

[float]
==== The `classic` similarity has been removed

The `classic` similarity relied on coordination factors for scoring to be good
in presence of stopwords in the query. This feature has been removed from
Lucene, which means that the `classic` similarity now produces scores of lower
quality. It is advised to switch to `BM25` instead, which is widely accepted
as a better alternative.

[float]
==== Similarities fail when unsupported options are provided

An error will now be thrown when unknown configuration options are provided
to similarities. Such unknown parameters were ignored before.
