[role="xpack"]
[[security-api-update-settings]]
=== Update Security index settings
++++
<titleabbrev>Update Security settings</titleabbrev>
++++

==== {api-prereq-title}

* To use this API, you must have at least the `manage_security` cluster privilege.

==== {api-description-title}
This API allows a user to modify the settings for the Security internal indices (`.security` and associated indices). Only a subset of settings are allowed to be modified. This includes:

- `index.auto_expand_replicas`
- `index.number_of_replicas`

An example of modifying the Security settings:

[source,console]
-----------------------------------------------------------
PUT /_security/settings
{
    "security": {
        "index.auto_expand_replicas": "0-all"
    },
    "security-tokens": {
        "index.auto_expand_replicas": "0-all"
    },
    "security-profile": {
        "index.auto_expand_replicas": "0-all"
    }
}
-----------------------------------------------------------
// TEST[skip:making sure all the indices have been created reliably is difficult]

The configured settings can be retrieved using the <<security-api-get-settings,Get Security index settings>> API. If a
given index is not in use on the system, but settings are provided for it, the request will be rejected - this API does
not yet support configuring the settings for these indices before they are in use.

==== {api-request-body-title}
`security`::
(Optional, object) Settings to be used for the index used for most security configuration, including Native realm users
and roles configured via the API.

`security-tokens`::
(Optional, object) Settings to be used for the index used to store <<tokens,security-api-get-token>>.

`security`::
(Optional, object) Settings to be used for the index used to store <<Profile,security-api-activate-user-profile>> information.
