[[important-node-settings]]

[float]
[[node.name]]
==== `node.name`

Elasticsearch uses `node.name` as a human readable identifier for a
particular instance of Elasticsearch so it is included in the response
of many APIs. It defaults to the hostname that the machine has when
Elasticsearch starts but can be configured explicitly in
`elasticsearch.yml` as follows:

[source,yaml]
--------------------------------------------------
node.name: prod-data-2
--------------------------------------------------

[float]
[[node.processors]]
==== `node.processors`

Elasticsearch sizes various thread pools on the basis of the number of
processors that the JVM detects are available. In most cases, this number is
equal to the number of logical cores on the host machine, a suitable default. In
some cases, for example when CPU quotas are in place, this is not a suitable
default. In these cases, you can control the number of allocated processors via
the `node.processors` setting, and Elasticsearch will adjust the sizing of its
thread pools accordingly.

[source,yaml]
--------------------------------------------------
node.processors: 16
--------------------------------------------------
