/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

apply plugin: 'elasticsearch.internal-java-rest-test'
apply plugin: 'elasticsearch.rest-resources'

dependencies {
  javaRestTestImplementation(testArtifact(project(xpackModule('snapshot-based-recoveries'))))
}

restResources {
  restApi {
    include 'indices', 'search', 'bulk', 'snapshot'
  }
}

tasks.named("javaRestTest").configure {
  usesDefaultDistribution("requires DEFAULT distribution for license enforcement and snapshot-based recovery")
}
