[role="xpack"]
[[how-monitoring-works]]
== How monitoring works
++++
<titleabbrev>How it works</titleabbrev>
++++

Each {es} node, {ls} node, {kib} instance, and Beat instance is considered
unique in the cluster based on its persistent UUID, which is written to the
<<path-settings,`path.data`>> directory when the node or instance starts.

Monitoring documents are just ordinary JSON documents built by monitoring each
{stack} component at a specified collection interval. If you want to alter the
templates for these indices, see <<config-monitoring-indices>>.

{metricbeat} is used to collect monitoring data and to ship it directly to the
monitoring cluster.

To learn how to collect monitoring data, see:

* <<collecting-monitoring-data>>
* <<configuring-metricbeat>>
* {kibana-ref}/xpack-monitoring.html[Monitoring {kib}]
* {logstash-ref}/configuring-logstash.html[Monitoring {ls}]
* Monitoring Beats:
** {auditbeat-ref}/monitoring.html[{auditbeat}]
** {filebeat-ref}/monitoring.html[{filebeat}]
** {functionbeat-ref}/monitoring.html[{functionbeat}]
** {heartbeat-ref}/monitoring.html[{heartbeat}]
** {metricbeat-ref}/monitoring.html[{metricbeat}]
** {packetbeat-ref}/monitoring.html[{packetbeat}]
** {winlogbeat-ref}/monitoring.html[{winlogbeat}]
