[[investigating-cpu-spikes]]
== Investigating CPU spikes

[discrete]
=== Monitoring

Elastic stack monitoring collects metrics from the Elasticsearch nodes, Logstash, Kibana instances, and Beats in your deployment.  You can also configure Filebeat to collect the logs from the same components of your deployment.  See the <<monitoring-production,monitoring production>> docs and configure monitoring.

[discrete]
=== Alerting
When you set up monitoring, several stack monitoring alerts become available in Stack Management > Alerts and actions.  You should consider <<alerting-getting-started,adding connectors>> to send the alerts to you, the default is to write the alerts to the Kibana log file.

[discrete]
=== Detecting high CPU utilization
These are indicators of high CPU utilization:

- monitoring reports high utilization
- high load averages
- frequent or long Java garbage collection (GC) cycles
- every GC cycle takes CPU time
- having 20 or more <<shard-count-recommendation,shards per GB of heap>>. 

[discrete]
=== Look for high CPU consuming threads

Occasional CPU intensive jobs are expected, but constant high CPU usage on 
long running jobs should be investigated.  If CPU utilization on a system
with an Elasticsearch node is high then find out which Elasticsearch
threads are contributing to this by using the <<cluster-nodes-hot-threads,nodes hot threads API>>:

[source,console]
--------------------------------------------------
GET _nodes/hot_threads
--------------------------------------------------

[discrete]
=== Look for long running tasks

Common high CPU causes are heavy read/write. Certain elasticsearch operations
can also be CPU intensive, like lookup, analyzer, nested aggregation, force
merge, percolate query, machine learning jobs. Some watcher jobs can also be
expensive (depending on the script).  Find long running tasks using the <<tasks,task management API>>: 

[source,console]
--------------------------------------------------
GET _tasks?detailed
--------------------------------------------------

