[role="xpack"]
[[security-api-enable-user-profile]]
=== Enable user profile API
++++
<titleabbrev>Enable user profile</titleabbrev>
++++

NOTE: The user profile feature is designed only for use by {kib} and
Elastic’s {observability}, {ents}, and {elastic-sec} solutions. Individual
users and external applications should not call this API directly. Elastic reserves
the right to change or remove this feature in future releases without prior notice.

Enables a user profile so it's visible in
<<security-api-suggest-user-profile,user profile searches>>.

[[security-api-enable-user-profile-request]]
==== {api-request-title}

`POST /_security/profile/<uid>/_enable`

`PUT /_security/profile/<uid>/_enable`

[[security-api-enable-user-profile-prereqs]]
==== {api-prereq-title}

To use this API, you must have the `manage_user_profile` cluster privilege.

[[security-api-enable-user-profile-desc]]
==== {api-description-title}

When you <<security-api-activate-user-profile,activate a user profile>>, it's
automatically enabled and visible in user profile searches. If you later
<<security-api-disable-user-profile,disable the user profile>>, you can use the
enable user profile API to make the profile visible in these searches again.

[[security-api-enable-user-profile-path-params]]
==== {api-path-parms-title}

`<uid>`::
(Required, string) Unique identifier for the user profile.

[[security-api-enable-user-profile-query-params]]
==== {api-query-parms-title}

include::{es-repo-dir}/rest-api/common-parms.asciidoc[tag=refresh]

[[security-api-enable-user-profile-example]]
==== {api-examples-title}

The following request enables the user profile for a `uid` matching
`u_79HkWkwmnBH5gqFKwoxggWPjEBOur1zLPXQPEl1VBW0_0`:

[source,console]
----
POST /_security/profile/u_79HkWkwmnBH5gqFKwoxggWPjEBOur1zLPXQPEl1VBW0_0/_enable
----
// TEST[setup:user_profiles]

