[role="xpack"]
[[security-api-get-service-account-tokens]]
=== Get service account tokens information API

beta::[]

++++
<titleabbrev>Get service account tokens information</titleabbrev>
++++

Retrieves information of all service tokens for a service account.

[[security-api-get-service-account-tokens-request]]
==== {api-request-title}

`GET /_security/service/<namespace>/<service>/credential`

[[security-api-get-service-account-tokens-prereqs]]
==== {api-prereq-title}

* To use this API, you must have at least the `manage_service_account` cluster privilege.

[[security-api-get-service-account-tokens-desc]]
==== {api-description-title}

When you are running in production mode, the service account feature requires TLS on the HTTP interface.
See <<encrypt-http-communication>>. A runtime check prevents you from invoking any service account
related APIs or authenticating with a service account token unless TLS is enabled on the HTTP interface.

The information for the service account tokens created by
<<security-api-create-service-account-token>> or
<<service-tokens-command,elasticsearch-service-tokens>> CLI tool
can be retrieved using this API.

NOTE: For tokens backed the `service_tokens` file, the API only returns those
tokens defined in the file local to the coordinating node.

[[security-api-get-service-account-tokens-path-params]]
==== {api-path-parms-title}

`namespace`::
(Required, string) An identifier for the namespace.

`service`::
(Required, string) An identifier for the service name.

[[security-api-get-service-account-tokens-example]]
==== {api-examples-title}

If you create a service account token as follows:

[source,console]
------------------------------------------------------------
POST /_security/service/elastic/fleet-server/credential/token/token1
------------------------------------------------------------

A successful call returns a JSON structure that provides
service account token information. For example:

[source,console-result]
--------------------------------------------------
{
  "created": true,
  "token": {
    "name": "token1",
    "value": "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuMTo3TFdaSDZWbVMxT0pOeXJXd3N3ZzBR"
  }
}
--------------------------------------------------
// TESTRESPONSE[s/AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuMTo3TFdaSDZWbVMxT0pOeXJXd3N3ZzBR/$body.token.value/]

You can use the following example to retrieve the service accounts:

[source,console]
--------------------------------------------------
GET /_security/service/elastic/fleet-server/credential
--------------------------------------------------

You can use the following example to retrieve the service account token by name:

[source,js]
--------------------------------------------------
{
  "service_account": "elastic/fleet-server",
  "node_name": "node0", <1>
  "count": 3,
  "tokens": {
    "token1": {}, <2>
    "token42": {} <3>
  },
  "file_tokens": {
    "my-token": {} <4>
  }
}
--------------------------------------------------
// NOTCONSOLE
<1> The local node name
<2> A `.security` index backed token created just now
<3> Another `.security` index backed token created previously
<4> A file backed token local to `node0`
