apply plugin: 'elasticsearch.internal-yaml-rest-test'

dependencies {
  yamlRestTestImplementation(testArtifact(project(xpackModule('core'))))
  yamlRestTestImplementation(testArtifact(project(':x-pack:plugin')))
}

// bring in text structure rest test suite
restResources {
  restApi {
    // needed for template installation, etc.
    include '_common', 'bulk', 'indices', 'text_structure'
  }
  restTests {
    includeXpack 'text_structure'
  }
}

tasks.named("yamlRestTest").configure {
  usesDefaultDistribution("text structure with security requires x-pack trial license and security")
}
