/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.elasticsearch.thrift;


public enum Method implements org.apache.thrift.TEnum {
    GET(0),
    PUT(1),
    POST(2),
    DELETE(3),
    HEAD(4),
    OPTIONS(5);

    private final int value;

    private Method(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     *
     * @return null if the value is not found.
     */
    public static Method findByValue(int value) {
        switch (value) {
            case 0:
                return GET;
            case 1:
                return PUT;
            case 2:
                return POST;
            case 3:
                return DELETE;
            case 4:
                return HEAD;
            case 5:
                return OPTIONS;
            default:
                return null;
        }
    }
}
