scm:
  enabled: true
  owner: elastic
  repository: elasticsearch
  branch: main
  commitusingapi: true
  # begin updatecli-compose policy values
  user: elasticmachine
  email: 42973632+elasticmachine@users.noreply.github.com
  # end updatecli-compose policy values
