[role="xpack"]
[[java-rest-high-security-get-role-mappings]]
=== Get Role Mappings API

[[java-rest-high-security-get-role-mappings-execution]]
==== Execution

Retrieving a role mapping can be performed using the `security().getRoleMappings()`
method and by setting role mapping name on `GetRoleMappingsRequest`:

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-execute]
--------------------------------------------------

Retrieving multiple role mappings can be performed using the `security.getRoleMappings()`
method and by setting role mapping names on `GetRoleMappingsRequest`:

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-list-execute]
--------------------------------------------------

Retrieving all role mappings can be performed using the `security.getRoleMappings()`
method and with no role mapping name on `GetRoleMappingsRequest`:

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-all-execute]
--------------------------------------------------

[[java-rest-high-security-get-role-mappings-response]]
==== Response

The returned `GetRoleMappingsResponse` contains the list of role mapping(s).

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-response]
--------------------------------------------------

[[java-rest-high-security-get-role-mappings-async]]
==== Asynchronous Execution

This request can be executed asynchronously using the `security().getRoleMappingsAsync()`
method:

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-execute-async]
--------------------------------------------------
<1> The `GetRoleMappingsRequest` to execute and the `ActionListener` to use when
the execution completes

The asynchronous method does not block and returns immediately. Once the request
has completed the `ActionListener` is called back using the `onResponse` method
if the execution successfully completed or using the `onFailure` method if
it failed.

A typical listener for a `GetRoleMappingsResponse` looks like:

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/SecurityDocumentationIT.java[get-role-mappings-execute-listener]
--------------------------------------------------
<1> Called when the execution is successfully completed. The response is
provided as an argument
<2> Called in case of failure. The raised exception is provided as an argument