--
:api: invalidate-my-api-key
:request: InvalidateApiKeyRequest
:response: InvalidateApiKeyResponse
--

[id="{upid}-{api}"]
=== Invalidate API key(s) owned by authenticated user API

API Key(s) owned by authenticated user can be invalidated using this API.

[id="{upid}-{api}-request"]
==== Invalidate My API Key Request
The +{request}+ supports invalidating

. A specific API key by api key id or by name

. All API key(s) for current logged in user

===== Specific API key by API key id
["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests-file}[invalidate-my-api-key-id-request]
--------------------------------------------------

===== Specific API key by API key name
["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests-file}[invalidate-my-api-key-name-request]
--------------------------------------------------

===== Invalidate all API key(s) owned by authenticated user
["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests-file}[invalidate-my-api-key-all-request]
--------------------------------------------------

include::../execution.asciidoc[]

[id="{upid}-{api}-response"]
==== Invalidate API Key Response

The returned +{response}+ contains the information regarding the API keys that the request
invalidated.

`invalidatedApiKeys`:: Available using `getInvalidatedApiKeys` lists the API keys
                      that this request invalidated.

`previouslyInvalidatedApiKeys`:: Available using `getPreviouslyInvalidatedApiKeys` lists the API keys
                                that this request attempted to invalidate
                                but were already invalid.

`errors`:: Available using `getErrors` contains possible errors that were encountered while
           attempting to invalidate API keys.

["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests-file}[{api}-response]
--------------------------------------------------