/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import org.elasticsearch.gradle.testclusters.StandaloneRestIntegTestTask

apply plugin: 'elasticsearch.internal-java-rest-test'
apply plugin: 'elasticsearch.bwc-test'
apply plugin: 'elasticsearch.bc-upgrade-test'

dependencies {
  javaRestTestImplementation testArtifact(project(':server'))
  javaRestTestImplementation testArtifact(project(xpackModule('core')))
  javaRestTestImplementation project(':x-pack:qa')
  javaRestTestImplementation testArtifact(project(xpackModule('inference')))
  javaRestTestImplementation project(':modules:reindex')
  javaRestTestImplementation testArtifact(project(':qa:rolling-upgrade'), 'javaRestTest')
}

buildParams.bwcVersions.withWireCompatible { bwcVersion, baseName ->
  // SearchableSnapshotsRollingUpgradeIT uses a specific repository to not interfere with other tests
  String searchableSnapshotRepository = "${layout.buildDirectory.get().asFile}/cluster/shared/searchable-snapshots-repo/${baseName}"

  tasks.register(bwcTaskName(bwcVersion), StandaloneRestIntegTestTask) {
    usesBwcDistribution(bwcVersion)
    systemProperty("tests.old_cluster_version", bwcVersion)
    systemProperty("tests.path.searchable.snapshots.repo", searchableSnapshotRepository)
    doFirst {
      delete(searchableSnapshotRepository)
    }
  }
}

tasks.withType(Test).configureEach {
  maxParallelForks = 1
}
