=== Snapshot and Restore changes

==== File-system repositories must be whitelisted

Locations of the shared file system repositories and the URL repositories with
`file:` URLs now have to be registered before starting Elasticsearch using the
`path.repo` setting. The `path.repo` setting can contain one or more
repository locations:

[source,yaml]
---------------
path.repo: ["/mnt/daily", "/mnt/weekly"]
---------------

If the repository location is specified as an absolute path it has to start
with one of the locations specified in `path.repo`. If the location is
specified as a relative path, it will be resolved against the first location
specified in the `path.repo` setting.

==== URL repositories must be whitelisted

URL repositories with `http:`, `https:`, and `ftp:` URLs have to be
whitelisted before starting Elasticsearch with the
`repositories.url.allowed_urls` setting. This setting supports wildcards in
the place of host, path, query, and fragment. For example:

[source,yaml]
-----------------------------------
repositories.url.allowed_urls: ["http://www.example.org/root/*", "https://*.mydomain.com/*?*#*"]
-----------------------------------

==== Wildcard expansion

The obsolete parameters `expand_wildcards_open` and `expand_wildcards_close`
are no longer supported by the snapshot and restore operations. These
parameters have been replaced by a single `expand_wildcards` parameter. See
<<multi-index,the multi-index docs>> for more.
