[[api]]
== API Extension Plugins

API extension plugins add new functionality to Elasticsearch by adding new APIs or features, usually to do with search or mapping.

[float]
=== Community contributed API extension plugins

A number of plugins have been contributed by our community:

* https://github.com/carrot2/elasticsearch-carrot2[carrot2 Plugin]:
  Results clustering with http://project.carrot2.org/[carrot2] (by Dawid Weiss)

* https://github.com/wikimedia/search-extra[Elasticsearch Trigram Accelerated Regular Expression Filter]:
  (by Wikimedia Foundation/Nik Everett)

* https://github.com/wikimedia/search-highlighter[Elasticsearch Experimental Highlighter]:
  (by Wikimedia Foundation/Nik Everett)

* https://github.com/YannBrrd/elasticsearch-entity-resolution[Entity Resolution Plugin]:
  Uses http://github.com/larsga/Duke[Duke] for duplication detection (by Yann Barraud)

* https://github.com/NLPchina/elasticsearch-sql/[SQL language Plugin]:
  Allows Elasticsearch to be queried with SQL (by nlpcn)

* https://github.com/codelibs/elasticsearch-taste[Elasticsearch Taste Plugin]:
  Mahout Taste-based Collaborative Filtering implementation (by CodeLibs Project)

* https://github.com/jurgc11/es-change-feed-plugin[WebSocket Change Feed Plugin] (by ForgeRock/Chris Clifton)
