[[mapper-size]]
=== Mapper size plugin

The mapper-size plugin provides the `_size` metadata field which, when enabled,
indexes the size in bytes of the original
{ref}/mapping-source-field.html[`_source`] field.

:plugin_name: mapper-size
include::install_remove.asciidoc[]

[[mapper-size-usage]]
==== Using the `_size` field

In order to enable the `_size` field, set the mapping as follows:

[source,console]
--------------------------
PUT my-index-000001
{
  "mappings": {
    "_size": {
      "enabled": true
    }
  }
}
--------------------------

The value of the `_size` field is accessible in queries, aggregations, scripts,
and when sorting. It can be retrieved using the {ref}/search-fields.html#search-fields-param[fields parameter]:

[source,console]
--------------------------
# Example documents
PUT my-index-000001/_doc/1
{
  "text": "This is a document"
}

PUT my-index-000001/_doc/2
{
  "text": "This is another document"
}

GET my-index-000001/_search
{
  "query": {
    "range": {
      "_size": {                      <1>
        "gt": 10
      }
    }
  },
  "aggs": {
    "sizes": {
      "terms": {
        "field": "_size",             <2>
        "size": 10
      }
    }
  },
  "sort": [
    {
      "_size": {                      <3>
        "order": "desc"
      }
    }
  ],
  "fields": ["_size"],                <4>
  "script_fields": {
    "size": {
      "script": "doc['_size']"        <5>
    }
  }
}
--------------------------
// TEST[continued]

<1> Querying on the `_size` field
<2> Aggregating on the `_size` field
<3> Sorting on the `_size` field
<4> Use the `fields` parameter to return the `_size` in the search response.
<5> Uses a
{ref}/search-fields.html#script-fields[script field]
to return the `_size` field in the search response.

[NOTE]
.Using `_size` in {kib}
================================================

To use the `_size` field in {kib}, update the `metaFields` setting and add 
`_size` to the list of meta fields. `metaFields` can be configured in {kib} 
from the Advanced Settings page in Management.

================================================