
[role="xpack"]
[[data-frames-settings]]
=== {dataframe-transforms-cap}  settings in Elasticsearch
[subs="attributes"]
++++
<titleabbrev>{dataframe-transforms-cap} settings</titleabbrev>
++++

You do not need to configure any settings to use {dataframe-transforms}. It is enabled by default.

All of these settings can be added to the `elasticsearch.yml` configuration file. 
The dynamic settings can also be updated across a cluster with the 
<<cluster-update-settings,cluster update settings API>>.

TIP: Dynamic settings take precedence over settings in the `elasticsearch.yml` 
file.

[float]
[[general-data-frames-settings]]
==== General {dataframe-transforms} settings

`xpack.data_frame.enabled`::
Set to `true` (default) to enable {dataframe-transforms} on the node. +
+
If set to `false` in `elasticsearch.yml`, the {dataframe-transform} APIs are disabled on the node.
Therefore the node cannot start or administrate transforms or receive transport (internal)
communication requests related to {dataframe-transform} APIs.
+
IMPORTANT: If you want to use {dataframe-transform} features in your cluster, you must have
`xpack.data_frame.enabled` set to `true` on all master-eligible nodes. This is the
default behavior.

`xpack.data_frame.num_transform_failure_retries` (<<cluster-update-settings,Dynamic>>)::
The number of times that a {dataframe-transform} retries when it experiences a
non-fatal error. Once the number of retries is exhausted, the {dataframe-transform}
task will be marked as `failed`. The default value is `10` with a valid minimum of `0`
and maximum of `100`.
If a {dataframe-transform} is already running, it will have to be restarted
to use the changed setting.
