[[snapshot-settings]]
=== Snapshot and restore settings

The following cluster settings configure <<snapshot-restore,snapshot and
restore>>.

[[snapshot-max-concurrent-ops]]
`snapshot.max_concurrent_operations`::
(<<dynamic-cluster-setting,Dynamic>>, integer) Maximum number of concurrent
snapshot operations. Defaults to `1000`.
+
This limit applies in total to all ongoing snapshot creation, cloning, and
deletion operations. {es} will reject any operations that would exceed this
limit.

==== {slm-init} settings

The following cluster settings configure <<automate-snapshots-slm,{slm}
({slm-init})>>.

[[slm-history-index-enabled]]
`slm.history_index_enabled`::
(<<dynamic-cluster-setting,Dynamic>>, Boolean)
Controls whether {slm-init} records the history of actions taken as part of {slm-init} policies
to the `slm-history-*` indices. Defaults to `true`.

[[slm-retention-schedule]]
`slm.retention_schedule`::
(<<dynamic-cluster-setting,Dynamic>>, <<schedule-cron,cron scheduler value>>)
Controls when the <<slm-retention-task,retention task>> runs.
Can be a periodic or absolute time schedule.
Supports all values supported by the <<schedule-cron,cron scheduler>>.
Defaults to daily at 1:30am UTC: `0 30 1 * * ?`.

[[slm-retention-duration]]
`slm.retention_duration`::
(<<dynamic-cluster-setting,Dynamic>>, <<time-units,time value>>)
Limits how long {slm-init} should spend deleting old snapshots.
Defaults to one hour: `1h`.

[[slm-health-failed-snapshot-warn-threshold]]
`slm.health.failed_snapshot_warn_threshold`::
(<<dynamic-cluster-setting,Dynamic>>, Long)
The number of failed invocations since last successful snapshot that
indicate a problem with the policy in the health api.
Defaults to a health api warning after five repeated failures: `5L`.

[[repositories-url-allowed]]
// tag::repositories-url-allowed[]
`repositories.url.allowed_urls` {ess-icon}::
(<<static-cluster-setting,Static>>)
Specifies the <<snapshots-read-only-repository,read-only URL repositories>> that snapshots can be restored from.
// end::repositories-url-allowed[]
