
[role="xpack"]
[[transform-settings]]
=== {transforms-cap}  settings in Elasticsearch
[subs="attributes"]
++++
<titleabbrev>{transforms-cap} settings</titleabbrev>
++++

You do not need to configure any settings to use {transforms}. It is enabled by
default.

All of these settings can be added to the `elasticsearch.yml` configuration file.
The dynamic settings can also be updated across a cluster with the
<<cluster-update-settings,cluster update settings API>>.

TIP: Dynamic settings take precedence over settings in the `elasticsearch.yml`
file.

[discrete]
[[general-transform-settings]]
==== General {transforms} settings

`node.transform`::
deprecated:[7.9.0,"Use <<modules-node,node.roles>> instead."]
Set to `true` to identify the node as a _transform node_. If `node.data`
is `false` for the node, the default value is `false`. Otherwise, the default
value is `true`.
+
If set to `false` in `elasticsearch.yml`, the node cannot run transforms. If
you want to run transforms, there must be at least one transform node in your
cluster. +
+
IMPORTANT: On dedicated coordinating nodes or dedicated master nodes, disable
the node.transform role.

`xpack.transform.enabled`::
deprecated:[7.8.0,Basic License features should always be enabled] +
This deprecated setting no longer has any effect.

`xpack.transform.num_transform_failure_retries` (<<cluster-update-settings,Dynamic>>)::
The number of times that a {transform} retries when it experiences a
non-fatal error. Once the number of retries is exhausted, the {transform}
task will be marked as `failed`. The default value is `10` with a valid minimum of `0`
and maximum of `100`.
If a {transform} is already running, it will have to be restarted
to use the changed setting.
