apiVersion: 1

datasources:
  - name: Elasticsearch (Prometheus API)
    type: prometheus
    uid: es-prometheus
    access: proxy
    url: http://host.docker.internal:9200/_prometheus
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: password
    jsonData:
      httpMethod: GET
      timeInterval: 5s
    isDefault: true
    editable: true

  - name: PromQL Downsample Raw
    type: prometheus
    uid: promql-downsample-raw
    access: proxy
    url: http://host.docker.internal:9200/_prometheus/promql-downsample-raw
    version: 1
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: password
    jsonData:
      httpMethod: GET
      timeInterval: 10m
    editable: true

  - name: PromQL Downsample 30m
    type: prometheus
    uid: promql-downsample-30m
    access: proxy
    url: http://host.docker.internal:9200/_prometheus/promql-downsample-30m
    version: 1
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: password
    jsonData:
      httpMethod: GET
      timeInterval: 10m
    editable: true

  - name: PromQL Downsample 1h
    type: prometheus
    uid: promql-downsample-1h
    access: proxy
    url: http://host.docker.internal:9200/_prometheus/promql-downsample-1h
    version: 1
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: password
    jsonData:
      httpMethod: GET
      timeInterval: 10m
    editable: true

  - name: PromQL Downsample 2h
    type: prometheus
    uid: promql-downsample-2h
    access: proxy
    url: http://host.docker.internal:9200/_prometheus/promql-downsample-2h
    version: 1
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: password
    jsonData:
      httpMethod: GET
      timeInterval: 10m
    editable: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET
      timeInterval: 5s
    editable: true
