[[breaking-changes-6.6]]
== Breaking changes in 6.6
++++
<titleabbrev>6.6</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to Elasticsearch 6.6.

* <<breaking_66_search_changes>>

See also <<release-highlights>> and <<es-release-notes>>.

[float]
[[breaking_66_search_changes]]
=== Search changes

[float]
==== `query_string`, `multi_match` and `simple_query_string` query

Using automatically expanded fields for the "all fields" mode ("default_field": "*")
for the `query_string`, `multi_match` and `simple_query_string` now raises a warning and
a deprecation notice to be logged for queries beyond a certain number of fields. This limit
will be enforced with a hard error starting in 7.0 and is determined by the
`indices.query.bool.max_clause_count` setting which defaults to 1024.

[float]
==== Deprecate `_source_exclude` and `_source_include` URL Parameters

`_source_exclude` and `_source_include` are deprecated in favor of
`_source_excludes` and `_source_includes` because those line up better with the
rest of Elasticsearc's APIs and Elasticsearch will raise a deprecation warning
if those are used on any APIs. We plan to drop support for `_source_exclude` and
`_source_include` in 7.0.


[float]
==== Boosts on inner span queries are not allowed.

Attempts to set `boost` on inner span queries will now throw a parsing exception.