[[migrating-8.16]]
== Migrating to 8.16
++++
<titleabbrev>8.16</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to {es} 8.16.

See also <<release-highlights>> and <<es-release-notes>>.

coming::[8.16.0]


[discrete]
[[breaking-changes-8.16]]
=== Breaking changes

The following changes in {es} 8.16 might affect your applications
and prevent them from operating normally.
Before upgrading to 8.16, review these changes and take the described steps
to mitigate the impact.

[discrete]
[[breaking_816_locale_change]]
==== JDK locale database change

{es} 8.16 changes the version of the JDK that is included from version 22 to version 23. This changes
the locale database that is used by Elasticsearch from the _COMPAT_ database to the _CLDR_ database.
This can result in significant changes to custom textual date field formats,
and calculations for custom week-date date fields.

For more information see <<custom-date-formats,custom date formats>>.

If you run {es} 8.16 on JDK version 22 or below, it will use the _COMPAT_ locale database
to match the behavior of 8.15. However, please note that starting with {es} 9.0,
{es} will use the _CLDR_ database regardless of JDK version it is run on.
