[[breaking-changes-7.8]]
== Breaking changes in 7.8
++++
<titleabbrev>7.8</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to Elasticsearch 7.8.

See also <<release-highlights>> and <<es-release-notes>>.

coming[7.8.0]

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

//end::notable-breaking-changes[]

[discrete]
[[breaking_78_mappings_changes]]
=== Mappings changes

[discrete]
[[prevent-enabled-setting-change]]
==== `enabled` setting cannot be changed on root mapper

Previously, Elasticsearch accepted mapping updates that tried to change the
`enabled` setting on the root mapping. The update was not applied, but the
request didn't throw an error. As of 7.8, requests that attempt to change
`enabled` on the root mapping will fail.

[discrete]
[[breaking_78_settings_changes]]
=== Settings changes

[discrete]
[[deprecate-node-local-storage]]
==== `node.local_storage` is deprecated

In Elasticsearch 7.8.0, the setting `node.local_storage` was deprecated and
beginning in Elasticsearch 8.0.0 all nodes will require local storage.
