[[breaking-changes-7.8]]
== Breaking changes in 7.8
++++
<titleabbrev>7.8</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to {es} 7.8.

See also <<release-highlights>> and <<es-release-notes>>.

coming[7.8.0]

* <<breaking_78_mappings_changes>>
* <<breaking_78_settings_changes>>

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

[discrete]
[[breaking_78_mappings_changes]]
=== Mappings changes

[[prevent-enabled-setting-change]]
.The `enabled` mapping parameter cannot be changed for a root mapping.
[%collapsible]
====
*Details* +
Mapping requests that attempt to change the {ref}/enabled.html[`enabled`]
mapping parameter for a root mapping will fail and return an error.

Previously, {es} accepted mapping requests that attempted to change the
`enabled` parameter of the root mapping. Theses changes were not applied, but
such requests didn't return an error.

*Impact* +
To avoid errors, do not submit mapping requests that change the
{ref}/enabled.html[`enabled`] mapping parameter.
====

[[prevent-include-in-root-change]]
.The `include_in_parent` and `include_in_root` mapping parameters cannot be changed for `nested` fields.
[%collapsible]
====
*Details* +
Mapping requests that attempt to change the
{ref}/nested.html#nested-include-in-parent-parm[`include_in_parent`] or
{ref}/nested.html#nested-include-in-root-parm[`include_in_root`] mapping
parameter for a `nested` field will fail and return an error.

Previously, {es} accepted mapping requests that attempted to change the
`include_in_parent` or `include_in_root` parameter. Theses changes were not
applied, but such requests didn't return an error.

*Impact* +
To avoid errors, do not submit mapping requests that change the
{ref}/nested.html#nested-include-in-parent-parm[`include_in_parent`] or
{ref}/nested.html#nested-include-in-root-parm[`include_in_root`] mapping
parameter.
====

.The get field mapping API's `local` query parameter is deprecated.
[%collapsible]
====
*Details* +
The {ref}/indices-get-field-mapping.html[get field mapping API]'s `local` query
parameter is deprecated and will be removed in {es} 8.0.0.

The `local` parameter is a no-op. The API always retrieves field mappings
locally.

*Impact* +
To avoid deprecation warnings, discontinue use of the `local` parameter.
====

[discrete]
[[breaking_78_settings_changes]]
=== Settings changes

[[deprecate-node-local-storage]]
.The `node.local_storage` setting is deprecated.
[%collapsible]
====
*Details* +
The `node.local_storage` setting is deprecated. In {es} 8.0.0, all nodes require
local storage.

*Impact* +
To avoid deprecation warnings, discontinue use of the `node.local_storage`
setting.
====

//end::notable-breaking-changes[]