/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.ml.utils;

import java.util.Map;

/**
 * {@code @allocates_dynamic} estimators for the {@code domainSplit} functions in this module's allowlist. Each is a
 * {@code public static long} method matching the allowlisted function's parameters and returns the heap cost of the list
 * it allocates. Invoked from generated bytecode on the allocation pre-check path, so they must be cheap, must not allocate,
 * and must not throw.
 *
 * <p>The trivial sizing math is reimplemented locally rather than shared from {@code lang-painless}, which exposes it only
 * as non-SPI implementation detail; this module depends on {@code painless-spi} alone.
 */
public final class MlAllocationEstimators {

    /** Fixed overhead of a freshly allocated {@link String}: the object plus its backing array header. */
    private static final long STRING_RESULT_OVERHEAD = 32;

    /** Heap cost of an empty {@link java.util.ArrayList} shell (object plus its default backing array reference). */
    private static final long ARRAY_LIST_SHELL_BYTES = 40;

    private static final int ARRAY_HEADER = 16;
    private static final int REFERENCE_SIZE = 8;

    private MlAllocationEstimators() {}

    /** Signed multiply saturating to {@link Long#MAX_VALUE} on overflow, so an enormous length trips the limit rather than wrapping. */
    private static long mulSat(long a, long b) {
        try {
            return Math.multiplyExact(a, b);
        } catch (ArithmeticException overflow) {
            return ((a ^ b) < 0) ? Long.MIN_VALUE : Long.MAX_VALUE;
        }
    }

    /** Signed add saturating to {@link Long#MAX_VALUE} on overflow. */
    private static long addSat(long a, long b) {
        try {
            return Math.addExact(a, b);
        } catch (ArithmeticException overflow) {
            return (a < 0) ? Long.MIN_VALUE : Long.MAX_VALUE;
        }
    }

    /** Rounds {@code bytes} up to the nearest 8-byte alignment boundary, saturating rather than overflowing. */
    private static long pad8(long bytes) {
        return addSat(bytes, 7L) & ~7L;
    }

    /** Heap size of a reference array of {@code length} elements: header plus payload, 8-byte aligned. */
    private static long referenceArrayBytes(long length) {
        return pad8(addSat(ARRAY_HEADER, mulSat(REFERENCE_SIZE, length)));
    }

    /** Heap cost of a {@link String} of {@code chars} UTF-16 characters: fixed overhead plus 2 bytes per char. */
    private static long newStringBytes(long chars) {
        return STRING_RESULT_OVERHEAD + mulSat(2L, Math.max(0L, chars));
    }

    /** {@code domainSplit}: a fixed two-element list plus the subdomain/domain substrings (~ the host length). */
    public static long domainSplitBytes(String host) {
        long len = host == null ? 0 : host.length();
        return ARRAY_LIST_SHELL_BYTES + referenceArrayBytes(2) + newStringBytes(len);
    }

    /** Overload of {@link #domainSplitBytes(String)} for the {@code (String, Map)} signature. */
    public static long domainSplitBytes(String host, Map<?, ?> params) {
        return domainSplitBytes(host);
    }
}
