/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.sql.expression.function.scalar.whitelist;

/**
 * {@code @allocates_dynamic} estimators for the SQL string functions in {@code sql_whitelist.txt}. Each is a
 * {@code public static long} method matching the allowlisted function's parameters and returns the heap cost of the
 * {@link String} it allocates. Invoked from generated bytecode on the allocation pre-check path, so they must be cheap,
 * must not allocate, and must not throw — even on argument values the real function would reject.
 *
 * <p>The trivial sizing math is reimplemented locally rather than shared from {@code lang-painless}, which exposes it only
 * as non-SPI implementation detail; this module depends on {@code painless-spi} alone.
 */
public final class SqlAllocationEstimators {

    /** Fixed overhead of a freshly allocated {@link String}: the object plus its backing array header. */
    private static final long STRING_RESULT_OVERHEAD = 32;

    private SqlAllocationEstimators() {}

    /** Signed multiply saturating to {@link Long#MAX_VALUE} on overflow, so an enormous count trips the limit rather than wrapping. */
    private static long mulSat(long a, long b) {
        try {
            return Math.multiplyExact(a, b);
        } catch (ArithmeticException overflow) {
            return ((a ^ b) < 0) ? Long.MIN_VALUE : Long.MAX_VALUE;
        }
    }

    /**
     * Heap cost of a {@link String} of {@code chars} UTF-16 characters: fixed overhead plus 2 bytes per char (negative lengths
     * cost only the overhead).
     */
    private static long newStringBytes(long chars) {
        return STRING_RESULT_OVERHEAD + mulSat(2L, Math.max(0L, chars));
    }

    /** {@code CONCAT}: a new String of {@code left.length() + right.length()} chars. */
    public static long concatBytes(String left, String right) {
        return newStringBytes((left == null ? 0 : left.length()) + (long) (right == null ? 0 : right.length()));
    }

    /** {@code LCASE}/{@code UCASE}/{@code LTRIM}/{@code RTRIM}/{@code TRIM}: a new String approximately the source length. */
    public static long recaseBytes(String value) {
        return newStringBytes(value == null ? 0 : value.length());
    }

    /** {@code LEFT}/{@code RIGHT}: a new String no longer than {@code value}. */
    public static long boundedStringBytes(String value, Number count) {
        return newStringBytes(value == null ? 0 : value.length());
    }

    /** {@code SUBSTRING}: a new String no longer than {@code value}. */
    public static long boundedStringBytes(String value, Number start, Number length) {
        return newStringBytes(value == null ? 0 : value.length());
    }

    /** {@code REPEAT}: a new String of {@code value} repeated {@code count} times — a growth vector for large counts. */
    public static long stringRepeatBytes(String value, Number count) {
        long len = value == null ? 0 : value.length();
        long n = count == null ? 0 : count.longValue();
        return newStringBytes(mulSat(len, Math.max(0L, n)));
    }

    /** {@code SPACE}: a new String of {@code count} characters — a growth vector for large counts. */
    public static long stringOfCountBytes(Number count) {
        return newStringBytes(count == null ? 0 : Math.max(0L, count.longValue()));
    }
}
