/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.gradle.internal.foreign;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.plugins.JavaLibraryPlugin;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.gradle.api.tasks.TaskProvider;
import org.gradle.api.tasks.bundling.Jar;
import org.gradle.api.tasks.compile.JavaCompile;
import org.gradle.jvm.toolchain.JavaLanguageVersion;
import org.gradle.jvm.toolchain.JavaToolchainService;

import java.io.File;

import javax.inject.Inject;

/**
 * Wires up annotation processing and post-compile module-info augmentation for modules that contain
 * {@code @LibrarySpecification} interfaces from {@code libs/ffm}.
 *
 * <p>This plugin handles two responsibilities that any consumer of the FFM annotation processor needs:
 * <ul>
 *   <li>Running the annotation processor as an external {@code javac} process (the processor requires
 *       the JDK 24+ {@code java.lang.classfile} API, which the Gradle daemon's bundled JDK 21 cannot
 *       load).</li>
 *   <li>Post-processing the compiled {@code module-info.class} to inject {@code provides
 *       org.elasticsearch.foreign.LibraryProvider with <generated $Provider classes>;} directives.
 *       The source {@code module-info.java} cannot reference these classes because they only exist
 *       as generated bytecode.</li>
 * </ul>
 */
public class ForeignLibraryPlugin implements Plugin<Project> {

    private static final int JDK_VERSION_FOR_PROCESSOR = 25;

    static final String PROCESSOR_CONFIGURATION_NAME = "foreignLibraryProcessor";
    static final String PROCESS_ANNOTATIONS_TASK_NAME = "processForeignAnnotations";
    static final String AUGMENT_MODULE_INFO_TASK_NAME = "augmentForeignModuleInfo";

    private static final String GENERATED_CLASSES_DIR = "generated-foreign-library-classes";
    private static final String AUGMENTED_MODULE_INFO_DIR = "augmented-foreign-module-info";
    private static final String SERVICES_FILE = "META-INF/services/org.elasticsearch.foreign.LibraryProvider";
    private static final String MODULE_INFO_CLASS = "module-info.class";

    private final JavaToolchainService javaToolchains;

    @Inject
    public ForeignLibraryPlugin(JavaToolchainService javaToolchains) {
        this.javaToolchains = javaToolchains;
    }

    @Override
    public void apply(Project project) {
        project.getPluginManager().apply(JavaLibraryPlugin.class);

        // libs/ffm is part of the consumer's public API: annotated interfaces extend types from
        // org.elasticsearch.foreign (e.g. CloseableByteBuffer), so it must be exposed transitively.
        project.getDependencies().add(JavaPlugin.API_CONFIGURATION_NAME, project.project(":libs:ffm"));

        Configuration processorConfiguration = project.getConfigurations().create(PROCESSOR_CONFIGURATION_NAME);
        project.getDependencies().add(PROCESSOR_CONFIGURATION_NAME, project.project(":libs:ffm:processor"));

        SourceSet mainSourceSet = project.getExtensions().getByType(SourceSetContainer.class).getByName(SourceSet.MAIN_SOURCE_SET_NAME);
        Configuration compileClasspath = project.getConfigurations().getByName(mainSourceSet.getCompileClasspathConfigurationName());

        TaskProvider<ForeignAnnotationProcessorTask> processAnnotations = registerProcessAnnotationsTask(
            project,
            mainSourceSet,
            compileClasspath,
            processorConfiguration
        );
        TaskProvider<AugmentForeignModuleInfoTask> augmentModuleInfo = registerAugmentModuleInfoTask(
            project,
            processAnnotations,
            processorConfiguration
        );

        // The generated $Impl / $Provider classes and META-INF/services entries belong on every
        // downstream classpath that consumes this module's main output (tests, jar, etc.).
        mainSourceSet.getOutput().dir(processAnnotations.flatMap(ForeignAnnotationProcessorTask::getOutputDirectory));

        wireCompileJava(project, processAnnotations);
        wireJar(project, augmentModuleInfo);
    }

    private TaskProvider<ForeignAnnotationProcessorTask> registerProcessAnnotationsTask(
        Project project,
        SourceSet mainSourceSet,
        Configuration modulePath,
        Configuration processorPath
    ) {
        JavaPluginExtension javaExtension = project.getExtensions().getByType(JavaPluginExtension.class);

        return project.getTasks().register(PROCESS_ANNOTATIONS_TASK_NAME, ForeignAnnotationProcessorTask.class, task -> {
            task.getSources().from(mainSourceSet.getJava());
            task.getModulePath().from(modulePath);
            // Include the FFM module on the processor module path as well: the processor reads the
            // annotated interfaces' signatures, which transitively reference @LibrarySpecification.
            task.getProcessorModulePath().from(processorPath, modulePath);
            task.getReleaseVersion().set(project.provider(() -> javaExtension.getTargetCompatibility().getMajorVersion()));
            task.getJavaCompiler()
                .set(javaToolchains.compilerFor(spec -> spec.getLanguageVersion().set(JavaLanguageVersion.of(JDK_VERSION_FOR_PROCESSOR))));
            task.getOutputDirectory().set(project.getLayout().getBuildDirectory().dir(GENERATED_CLASSES_DIR));
        });
    }

    private TaskProvider<AugmentForeignModuleInfoTask> registerAugmentModuleInfoTask(
        Project project,
        TaskProvider<ForeignAnnotationProcessorTask> processAnnotations,
        Configuration augmenterClasspath
    ) {
        TaskProvider<JavaCompile> compileJava = project.getTasks().named(JavaPlugin.COMPILE_JAVA_TASK_NAME, JavaCompile.class);

        return project.getTasks().register(AUGMENT_MODULE_INFO_TASK_NAME, AugmentForeignModuleInfoTask.class, task -> {
            task.getInputModuleInfo().set(compileJava.flatMap(t -> t.getDestinationDirectory().file(MODULE_INFO_CLASS)));
            task.getServicesFile().set(processAnnotations.flatMap(t -> t.getOutputDirectory().file(SERVICES_FILE)));
            task.getAugmenterClasspath().from(augmenterClasspath);
            task.getJavaLauncher()
                .set(javaToolchains.launcherFor(spec -> spec.getLanguageVersion().set(JavaLanguageVersion.of(JDK_VERSION_FOR_PROCESSOR))));
            task.getOutputModuleInfo()
                .set(project.getLayout().getBuildDirectory().file(AUGMENTED_MODULE_INFO_DIR + "/" + MODULE_INFO_CLASS));
        });
    }

    private static void wireCompileJava(Project project, TaskProvider<ForeignAnnotationProcessorTask> processAnnotations) {
        project.getTasks().named(JavaPlugin.COMPILE_JAVA_TASK_NAME, JavaCompile.class).configure(task -> {
            task.dependsOn(processAnnotations);
            // Annotation processing already happened in processAnnotations — disable it here so javac does
            // not try to load the processor with the Gradle daemon's JDK.
            task.getOptions().getCompilerArgs().add("-proc:none");
        });
    }

    private static void wireJar(Project project, TaskProvider<AugmentForeignModuleInfoTask> augmentModuleInfo) {
        Provider<File> compiledModuleInfo = project.getTasks()
            .named(JavaPlugin.COMPILE_JAVA_TASK_NAME, JavaCompile.class)
            .flatMap(t -> t.getDestinationDirectory().file(MODULE_INFO_CLASS))
            .map(f -> f.getAsFile());
        Provider<File> augmentedModuleInfo = augmentModuleInfo.flatMap(AugmentForeignModuleInfoTask::getOutputModuleInfo)
            .map(f -> f.getAsFile());

        project.getTasks().named(JavaPlugin.JAR_TASK_NAME, Jar.class).configure(task -> {
            // Substitute the augmented module-info.class for the original. The generated $Impl /
            // $Provider classes and META-INF/services file are picked up automatically via the
            // main source set's output dirs configured in apply().
            task.exclude(element -> element.getFile().equals(compiledModuleInfo.get()));
            task.from(augmentedModuleInfo);
        });
    }
}
