[role="xpack"]
[testenv="basic"]
[[get-transform]]
=== Get {transforms} API

[subs="attributes"]
++++
<titleabbrev>Get {transforms}</titleabbrev>
++++

Retrieves configuration information for {transforms}.

beta[]

[[get-transform-request]]
==== {api-request-title}

`GET _transform/<transform_id>` +

`GET _transform/<transform_id>,<transform_id>` +

`GET _transform/` +

`GET _transform/_all` +

`GET _transform/*`

[[get-transform-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have `monitor_transform` 
cluster privileges to use this API. The built-in `transform_user` role has these 
privileges. For more information, see <<security-privileges>> and 
<<built-in-roles>>.

[[get-transform-desc]]
==== {api-description-title}

You can get information for multiple {transforms} in a single API
request by using a comma-separated list of identifiers or a wildcard expression.
You can get information for all {transforms} by using `_all`, by
specifying `*` as the `<transform_id>`, or by omitting the `<transform_id>`.

[[get-transform-path-parms]]
==== {api-path-parms-title}

`<transform_id>`::
(Optional, string)
include::{docdir}/rest-api/common-parms.asciidoc[tag=transform-id-wildcard]
  
[[get-transform-query-parms]]
==== {api-query-parms-title}

`allow_no_match`::
(Optional, boolean)
include::{docdir}/rest-api/common-parms.asciidoc[tag=allow-no-match-transforms1]

`from`::
(Optional, integer)
include::{docdir}/rest-api/common-parms.asciidoc[tag=from-transforms]

`size`::
(Optional, integer)
include::{docdir}/rest-api/common-parms.asciidoc[tag=size-transforms]

[[get-transform-response]]
==== {api-response-body-title}

The API returns an array of {transform} resources, which are sorted by the `id`
value in ascending order and have the following properties:

`create_time`::
(string) The time the {transform} was created. For example, `1576094542936`.
This property is informational; you cannot change its value.

`description`::
  (string) A description of the {transform}.

`dest`::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=dest]

`dest`.`index`::: 
(string)
include::{docdir}/rest-api/common-parms.asciidoc[tag=dest-index]

`dest`.`pipeline`:::
(string)
include::{docdir}/rest-api/common-parms.asciidoc[tag=dest-pipeline]

`frequency`::
(<<time-units,time units>>)
include::{docdir}/rest-api/common-parms.asciidoc[tag=frequency]

`id`::
(string)
include::{docdir}/rest-api/common-parms.asciidoc[tag=transform-id]

`pivot`::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=pivot]

`pivot`.`aggregations`:::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=pivot-aggs]

`pivot`.`group_by`:::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=pivot-group-by]

`pivot`.`max_page_search_size`:::
(integer)
include::{docdir}/rest-api/common-parms.asciidoc[tag=pivot-max-page-search-size]

`source`:: 
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=source-transforms]

`source`.`index`:::
(string or array)  
include::{docdir}/rest-api/common-parms.asciidoc[tag=source-index-transforms]

`source`.`query`:::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=source-query-transforms]

`sync`::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=sync]

`synch `.`time`:::
(object)
include::{docdir}/rest-api/common-parms.asciidoc[tag=sync-time]

`sync`.`time`.`delay`::::
(<<time-units,time units>>)
include::{docdir}/rest-api/common-parms.asciidoc[tag=sync-time-delay]

`sync`.`time`.`field`::::
(string)
include::{docdir}/rest-api/common-parms.asciidoc[tag=sync-time-field]

`version`::
(string) The version of {es} that existed on the node when the {transform} was
created.
  
[[get-transform-response-codes]]
==== {api-response-codes-title}

`404` (Missing resources)::
  If `allow_no_match` is `false`, this code indicates that there are no
  resources that match the request or only partial matches for the request.  

[[get-transform-example]]
==== {api-examples-title}

The following example retrieves information about a maximum of ten {transforms}:

[source,console]
--------------------------------------------------
GET _transform?size=10
--------------------------------------------------
// TEST[skip:setup kibana sample data]

The following example gets configuration information for the
`ecommerce_transform` {transform}:

[source,console]
--------------------------------------------------
GET _transform/ecommerce_transform
--------------------------------------------------
// TEST[skip:setup kibana sample data]

The API returns the following results:

[source,console-result]
----
{
  "count" : 1,
  "transforms" : [
    {
      "id" : "ecommerce_transform",
      "source" : {
        "index" : [
          "kibana_sample_data_ecommerce"
        ],
        "query" : {
          "term" : {
            "geoip.continent_name" : {
              "value" : "Asia"
            }
          }
        }
      },
      "dest" : {
        "index" : "kibana_sample_data_ecommerce_transform"
      },
      "frequency": "1m",
      "pivot" : {
        "group_by" : {
          "customer_id" : {
            "terms" : {
              "field" : "customer_id"
            }
          }
        },
        "aggregations" : {
          "max_price" : {
            "max" : {
              "field" : "taxful_total_price"
            }
          }
        }
      },
      "description" : "Maximum priced ecommerce data by customer_id in Asia",
      "version" : "7.5.0",
      "create_time" : 1576094542936
    }
  ]
}

----
