/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.expression.function;

import com.unboundid.util.NotNull;

import org.elasticsearch.common.Strings;
import org.elasticsearch.core.PathUtils;
import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;
import org.elasticsearch.xcontent.XContentBuilder;
import org.elasticsearch.xcontent.json.JsonXContent;
import org.elasticsearch.xpack.esql.CsvTestsDataLoader;
import org.elasticsearch.xpack.esql.core.type.DataType;
import org.elasticsearch.xpack.esql.expression.function.fulltext.MatchOperator;
import org.elasticsearch.xpack.esql.expression.function.scalar.string.RLike;
import org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLike;
import org.elasticsearch.xpack.esql.expression.predicate.logical.And;
import org.elasticsearch.xpack.esql.expression.predicate.logical.Not;
import org.elasticsearch.xpack.esql.expression.predicate.logical.Or;
import org.elasticsearch.xpack.esql.expression.predicate.nulls.IsNotNull;
import org.elasticsearch.xpack.esql.expression.predicate.nulls.IsNull;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Add;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Div;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Mod;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Mul;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Neg;
import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Sub;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.Equals;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.GreaterThan;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.GreaterThanOrEqual;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.In;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.LessThan;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.LessThanOrEqual;
import org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.NotEquals;
import org.elasticsearch.xpack.esql.session.Configuration;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.annotation.Annotation;
import java.lang.reflect.Constructor;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static java.util.Map.entry;
import static org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.constructorWithFunctionInfo;
import static org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.definition;
import static org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.functionRegistered;
import static org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.shouldHideSignature;
import static org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.signatures;
import static org.elasticsearch.xpack.esql.expression.function.EsqlFunctionRegistry.mapParam;
import static org.elasticsearch.xpack.esql.expression.function.EsqlFunctionRegistry.param;
import static org.elasticsearch.xpack.esql.expression.function.EsqlFunctionRegistry.paramWithoutAnnotation;

public abstract class DocsV3Support {

    static final String DOCS_WARNING =
        "% This is generated by ESQL's AbstractFunctionTestCase. Do no edit it. See ../README.md for how to regenerate it.\n\n";

    static final String PREVIEW_CALLOUT = """
        ::::{warning}
        Do not use on production environments. This functionality is in technical preview and
        may be changed or removed in a future release. Elastic will work to fix any issues, but features in technical preview
        are not subject to the support SLA of official GA features.
        ::::
        """;

    static FunctionDocsSupport forFunctions(String name, Class<?> testClass) {
        return new FunctionDocsSupport(name, testClass);
    }

    static OperatorsDocsSupport forOperators(String name, Class<?> testClass) {
        return new OperatorsDocsSupport(name, testClass);
    }

    static void renderDocs(String name, Class<?> testClass) throws IOException {
        if (OPERATORS.containsKey(name)) {
            var docs = DocsV3Support.forOperators(name, testClass);
            docs.renderSignature();
            docs.renderDocs();
        } else if (functionRegistered(name)) {
            var docs = DocsV3Support.forFunctions(name, testClass);
            docs.renderSignature();
            docs.renderDocs();
        } else {
            LogManager.getLogger(testClass).info("Skipping rendering docs because the function '" + name + "' isn't registered");
        }
    }

    public static void renderNegatedOperator(
        @NotNull Constructor<?> ctor,
        String name,
        Function<String, String> description,
        Class<?> testClass
    ) throws IOException {
        var docs = forOperators("not " + name.toLowerCase(Locale.ROOT), testClass);
        docs.renderDocsForNegatedOperators(ctor, description);
    }

    private static final Map<String, String> MACROS = new HashMap<>();
    private static final Map<String, String> knownFiles;
    private static final Map<String, String> knownCommands;
    private static final Map<String, String> knownOperators;
    private static final Map<String, String> knownMapping;

    static {
        MACROS.put("wikipedia", "https://en.wikipedia.org/wiki");
        MACROS.put("javadoc8", "https://docs.oracle.com/javase/8/docs/api");
        MACROS.put("javadoc14", "https://docs.oracle.com/en/java/javase/14/docs/api");
        MACROS.put("javadoc", "https://docs.oracle.com/en/java/javase/11/docs/api");
        // This static list of known root query-languages/-*.md files is used to simulate old simple ascii-doc links
        knownFiles = Map.ofEntries(
            entry("esql-commands", "esql/esql-commands.md"),
            entry("esql-enrich-data", "esql/esql-enrich-data.md"),
            entry("esql-examples", "esql/esql-examples.md"),
            entry("esql-functions-operators", "esql/esql-functions-operators.md"),
            entry("esql-implicit-casting", "esql/esql-implicit-casting.md"),
            entry("esql-metadata-fields", "esql/esql-metadata-fields.md"),
            entry("esql-multivalued-fields", "esql/esql-multivalued-fields.md"),
            entry("esql-process-data-with-dissect-grok", "esql/esql-process-data-with-dissect-grok.md"),
            entry("esql-syntax", "esql/esql-syntax.md"),
            entry("esql-time-spans", "esql/esql-time-spans.md"),
            entry("esql-limitations", "esql/limitations.md"),
            entry("esql-function-named-params", "esql/esql-syntax.md"),
            entry("query-dsl-query-string-query", "query-dsl/query-dsl-query-string-query.md")
        );
        // Static links to the commands file
        knownCommands = Map.ofEntries(entry("where", "where"), entry("stats-by", "stats"));
        // Static links to handwritten operators files
        knownOperators = Map.ofEntries(entry("cast-operator", "Cast (::)"));
        // Static links to mapping-reference
        knownMapping = Map.ofEntries(
            entry("text", "/reference/elasticsearch/mapping-reference/text.md"),
            entry("semantic-text", "/reference/elasticsearch/mapping-reference/semantic-text.md"),
            entry("mapping-index", "/reference/elasticsearch/mapping-reference/mapping-index.md"),
            entry("doc-values", "/reference/elasticsearch/mapping-reference/doc-values.md")
        );
    }
    /**
     * Operators are unregistered functions.
     */
    static final Map<String, OperatorConfig> OPERATORS = Map.ofEntries(
        // Binary
        operatorEntry("equals", "==", Equals.class, OperatorCategory.BINARY),
        operatorEntry("not_equals", "!=", NotEquals.class, OperatorCategory.BINARY),
        operatorEntry("greater_than", ">", GreaterThan.class, OperatorCategory.BINARY),
        operatorEntry("greater_than_or_equal", ">=", GreaterThanOrEqual.class, OperatorCategory.BINARY),
        operatorEntry("less_than", "<", LessThan.class, OperatorCategory.BINARY),
        operatorEntry("less_than_or_equal", "<=", LessThanOrEqual.class, OperatorCategory.BINARY),
        operatorEntry("add", "+", Add.class, OperatorCategory.BINARY),
        operatorEntry("sub", "-", Sub.class, OperatorCategory.BINARY),
        operatorEntry("mul", "*", Mul.class, OperatorCategory.BINARY),
        operatorEntry("div", "/", Div.class, OperatorCategory.BINARY),
        operatorEntry("mod", "%", Mod.class, OperatorCategory.BINARY),
        // Unary
        operatorEntry("neg", "-", Neg.class, OperatorCategory.UNARY),
        // Logical
        operatorEntry("and", "AND", And.class, OperatorCategory.LOGICAL),
        operatorEntry("or", "OR", Or.class, OperatorCategory.LOGICAL),
        operatorEntry("not", "NOT", Not.class, OperatorCategory.LOGICAL),
        // NULL and IS NOT NULL
        operatorEntry("is_null", "IS NULL", IsNull.class, OperatorCategory.NULL_PREDICATES),
        operatorEntry("is_not_null", "IS NOT NULL", IsNotNull.class, OperatorCategory.NULL_PREDICATES),
        // LIKE AND RLIKE
        // case "rlike", "like", "in", "not_rlike", "not_like", "not_in" -> true;
        operatorEntry("like", "LIKE", WildcardLike.class, OperatorCategory.LIKE_AND_RLIKE, true),
        operatorEntry("rlike", "RLIKE", RLike.class, OperatorCategory.LIKE_AND_RLIKE, true),
        // IN
        operatorEntry("in", "IN", In.class, OperatorCategory.IN, true),
        // Search
        operatorEntry("match_operator", ":", MatchOperator.class, OperatorCategory.SEARCH)
    );

    enum OperatorCategory {
        BINARY,
        UNARY,
        LOGICAL,
        NULL_PREDICATES,
        IN,
        LIKE_AND_RLIKE,
        SEARCH
    }

    record OperatorConfig(String name, String symbol, Class<?> clazz, OperatorCategory category, boolean variadic) {}

    private static Map.Entry<String, OperatorConfig> operatorEntry(
        String name,
        String symbol,
        Class<?> clazz,
        OperatorCategory category,
        boolean variadic
    ) {
        return entry(name, new OperatorConfig(name, symbol, clazz, category, variadic));
    }

    private static Map.Entry<String, OperatorConfig> operatorEntry(String name, String symbol, Class<?> clazz, OperatorCategory category) {
        return entry(name, new OperatorConfig(name, symbol, clazz, category, false));
    }

    protected final String category;
    protected final String name;
    protected final Logger logger;
    protected final Class<?> testClass;

    private DocsV3Support(String category, String name, Class<?> testClass) {
        this.category = category;
        this.name = name;
        this.logger = LogManager.getLogger(testClass);
        this.testClass = testClass;
    }

    String replaceLinks(String text) {
        return replaceAsciidocLinks(replaceMacros(text));
    }

    private String replaceAsciidocLinks(String text) {
        Pattern pattern = Pattern.compile("<<([^>]*)>>");
        Matcher matcher = pattern.matcher(text);
        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String match = matcher.group(1);
            matcher.appendReplacement(result, getLink(match));
        }
        matcher.appendTail(result);
        return result.toString();
    }

    private String replaceMacros(String text) {
        Pattern pattern = Pattern.compile("\\{([^}]+)}(/[^\\[]+)\\[([^]]+)\\]");

        Matcher matcher = pattern.matcher(text);
        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String macro = matcher.group(1);
            String path = matcher.group(2);
            String display = matcher.group(3);
            matcher.appendReplacement(result, getMacroLink(macro, path, display));
        }
        matcher.appendTail(result);
        return result.toString();
    }

    private String getMacroLink(String macro, String path, String display) {
        if (MACROS.containsKey(macro) == false) {
            throw new IllegalArgumentException("Unknown macro [" + macro + "]");
        }
        return String.format(Locale.ROOT, "[%s](%s%s)", display, MACROS.get(macro), path);
    }

    /**
     * The new link syntax is extremely verbose.
     * Rather than make a large number of messy changes to the java files, we simply re-write the existing links to the new syntax.
     */
    private String getLink(String key) {
        String[] parts = key.split(",\\s*");
        // Inject esql examples
        if (parts[0].equals("load-esql-example")) {
            try {
                Map<String, String> example = Arrays.stream(parts[1].trim().split("\\s+"))
                    .map(s -> s.split("\\s*=\\s*", 2))
                    .map(p -> entry(p[0], p[1]))
                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
                return "```esql\n" + loadExample(example.get("file"), example.get("tag")) + "\n```\n";
            } catch (IOException e) {
                return e.getMessage();
            }
        }
        // Known root query-languages markdown files
        if (knownFiles.containsKey(parts[0])) {
            return makeLink(key, "", "/reference/query-languages/" + knownFiles.get(parts[0]));
        }
        // Old-style links within ES|QL reference
        if (key.startsWith("esql-")) {
            String cmd = parts[0].replace("esql-", "");
            String parentFile = knownCommands.containsKey(cmd)
                ? "/reference/query-languages/esql/esql-commands.md"
                : "/reference/query-languages/esql/esql-functions-operators.md";
            return makeLink(key, "esql-", parentFile);
        }
        // Old-style links to Query DSL pages
        if (key.startsWith("query-dsl-")) {
            // <<query-dsl-match-query,match query>>
            // [`match`](/reference/query-languages/query-dsl/query-dsl-match-query.md)
            return makeLink(key, "query-dsl-", "/reference/query-languages/query-dsl/query-dsl-match-query.md");
        }
        // Known links to mapping-reference
        if (knownMapping.containsKey(parts[0])) {
            return makeLink(key, "", knownMapping.get(parts[0]));
        }
        // Various other remaining old asciidoc links
        // <<match-field-params,match query parameters>>
        return switch (parts[0]) {
            case "match-field-params" -> makeLink(key, "", "/reference/query-languages/query-dsl-match-query.md");
            case "search-aggregations-bucket-histogram-aggregation" -> makeLink(
                key,
                "",
                "/reference/data-analysis/aggregations/search-aggregations-bucket-histogram-aggregation.md"
            );
            default -> throw new IllegalArgumentException("Invalid link key <<" + key + ">>");
        };
    }

    private String makeLink(String key, String prefix, String parentFile) {
        String displayText = key.substring(prefix.length());
        if (knownCommands.containsKey(displayText)) {
            displayText = "`" + knownCommands.get(displayText).toUpperCase(Locale.ROOT) + "`";
        } else if (knownOperators.containsKey(displayText)) {
            displayText = "`" + knownOperators.get(displayText) + "`";
        } else {
            int comma = displayText.indexOf(',');
            if (comma > 0) {
                key = prefix + displayText.substring(0, comma);
                displayText = displayText.substring(comma + 1).trim();
            } else if (parentFile.contains("esql/esql-")) {
                // For ES|QL commands and functions we normally make uppercase code
                displayText = "`" + displayText.toUpperCase(Locale.ROOT) + "`";
            }
        }
        if (parentFile.contains("/" + key + ".md")) {
            // The current docs-builder trips off all link targets that match the filename, so we need to do the same
            return String.format(Locale.ROOT, "[%s](%s)", displayText, parentFile);
        } else {
            return String.format(Locale.ROOT, "[%s](%s#%s)", displayText, parentFile, key);
        }
    }

    void writeToTempImageDir(String str) throws IOException {
        // We have to write to a tempdir because it’s all test are allowed to write to. Gradle can move them.
        Path dir = PathUtils.get(System.getProperty("java.io.tmpdir")).resolve("esql").resolve("images").resolve(category);
        writeToTempDir(dir, "svg", str);
    }

    void writeToTempSnippetsDir(String subdir, String str) throws IOException {
        // We have to write to a tempdir because it’s all test are allowed to write to. Gradle can move them.
        Path dir = PathUtils.get(System.getProperty("java.io.tmpdir"))
            .resolve("esql")
            .resolve("_snippets")
            .resolve(category)
            .resolve(subdir);
        writeToTempDir(dir, "md", str);
    }

    void writeToTempKibanaDir(String subdir, String extension, String str) throws IOException {
        // We have to write to a tempdir because it’s all test are allowed to write to. Gradle can move them.
        Path dir = PathUtils.get(System.getProperty("java.io.tmpdir")).resolve("esql").resolve("kibana").resolve(subdir).resolve(category);
        writeToTempDir(dir, extension, str);
    }

    private void writeToTempDir(Path dir, String extension, String str) throws IOException {
        Files.createDirectories(dir);
        Path file = dir.resolve(name + "." + extension);
        Files.writeString(file, str);
        logger.info("Wrote to file: {}", file);
    }

    protected abstract void renderSignature() throws IOException;

    protected abstract void renderDocs() throws IOException;

    static class FunctionDocsSupport extends DocsV3Support {
        private FunctionDocsSupport(String name, Class<?> testClass) {
            super("functions", name, testClass);
        }

        @Override
        protected void renderSignature() throws IOException {
            String rendered = buildFunctionSignatureSvg();
            if (rendered == null) {
                logger.info("Skipping rendering signature because the function isn't registered");
            } else {
                logger.info("Writing function signature");
                writeToTempImageDir(rendered);
            }
        }

        @Override
        protected void renderDocs() throws IOException {
            FunctionDefinition definition = definition(name);
            renderSignature();
            EsqlFunctionRegistry.FunctionDescription description = EsqlFunctionRegistry.description(definition);
            if (name.equals("case")) {
                /*
                 * Hack the description, so we render a proper one for case.
                 */
                // TODO build the description properly *somehow*
                EsqlFunctionRegistry.ArgSignature trueValue = description.args().get(1);
                EsqlFunctionRegistry.ArgSignature falseValue = new EsqlFunctionRegistry.ArgSignature(
                    "elseValue",
                    trueValue.type(),
                    "The value that’s returned when no condition evaluates to `true`.",
                    true
                );
                description = new EsqlFunctionRegistry.FunctionDescription(
                    description.name(),
                    List.of(description.args().get(0), trueValue, falseValue),
                    description.returnType(),
                    description.description(),
                    description.variadic(),
                    description.type()
                );
            }
            renderTypes(name, description.args());
            renderParametersList(description.argNames(), description.argDescriptions());
            FunctionInfo info = EsqlFunctionRegistry.functionInfo(definition);
            assert info != null;
            renderDescription(description.description(), info.detailedDescription(), info.note());
            Optional<EsqlFunctionRegistry.ArgSignature> mapArgSignature = description.args()
                .stream()
                .filter(EsqlFunctionRegistry.ArgSignature::mapArg)
                .findFirst();
            boolean hasFunctionOptions = mapArgSignature.isPresent();
            if (hasFunctionOptions) {
                renderFunctionNamedParams((EsqlFunctionRegistry.MapArgSignature) mapArgSignature.get());
            }
            boolean hasExamples = renderExamples(info);
            boolean hasAppendix = renderAppendix(info.appendix());
            renderFullLayout(info.preview(), hasExamples, hasAppendix, hasFunctionOptions);
            renderKibanaInlineDocs(name, info);
            renderKibanaFunctionDefinition(name, info, description.args(), description.variadic());
        }

        private void renderFunctionNamedParams(EsqlFunctionRegistry.MapArgSignature mapArgSignature) throws IOException {
            String header = "| name | types | description |\n| --- | --- | --- |";

            List<String> table = new ArrayList<>();
            for (Map.Entry<String, EsqlFunctionRegistry.MapEntryArgSignature> argSignatureEntry : mapArgSignature.mapParams().entrySet()) {
                StringBuilder builder = new StringBuilder("| ");
                EsqlFunctionRegistry.MapEntryArgSignature arg = argSignatureEntry.getValue();
                builder.append(arg.name()).append(" | ").append(arg.type()).append(" | ").append(arg.description());
                table.add(builder.append(" |").toString());
            }

            String rendered = DOCS_WARNING + """
                **Supported function named parameters**

                """ + header + "\n" + table.stream().collect(Collectors.joining("\n")) + "\n";
            logger.info("Writing function named parameters for [{}]:\n{}", name, rendered);
            writeToTempSnippetsDir("functionNamedParams", rendered);
        }

        private void renderFullLayout(boolean preview, boolean hasExamples, boolean hasAppendix, boolean hasFunctionOptions)
            throws IOException {
            StringBuilder rendered = new StringBuilder(
                DOCS_WARNING + """
                    ## `$UPPER_NAME$` [esql-$NAME$]
                    $PREVIEW_CALLOUT$
                    **Syntax**

                    :::{image} ../../../images/$CATEGORY$/$NAME$.svg
                    :alt: Embedded
                    :class: text-center
                    :::

                    """.replace("$NAME$", name)
                    .replace("$CATEGORY$", category)
                    .replace("$UPPER_NAME$", name.toUpperCase(Locale.ROOT))
                    .replace("$PREVIEW_CALLOUT$", preview ? PREVIEW_CALLOUT : "")
            );
            for (String section : new String[] { "parameters", "description", "types" }) {
                rendered.append(addInclude(section));
            }
            if (hasFunctionOptions) {
                rendered.append(addInclude("functionNamedParams"));
            }
            if (hasExamples) {
                rendered.append(addInclude("examples"));
            }
            if (hasAppendix) {
                rendered.append(addInclude("appendix"));
            }
            logger.info("Writing layout for [{}]:\n{}", name, rendered.toString());
            writeToTempSnippetsDir("layout", rendered.toString());
        }

        private String addInclude(String section) {
            return """

                :::{include} ../$SECTION$/$NAME$.md
                :::
                """.replace("$NAME$", name).replace("$SECTION$", section);
        }
    }

    static class OperatorsDocsSupport extends DocsV3Support {

        private OperatorsDocsSupport(String name, Class<?> testClass) {
            super("operators", name, testClass);
        }

        @Override
        protected void renderSignature() throws IOException {
            OperatorConfig op = OPERATORS.get(name);
            String rendered = (switch (op.category()) {
                case BINARY -> RailRoadDiagram.binaryOperator(op.symbol());
                case UNARY -> RailRoadDiagram.unaryOperator(op.symbol());
                case SEARCH -> RailRoadDiagram.searchOperator(op.symbol());
                default -> buildFunctionSignatureSvg();
            });
            if (rendered == null) {
                logger.info("Skipping rendering signature because the operator isn't registered");
            } else {
                logger.info("Writing operator signature");
                writeToTempImageDir(rendered);
            }
        }

        @Override
        protected void renderDocs() throws IOException {
            DocsV3Support.OperatorConfig op = OPERATORS.get(name);
            Constructor<?> ctor = constructorWithFunctionInfo(op.clazz());
            if (ctor != null) {
                FunctionInfo functionInfo = ctor.getAnnotation(FunctionInfo.class);
                assert functionInfo != null;
                renderDocsForOperators(op.name(), ctor, functionInfo, op.variadic());
            } else {
                logger.info("Skipping rendering docs for operator '" + op.name() + "' with no @FunctionInfo");
            }
        }

        void renderDocsForNegatedOperators(Constructor<?> ctor, Function<String, String> description) throws IOException {
            String baseName = name.toLowerCase(Locale.ROOT).replace("not ", "");
            OperatorConfig op = OPERATORS.get(baseName);
            assert op != null;
            FunctionInfo orig = ctor.getAnnotation(FunctionInfo.class);
            assert orig != null;
            FunctionInfo functionInfo = new FunctionInfo() {
                @Override
                public Class<? extends Annotation> annotationType() {
                    return orig.annotationType();
                }

                @Override
                public String operator() {
                    return name;
                }

                @Override
                public String[] returnType() {
                    return orig.returnType();
                }

                @Override
                public boolean preview() {
                    return orig.preview();
                }

                @Override
                public String description() {
                    return description.apply(orig.description().replace(baseName, name));
                }

                @Override
                public String detailedDescription() {
                    return "";
                }

                @Override
                public String note() {
                    return orig.note().replace(baseName, name);
                }

                @Override
                public String appendix() {
                    return orig.appendix().replace(baseName, name);
                }

                @Override
                public FunctionType type() {
                    return orig.type();
                }

                @Override
                public Example[] examples() {
                    // throw away examples
                    return new Example[] {};
                }
            };
            renderDocsForOperators("not_" + baseName, ctor, functionInfo, op.variadic());
        }

        void renderDocsForOperators(String name, Constructor<?> ctor, FunctionInfo info, boolean variadic) throws IOException {
            renderKibanaInlineDocs(name, info);

            var params = ctor.getParameters();

            List<EsqlFunctionRegistry.ArgSignature> args = new ArrayList<>(params.length);
            for (int i = 1; i < params.length; i++) { // skipping 1st argument, the source
                if (Configuration.class.isAssignableFrom(params[i].getType()) == false) {
                    MapParam mapParamInfo = params[i].getAnnotation(MapParam.class);
                    if (mapParamInfo != null) {
                        args.add(mapParam(mapParamInfo));
                    } else {
                        Param paramInfo = params[i].getAnnotation(Param.class);
                        args.add(paramInfo != null ? param(paramInfo) : paramWithoutAnnotation(params[i].getName()));
                    }
                }
            }
            renderKibanaFunctionDefinition(name, info, args, variadic);
            renderDetailedDescription(info.detailedDescription(), info.note());
            renderTypes(name, args);
            renderExamples(info);
            // TODO: Consider rendering more for operators, like layout, which is currently static
        }

        void renderDetailedDescription(String detailedDescription, String note) throws IOException {
            StringBuilder rendered = new StringBuilder();
            if (Strings.isNullOrEmpty(detailedDescription) == false) {
                detailedDescription = replaceLinks(detailedDescription.trim());
                rendered.append("\n").append(detailedDescription).append("\n");
            }

            if (Strings.isNullOrEmpty(note) == false) {
                rendered.append("\n::::{note}\n").append(replaceLinks(note)).append("\n::::\n\n");
            }
            if (rendered.isEmpty() == false) {
                rendered.append("\n");
                logger.info("Writing detailed description for [{}]:\n{}", name, rendered);
                writeToTempSnippetsDir("detailedDescription", rendered.toString());
            }
        }
    }

    protected String buildFunctionSignatureSvg() throws IOException {
        FunctionDefinition definition = definition(name);
        return (definition != null) ? RailRoadDiagram.functionSignature(definition) : null;
    }

    void renderParametersList(List<String> argNames, List<String> argDescriptions) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append(DOCS_WARNING);
        builder.append("**Parameters**\n");
        for (int a = 0; a < argNames.size(); a++) {
            String description = replaceLinks(argDescriptions.get(a));
            builder.append("\n`").append(argNames.get(a)).append("`\n:   ").append(description).append('\n');
        }
        builder.append('\n');
        String rendered = builder.toString();
        logger.info("Writing parameters for [{}]:\n{}", name, rendered);
        writeToTempSnippetsDir("parameters", rendered);
    }

    void renderTypes(String name, List<EsqlFunctionRegistry.ArgSignature> args) throws IOException {
        StringBuilder header = new StringBuilder("| ");
        StringBuilder separator = new StringBuilder("| ");
        List<String> argNames = args.stream().map(EsqlFunctionRegistry.ArgSignature::name).toList();
        for (String arg : argNames) {
            header.append(arg).append(" | ");
            separator.append("---").append(" | ");
        }
        header.append("result |");
        separator.append("--- |");

        List<String> table = new ArrayList<>();
        var signatures = signatures(testClass);
        for (Map.Entry<List<DataType>, DataType> sig : signatures(testClass).entrySet()) { // TODO flip to using sortedSignatures
            if (shouldHideSignature(sig.getKey(), sig.getValue())) {
                continue;
            }
            if (sig.getKey().size() > argNames.size()) { // skip variadic [test] cases (but not those with optional parameters)
                continue;
            }
            StringBuilder b = new StringBuilder("| ");
            for (int i = 0; i < sig.getKey().size(); i++) {
                DataType argType = sig.getKey().get(i);
                EsqlFunctionRegistry.ArgSignature argSignature = args.get(i);
                if (argSignature.mapArg()) {
                    b.append("named parameters");
                } else {
                    b.append(argType.esNameIfPossible());
                }
                b.append(" | ");
            }
            b.append("| ".repeat(argNames.size() - sig.getKey().size()));
            b.append(sig.getValue().esNameIfPossible());
            b.append(" |");
            table.add(b.toString());
        }
        Collections.sort(table);
        if (table.isEmpty()) {
            table.add(signatures.values().iterator().next().esNameIfPossible());
        }

        String rendered = DOCS_WARNING + """
            **Supported types**

            """ + header + "\n" + separator + "\n" + table.stream().collect(Collectors.joining("\n")) + "\n\n";
        logger.info("Writing function types for [{}]:\n{}", name, rendered);
        writeToTempSnippetsDir("types", rendered);
    }

    void renderDescription(String description, String detailedDescription, String note) throws IOException {
        description = replaceLinks(description.trim());
        note = replaceLinks(note);
        String rendered = DOCS_WARNING + """
            **Description**

            """ + description + "\n";

        detailedDescription = replaceLinks(detailedDescription.trim());
        if (Strings.isNullOrEmpty(detailedDescription) == false) {
            rendered += "\n" + detailedDescription + "\n";
        }

        if (Strings.isNullOrEmpty(note) == false) {
            rendered += "\n::::{note}\n" + note + "\n::::\n\n";
        }
        rendered += "\n";
        logger.info("Writing description for [{}]:\n{}", name, rendered);
        writeToTempSnippetsDir("description", rendered);
    }

    protected boolean renderExamples(FunctionInfo info) throws IOException {
        if (info == null || info.examples().length == 0) {
            return false;
        }
        StringBuilder builder = new StringBuilder();
        builder.append(DOCS_WARNING);
        if (info.examples().length == 1) {
            builder.append("**Example**\n\n");
        } else {
            builder.append("**Examples**\n\n");
        }
        for (Example example : info.examples()) {
            if (example.description().length() > 0) {
                builder.append(replaceLinks(example.description().trim()));
                builder.append("\n\n");
            }
            String exampleQuery = loadExampleQuery(example);
            String exampleResult = loadExampleResult(example);
            builder.append(exampleQuery).append("\n").append(exampleResult).append("\n");
            if (example.explanation().length() > 0) {
                builder.append("\n");
                builder.append(replaceLinks(example.explanation().trim()));
                builder.append("\n\n");
            }
        }
        builder.append('\n');
        String rendered = builder.toString();
        logger.info("Writing examples for [{}]:\n{}", name, rendered);
        writeToTempSnippetsDir("examples", rendered);
        return true;
    }

    void renderKibanaInlineDocs(String name, FunctionInfo info) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append("""
            <!--
            This is generated by ESQL’s AbstractFunctionTestCase. Do no edit it. See ../README.md for how to regenerate it.
            -->

            """);
        builder.append("### ").append(name.toUpperCase(Locale.ROOT)).append("\n");
        builder.append(removeAsciidocLinks(info.description())).append("\n\n");

        if (info.examples().length > 0) {
            Example example = info.examples()[0];
            builder.append("```\n");
            builder.append(loadExample(example.file(), example.tag()));
            builder.append("\n```\n");
        }
        if (Strings.isNullOrEmpty(info.note()) == false) {
            builder.append("Note: ").append(removeAsciidocLinks(info.note())).append("\n");
        }
        String rendered = builder.toString();
        logger.info("Writing kibana inline docs for [{}]:\n{}", name, rendered);
        writeToTempKibanaDir("docs", "md", rendered);
    }

    void renderKibanaFunctionDefinition(String name, FunctionInfo info, List<EsqlFunctionRegistry.ArgSignature> args, boolean variadic)
        throws IOException {

        try (XContentBuilder builder = JsonXContent.contentBuilder().prettyPrint().lfAtEnd().startObject()) {
            builder.field(
                "comment",
                "This is generated by ESQL’s AbstractFunctionTestCase. Do no edit it. See ../README.md for how to regenerate it."
            );
            if (false == info.operator().isEmpty()) {
                builder.field("type", "operator");
                builder.field("operator", info.operator());
                // TODO: Bring back this assertion
                // assertThat(isAggregation(), equalTo(false));
            } else {
                builder.field("type", switch (info.type()) {
                    case SCALAR -> "scalar";
                    case AGGREGATE -> "agg";
                    case GROUPING -> "grouping";
                });
            }
            builder.field("name", name);
            builder.field("description", removeAsciidocLinks(info.description()));
            if (Strings.isNullOrEmpty(info.note()) == false) {
                builder.field("note", removeAsciidocLinks(info.note()));
            }
            // TODO aliases

            builder.startArray("signatures");
            if (args.isEmpty()) {
                builder.startObject();
                builder.startArray("params");
                builder.endArray();
                // There should only be one return type so just use that as the example
                builder.field("returnType", signatures(testClass).values().iterator().next().esNameIfPossible());
                builder.endObject();
            } else {
                int minArgCount = (int) args.stream().filter(a -> false == a.optional()).count();
                for (Map.Entry<List<DataType>, DataType> sig : sortedSignatures()) {
                    if (variadic && sig.getKey().size() > args.size()) {
                        // For variadic functions we test much longer signatures, let’s just stop at the last one
                        continue;
                    }
                    if (sig.getKey().size() < minArgCount) {
                        throw new IllegalArgumentException("signature " + sig.getKey() + " is missing non-optional arg for " + args);
                    }
                    if (shouldHideSignature(sig.getKey(), sig.getValue())) {
                        continue;
                    }
                    builder.startObject();
                    builder.startArray("params");
                    for (int i = 0; i < sig.getKey().size(); i++) {
                        EsqlFunctionRegistry.ArgSignature arg = args.get(i);
                        builder.startObject();
                        builder.field("name", arg.name());
                        if (arg.mapArg()) {
                            builder.field("type", "function_named_parameters");
                            builder.field(
                                "mapParams",
                                arg.mapParams()
                                    .values()
                                    .stream()
                                    .map(mapArgSignature -> "{" + mapArgSignature + "}")
                                    .collect(Collectors.joining(", "))
                            );
                        } else {
                            builder.field("type", sig.getKey().get(i).esNameIfPossible());
                        }
                        builder.field("optional", arg.optional());
                        builder.field("description", arg.description());
                        builder.endObject();
                    }
                    builder.endArray();
                    builder.field("variadic", variadic);
                    builder.field("returnType", sig.getValue().esNameIfPossible());
                    builder.endObject();
                }
            }
            builder.endArray();

            if (info.examples().length > 0) {
                builder.startArray("examples");
                for (Example example : info.examples()) {
                    builder.value(loadExample(example.file(), example.tag()));
                }
                builder.endArray();
            }
            builder.field("preview", info.preview());
            builder.field("snapshot_only", EsqlFunctionRegistry.isSnapshotOnly(name));

            String rendered = Strings.toString(builder.endObject());
            logger.info("Writing kibana function definition for [{}]:\n{}", name, rendered);
            writeToTempKibanaDir("definition", "json", rendered);
        }
    }

    private String removeAsciidocLinks(String asciidoc) {
        return asciidoc.replaceAll("[^ ]+\\[([^\\]]+)\\]", "$1");
    }

    private List<Map.Entry<List<DataType>, DataType>> sortedSignatures() {
        List<Map.Entry<List<DataType>, DataType>> sortedSignatures = new ArrayList<>(signatures(testClass).entrySet());
        Collections.sort(sortedSignatures, (lhs, rhs) -> {
            int maxlen = Math.max(lhs.getKey().size(), rhs.getKey().size());
            for (int i = 0; i < maxlen; i++) {
                if (lhs.getKey().size() <= i) {
                    return -1;
                }
                if (rhs.getKey().size() <= i) {
                    return 1;
                }
                int c = lhs.getKey().get(i).esNameIfPossible().compareTo(rhs.getKey().get(i).esNameIfPossible());
                if (c != 0) {
                    return c;
                }
            }
            return lhs.getValue().esNameIfPossible().compareTo(rhs.getValue().esNameIfPossible());
        });
        return sortedSignatures;
    }

    protected boolean renderAppendix(String appendix) throws IOException {
        if (appendix.isEmpty()) {
            return false;
        }

        String rendered = DOCS_WARNING + replaceLinks(appendix) + "\n";

        logger.info("Writing appendix for [{}]:\n{}", name, rendered);
        writeToTempSnippetsDir("appendix", rendered);
        return true;
    }

    private HashMap<String, Map<String, String>> examples = new HashMap<>();

    protected String loadExampleQuery(Example example) throws IOException {
        return "```esql\n" + loadExample(example.file(), example.tag()) + "\n```\n";
    }

    protected String loadExampleResult(Example example) throws IOException {
        return loadExample(example.file(), example.tag() + "-result");
    }

    protected String loadExample(String csvSpec, String tag) throws IOException {
        if (examples.containsKey(csvSpec) == false) {
            var taggedExamples = loadExampleFile(csvSpec);
            examples.put(csvSpec, taggedExamples);
            return taggedExamples.get(tag);
        } else {
            return examples.get(csvSpec).get(tag);
        }
    }

    protected Map<String, String> loadExampleFile(String csvSpec) throws IOException {
        Map<String, String> taggedExamples = new HashMap<>();
        String csvFile = csvSpec.endsWith(".csv-spec") ? csvSpec : csvSpec + ".csv-spec";
        InputStream specInputStream = CsvTestsDataLoader.class.getResourceAsStream("/" + csvFile);
        if (specInputStream == null) {
            throw new IllegalArgumentException("Failed to find examples file [" + csvFile + "]");
        }
        try (BufferedReader spec = new BufferedReader(new InputStreamReader(specInputStream, StandardCharsets.UTF_8))) {

            String line;
            Pattern tagPattern = Pattern.compile("//\\s*(tag|end)::([\\w\\-_]+)\\[]");

            String currentTag = null;
            List<String> currentLines = null;

            while ((line = spec.readLine()) != null) {
                Matcher tagMatcher = tagPattern.matcher(line);
                if (tagMatcher.find()) {
                    String tagType = tagMatcher.group(1);
                    currentTag = tagMatcher.group(2);
                    if (tagType.equals("tag")) {
                        currentLines = new ArrayList<>();
                    } else if (tagType.equals("end")) {
                        if (currentLines == null) {
                            throw new IllegalArgumentException("End tag found, but no starting tag was found: " + line);
                        }
                        taggedExamples.put(currentTag, reformatExample(currentTag, currentLines));
                        currentLines = null;
                        currentTag = null;
                    }
                } else if (currentTag != null) {
                    currentLines.add(line); // Collect lines within the block
                }
            }
        }
        return taggedExamples;
    }

    protected String reformatExample(String tag, List<String> lines) {
        if (tag.endsWith("-result")) {
            StringBuffer sb = new StringBuffer();
            for (String line : lines) {
                sb.append(renderTableLine(line, sb.isEmpty()));
            }
            return sb.toString();
        } else {
            return lines.stream().map(l -> l.stripTrailing().replaceAll("\\\\", "\\\\\\\\")).collect(Collectors.joining("\n"));
        }
    }

    private String renderTableLine(String line, boolean header) {
        String[] columns = line.split("\\|");
        if (header) {
            return renderTableLine(columns) + renderTableSpacerLine(columns.length);
        } else {
            return renderTableLine(columns);
        }
    }

    private String renderTableLine(String[] columns) {
        StringBuffer sb = new StringBuffer();
        sb.append("| ");
        for (int i = 0; i < columns.length; i++) {
            if (i > 0) {
                sb.append(" | ");
            }
            // Some cells have regex content (see CATEGORIZE), so we need to escape this
            sb.append(columns[i].trim().replaceAll("\\.\\*", ".\\\\*"));
        }
        return sb.append(" |\n").toString();
    }

    private String renderTableSpacerLine(int columns) {
        StringBuffer sb = new StringBuffer();
        sb.append("| ");
        for (int i = 0; i < columns; i++) {
            if (i > 0) {
                sb.append(" | ");
            }
            sb.append("---");
        }
        return sb.append(" |\n").toString();
    }
}
