[[reset-features-api]]
=== Reset features API
++++
<titleabbrev>Reset features</titleabbrev>
++++

experimental::[]

Clears all of the the state information stored in system indices by {es} features, including the security and machine learning indices.

WARNING: Intended for development and testing use only. Do not reset features on a production cluster.  

[source,console]
-----------------------------------
POST /_features/_reset
-----------------------------------

[[reset-features-api-request]]
==== {api-request-title}

`POST /_features/_reset`


[[reset-features-api-desc]]
==== {api-description-title}

Return a cluster to the same state as a new installation by resetting the feature state for all {es} features. This deletes all state information stored in system indices.

Note that select features might provide a way to reset particular system indices. Using this API resets _all_ features, both those that are built-in and implemented as plugins. 

To list the features that will be affected, use the <<get-features-api,get features API>>. 

IMPORTANT: The features installed on the node you submit this request to are the features that will be reset. Run on the master node if you have any doubts about which plugins are installed on individual nodes.

==== {api-examples-title}
Example response:
[source,console-result]
----
{
  "features" : [
    {
      "feature_name" : "async_search",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "enrich",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "fleet",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "geoip",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "kibana",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "logstash_management",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "machine_learning",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "searchable_snapshots",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "security",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "tasks",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "transform",
      "status" : "SUCCESS"
    },
    {
      "feature_name" : "watcher",
      "status" : "SUCCESS"
    }
  ]
}
----
