/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.eql.expression.function.scalar.whitelist;

import java.util.List;

/**
 * {@code @allocates_dynamic} estimators for the EQL string functions in {@code eql_whitelist.txt}. Each is a
 * {@code public static long} method matching the allowlisted function's parameters and returns the heap cost of the
 * {@link String} it allocates. Invoked from generated bytecode on the allocation pre-check path, so they must be cheap,
 * must not allocate, and must not throw — even on argument values the real function would reject.
 *
 * <p>The trivial sizing math is reimplemented locally rather than shared from {@code lang-painless}, which exposes it only
 * as non-SPI implementation detail; this module depends on {@code painless-spi} alone.
 */
public final class EqlAllocationEstimators {

    /** Fixed overhead of a freshly allocated {@link String}: the object plus its backing array header. */
    private static final long STRING_RESULT_OVERHEAD = 32;

    /** Conservative cost for a value whose {@code toString()} length is not knowable without allocating it. */
    private static final long UNKNOWN_TOSTRING_BYTES = 256;

    private EqlAllocationEstimators() {}

    /** Signed multiply saturating to {@link Long#MAX_VALUE} on overflow, so an enormous length trips the limit rather than wrapping. */
    private static long mulSat(long a, long b) {
        try {
            return Math.multiplyExact(a, b);
        } catch (ArithmeticException overflow) {
            return ((a ^ b) < 0) ? Long.MIN_VALUE : Long.MAX_VALUE;
        }
    }

    /**
     * Heap cost of a {@link String} of {@code chars} UTF-16 characters: fixed overhead plus 2 bytes per char (negative lengths
     * cost only the overhead).
     */
    private static long newStringBytes(long chars) {
        return STRING_RESULT_OVERHEAD + mulSat(2L, Math.max(0L, chars));
    }

    /**
     * {@code string}/{@code nullSafeSortString}: a new String from an arbitrary value's {@code toString()}. A
     * {@link CharSequence} contributes its real length; anything else falls back to a conservative fixed size.
     */
    public static long stringValueBytes(Object value) {
        return value instanceof CharSequence cs ? newStringBytes(cs.length()) : UNKNOWN_TOSTRING_BYTES;
    }

    /** {@code concat(List)}: a new String concatenating a list's elements, sized by their summed lengths. */
    public static long listConcatBytes(List<?> values) {
        if (values == null) {
            return newStringBytes(0);
        }
        long chars = 0;
        for (Object value : values) {
            chars += value instanceof CharSequence cs ? cs.length() : 128; // fallback for non-CharSequence elements
            if (chars > Integer.MAX_VALUE) {
                break; // already large enough to trip any limit; avoid overflow
            }
        }
        return newStringBytes(chars);
    }

    /** {@code substring}: a new String no longer than {@code value}. */
    public static long boundedStringBytes(String value, Number start, Number end) {
        return newStringBytes(value == null ? 0 : value.length());
    }

    /** {@code between}: extracts a substring of the first argument, so it is no larger than that string. */
    public static long betweenBytes(String value, String left, String right, Boolean greedy, Boolean caseSensitive) {
        return newStringBytes(value == null ? 0 : value.length());
    }
}
