/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.action.bulk;

import org.apache.lucene.util.BytesRef;
import org.apache.lucene.util.Accountable;
import org.elasticsearch.core.Nullable;
import org.elasticsearch.core.Releasable;
import org.elasticsearch.xcontent.XContentType;

import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * A binary columnar representation of a batch of documents for bulk indexing.
 * Backed by a contiguous byte array. Provides zero-copy read access to per-document
 * metadata and columnar field data.
 *
 * <h2>Binary Layout</h2>
 * <pre>
 * [Header]
 *   4 bytes: magic (0x45534442 = "ESDB")
 *   4 bytes: version (1)
 *   4 bytes: document count (N)
 *   4 bytes: column count (M)
 *
 * [Per-document metadata] (row-oriented)
 *   For each doc i (0..N-1):
 *     4 bytes: id byte length, followed by UTF-8 id bytes
 *     4 bytes: routing byte length (0 = null), followed by UTF-8 routing bytes
 *     1 byte:  XContentType ordinal
 *     8 bytes: autoGeneratedTimestamp (BE long)
 *     1 byte:  isRetry flag
 *
 * [Column directory]
 *   For each column j (0..M-1):
 *     4 bytes: field path byte length, followed by UTF-8 field path bytes
 *     1 byte:  column type tag
 *     4 bytes: offset into column data section (relative to start of column data)
 *     4 bytes: length of column data
 *
 * [Column data]
 *   Contiguous column data blocks, referenced by directory offsets
 * </pre>
 */
public class DocumentBatch implements Releasable, Accountable {

    public static final int MAGIC = 0x45534442; // "ESDB"
    public static final int VERSION = 1;

    private static final VarHandle INT_HANDLE = MethodHandles.byteArrayViewVarHandle(int[].class, ByteOrder.BIG_ENDIAN);
    private static final VarHandle LONG_HANDLE = MethodHandles.byteArrayViewVarHandle(long[].class, ByteOrder.BIG_ENDIAN);

    private final byte[] data;
    private final int docCount;
    private final int columnCount;

    // Parsed offsets for fast access
    private final int[] docMetadataOffsets;  // offset to each doc's metadata block
    private final int columnDirectoryOffset;
    private final int columnDataOffset;

    // Optional per-document tsid. Null when the index is not a time series index.
    // When present, every document in the batch has a tsid (all-or-nothing).
    private @Nullable BytesRef[] tsids;

    public DocumentBatch(byte[] data) {
        this.data = data;

        // Parse header
        int magic = (int) INT_HANDLE.get(data, 0);
        if (magic != MAGIC) {
            throw new IllegalArgumentException("Invalid DocumentBatch magic: " + Integer.toHexString(magic));
        }
        int version = (int) INT_HANDLE.get(data, 4);
        if (version != VERSION) {
            throw new IllegalArgumentException("Unsupported DocumentBatch version: " + version);
        }
        this.docCount = (int) INT_HANDLE.get(data, 8);
        this.columnCount = (int) INT_HANDLE.get(data, 12);

        // Parse doc metadata offsets
        this.docMetadataOffsets = new int[docCount];
        int pos = 16; // after header
        for (int i = 0; i < docCount; i++) {
            docMetadataOffsets[i] = pos;
            // Skip id
            int idLen = (int) INT_HANDLE.get(data, pos);
            pos += 4 + idLen;
            // Skip routing
            int routingLen = (int) INT_HANDLE.get(data, pos);
            pos += 4 + routingLen;
            // Skip XContentType(1) + autoGeneratedTimestamp(8) + isRetry(1)
            pos += 10;
        }

        this.columnDirectoryOffset = pos;

        // Parse column directory to find column data start
        int dirPos = pos;
        for (int j = 0; j < columnCount; j++) {
            int pathLen = (int) INT_HANDLE.get(data, dirPos);
            dirPos += 4 + pathLen;
            dirPos += 1; // type tag
            dirPos += 4; // offset
            dirPos += 4; // length
        }
        this.columnDataOffset = dirPos;
    }

    /**
     * Returns the raw backing byte array for serialization.
     */
    public byte[] getRawData() {
        return data;
    }

    public int docCount() {
        return docCount;
    }

    public int columnCount() {
        return columnCount;
    }

    public String docId(int docIndex) {
        int pos = docMetadataOffsets[docIndex];
        int idLen = (int) INT_HANDLE.get(data, pos);
        if (idLen == 0) return null;
        return new String(data, pos + 4, idLen, StandardCharsets.UTF_8);
    }

    public String docRouting(int docIndex) {
        int pos = docMetadataOffsets[docIndex];
        // Skip id
        int idLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + idLen;
        // Read routing
        int routingLen = (int) INT_HANDLE.get(data, pos);
        if (routingLen == 0) return null;
        return new String(data, pos + 4, routingLen, StandardCharsets.UTF_8);
    }

    public XContentType docXContentType(int docIndex) {
        int pos = docMetadataOffsets[docIndex];
        // Skip id
        int idLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + idLen;
        // Skip routing
        int routingLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + routingLen;
        // Read XContentType ordinal
        return XContentType.ofOrdinal(data[pos]);
    }

    public long docAutoGeneratedTimestamp(int docIndex) {
        int pos = docMetadataOffsets[docIndex];
        // Skip id
        int idLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + idLen;
        // Skip routing
        int routingLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + routingLen;
        // Skip XContentType
        pos += 1;
        return (long) LONG_HANDLE.get(data, pos);
    }

    public boolean docIsRetry(int docIndex) {
        int pos = docMetadataOffsets[docIndex];
        // Skip id
        int idLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + idLen;
        // Skip routing
        int routingLen = (int) INT_HANDLE.get(data, pos);
        pos += 4 + routingLen;
        // Skip XContentType(1) + autoGeneratedTimestamp(8)
        pos += 9;
        return data[pos] != 0;
    }

    /**
     * Sets the per-document tsids for this batch. When non-null, every element must be non-null
     * and the array length must equal {@link #docCount()}.
     */
    public void setTsids(@Nullable BytesRef[] tsids) {
        if (tsids != null && tsids.length != docCount) {
            throw new IllegalArgumentException("tsids array length [" + tsids.length + "] must match docCount [" + docCount + "]");
        }
        this.tsids = tsids;
    }

    /**
     * Returns the tsid for the given document index, or null if tsids are not present.
     */
    public @Nullable BytesRef docTsid(int docIndex) {
        return tsids != null ? tsids[docIndex] : null;
    }

    /**
     * Returns true if this batch contains per-document tsids.
     */
    public boolean hasTsids() {
        return tsids != null;
    }

    /**
     * Returns an iterator over the columns in this batch.
     */
    public Iterator<FieldColumn> columns() {
        List<FieldColumn> cols = new ArrayList<>(columnCount);
        int dirPos = columnDirectoryOffset;
        for (int j = 0; j < columnCount; j++) {
            int pathLen = (int) INT_HANDLE.get(data, dirPos);
            String fieldPath = new String(data, dirPos + 4, pathLen, StandardCharsets.UTF_8);
            dirPos += 4 + pathLen;

            ColumnType type = ColumnType.fromId(data[dirPos]);
            dirPos += 1;

            int colOffset = (int) INT_HANDLE.get(data, dirPos);
            dirPos += 4;
            int colLength = (int) INT_HANDLE.get(data, dirPos);
            dirPos += 4;

            cols.add(new FieldColumn(fieldPath, type, data, columnDataOffset + colOffset, colLength, docCount));
        }
        return cols.iterator();
    }

    /**
     * Returns the list of columns for random access.
     */
    public List<FieldColumn> columnList() {
        List<FieldColumn> cols = new ArrayList<>(columnCount);
        Iterator<FieldColumn> it = columns();
        while (it.hasNext()) {
            cols.add(it.next());
        }
        return cols;
    }

    /**
     * Returns the backing byte array. For testing and serialization.
     */
    public byte[] rawData() {
        return data;
    }

    @Override
    public void close() {
        // No resources to release for byte[]-backed implementation
    }

    @Override
    public long ramBytesUsed() {
        long size = data.length + (long) docMetadataOffsets.length * Integer.BYTES + 64; // estimate overhead
        if (tsids != null) {
            for (BytesRef tsid : tsids) {
                size += tsid.length + 16; // bytes + BytesRef object overhead
            }
        }
        return size;
    }
}
