[[index-modules-indexing-pressure]]
== Indexing Pressure

Indexing documents into Elasticsearch introduces system load in the form of
memory and CPU load. Each indexing operation includes coordinating, primary, and
replica steps. These steps can be performed across multiple nodes in the
cluster. If too much indexing work is introduced into the system, the cluster
can become saturated.

Indexing pressure is primarily generated by external operations such as indexing
requests or CCR follow tasks. However, there is some internal indexing pressure
during a shard recovery or primary failover.

Elasticsearch internally monitors indexing load. When the load exceeds
certain limits, new indexing work will be rejected.

[float]
=== Indexing Steps

External indexing operations go through three steps. The node receiving the
indexing is the coordinating node. In the coordinating step the node performs
any configured ingest pipelines, separates the request into individual shard
requests, and dispatches them to the primary shards.

In the primary step, the primary shard node ensures that it is still the primary
(otherwise it reroutes the request to the new primary), waits on active shards,
indexes the documents into its translog and Lucene, and dispatches to the
replicas.

Finally, in the replica step, every available replica node indexes the documents
into its translog and Lucene.


[float]
=== Memory Limits

Elasticsearch exposes a node setting `indexing_pressure.memory.limit` which
restricts the number of bytes for outstanding indexing requests. Be default,
this setting is configured to be 10% of the heap.

A node will start rejecting new indexing work at the coordinating or primary
step when the number of outstanding coordinating, primary and replica indexing
requests is greater than the configured limit.

A node will start rejecting new indexing work at the replica step when the
number of outstanding replica indexing requests is greater than 1.5x the
configured limit. This design means that as indexing pressure builds on nodes,
they will naturally stop accepting coordinating and primary work in favor of
outstanding replica work.


[float]
=== Monitoring

Indexing pressure metrics are exposed by the `GET /_nodes/stats` API.
