[[delete-connector-sync-job-api]]
=== Delete connector sync job API
++++
<titleabbrev>Delete connector sync job</titleabbrev>
++++

beta::[]

Removes a connector sync job and its associated data.
This is a destructive action that is not recoverable.

To get started with Connector APIs, check out <<es-connectors-tutorial-api, our tutorial>>.


[[delete-connector-sync-job-api-request]]
==== {api-request-title}

`DELETE _connector/_sync_job/<connector_sync_job_id>`

[[delete-connector-sync-job-api-prereq]]
==== {api-prereq-title}

* To sync data using self-managed connectors, you need to deploy the <<es-connectors-deploy-connector-service,Elastic connector service>>. on your own infrastructure. This service runs automatically on Elastic Cloud for Elastic managed connectors.

[[delete-connector-sync-job-api-path-params]]
==== {api-path-parms-title}

`<connector_sync_job_id>`::
(Required, string)

[[delete-connector-sync-job-api-response-codes]]
==== {api-response-codes-title}

`400`::
The `connector_sync_job_id` was not provided.

`404`::
No connector sync job matching `connector_sync_job_id` could be found.

[[delete-connector-sync-job-api-example]]
==== {api-examples-title}

The following example deletes the connector sync job with ID `my-connector-sync-job-id`:

[source,console]
----
DELETE _connector/_sync_job/my-connector-sync-job-id
----
// TEST[skip:there's no way to clean up after this code snippet, as we don't know the ids of sync jobs ahead of time]

[source,console-result]
----
{
    "acknowledged": true
}
----
