#
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the "Elastic License
# 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
# Public License v 1"; you may not use this file except in compliance with, at
# your election, the "Elastic License 2.0", the "GNU Affero General Public
# License v3.0 only", or the "Server Side Public License, v 1".
#

# Log4j2 uses log4j2-test.properties when present instead of log4j2.properties.
# The dependency on testFixturesImplementation(project(":test:framework")) transitively adds log4j2-test.properties
# from test/framework to the classpath. It loads HeaderWarningAppender, a custom Log4j plugin from the server module
# which isn't registered, and causes initialization errors in benchmarks.
#
# This log4j2-test.properties file avoids this.

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c] [%node_name]%marker %m%n

# Do not log at all if it is not really critical - we're in a benchmark
rootLogger.level = error
rootLogger.appenderRef.console.ref = console

# Show native vector library capabilities during benchmarks
logger.nativeVec.name = org.elasticsearch.nativeaccess.jdk.JdkVectorLibrary
logger.nativeVec.level = info

