/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.datasources.glob;

import org.elasticsearch.core.Nullable;

import java.util.ArrayList;
import java.util.List;

/**
 * Expands brace groups ({@code {a,b,c}}) in glob patterns into concrete path candidates.
 * Also detects whether a glob is "brace-only" — meaning the pattern contains {@code {...}}
 * groups but no {@code *}, {@code ?}, or {@code [...]} anywhere (neither inside nor outside
 * braces), so that every expanded candidate is a concrete path.
 * <p>
 * Nested braces ({@code {a,{b,c}}}) are not supported; the expansion uses the first
 * closing brace after each opening brace. This is sufficient for patterns generated by
 * {@link GlobExpander#rewriteGlobWithHints} which always produces flat brace groups.
 * Unbalanced braces are treated as literals.
 */
final class BraceExpander {

    private BraceExpander() {}

    /**
     * Returns {@code true} if the glob contains only brace-group metacharacters.
     * A pattern with no metacharacters at all returns {@code false} (it's a literal, not a brace pattern).
     */
    static boolean isBraceOnly(String glob) {
        boolean hasBrace = false;
        boolean inBrace = false;
        for (int i = 0; i < glob.length(); i++) {
            char c = glob.charAt(i);
            if (c == '*' || c == '?' || c == '[') {
                return false;
            }
            if (inBrace) {
                if (c == '}') {
                    inBrace = false;
                } else if (c == '{') {
                    return false;
                }
            } else if (c == '{') {
                inBrace = true;
                hasBrace = true;
            }
        }
        return hasBrace && inBrace == false;
    }

    /**
     * Expands all brace groups in the glob into a list of concrete path candidates.
     * Returns {@code null} if the Cartesian product exceeds {@code maxExpansion},
     * signaling that the caller should fall back to listing.
     * Returns a single-element list containing the input if no braces are found.
     */
    @Nullable
    static List<String> expand(String glob, int maxExpansion) {
        int braceStart = glob.indexOf('{');
        if (braceStart < 0) {
            return List.of(glob);
        }
        int braceEnd = glob.indexOf('}', braceStart + 1);
        if (braceEnd < 0) {
            return List.of(glob);
        }

        String prefix = glob.substring(0, braceStart);
        String[] alternatives = glob.substring(braceStart + 1, braceEnd).split(",", -1);
        String suffix = glob.substring(braceEnd + 1);

        List<String> result = new ArrayList<>();
        for (String alt : alternatives) {
            String expanded = prefix + alt + suffix;
            List<String> subExpanded = expand(expanded, maxExpansion);
            if (subExpanded == null) {
                return null;
            }
            for (String s : subExpanded) {
                result.add(s);
                if (result.size() > maxExpansion) {
                    return null;
                }
            }
        }
        return result;
    }
}
