/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.datasources.glob;

import org.elasticsearch.core.Nullable;

/**
 * Expands brace groups ({@code {a,b,c}}) in glob patterns into concrete path candidates.
 * Also detects whether a glob is "brace-only" — meaning the pattern contains {@code {...}}
 * groups but no {@code *}, {@code ?}, or {@code [...]} anywhere (neither inside nor outside
 * braces), so that every expanded candidate is a concrete path.
 * <p>
 * Nested braces ({@code {a,{b,c}}}) are not supported; the expansion uses the first
 * closing brace after each opening brace. This is sufficient for patterns generated by
 * {@link GlobExpander#rewriteGlobWithHints} which always produces flat brace groups.
 * Unbalanced braces are treated as literals.
 */
final class BraceExpander {

    private BraceExpander() {}

    /**
     * Package-private so {@link GlobMatcher} parses brace bodies with the very same code the brace-only fast path
     * uses. The two used to disagree: this expanded {@code {1..3}} numerically while the matcher read the literal
     * text, so one construct meant two different things depending on which engine a pattern happened to reach.
     */
    static String[] expandBraceContent(String content, int maxExpansion) {
        int dotDot = content.indexOf("..");
        if (dotDot > 0 && dotDot < content.length() - 2 && content.indexOf(',') < 0) {
            String startStr = content.substring(0, dotDot);
            String endStr = content.substring(dotDot + 2);
            if (isNumeric(startStr) && isNumeric(endStr)) {
                String[] rangeResult = expandNumericRange(startStr, endStr, maxExpansion);
                if (rangeResult != null) {
                    return rangeResult;
                }
                return null;
            }
        }
        return content.split(",", -1);
    }

    private static boolean isNumeric(String s) {
        if (s.isEmpty()) {
            return false;
        }
        for (int i = 0; i < s.length(); i++) {
            if (Character.isDigit(s.charAt(i)) == false) {
                return false;
            }
        }
        return true;
    }

    @Nullable
    private static String[] expandNumericRange(String startStr, String endStr, int maxExpansion) {
        long start;
        long end;
        try {
            start = Long.parseLong(startStr);
            end = Long.parseLong(endStr);
        } catch (NumberFormatException e) {
            return null;
        }

        int width = Math.max(startStr.length(), endStr.length());
        boolean zeroPad = (startStr.length() > 1 && startStr.charAt(0) == '0') || (endStr.length() > 1 && endStr.charAt(0) == '0');

        long count;
        if (start <= end) {
            count = end - start + 1;
        } else {
            count = start - end + 1;
        }
        if (count < 0 || count > maxExpansion) {
            return null;
        }

        String[] result = new String[(int) count];
        long step = start <= end ? 1 : -1;
        long current = start;
        for (int i = 0; i < count; i++) {
            result[i] = zeroPad ? padWithZeros(current, width) : Long.toString(current);
            current += step;
        }
        return result;
    }

    private static String padWithZeros(long value, int width) {
        String str = Long.toString(value);
        if (str.length() >= width) {
            return str;
        }
        StringBuilder sb = new StringBuilder(width);
        for (int i = str.length(); i < width; i++) {
            sb.append('0');
        }
        sb.append(str);
        return sb.toString();
    }
}
