[[voting-config-exclusions]]
== Voting configuration exclusions API
++++
<titleabbrev>Voting Configuration Exclusions</titleabbrev>
++++

Adds or removes master-eligible nodes from the
<<modules-discovery-voting,voting configuration exclusion list>>.

[float]
=== Request

[source,js]
--------------------------------------------------
# Add a node to the voting configuration exclusions list 
POST /_cluster/voting_config_exclusions/<node_name>

# Remove all exclusions from the list
DELETE /_cluster/voting_config_exclusions
--------------------------------------------------
// CONSOLE

[float]
=== Path parameters

`node_name`::
  A <<cluster-nodes,node filter>> that identifies {es} nodes.

[float]
=== Description
  
If the <<modules-discovery-settings,`cluster.auto_shrink_voting_configuration`
setting>> is `true`, and there are more than three master-eligible nodes in the
cluster, and you remove fewer than half of the master-eligible nodes in the
cluster at once, then the <<modules-discovery-voting,voting configuration>>
automatically shrinks when you remove master-eligible nodes from the cluster.

If the `cluster.auto_shrink_voting_configuration` setting is `false`, or you
wish to shrink the voting configuration to contain fewer than three nodes, or
you wish to remove half or more of the master-eligible nodes in the cluster at
once, you must use this API to remove departed nodes from the voting
configuration manually. It adds an entry for that node in the voting
configuration exclusions list. The cluster then tries to reconfigure the voting
configuration to remove that node and to prevent it from returning.

If the API fails, you can safely retry it.  Only a successful response
guarantees that the node has been removed from the voting configuration and will
not be reinstated.

NOTE: Voting exclusions are required only when you remove at least half of the
master-eligible nodes from a cluster in a short time period. They are not
required when removing master-ineligible nodes or fewer than half of the
master-eligible nodes.

The <<modules-discovery-settings,`cluster.max_voting_config_exclusions`
setting>> limits the size of the voting configuration exclusion list. The
default value is `10`. Since voting configuration exclusions are persistent and
limited in number, you must clear the voting config exclusions list once the
exclusions are no longer required.

For more information, see <<modules-discovery-removing-nodes>>.

