[[setup]]
= Set up Elasticsearch

[partintro]
--
This section includes information on how to setup Elasticsearch and get it
running, including:

* Downloading
* Installing
* Starting
* Configuring

[[supported-platforms]]
[float]
== Supported platforms

The matrix of officially supported operating systems and JVMs is available here:
link:/support/matrix[Support Matrix]. Elasticsearch is tested on the listed
platforms, but it is possible that it will work on other platforms too.

[float]
[[jvm-version]]
== Java (JVM) Version

Elasticsearch is built using Java, and includes a bundled version of
http://openjdk.java.net[OpenJDK] from the JDK maintainers (GPLv2+CE)
within each distribution. The bundled JVM is the recommended JVM and
is located within the `jdk` directory of the Elasticsearch home directory.

To use your own version of Java, set the `JAVA_HOME` environment variable.
If you must use a version of Java that is different from the bundled JVM,
we recommend using a link:/support/matrix[supported]
http://www.oracle.com/technetwork/java/eol-135779.html[LTS version of Java].
Elasticsearch will refuse to start if a known-bad version of Java is used.
The bundled JVM directory may be removed when using your own JVM.

[float]
[[garbage-collectors]]
== JVM garbage collectors

The default garbage collector for {es} is Concurrent-Mark and Sweep (CMS). 
This GC runs concurrently with the execution of the application so that it
can minimize pauses. It does, however, have two stop-the-world phases when 
the JVM literally halts execution so it can trace the object graph and
collect dead objects. CMS also has trouble collecting large heaps.

{es} also supports the newer Garbage First GC (G1GC). G1GC minimizes pauses 
and operates better on large heaps than CMS. To use G1GC, you must run JDK 8u40
or later. 

You might want to switch garbage collectors if frequent, long garbage collection
is impacting the stability of your cluster. Long GCs can cause nodes to drop out
of a cluster for brief periods, which causes {es} to relocate shards to
keep the cluster balanced. This in turn increases network traffic and disk
I/O, which impacts the cluster's ability to service the normal indexing and query
load.

--

include::setup/install.asciidoc[]

include::setup/configuration.asciidoc[]

include::setup/jvm-options.asciidoc[]

include::setup/secure-settings.asciidoc[]

include::setup/logging-config.asciidoc[]

include::settings/audit-settings.asciidoc[]

include::settings/ccr-settings.asciidoc[]

include::settings/ilm-settings.asciidoc[]

include::settings/license-settings.asciidoc[]

include::settings/ml-settings.asciidoc[]

include::settings/monitoring-settings.asciidoc[]

include::settings/security-settings.asciidoc[]

include::settings/sql-settings.asciidoc[]

include::settings/notification-settings.asciidoc[]

include::setup/important-settings.asciidoc[]

include::setup/sysconfig.asciidoc[]

include::setup/bootstrap-checks.asciidoc[]

include::setup/starting.asciidoc[]

include::setup/stopping.asciidoc[]

include::setup/add-nodes.asciidoc[]
