/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

/**
 * Runtime entry point for Painless allocation tracking, called from generated bytecode just before an allocation. Only
 * referenced when tracking is enabled (a positive limit).
 */
public final class AllocationGuard {

    private AllocationGuard() {}

    /**
     * Charges {@code bytes} against the script's running total and returns the new total, throwing a {@link PainlessError}
     * (uncatchable from script source) if it exceeds {@code limit}. {@code allocationSite} is a diagnostic label, ideally
     * including the Painless source location.
     */
    public static long checkAlloc(PainlessScript script, long bytes, long limit, String allocationSite) {
        long total = script.$incAllocBytes(bytes);
        if (total > limit) {
            throw new PainlessError(
                "script allocation limit exceeded: allocation of ["
                    + bytes
                    + "] bytes at ["
                    + allocationSite
                    + "] brings the running total to ["
                    + total
                    + "] bytes, over the limit of ["
                    + limit
                    + "] bytes"
            );
        }
        return total;
    }
}
