/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;

/**
 * Runtime helper for Painless allocation tracking. The per-instance charge-and-check lives on the generated script class's
 * {@link PainlessScript#$checkAllocBytes(long)} override (which bakes in the per-context limit); this helper is called by that
 * override on the rare breach path to log and raise the limit error, keeping the generated bytecode small. It also receives
 * the per-execution total on the way out of {@code execute} when metrics are enabled. Only referenced when tracking is
 * enabled (a positive limit, metrics, or both).
 */
public final class AllocationGuard {

    private static final Logger logger = LogManager.getLogger(AllocationGuard.class);

    private AllocationGuard() {}

    /**
     * Records what one script execution allocated. Called from the generated {@code execute} method immediately before it
     * returns, while the counter still holds this execution's total and before the next execution zeroes it.
     * <p>
     * Deliberately on the normal return path only. An execution that throws — including one failed by the allocation limit —
     * contributes no sample, so the histogram describes executions that ran to completion. Instrumenting the exceptional path
     * too would mean wrapping every generated {@code execute} in a handler, and a partial total from an aborted execution
     * would skew the distribution it is meant to describe.
     */
    public static void recordExecutionAllocation(String scriptContextName, long totalBytes) {
        AllocationMetrics.getInstance().recordExecutionAllocation(scriptContextName, totalBytes);
    }

    /**
     * Clamps an {@code @allocates} estimator's result to {@code [0, Long.MAX_VALUE / 2]} before it is charged: a
     * negative result (an estimator bug) must not credit the running total, and a huge one must trip any configurable limit
     * without overflowing it (so estimators may return {@code Long.MAX_VALUE} for "definitely over"). Estimators must not
     * throw; a thrown exception propagates and fails the script.
     */
    public static long sanitizeEstimate(long estimatedBytes) {
        return Math.clamp(estimatedBytes, 0L, Long.MAX_VALUE / 2);
    }

    /**
     * Charges a {@code def}-dispatched {@code +} before it runs, but only when it is actually a string concat (an operand is a
     * {@link String}, per {@link DefMath}'s rule) — so numeric {@code def + def} rebox is left untracked by design. The estimate
     * reuses the statically-typed concat bound (see {@link AllocSizes#stringConcatOperandBytes}). Caller boxes primitive
     * operands so both arrive as {@link Object}; emitted only when tracking is enabled.
     */
    public static void checkDefConcatAlloc(PainlessScript script, Object left, Object right) {
        if (left instanceof String || right instanceof String) {
            script.$checkAllocBytes(
                AllocSizes.STRING_CONCAT_RESULT_OVERHEAD + AllocSizes.stringConcatOperandBytes(left) + AllocSizes.stringConcatOperandBytes(
                    right
                )
            );
        }
    }

    /**
     * Logs a {@code WARN} and throws a {@link PainlessError} describing an allocation that pushed a script over its limit.
     * {@link PainlessError} is an {@link Error}, so it cannot be caught from Painless source. Never returns normally. The
     * specific allocation that crossed the limit is not reported: it is whichever happened to tip the running total, not
     * necessarily the dominant cost, so naming it would mislead more than help.
     *
     * @param attemptedBytes the size of the allocation that tripped the limit
     * @param totalBytes the running total after charging the allocation
     * @param limitBytes the per-context limit
     */
    public static void allocationLimitExceeded(long attemptedBytes, long totalBytes, long limitBytes) {
        logger.warn(
            "Painless script allocation limit exceeded: allocation of [{}] bytes brings running total to [{}] bytes (limit [{}] bytes)",
            attemptedBytes,
            totalBytes,
            limitBytes
        );
        throw new PainlessError(
            "script allocation limit exceeded: allocation of ["
                + attemptedBytes
                + "] bytes brings the running total to ["
                + totalBytes
                + "] bytes, over the limit of ["
                + limitBytes
                + "] bytes"
        );
    }
}
