/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

import org.elasticsearch.telemetry.metric.LongCounter;
import org.elasticsearch.telemetry.metric.MeterRegistry;

import java.util.Map;

/**
 * APM counters for Painless allocation-threshold breaches. Per node, so per-cluster (and in serverless, per-project)
 * aggregation comes from the reporting pipeline.
 * <p>
 * Attributed by script context only. The script <i>name</i> is deliberately not an attribute: inline scripts are named per
 * source, so cardinality would be unbounded. Name and source go to the log instead, bounded by the warning latch.
 * <p>
 * Held statically because the callers are {@link AllocationGuard} methods invoked from generated bytecode, which has no
 * object to carry a reference on. Starts as {@link #NOOP}, installed at startup from {@code PainlessPlugin#createComponents}
 * — always before any script runs; a node without telemetry keeps the no-op.
 */
public final class AllocationMetrics {

    public static final String METRIC_WARN_EXCEEDED = "es.script.painless.allocation.warn_exceeded.total";
    public static final String METRIC_LIMIT_EXCEEDED = "es.script.painless.allocation.limit_exceeded.total";

    /** Attribute naming the script context a breach happened in. */
    static final String CONTEXT_ATTRIBUTE = "context";

    /** Used until real telemetry is installed, and by tests that do not care about metrics. */
    public static final AllocationMetrics NOOP = new AllocationMetrics(MeterRegistry.NOOP);

    private static volatile AllocationMetrics instance = NOOP;

    private final LongCounter warnExceededCounter;
    private final LongCounter limitExceededCounter;

    public AllocationMetrics(MeterRegistry meterRegistry) {
        warnExceededCounter = meterRegistry.registerLongCounter(
            METRIC_WARN_EXCEEDED,
            "number of Painless script executions whose heuristic allocation total crossed the per-context warning threshold",
            "unit"
        );
        limitExceededCounter = meterRegistry.registerLongCounter(
            METRIC_LIMIT_EXCEEDED,
            "number of Painless script executions failed for exceeding the per-context heuristic allocation limit",
            "unit"
        );
    }

    /** Installs the node metrics at startup; tests use it to swap in a recording registry and restore {@link #NOOP}. */
    public static void setInstance(AllocationMetrics allocationMetrics) {
        instance = allocationMetrics;
    }

    static AllocationMetrics getInstance() {
        return instance;
    }

    /** Counts one execution that crossed the warning threshold; at most once per execution, per the latch. */
    void recordWarnExceeded(String scriptContextName) {
        warnExceededCounter.incrementBy(1L, Map.of(CONTEXT_ATTRIBUTE, scriptContextName));
    }

    /** Counts one execution failed by the allocation limit. */
    void recordLimitExceeded(String scriptContextName) {
        limitExceededCounter.incrementBy(1L, Map.of(CONTEXT_ATTRIBUTE, scriptContextName));
    }
}
