[role="xpack"]
[[ccr-get-auto-follow-pattern]]
=== Get auto-follow pattern API
++++
<titleabbrev>Get auto-follow pattern</titleabbrev>
++++

Get auto-follow patterns.

[[ccr-get-auto-follow-pattern-request]]
==== {api-request-title}

//////////////////////////

[source,console]
--------------------------------------------------
PUT /_ccr/auto_follow/my_auto_follow_pattern
{
  "remote_cluster" : "remote_cluster",
  "leader_index_patterns" :
  [
    "leader_index*"
  ],
  "leader_index_exclusion_patterns":
  [
    "leader_index_001"
  ],
  "follow_index_pattern" : "{{leader_index}}-follower"
}
--------------------------------------------------
// TEST[setup:remote_cluster]
// TESTSETUP

[source,console]
--------------------------------------------------
DELETE /_ccr/auto_follow/my_auto_follow_pattern
--------------------------------------------------
// TEST
// TEARDOWN

//////////////////////////

[source,console]
--------------------------------------------------
GET /_ccr/auto_follow/
--------------------------------------------------

[source,console]
--------------------------------------------------
GET /_ccr/auto_follow/<auto_follow_pattern_name>
--------------------------------------------------
// TEST[s/<auto_follow_pattern_name>/my_auto_follow_pattern/]

[[ccr-get-auto-follow-pattern-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have `manage_ccr` cluster
privileges on the cluster that contains the follower index. For more information,
see <<security-privileges>>.

[[ccr-get-auto-follow-pattern-desc]]
==== {api-description-title}

This API gets configured <<ccr-auto-follow,auto-follow patterns>>.
This API will return the specified auto-follow pattern collection.

[[ccr-get-auto-follow-pattern-path-parms]]
==== {api-path-parms-title}

`<auto_follow_pattern_name>`::
  (Optional, string) Specifies the auto-follow pattern collection that you want
  to retrieve. If you do not specify a name, the API returns information for all
  collections.

[[ccr-get-auto-follow-pattern-examples]]
==== {api-examples-title}

This example retrieves information about an auto-follow pattern collection
named `my_auto_follow_pattern`:

[source,console]
--------------------------------------------------
GET /_ccr/auto_follow/my_auto_follow_pattern
--------------------------------------------------
// TEST[setup:remote_cluster]

The API returns the following result:

[source,console-result]
--------------------------------------------------
{
  "patterns": [
    {
      "name": "my_auto_follow_pattern",
      "pattern": {
        "active": true,
        "remote_cluster" : "remote_cluster",
        "leader_index_patterns" :
        [
          "leader_index*"
        ],
        "leader_index_exclusion_patterns":
        [
          "leader_index_001"
        ],
        "follow_index_pattern" : "{{leader_index}}-follower"
      }
    }
  ]
}
--------------------------------------------------
