steps:
  - command: .buildkite/scripts/dra-workflow.sh
    env:
      USE_DRA_CREDENTIALS: "true"
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2204
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - wait
  # The hadoop build depends on the ES artifact
  # So let's trigger the hadoop build any time we build a new staging artifact
  - trigger: elasticsearch-hadoop-dra-workflow
    async: true
    build:
      branch: "${BUILDKITE_BRANCH}"
      env:
        DRA_WORKFLOW: staging
    if: build.env('DRA_WORKFLOW') == 'staging'
