steps:
  - command: .buildkite/scripts/dra-workflow.sh
    env:
      USE_MAVEN_GPG: "true"
      USE_MAVEN_S3_CREDENTIALS: "true"
      USE_PROD_DOCKER_CREDENTIALS: "true"
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2204
      machineType: custom-32-98304
      localSsds: 1
      localSsdInterface: nvme
      diskSizeGb: 350
