steps:
  - label: sanity-check
    command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dorg.elasticsearch.build.cache.push=true -Dignore.tests.seed -Dscan.capture-task-input-files precommit
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - wait
  - label: part1
    command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dorg.elasticsearch.build.cache.push=true -Dignore.tests.seed -Dscan.capture-task-input-files checkPart1
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n1-standard-32
      buildDirectory: /dev/shm/bk
  - label: part2
    command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dorg.elasticsearch.build.cache.push=true -Dignore.tests.seed -Dscan.capture-task-input-files checkPart2
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n1-standard-32
      buildDirectory: /dev/shm/bk
  - wait
  - trigger: elasticsearch-dra-workflow
    label: Trigger DRA snapshot workflow
    async: true
    build:
      branch: "$BUILDKITE_BRANCH"
      commit: "$BUILDKITE_COMMIT"
      env:
        DRA_WORKFLOW: snapshot
