      - label: "{{matrix.image}} / $BWC_VERSION / packaging-tests-upgrade"
        command: ./.ci/scripts/packaging-test.sh -Dbwc.checkout.align=true destructiveDistroUpgradeTest.v$BWC_VERSION
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - rocky-8
              - ubuntu-2404
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          machineType: custom-16-32768
          buildDirectory: /dev/shm/bk
        env:
          BWC_VERSION: $BWC_VERSION
