steps:
  - group: platform-support-unix
    steps:
      - label: "{{matrix.image}} / platform-support-unix"
        command: .ci/scripts/run-gradle.sh --continue -Dbwc.checkout.align=true functionalTests
        timeout_in_minutes: 420
        matrix:
          setup:
            image:
              - ubuntu-2604
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          localSsds: 1
          localSsdInterface: nvme
          machineType: custom-32-98304
        env: {}
        retry:
          automatic:
            - exit_status: "-1"
              limit: 3
              signal_reason: none
            - signal_reason: agent_stop
              limit: 3
            - exit_status: "1"
              limit: 1
  - group: platform-support-arm
    steps:
      - label: "{{matrix.image}} / {{matrix.GRADLE_TASK}} / platform-support-arm"
        command: .ci/scripts/run-gradle.sh --continue -Dbwc.checkout.align=true {{matrix.GRADLE_TASK}}
        timeout_in_minutes: 420
        matrix:
          setup:
            image:
              - ubuntu-2604-aarch64
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - checkPart4
              - checkPart5
              - checkPart6
              - checkRestCompat
        agents:
          provider: aws
          imagePrefix: elasticsearch-{{matrix.image}}
          instanceType: m6g.8xlarge
          diskSizeGb: 350
          diskType: gp3
          diskName: /dev/sda1
        env:
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
        retry:
          automatic:
            - exit_status: "-1"
              limit: 3
              signal_reason: none
            - signal_reason: agent_stop
              limit: 3
            - exit_status: "1"
              limit: 1
