steps:
  - group: platform-support-unix
    steps:
      - label: "{{matrix.image}} / platform-support-unix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true check
        matrix:
          setup:
            image:
              - centos-7
              - debian-10
              - debian-11
              - opensuse-leap-15
              - oraclelinux-7
              - oraclelinux-8
              - sles-12
              - sles-15
              - ubuntu-1804
              - ubuntu-2004
              - ubuntu-2204
              - rocky-8
              - rhel-7
              - rhel-8
              - rhel-9
              - almalinux-8
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          machineType: custom-32-98304
          diskSizeGb: 350
        env: {}
