      - label: $BWC_VERSION / bwc
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true v$BWC_VERSION#bwcTest
        timeout_in_minutes: 300
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          buildDirectory: /dev/shm/bk
        env:
          BWC_VERSION: $BWC_VERSION