steps:
  - group: java-fips-matrix
    steps:
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.GRADLE_TASK}} / java-fips-matrix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dtests.fips.enabled=true $$GRADLE_TASK
        timeout_in_minutes: 180
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - openjdk17
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - bwcTestSnapshots
              - checkRestCompat
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: custom-32-98304
          buildDirectory: /dev/shm/bk
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
