# Temporary: only run third-party tests (temp testing branch)
steps:
  - group: third-party tests
    steps:
      - label: third-party / azure-sas
        command: |
          export azure_storage_container=elasticsearch-ci-thirdparty-sas
          export azure_storage_base_path=$BUILDKITE_BRANCH

          .ci/scripts/run-gradle.sh --continue azureThirdPartyTest
        env:
          USE_3RD_PARTY_AZURE_SAS_CREDENTIALS: "true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk

      - label: third-party / azure
        command: |
          export azure_storage_container=elasticsearch-ci-thirdparty
          export azure_storage_base_path=$BUILDKITE_BRANCH

          .ci/scripts/run-gradle.sh --continue azureThirdPartyTest
        env:
          USE_3RD_PARTY_AZURE_CREDENTIALS: "true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk

      - label: third-party / gcs
        command: |
          export google_storage_bucket=elasticsearch-ci-thirdparty
          export google_storage_base_path=$BUILDKITE_BRANCH

          .ci/scripts/run-gradle.sh --continue gcsThirdPartyTest
        env:
          USE_3RD_PARTY_GCS_CREDENTIALS: "true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk

      - label: third-party / geoip
        command: |
          .ci/scripts/run-gradle.sh --continue :modules:ip-location:internalClusterTest -Dtests.jvm.argline="-Dgeoip_use_service=true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk

      - label: third-party / s3
        command: |
          export amazon_s3_bucket=elasticsearch-ci.us-west-2
          export amazon_s3_base_path=$BUILDKITE_BRANCH

          .ci/scripts/run-gradle.sh --continue s3ThirdPartyTest
        env:
          USE_3RD_PARTY_S3_CREDENTIALS: "true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk

      - label: third-party / ms-graph
        command: |
          .ci/scripts/run-gradle.sh --continue msGraphThirdPartyTest
        env:
          USE_3RD_PARTY_MS_GRAPH_CREDENTIALS: "true"
        timeout_in_minutes: 30
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2404
          machineType: n4-standard-8
          diskType: hyperdisk-balanced
          buildDirectory: /dev/shm/bk
