steps:
  - label: esql-generative-single-node
    command: .ci/scripts/run-gradle.sh -Ptests.mutes.enabled=false :x-pack:plugin:esql:qa:server:single-node:generativeTests
    timeout_in_minutes: 120
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n4-standard-16
      diskType: hyperdisk-balanced
      buildDirectory: /dev/shm/bk

  - label: esql-generative-multi-node
    command: .ci/scripts/run-gradle.sh -Ptests.mutes.enabled=false :x-pack:plugin:esql:qa:server:multi-node:generativeTests
    timeout_in_minutes: 120
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2404
      machineType: n4-standard-16
      diskType: hyperdisk-balanced
      buildDirectory: /dev/shm/bk
