agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2022
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
  useVault: false
steps:
  - label: concurrent-search-tests
    command: $$WORKSPACE/.ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
      -Dtests.jvm.argline=-Des.concurrent_search=true
      -Des.concurrent_search=true check
