agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2004
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
steps:
  - group: bwc-snapshots-windows
    steps:
      - label: "{{matrix.BWC_VERSION}} / bwc-snapshots-windows"
        command: .buildkite\generated-scripts\4ef3241cf6b8dbbae758f32a006b0bc0.bat
        matrix:
          setup:
            BWC_VERSION:
              - 7.17.11
              - 8.8.2
              - 8.9.0
        agents:
          provider: gcp
          image: family/core-windows-2022
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          BWC_VERSION: "{{matrix.BWC_VERSION}}"
  - group: packaging-tests-windows-nojdk
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-nojdk"
        command: .buildkite\generated-scripts\ca6b2b9c7738eac3d32fd7cd4ac2faa8.bat
        matrix:
          setup:
            image:
              - family/core-windows-2012-r2
              - family/core-windows-2016
              - family/core-windows-2019
              - family/core-windows-2022
            PACKAGING_TASK:
              - default-windows-archive
              - default-windows-archive-no-jdk
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows-sample-nojdk
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-sample-nojdk"
        command: .buildkite\generated-scripts\ca6b2b9c7738eac3d32fd7cd4ac2faa8.bat
        matrix:
          setup:
            image:
              - family/core-windows-2019
            PACKAGING_TASK:
              - default-windows-archive
              - default-windows-archive-no-jdk
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows-sample
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-sample"
        command: .buildkite\generated-scripts\ca6b2b9c7738eac3d32fd7cd4ac2faa8.bat
        matrix:
          setup:
            image:
              - family/core-windows-2019
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-windows"
        command: .buildkite\generated-scripts\ca6b2b9c7738eac3d32fd7cd4ac2faa8.bat
        matrix:
          setup:
            image:
              - family/core-windows-2012-r2
              - family/core-windows-2016
              - family/core-windows-2019
              - family/core-windows-2022
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - label: part-1-windows
    command: .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-2-windows
    command: .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-3-windows
    command: .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
