agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2004
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
steps:
  - group: java-fips-matrix
    steps:
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.GRADLE_TASK}} / java-fips-matrix"
        command: $$WORKSPACE/.ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          -Dtests.fips.enabled=true $$GRADLE_TASK
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - openjdk17
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - bwcTestSnapshots
              - checkRestCompat
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
