[role="xpack"]
[testenv="basic"]
[[rollup-get-job]]
=== Get rollup jobs API
++++
<titleabbrev>Get job</titleabbrev>
++++

Returns the configuration, stats and status of rollup jobs.

experimental[]

[float]
[[rollup-get-job-request]]
==== {api-request-title}

`GET _rollup/job/<job_id>`

[float]
[[rollup-get-job-prereqs]]
==== {api-prereq-title}

If the {es} {security-features} are enabled, you must have `monitor`,
`monitor_rollup`, `manage` or `manage_rollup` cluster privileges to use this API.
For more information, see
{stack-ov}/security-privileges.html[Security privileges].

[float]
[[rollup-get-job-desc]]
==== {api-description-title}

The API can return the details for a single job or for all jobs.

NOTE: This API returns only active (both `STARTED` and `STOPPED`) jobs. If a job
was created, ran for a while, then deleted, this API does not return any details
about the job. For details about historical jobs, the
<<rollup-get-rollup-caps,rollup capabilities API>> may be more useful.

[float]
[[rollup-get-job-path-params]]
==== {api-path-parms-title}

`<job_id>` (Optional)::
  (string) Identifier for the job to retrieve. If omitted (or `_all` is used),
  all jobs are returned.

[float]
[[rollup-get-job-response-body]]
==== {api-response-body-title}

`jobs`::
  An array of rollup job resources.
  
    `config`::: (object) The rollup job's configuration. See
    <<rollup-job-config-objects>>.
    
    `status`::: (object) The current status of the rollup job's indexer. For
    example, `"job_state" : "stopped"`. See <<rollup-job-stats-objects>>.
      
    `stats`::: (object) Transient statistics about the rollup job, such as how
    many documents have been processed and how many rollup summary docs have
    been indexed. See <<rollup-job-stats-objects>>.

For more information, see <<rollup-job-objects>>.

[float]
[[rollup-get-job-example]]
==== {api-example-title}

If you have already created a rollup job named `sensor`, you can retrieve the
details about the job:

[source,js]
--------------------------------------------------
GET _rollup/job/sensor
--------------------------------------------------
// CONSOLE
// TEST[setup:sensor_rollup_job]

The API yields the following response:

[source,js]
----
{
    "jobs" : [
        {
          "config" : {
            "id" : "sensor",
            "index_pattern" : "sensor-*",
            "rollup_index" : "sensor_rollup",
            "cron" : "*/30 * * * * ?",
            "groups" : {
              "date_histogram" : {
                "fixed_interval" : "1h",
                "delay": "7d",
                "field": "timestamp",
                "time_zone": "UTC"
              },
              "terms" : {
                "fields" : [
                  "node"
                ]
              }
            },
            "metrics" : [
              {
                "field" : "temperature",
                "metrics" : [
                  "min",
                  "max",
                  "sum"
                ]
              },
              {
                "field" : "voltage",
                "metrics" : [
                  "avg"
                ]
              }
            ],
            "timeout" : "20s",
            "page_size" : 1000
          },
          "status" : {
            "job_state" : "stopped"
          },
          "stats" : {
            "pages_processed" : 0,
            "documents_processed" : 0,
            "rollups_indexed" : 0,
            "trigger_count" : 0,
            "index_failures": 0,
            "index_time_in_ms": 0,
            "index_total": 0,
            "search_failures": 0,
            "search_time_in_ms": 0,
            "search_total": 0
          }
        }
    ]
}
----
// TESTRESPONSE

The `jobs` array contains a single job (`id: sensor`) since we requested a
single job in the endpoint's URL.
