[role="xpack"]
[testenv="basic"]
[[rollup-job-config-objects]]
=== Rollup job config API objects
++++
<titleabbrev>Rollup job config</titleabbrev>
++++

The `config` object holds the rollup job's configuration. It is used by the
<<rollup-put-job,create rollup job API>> and the
<<rollup-get-job,get rollup jobs API>>.

`cron`:: 
  (string) A cron string that defines when the rollup job executes.

`groups`:: 
  (object) Defines the grouping fields that are defined for this rollup job. See
  <<rollup-job-config>> and <<rollup-job-group-objects>>.

`id`:: 
  (string) An identifier for the rollup job. This property is informational; it
  is returned by the <<rollup-get-job,get rollup jobs API>>.

`index_pattern`::
  (string) The index or index pattern to roll up. It supports wildcard-style
  patterns such as `logstash-*`.

`metrics`::
  (object) Defines the metrics are collected for each grouping tuple.
  See <<rollup-job-config,rollup job config>> and <<rollup-job-metrics-objects>>.

`page_size`::
  (integer) The number of bucket results that are processed on each iteration of
  the rollup indexer. A larger value tends to execute faster, but requires more
  memory during processing.

`rollup_index`::
  (string) The index that contains the rollup results. The index can be shared
  with other rollup jobs.

////
`timeout`:: TBD. Exists in get jobs but not put job.
////

[float]
[[rollup-job-group-objects]]
==== Rollup job group API objects
 
`date_histogram`:: (object) TBD

[float]
[[rollup-job-metrics-objects]]
==== Rollup job metrics API objects

The `metrics` resource is an array of the following properties:
 
`field`:: TBD

metrics:: (array) TBD

////
`config`::
  (object) TBD

`cron`::
  (string) A cron string that defines when the rollup job runs. It defines an
  interval of when to run the job's indexer. When the interval triggers, the
  indexer attempts to roll up the data in the index pattern. The cron pattern is
  unrelated to the time interval of the data being rolled up. For example, you
  can create hourly rollups of your document (as defined in the
  <<rollup-groups-config,grouping configuration>>) but run the indexer only on a
  daily basis at midnight, as defined by the cron. The cron pattern is defined
  just like the {watcher} cron schedule.

`fields`::
  (object) A list of fields that contain data that is eligible for rollup
  searches.
  
`groups`::
  (object) A list of the grouping fields. 

`index_pattern`::
  (string) The index or index pattern that is rolled up. Supports wildcard-style
  patterns (for example, `logstash-*`).
+
--
[NOTE]
This property value cannot be a pattern that also matches the `rollup_index`.
For example, the pattern `"foo-*"` matches the rollup index `"foo-rollup"`. This
situation causes problems because the rollup job attempts to roll up its own
data at runtime. If you attempt to configure a pattern that matches the
`rollup_index`, an exception is thrown to prevent this behavior.

--

`job_id`::
  (string) The unique identifier for the data that is associated with the rollup
  job. It can be any alphanumeric string.

`metrics`::
  (object) The metrics to collect for each group.
  
`page_size`::
  (int) The number of bucket results that are processed on each iteration of the
  rollup indexer. A larger value tends to execute faster but requires more
  memory during processing. This property has no effect on how the data is
  rolled up; it is merely used for tweaking the speed or memory cost of the
  indexer.

`rollup_index`::
  (string) The index that contains rollup results. This index stores all the
  rollup data that is generated by the job. It can be shared by multiple rollup
  jobs.
////
