
# ELASTICSEARCH CONFIDENTIAL
# __________________
#
#  [2017] Elasticsearch Incorporated. All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Elasticsearch Incorporated and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Elasticsearch Incorporated
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Elasticsearch Incorporated.

# This Vagrantfile exists to define a virtual machine running OpenLDAP
# for usage as a testing fixture for the build process..

Vagrant.configure("2") do |config|

  config.vm.define "openldap" do |config|
    config.vm.box = "elastic/ubuntu-16.04-x86_64"
  end

  config.vm.hostname = "openldap.build.elastic.co"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 389, host: 60389, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 636, host: 60636, protocol: "tcp"

  config.vm.provision "shell", path: "src/main/resources/provision/installopenldap.sh"

end
