name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@v1
    with:
      enable-vale-linting: true
      vale-paths: |
        docs/reference/**
        docs/extend/**
        !docs/reference/query-languages/esql/**
      path-pattern: docs/**
      path-pattern-ignore: |
        docs/changelog/**
        docs/releases/**
