# Daily update of JDK update branch with changes from main
name: "Merge main to openjdk23-bundle branch"
on:
  schedule:
    - cron: "30 17 * * *"
  workflow_dispatch: {}

jobs:
  merge-branch:
    if: github.repository == 'elastic/elasticsearch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: merge
        uses: devmasx/merge-branch@1.4.0
        with:
          type: "now"
          target_branch: openjdk23-bundle
          github_token: ${{ secrets.ELASTICSEARCHMACHINE_TOKEN }}
