[[indices-create-index]]
== Create index API
++++
<titleabbrev>Create index</titleabbrev>
++++

Creates an index.

[float]
[[indices-create-index-request]]
=== {api-request-title}

`PUT <index>`

[float]
[[sample-api-desc]]
=== {api-description-title}
You can use the create index API to manually create an index in {es}.

[float]
[[indices-create-index-path-params]]
=== {api-path-parms-title}

`<index>` (Required)::
+
--
(string) Name of the index.

[NOTE]
====
Index names must meet the following criteria:

* Must be lowercase only
* deprecated:[7.0, "Index names can no longer include a colon (`:`)."] Cannot
include the following characters: `\`, `/`, `*`, `?`, `"`, `<`, `>`, `|`, ` `
(space character), `,`, `#`, or `:`.
* Cannot begin with the following characters: `-`, `_`, `+`.
* Cannot be named `.` or `..`.
* Cannot be longer than 255 bytes, including multi-byte characters.
====
--

[float]
[[indices-create-index-query-params]]
=== {api-query-parms-title}

[[create-index-wait-for-active-shards]]
`wait_for_active_shards` (Optional)::
(integer) Number of active shard copies required to start before returning a
response. See
<<index-wait-for-active-shards>>.

include::{docdir}/rest-api/timeoutparms.asciidoc[]

[float]
[[indices-create-index-request-body]]
=== {api-request-body-title}

[[create-index-aliases]]
`aliases` (Optional)::
(object) Index aliases which include the index. See <<indices-aliases, Index
aliases>>.

[[mappings]]
`mappings` (Optional)::
(object) Describes fields in the index and their datatypes. See <<mapping-types,
Field datatypes>>.

[[create-index-settings]]
`settings` (Optional)::
(object) Configuration options for the index. See <<index-modules-settings,
Index settings>>.


[float]
[[indices-create-index-response-body]]
=== {api-response-body-title}

`acknowledged`::
+
--
(boolean) Indicates whether the index was successfully created in the cluster
before timing out.

If `false`, it is possible that {es} still successfully created the index. A
`false` value only indicates the operation timed out before the response.
--

`shards_acknowledged`::
+
--
(boolean) Indicates whether the required number of active shard copies started
before timing out.

If `false`, it is possible that {es} still successfully created the index. A
`false` value only indicates the operation timed out before the response.
--

`index`::
(string) Name of the index.

[float]
[[indices-create-index-example]]
=== {api-example-title}

[source,js]
----
PUT test
{
    "aliases" : {
        "alias_1" : {},
        "alias_2" : {
            "filter" : {
                "term" : {"user" : "kimchy" }
            },
            "routing" : "kimchy"
        }
    },
    "mappings" : {
        "properties" : {
            "field1" : { "type" : "text" }
        }
    },
    "settings" : {
        "number_of_shards" : 1
    }
}
----
// CONSOLE

The API returns the following result:

[source,js]
----
{
    "acknowledged": true,
    "shards_acknowledged": true,
    "index": "test"
}
----
// TESTRESPONSE
