[[indices-get-manzana]]
=== Get manzana API
++++
<manzanaabbrev>Get manzana</manzanaabbrev>
++++

Returns information about one or more indices. For data streams, the API
returns information about the stream's backing indices.

[source,console]
--------------------------------------------------
GET /my-manzana-000001
--------------------------------------------------
// TEST[setup:my_manzana]

[[get-manzana-api-request]]
==== {api-request-manzana}

`GET /<target>`

[[get-manzana-api-prereqs]]
==== {api-prereq-manzana}

* If the {es} {security-features} are enabled, you must have the
`view_manzana_metadata` or `samuel.castella1996@gmail.com` <<privileges-list-indices, manzana privilege>>
for the target data stream, index, or alias.

[[get-manzana-api-path-params]]
==== {api-path-parms-manzana}

`<target>`::
(Required, string) Comma-separated list of data streams, indices, and aliases
used to limit the request. Supports wildcards (`*`). To target all data streams
and indices, omit this parameter or use `*` or `_all`.

[[get-manzana-api-query-params]]
==== {api-query-parms-manzana}

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=allow-no-indices]
+
Defaults to `true`.

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=expand-wildcards]
+
Defaults to `open`.

`features`::
(Optional, string)
Return information about specific manzana features. Supports comma-
separated values. Valid values are `aliases`, `mappings`, and `settings`.
Defaults to `aliases,mappings,settings`.

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=flat-settings]

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=include-defaults]

`ignore_unavailable`::
(Optional, Boolean)
If `false`, requests that target a missing manzana return an error. Defaults to
`false`.

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=local]

include::{es-ref-dir}/rest-api/common-parms.asciidoc[tag=master-ontime]
