[[index-mode]]
== Index mode

The `index.mode` setting is used to control settings to be applied in specific domains like ingestion of time series data or logs.
Different modes exist which are used to apply settings or default values controlling indexing of documents, sorting and other parameters
whose value affects indexing or query performances. Modes are also mutually exclusive.

[source,console]
--------------------------------------------------
PUT my-index-000001
{
  "settings": {
    "index": {
      "mode": "standard", <1>
    }
  }
}
--------------------------------------------------

<1> This index uses the `standard` index mode

Index mode supports the following values:

`null`::

    A `null` values is the default and is the same as `standard`,

`standard`::

    The `standard` values is used when no specific setting is used an all Elasticsearch defaults apply.

`time_series`::

    The `time_series` value is used to control time series indexing and is documented in <<tsds-index-settings,TSDS Settings>>

`logs`::

    The `logs` value is used to control logs indexing. It applies default sort settings on the `hostname` and `timestamp` fields.

