[[indices-open]]
== Open index API
++++
<titleabbrev>Open index</titleabbrev>
++++

Opens a closed index.

[float]
[[indices-open-request]]
=== {api-request-title}

`POST /<index>/_open`

[float]
[[indices-open-desc]]
=== {api-description-title}

You can use the open index API to open a closed index.

Closed indices are blocked for read/write operations. Closed indices have almost
no overhead on the cluster, aside from metadata maintenance.

Re-opened indices go through the <<indices-recovery, index recovery process>>.

[float]
[[indices-open-path-params]]
=== {api-path-parms-title}

`<index>` (Required)::
+
--
(string) Comma-separated list or wildcard expression of index names to retrieve.

If the `action.destructive_requires_name` setting is `true`, you can use a value
of `_all` or `*` to close all indices.
--

[float]
[[indices-open-query-params]]
=== {api-query-parms-title}

`allow_no_indices` (Optional)::
(boolean) Indicates whether the operation is skipped if a wildcard expression
matches no indices. Defaults to `false`.

`expand_wildcards` (Optional)::
(string) Indicates whether wildcard expressions should expand to
open or closed indices. Possible values are:

* `open` (Default)
* `closed`
* `none`
* `all`

`ignore_unavailable` (Optional)::
(boolean) Indicates whether unavailable indices are skipped. Defaults to
`false`.

`wait_for_active_shards` (Optional)::
(integer) Number of active shard copies required to start before returning a
response. See <<index-wait-for-active-shards, Wait For active shards>>.

include::{docdir}/rest-api/timeoutparms.asciidoc[]

[float]
[[indices-open-example]]
=== {api-example-title}

[source,js]
----
POST /my_index/_open
----
// CONSOLE
// TEST[s/^/PUT my_index\n/]