[[indices-refresh]]
== Refresh API
++++
<titleabbrev>Refresh</titleabbrev>
++++

Refresh an index, making all operations performed since the last refresh
available for search.

[float]
[[indices-refresh-request]]
=== {api-request-title}

`POST /<index>/_refresh`

`GET /<index>/_refresh`

[float]
[[indices-refresh-desc]]
=== {api-description-title}

You can use the refresh API to explicitly refresh one or more indices, making
all operations performed since the last refresh available for search.

The near real-time capabilities depend on the index engine used. For
example, the internal one requires refresh to be called, but by default a
refresh is scheduled periodically.

[float]
[[indices-refresh-path-params]]
=== {api-path-parms-title}

`<index>` (Required)::
+
--
(string) Comma-separated list or wildcard expression of indices to refresh.

You can use a value of `_all` or `*` to refresh all indices.

If no value is provided, the API refreshes all indices.
--

[float]
[[indices-refresh-query-params]]
=== {api-query-parms-title}

`allow_no_indices` (Optional)::
(boolean) Indicates whether the operation is skipped if a wildcard expression
matches no indices. Defaults to `false`.

`expand_wildcards` (Optional)::
+
--
(string) Indicates whether wildcard expressions should expand to
<<indices-open-close, open or closed indices>>. Possible values are:

* `open` (Default)
* `closed`
* `none`
* `all`
--

`ignore_unavailable` (Optional)::
(boolean) Indicates whether unavailable indices are skipped. Defaults to
`false`.

[float]
[[sample-api-example]]
=== {api-examples-title}

[source,js]
----
POST /twitter/_refresh
----
// CONSOLE
// TEST[setup:twitter]