[[indices-split-index]]
== Split index API
++++
<titleabbrev>Split index</titleabbrev>
++++

Splits an existing index into a new index with more primary shards.

[float]
[[indices-split-index-request]]
=== {api-request-title}

`POST <source-index>/_split/<target-index>`

[float]
[[indices-split-index-prereqs]]
=== {api-prereq-title}

To be split, an index must meet the following criteria:

* The cluster must have a `green` health status. You can check the health status
  of a cluster using the <<cluster-health, cluster health API>>.

* The node handling the split process must have enough free disk space for a
  second copy of the source index.

See <<prepare-index-for-splitting>>.

[float]
[[indices-split-index-desc]]
=== {api-description-title}

include::{docdir}/administering/split-index.asciidoc[tag=split-index-intro]

[float]
[[indices-split-index-path-params]]
=== {api-path-parms-title}

`<source-index>` (Required)::
(string) Name of the existing index to split.

`<target-index>` (Required)::
+
--
(string) Name of the new index to create.

This cannot be an existing index. If this index exists prior to the request,
{es} returns an error.
--

[float]
[[indices-split-index-query-params]]
=== {api-query-parms-title}

 `wait_for_active_shards` (Optional)::
(integer) Number of active shard copies required to start before returning a
response. See <<index-wait-for-active-shards>>.

include::{docdir}/rest-api/timeoutparms.asciidoc[]

[float]
[[indices-split-index-request-body]]
=== {api-request-body-title}

`aliases` (Optional)::
(object) Index aliases which include the new `<target-index>`. See
<<indices-aliases>>.

`settings` (Optional)::
+
--
(object) Configuration options for the new `<target-index>`. See
<<index-modules-settings>>.

[IMPORTANT]
====
You can set the number of primary shards for the new `<target-index>` using the
`index.number_of_shards` setting.

The new number of primary shards in the target index **must be**:

* Greater than the current number of shards in the source index.

* A factor of the number of shards in the source index.

For example, you can split a `<source-index>` with `5` primary shards into a
`<target-index>` with `10`, `20` or `40` primary shards.

See <<split-index>>.
====
--

[float]
[[indices-split-index-example]]
=== {api-example-title}

[source,js]
----
POST my_source_index/_split/my_target_index
{
  "settings": {
    "index.number_of_shards": 6
  },
  "aliases": {
    "my_search_indices": {}
  }
}
----
// CONSOLE
// TEST[s/^/PUT my_source_index\n{"settings": {"index.blocks.write": true, "index.number_of_shards": "1"}}\n/]