/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

apply plugin: 'elasticsearch.test-with-dependencies'
apply plugin: 'elasticsearch.internal-yaml-rest-test'
apply plugin: 'elasticsearch.internal-java-rest-test'
apply plugin: 'elasticsearch.yaml-rest-compat-test'
apply plugin: 'elasticsearch.internal-cluster-test'

esplugin {
  description = 'The Reindex module adds APIs to reindex from one index to another or update documents in place.'
  classname = 'org.elasticsearch.reindex.ReindexPlugin'
}

dependencies {
  api project(":client:rest")
  api project(":libs:ssl-config")
  // for parent/child testing
  testImplementation project(':modules:parent-join')
  testImplementation project(':modules:rest-root')

  clusterModules project(':modules:lang-painless')
  clusterModules project(':modules:parent-join')
  clusterModules project(":modules:rest-root")

  // Testcontainers-backed old Elasticsearch fixtures for reindex-from-remote (see javaRestTest)
  javaRestTestImplementation project(':test:fixtures:old-elasticsearch')
  javaRestTestImplementation project(':test:fixtures:testcontainer-utils')
  javaRestTestRuntimeOnly "org.slf4j:slf4j-simple:${versions.slf4j}"
}

restResources {
  restApi {
    include '_common', 'cluster', 'nodes', 'indices', 'index', 'get', 'search', 'mget', 'count',
                'update_by_query', 'delete_by_query', 'reindex_rethrottle', 'tasks', 'reindex', 'put_script', 'bulk', 'info'
  }
}

tasks.named("thirdPartyAudit").configure {
  ignoreMissingClasses(
          // Commons logging
          'javax.servlet.ServletContextEvent',
          'javax.servlet.ServletContextListener',
          'org.apache.avalon.framework.logger.Logger',
          'org.apache.log.Hierarchy',
          'org.apache.log.Logger',
  )
}

tasks.named("forbiddenPatterns").configure {
  // PKCS#12 file are not UTF-8
  exclude '**/*.p12'
}

tasks.named("yamlRestTestV7CompatTransform").configure { task ->
    task.skipTest("reindex/20_validation/reindex without source gives useful error message", "exception with a type. Not much benefit adding _doc there.")
    task.skipTest("update_by_query/20_validation/update_by_query without source gives useful error message", "exception with a type. Not much benefit adding _doc there.")

    // these tests are all relying on a call to refresh all indices, when they could easily be changed
    // in 7.x to call the specific index they want to refresh.
    // See https://github.com/elastic/elasticsearch/issues/81188
    task.skipTest("delete_by_query/70_throttle/Rethrottle to -1 which turns off throttling", "test relies on system index being non-hidden")
    task.skipTest("delete_by_query/80_slices/Multiple slices with rethrottle", "test relies on system index being non-hidden")
    task.skipTest("delete_by_query/80_slices/Multiple slices with wait_for_completion=false", "test relies on system index being non-hidden")
    task.skipTest("reindex/80_slices/Multiple slices with rethrottle", "test relies on system index being non-hidden")
    task.skipTest("reindex/80_slices/Multiple slices with wait_for_completion=false", "test relies on system index being non-hidden")
    task.skipTest("update_by_query/70_slices/Multiple slices with rethrottle", "test relies on system index being non-hidden")
    task.skipTest("update_by_query/70_slices/Multiple slices with wait_for_completion=false", "test relies on system index being non-hidden")

    task.addAllowedWarningRegex("\\[types removal\\].*")
}

tasks.named("yamlRestTestV7CompatTest").configure {
  systemProperty 'tests.rest.blacklist', [
    'update_by_query/80_scripting/Can\'t change _id',
    'update_by_query/80_scripting/Set unsupported operation type',
    'update_by_query/80_scripting/Setting bogus context is an error',

  ].join(',')
}
